apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: approve-auditor2-emissionchannel-peer0datalock1-1
  namespace: auditor2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: approve-auditor2-emissionchannel-peer0datalock1-1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: auditor2-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.auditor2-net:7051
      localmspid: auditor2MSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      authpath: dev-testauditor2-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/auditor2-net/users/admin 
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/auditor2-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.orderer-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: datalock
      version: 1
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: emissionchannel
