apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: auditor2-cacerts-job
  namespace: auditor2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: auditor2-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: auditor2
      component_name: auditor2-net
      namespace: auditor2-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      authpath: devauditor2-net-auth
      secretcryptoprefix: secretsv2/data/crypto/peerOrganizations/auditor2-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/auditor2-net/ca/auditor2
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Auditor2/CN=ca.auditor2-net
