apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaincode-install-auditor2-peer0-1
  namespace: auditor2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: chaincode-install-auditor2-peer0-1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: auditor2-net
      network:
        version: 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.auditor2-net:7051
      localmspid: auditor2MSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://ae7339fc62cc9405db5036312ef6a0e5-1510386643.eu-west-1.elb.amazonaws.com:8200
      authpath: dev-testauditor2-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/auditor2-net/users/admin 
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/auditor2-net/orderer
      secretgitprivatekey: secretsv2/data/credentials/auditor2-net/git
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.orderer-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: emission
      version: 1
      lang: node
      maindirectory: 
      repository:
        hostname: "github.com"
        git_username: "adityajoshi12"
        url: github.com/adityajoshi12/bevel.git
        branch: main
        path: chaincode
      endorsementpolicies:  ''
