apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://ae7339fc62cc9405db5036312ef6a0e5-1510386643.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIPgytU5WlqrAtkswOWQ+xntQcKOKBmia+hBi+udzp8NPEt5cCttcCthcCngKWggBEAEaBgis
      7emXBiIKc3lzY2hhbm5lbCpAMjI2YzdmOTdlMTYwMzM3OGQwMzhjYzM1Yzc4M2E3YzBkZGNkZTc1
      NzMxMmY4Y2VmYzc4MDQ3NTY3MzFiNzBjORIaEhh0IbQDAOQD0rWABNwOrDq7Mt6Rzfmvf1wS21sK
      2FsS1VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVUt3TWJydTIxM1VQTC8yMFphdHM3bndaQzlBZ3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRVeE5URTJNalphRncweU5UQTJNRFF4TlRFMk1qWmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVF3end1Und0NWFXM2VvYlRMM3BwSTh6
      UUVMbUpEbEJ2RXN4OG9Ic1dLVWc4KzlUQzFuOTArTzByeDljQ2hrCm52dmlMT0VkMTVpaXFYVmxl
      bXZQamdKRm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVMFZ4ZXVzQXpOZFZnL3B0OER0dUxQZVgyU1NVd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdGaXFMRVU2VlV3SlcveVloakhEaHRYSHlFWXZwaURtaEdNUk11V2NNRUYwQ0lR
      Q3Vldk9hCm4rZlU5NUlMYXZlb0JtMWtUWnpVQWQ0U0lMMEQydEFUR1pCbDlBPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFEQ0NB
      bnVnQXdJQkFnSVRWYmN3bWVGdW9XNVlvOHFpaUVSWE9FVGJ6akFLQmdncWhrak9QUVFEQWpCYQpN
      UXN3Q1FZRFZRUUdFd0pIUWpFUE1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIy
      NWtiMjR4CkVEQU9CZ05WQkFvTUIwOXlaR1Z5WlhJeEZ6QVZCZ05WQkFNTURtTmhMbTl5WkdWeVpY
      SXRibVYwTUI0WERUSXkKTURneE5URTFNVGN3TUZvWERUSXpNRGd4TlRFMU1qSXdNRm93YURFTE1B
      a0dBMVVFQmhNQ1IwSXhHekFaQmdOVgpCQWNURWpVeExqVXdMeTB3TGpFekwweHZibVJ2YmpFUU1B
      NEdBMVVFQ2hNSFQzSmtaWEpsY2pFT01Bd0dBMVVFCkN4TUZZV1J0YVc0eEdqQVlCZ05WQkFNTUVV
      RmtiV2x1UUc5eVpHVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMEMKQVFZSUtvWkl6ajBEQVFjRFFn
      QUVxaS9tVUZUWHB2WWpiUStRS3V3ejFKcVBLUit4QmZBcXFETlpubUtad0tSagpYNXhYY2draWh0
      bU13N1BjcldtRDk2UkNzbXNOeCtXUENzVzZtVnlISjZPQ0FSQXdnZ0VNTUE0R0ExVWREd0VCCi93
      UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJGd29XSWFhK0FUZWltREhB
      ZGVGNm4KZXhzTkh6QWZCZ05WSFNNRUdEQVdnQlRSWEY2NndETTExV0QrbTN3TzI0czk1ZlpKSlRB
      a0JnTlZIUkVFSFRBYgpnaGxqWVMxMGIyOXNjeTAyTnpkbU9UbGlObU5rTFRSblpEUmlNSUdGQmdn
      cUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJcwpJbWhtTGxSNWNHVWlPaUpoWkcx
      cGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJ2VVJvT3FPRVpoa1BzCm9KWE9rd080cEJG
      NEx6OWJyTTlCb1IwYnQwVUliQUlnREpFcGdTeTZnQzlNbUdvMitsY3JjTUFNUEU0dVo0OXcKU01Q
      dk94dG5YY0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUt3TWJydTIxM1VQ
      TC8yMFphdHM3bndaQzlBZ3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRV
      eE5URTJNalphRncweU5UQTJNRFF4TlRFMk1qWmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVF3end1Und0NWFXM2VvYlRMM3BwSTh6UUVMbUpEbEJ2RXN4OG9I
      c1dLVWc4KzlUQzFuOTArTzByeDljQ2hrCm52dmlMT0VkMTVpaXFYVmxlbXZQamdKRm8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      MFZ4ZXVzQXpOZFZnL3B0OER0dUxQZVgyU1NVd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdGaXFM
      RVU2VlV3SlcveVloakhEaHRYSHlFWXZwaURtaEdNUk11V2NNRUYwQ0lRQ3Vldk9hCm4rZlU5NUlM
      YXZlb0JtMWtUWnpVQWQ0U0lMMEQydEFUR1pCbDlBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRlcmVyTVNQEAEa
      BkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9yZGVyZXIx
      Lm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBt
      Z0F3SUJBZ0lVVHhtY0hTWEZQcVlYSk5LWFlWQlZUZEh6THVFd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5
      TFc1bGREQWVGdzB5Ck1qQTRNVFV4TlRFM01EQmFGdzB5TXpBNE1UVXhOVEl5TURCYU1HMHhDekFK
      QmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFP
      QmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1U
      Rkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVlbGVEY3VaM0wwbjIxeHdlL3BaSzZ4YnlRQndJdDV4aXA4dlkKQ1hpREJPaGpaem4z
      c0kyS0JvTCs1Z0JuKzBNSjNoZzJhMllPbS9LTWNHeFUrYXd1dzZPQ0FTZ3dnZ0VrTUE0RwpBMVVk
      RHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdE
      QVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVnY0E2RlQwNTJPQ0RoVkFvNGpEZXRnVkp1
      Rjh3SHdZRFZSMGoKQkJnd0ZvQVUwVnhldXNBek5kVmcvcHQ4RHR1TFBlWDJTU1V3T3dZRFZSMFJC
      RFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNi
      M0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1a
      bWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXVi
      M0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9Q
      UVFEQWdOSUFEQkZBaUVBbmNwU1grQXpVZVFsSXVENTJzUDdYa2EwQmpSWnJSaldvbmlDClA1YVR4
      QlVDSUhNNXp6eUFlbDFEaUhpQ3R5WEgwaGlyMFp5RG1tOTcwSldzZUpjS2FhUlAKLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NB
      cG1nQXdJQkFnSVVUeG1jSFNYRlBxWVhKTktYWVZCVlRkSHpMdUV3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UVXhOVEUzTURCYUZ3MHlNekE0TVRVeE5USXlNREJhTUcweEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJB
      TVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpq
      MERBUWNEUWdBRWVsZURjdVozTDBuMjF4d2UvcFpLNnhieVFCd0l0NXhpcDh2WQpDWGlEQk9oalp6
      bjNzSTJLQm9MKzVnQm4rME1KM2hnMmEyWU9tL0tNY0d4VSthd3V3Nk9DQVNnd2dnRWtNQTRHCkEx
      VWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJ
      d0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVWdjQTZGVDA1Mk9DRGhWQW80akRldGdW
      SnVGOHdId1lEVlIwagpCQmd3Rm9BVTBWeGV1c0F6TmRWZy9wdDhEdHVMUGVYMlNTVXdPd1lEVlIw
      UkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1W
      c2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pF
      dWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtq
      T1BRUURBZ05JQURCRkFpRUFuY3BTWCtBelVlUWxJdUQ1MnNQN1hrYTBCalJaclJqV29uaUMKUDVh
      VHhCVUNJSE01enp5QWVsMURpSGlDdHlYSDBoaXIwWnlEbW05NzBKV3NlSmNLYWFSUAotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hT
      aXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlu
      cxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLvLgoLQ29uc29ydGl1bXMS3y4SlC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvUt
      EsgWCgthdWRpdG9yMU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVVVHWXpvN0pFc211cnR6
      K2VDMzY0WFFuSVBKVXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE5U
      RTFNVGMwTWxvWERUSTFNRFl3TkRFMU1UYzBNbG93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRW9DMHc3ZjN0M3VDTjRETVlyVCtDWm5nM2VYVlluQ1MvUWND
      RXVEV1AwUlZuL0trcmxkRjhqV1FuCnppVVNBSXNGYkdIOEhtQjQzVy9DVHB2V0VuKzk3Nk5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZFSzdrWWpBZFlCemV1YSt0QWxtRjNHSStPNTZNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFD
      a0hLbjJYanFkMjBuY3N1ZVRuaVZJQkNESmpTbUFpTUJJZ3I4Z1hIWDVqd0loCkFQUS8rSnA0UDBi
      c0hlQ0twME1iWDRMem1VRFJ5aHUycEFmTG9XbFYxUGwwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVQlVU
      TmcyNVNSK1o3djVicW42WFhUdG9YODlVd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd4TlRFMU1UZ3dNRm9YRFRJek1EZ3hOVEUxTWpNd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRUg4OGxDb3JlWERERXVEV24KN2JXbnB6V0ZRcnlEcHNuSGlQNWFiOUpF
      a29zV0k3ZSswdCtxemw3aXEzRWlNbnc4SVlpQmxHOTRzbnAwQlBJRgozNmtCWDZPQ0FSa3dnZ0VW
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlFi
      c2IyT0M5ZUdKTWprcmF1Sy9uYUFhMHdadVRBZkJnTlZIU01FR0RBV2dCUkN1NUdJd0hXQWMzcm0K
      dnJRSlpoZHhpUGp1ZWpBakJnTlZIUkVFSERBYWdoaGpZUzEwYjI5c2N5MWlPV05pWW1aaVpHUXRk
      blpuYW1JdwpnWThHQ0NvREJBVUdCd2dCQklHQ2V5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlP
      aUowY25WbElpd2lZV1J0CmFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmhk
      V1JwZEc5eU1TSXNJbWhtTGtWdWNtOXMKYkcxbGJuUkpSQ0k2SWtGa2JXbHVRR0YxWkdsMGIzSXhM
      VzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZB
      aUVBcUVXMG5iS2c2eGlySTUxQzVFTEpwajNBcEpmcW81WXZ0SjkyCk9rV3JBZGdDSUR6aUZVUlp4
      ZDFicFJMbm55Qm9LK2lDRXlIMFBvQldGSGowWkpxUDZPbDkKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      VENDQWFLZ0F3SUJBZ0lVVUdZem83SkVzbXVydHorZUMzNjRYUW5JUEpVd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd4TlRFMU1UYzBNbG9YRFRJMU1EWXdOREUxTVRjME1s
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFb0Mwdzdm
      M3QzdUNONERNWXJUK0NabmczZVhWWW5DUy9RY0NFdURXUDBSVm4vS2tybGRGOGpXUW4KemlVU0FJ
      c0ZiR0g4SG1CNDNXL0NUcHZXRW4rOTc2TkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkVLN2tZakFkWUJ6ZXVhK3RBbG1GM0dJK081
      Nk1Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUUNrSEtuMlhqcWQyMG5jc3VlVG5pVklCQ0RKalNt
      QWlNQklncjhnWEhYNWp3SWgKQVBRLytKcDRQMGJzSGVDS3AwTWJYNEx6bVVEUnlodTJwQWZMb1ds
      VjFQbDAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsS
      CBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYI
      ARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJBZ0lVVmE1NGxDZWpyM1FRblN6STlqNS9PZ2ZFc0Fvd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TlRFMU1UZzFPVm9YRFRJMU1E
      WXdOREUxTVRnMU9Wb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFdS9JMk5JK0NTUnd2ejdUVUtQZjdDNmJ1YjZOQkJkWTBTMU5iZWo2ZVFQaHVKU0k3b1d1
      c0t4ZTYKRlROdmFGNk8wTUk0cm42K2VaenZiN0pTVDZkNDY2TkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkxCWnV5WVREMkdhUGlK
      bEVMVmVON2crVm9xY01Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJQ2t6VHBBU2NMTjcrZTdBTnha
      TnJaSlAraUxuU2txak5DYUdXb3o3Q1FWakFpRUEKOTZwZXQyZ1dCQ3BRa0hraFdpM2tkaUU2MUFF
      RUV1NVpGZU9wTURsMnFuST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlUQ0NBcHVnQXdJQkFnSVVlUDZURjNNUnl5VGg3SDk0bzZj
      NWdtRGphOWd3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hOVEUxTWpB
      d01Gb1hEVEl6TURneE5URTFNalV3TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      QkExT1ZxK2N4NCsyaCt5agpjbUh2akhDcVprNUFKQkV0Uk50SXYwRmppaTdMS0hkUXB4bk1nODJX
      ZDVWSUZFTWxxWE8zZlVqTXdBVVpNV1FyCi9VdnFJQnFqZ2dFYU1JSUJGakFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVU5TWZZNnNvbDFSd2ZFVEhl
      NUllQitkWTNTTzR3SHdZRFZSMGpCQmd3Rm9BVXNGbTdKaE1QWVpvKwpJbVVRdFY0M3VENVdpcHd3
      SkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE9EVTFOV1ptWWpoaU5pMHliVFZvClp6Q0Jqd1lJ
      S2dNRUJRWUhDQUVFZ1lKN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmgK
      WkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNkltRjFaR2wwYjNJeUlpd2lh
      R1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFXNUFZWFZrYVhSdmNqSXRibVYwSWl3aWFHWXVW
      SGx3WlNJNkltRmtiV2x1CkluMTlNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJUUN4MkNtSHlPaElV
      UGZ4UTNmMXVjQVk0YmlTNkplbXVUTFQKSnk5a05hNGFId0lnZjdObVFYYml3MmlNUERia0RncDNi
      NnFiRDJDUzJoQlI5dE1TaDdHd0NZaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJB
      Z0lVVmE1NGxDZWpyM1FRblN6STlqNS9PZ2ZFc0Fvd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd4TlRFMU1UZzFPVm9YRFRJMU1EWXdOREUxTVRnMU9Wb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFdS9JMk5JK0NTUnd2ejdUVUtQ
      ZjdDNmJ1YjZOQkJkWTBTMU5iZWo2ZVFQaHVKU0k3b1d1c0t4ZTYKRlROdmFGNk8wTUk0cm42K2Va
      enZiN0pTVDZkNDY2TkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRkxCWnV5WVREMkdhUGlKbEVMVmVON2crVm9xY01Bb0dDQ3FHClNN
      NDlCQU1DQTBnQU1FVUNJQ2t6VHBBU2NMTjcrZTdBTnhaTnJaSlAraUxuU2txak5DYUdXb3o3Q1FW
      akFpRUEKOTZwZXQyZ1dCQ3BRa0hraFdpM2tkaUU2MUFFRUV1NVpGZU9wTURsMnFuST0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggAGg8S
      DQoLYXVkaXRvcjJNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAaERIPCgth
      dWRpdG9yMk1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP//
      //8PGgZBZG1pbnMaSgoQT3JkZXJlckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0
      OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJf
      MBIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
