apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: devorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaINDsDlqYSSaKdR8cHwqwrEv15i1DJ3TM7OlxwMfmBfwwEtZcCtNcCtBcCngKWggBEAEaBgjk
      tr2XBiIKc3lzY2hhbm5lbCpAODczMTc2NDA4MDlmNjgzYzliZTRiY2Y5OTBkZTk4ZDMxMjBjNzNi
      MDkxNzRlOTgyZDdiYWQwNDAwZjZhNjc2YxIaEhhUbPdnkRFNzf5GMy04pnWQxFBQac/8gKoS01sK
      0FsSzVsSmyoKB09yZGVyZXISjyoSihYKCm9yZGVyZXJNU1AS+xUalxQKA01TUBKPFBKEFBKBFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVUZrelEzWmZYdHI4bDM4K2l6RVEwZmRMa1hkc3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURjd05qRTJNRE5hRncweU5UQTFNamN3TmpFMk1ETmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJlMFN2Z1lGNzRCeFJXOGRBckQxWUJB
      YkZSejNtZExRZ0xHY1c3cVdJcWErc0M1NVpGYUMxaVpIbENzclBvClFhUTc1c0JnREd6L0hWYVlF
      LzFXZS8wM28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVSEg2Yit1cUl1Y0xPaE1EaHUraG1nWjRPMWtvd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdKTTcyQldCMjh3SEQyN2FuMTNIa2RPWWhjRm9zYzBDb25JWURtK1hxWjdnQ0lG
      aTh2dkZwCmRtRmxKU2kya2ZsN1ExYzJJenBkOEd2cU14SnJUSDNQUXdpWAotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKSCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMURDQ0FudWdB
      d0lCQWdJVVdEZG93Z09vV2xyTkdDMGltcXMvbHhrTVNZWXdDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TURjd05qRTVNREJhRncweU16QTRNRGN3TmpJME1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJB
      UHV4WWFDWlRBMHB6eEZPRnVLSUxVQ3VYdnNsNnhYOGEwTlZseWNKa3ZpCjVxNS9ZLzNkNlFOd25E
      Y3IyV0lvUm1CcUljbm5XbjF6NUlnMUZBR0x4Q3FqZ2dFUE1JSUJDekFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVvRjMySGJ0emV4TTd4Z2h2ZVdY
      TwptTkpFVWpVd0h3WURWUjBqQkJnd0ZvQVVISDZiK3VxSXVjTE9oTURodStobWdaNE8xa293SXdZ
      RFZSMFJCQnd3CkdvSVlZMkV0ZEc5dmJITXROVGxtT0RVM1kyWTBMWEkyYldKNE1JR0ZCZ2dxQXdR
      RkJnY0lBUVI1ZXlKaGRIUnkKY3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0
      aU9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cApZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1
      MFNVUWlPaUpCWkcxcGJrQnZjbVJsY21WeUxXNWxkQ0lzCkltaG1MbFI1Y0dVaU9pSmhaRzFwYmlK
      OWZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQnpVMlNZdFd2ZnB6MGEKM2x2eHRVSU81cEpsNno2
      c2RETHFkYnczRHEyeXZnSWdLTUh4b2RmMnlrRkFWNnAxREdoNVIranpyTGRHdVVqQQoxRUlWY2Nl
      OGppUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVRmt6UTNaZlh0cjhsMzgr
      aXpFUTBmZExrWGRzd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNRGN3TmpF
      Mk1ETmFGdzB5TlRBMU1qY3dOakUyTUROYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEps
      Y2pFWApNQlVHQTFVRUF3d09ZMkV1YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DCkFBUmUwU3ZnWUY3NEJ4Ulc4ZEFyRDFZQkFiRlJ6M21kTFFnTEdjVzdxV0lx
      YStzQzU1WkZhQzFpWkhsQ3NyUG8KUWFRNzVzQmdER3ovSFZhWUUvMVdlLzAzbzBJd1FEQVBCZ05W
      SFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVISDZi
      K3VxSXVjTE9oTURodStobWdaNE8xa293Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0pNNzJCV0Iy
      OHdIRDI3YW4xM0hrZE9ZaGNGb3NjMENvbklZRG0rWHFaN2dDSUZpOHZ2RnAKZG1GbEpTaTJrZmw3
      UTFjMkl6cGQ4R3ZxTXhKclRIM1BRd2lYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1TUBABGgZBZG1pbnMi
      NwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMi
      MwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyIzCgdX
      cml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zKgZBZG1pbnMa
      IgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoC
      MnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRp
      ZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIRErcRCghldGNkcmFm
      dBKqEQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQzhqQ0NBcG1nQXdJQkFnSVVGcjBUVXBNakJ1dmZpTDg1em5iaXJaSTdJckV3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFR
      RERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1EY3dOakU1TURCYUZ3MHlNekE0TURj
      d05qSTBNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0
      eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdW
      eVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29a
      SXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXcxN05wQWIzN0orY0FZK2Y5am5HTFB1WFJYeVlKeHM1
      UWNxMQovd2pPS0p6NnhnWDh0aWNoR0Z5NzZxbXhiNWRreUJvMDc3aTg0TnptdFR2Y3Y3RzVaNk9D
      QVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNE
      QVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVXZ0YmVuMGox
      bmxGN0pTa2xkN0RTeHppMnRlZ3dId1lEVlIwagpCQmd3Rm9BVUhINmIrdXFJdWNMT2hNRGh1K2ht
      Z1o0TzFrb3dPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5
      WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYw
      ZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxF
      SWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxj
      aUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQkNWd054MEdwRjBmSG5hNGQ0T1NoTU90Z0Iy
      WFlhQmJBczVqK0IKTEhMRjhBSWdGYlpvaTJRWWtkQVoxRzRyVzFpVGJSR000QmVMeU1Qd3MrUS9z
      SDBEQ2E4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVUZyMFRVcE1qQnV2ZmlMODV6bmJpclpJN0lyRXdD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURW
      UVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURjd05qRTVNREJhRncweU16QTRN
      RGN3TmpJME1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRN
      QzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXla
      R1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApL
      b1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFdzE3TnBBYjM3SitjQVkrZjlqbkdMUHVYUlh5WUp4
      czVRY3ExCi93ak9LSno2eGdYOHRpY2hHRnk3NnFteGI1ZGt5Qm8wNzdpODROem10VHZjdjdHNVo2
      T0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJR
      Y0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVdnRiZW4w
      ajFubEY3SlNrbGQ3RFN4emkydGVnd0h3WURWUjBqCkJCZ3dGb0FVSEg2Yit1cUl1Y0xPaE1EaHUr
      aG1nWjRPMWtvd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dt
      OXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0lt
      RjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRF
      bEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhK
      bGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCQ1Z3TngwR3BGMGZIbmE0ZDRPU2hNT3Rn
      QjJYWWFCYkFzNWorQgpMSExGOEFJZ0ZiWm9pMlFZa2RBWjFHNHJXMWlUYlJHTTRCZUx5TVB3cytR
      L3NIMERDYTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAga
      BkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1pbnMS7y4K
      C0NvbnNvcnRpdW1zEt8uEpQuChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL1LRLIFgoLYXVk
      aXRvcjFNU1ASuBYa0BQKA01TUBLIFBK9FBK6FAoLYXVkaXRvcjFNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVlTnJOaTUzOXB3VjNTV1B5VVQ4YjlZ
      Y0FrT0F3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3dOekEyTVRjeE9W
      b1hEVEkxTURVeU56QTJNVGN4T1Zvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUVtZHdHMzRETHNQY1J3ZzFvdHYyU0lKUEQ0R2t2ZDlmMDZ6VFF6RXFLZEFl
      Q0dxRkpoM28vUzRFUQo2Rk1jK2RHUGtZVjdNZmkvVHhnQzR2MVJRR1gwUEtOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQ1A5MmpX
      a0liUXhWcm9WVUNFTlBHNjk0Mm5OTUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lRREU2R0tkWVdn
      dDk2ZkozQ1Y4dTBiNStXVmtESXVWUHRaK3VDMUVCdk5LTHdJZwpjVVpmc2k2QkVndWUrWGdXWlZm
      TlhMUnlWdDZmd0tSckRmMGZNUlUrcDFNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwcWdBd0lCQWdJVVhuU3lBYk1DN3Ew
      eFhBSkxINVVxeUpFMEFCVXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURn
      d056QTJNakF3TUZvWERUSXpNRGd3TnpBMk1qVXdNRm93ZWpFTE1Ba0dBMVVFQmhNQ1EwZ3hHakFZ
      CkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdoQmRXUnBkRzl5
      TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRFYk1Ca0dBMVVF
      QXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUU0NkNzRVRGNVFqejJjdjcwCnpFOFJMZG9tMlpTY3hnbEFPWWZHNlh1R3dZYmxJKzI5
      RVRraXR4b250QnFBZms4YkNOWUxVYTBvVUZYVW9tOHUKVmJMS3c2T0NBUm93Z2dFV01BNEdBMVVk
      RHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJTQ2dZWjBZMVNL
      M1hkT010RlB1V016M1lZSm1EQWZCZ05WSFNNRUdEQVdnQlFqL2RvMXBDRzBNVmE2CkZWQWhEVHh1
      dmVOcHpUQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAyT0dabU56WTFaamsyTFhSd2VuZDQK
      TUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFa
      U0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWVhWa2FYUnZj
      akVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5TVMxdVpYUWlM
      Q0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ1cvQzlS
      Ui8zUTZKdEtxNVU0d1lRWVBOSzl2T3RYdGFxMHRVeApLdDJxUDBBQ0lINEVlYkdoYkVNRFlCTDJX
      Nk9xNnpCemFaR2FzWnN5VFR3ZEdFSHczNmZRCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4K
      BFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dB
      d0lCQWdJVWVOck5pNTM5cHdWM1NXUHlVVDhiOVljQWtPQXdDZ1lJS29aSXpqMEVBd0l3ClhERUxN
      QWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFX
      Tm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      RXRibVYwTUI0WApEVEl5TURnd056QTJNVGN4T1ZvWERUSTFNRFV5TnpBMk1UY3hPVm93WERFTE1B
      a0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFX
      Tm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      RXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRW1kd0czNERMc1BjUndn
      MW90djJTSUpQRDRHa3ZkOWYwNnpUUXpFcUtkQWVDR3FGSmgzby9TNEVRCjZGTWMrZEdQa1lWN01m
      aS9UeGdDNHYxUlFHWDBQS05DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFm
      OEVCQU1DQWFZd0hRWURWUjBPQkJZRUZDUDkyaldrSWJReFZyb1ZVQ0VOUEc2OTQybk5NQW9HQ0Nx
      RwpTTTQ5QkFNQ0EwZ0FNRVVDSVFERTZHS2RZV2d0OTZmSjNDVjh1MGI1K1dWa0RJdVZQdFordUMx
      RUJ2TktMd0lnCmNVWmZzaTZCRWd1ZStYZ1daVmZOWExSeVZ0NmZ3S1JyRGYwZk1SVStwMU09Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYI
      ARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoR
      Eg8KC2F1ZGl0b3IxTVNQEAEaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9yMk1TUBK8FhrUFAoD
      TVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL0RDQ0FhS2dBd0lCQWdJVVFEdGw3d2RMcVdVOUh5bkVSU3ZwL2U4MkJJTXdDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURnd056QTJNVGd6TjFvWERUSTFNRFV5TnpBMk1U
      Z3pOMW93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRXZF
      N0tlWVk0Zktob0JNY0gxZGdhdDdad0dEVUhaUDh4aElLWW9iUDlyVDhaWlNWeWhiMURqUWhqCks3
      VlpDOE5nWUFoUGI2K1Rsa1NCN0d1TTJTRmdSYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZDVWIvM0MxNGZjL2VNTENDS0t4bnFW
      MG5YOGxNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFEMFZFazd1LzNvMU1LQzRZa2h1em12WjlG
      MG83b1UzZ3FrUko1N0prWWpKd0lnClJRQWFmTEtSVkk5QU1md2t3eWk3aWl5N0pYQ3BoKyswVHNv
      TlB0Z1hJd289Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM5VENDQXB1Z0F3SUJBZ0lVSW1xVnN2NXNKb2t2SHFoUzRJZlRCTE9WTStV
      d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZ
      R0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3TnpBMk1qSXdNRm9YRFRJ
      ek1EZ3dOekEyTWpjd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdOVkJBY1RFalV4TGpV
      d0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4SHpBTQpCZ05WQkFz
      VEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1NRWtGa2JXbHVRR0Yx
      ClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJYklqQzB3
      U2FJSXRiQVYKQ09jWjdYNjRtVmFjeWVDUjRmZ0Z6REoxZzF1cjB5WW5QTm0vZkFwTk83Z0VHYTlC
      cWp0bWtNQXd3KzN5azNDbApvdU5jVHNtamdnRWFNSUlCRmpBT0JnTlZIUThCQWY4RUJBTUNCNEF3
      REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVcHZrb252ZjU1NVpDSXl1NnYvVFptU094
      UGQwd0h3WURWUjBqQkJnd0ZvQVVKUnYvY0xYaDl6OTQKd3NJSW9yR2VwWFNkZnlVd0pBWURWUjBS
      QkIwd0c0SVpZMkV0ZEc5dmJITXROelprTkRjNE9EUTJOQzAzT1RWdwpjVENCandZSUtnTUVCUVlI
      Q0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlMQ0poClpHMXBiaUk2
      SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJaXdpYUdZdVJXNXkK
      YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJ
      bUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEVDZWc2xuRzRUU3k1VzRDamxK
      Q2N4Vm9iS0s5ZDJkOEFwCk92R1VSbmZIZ1FJZ0V4bjB6aGYxVk9lRllYTWtOb3NoSC9NSDIxNkNY
      YUd5b3RTc3JEcjk3K3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1
      NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVVFEdGw3
      d2RMcVdVOUh5bkVSU3ZwL2U4MkJJTXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURW
      UVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApE
      VEl5TURnd056QTJNVGd6TjFvWERUSTFNRFV5TnpBMk1UZ3pOMW93WERFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZR
      UUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3
      WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRXZFN0tlWVk0Zktob0JNY0gxZGdhdDdad0dE
      VUhaUDh4aElLWW9iUDlyVDhaWlNWeWhiMURqUWhqCks3VlpDOE5nWUFoUGI2K1Rsa1NCN0d1TTJT
      RmdSYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hR
      WURWUjBPQkJZRUZDVWIvM0MxNGZjL2VNTENDS0t4bnFWMG5YOGxNQW9HQ0NxRwpTTTQ5QkFNQ0Ew
      Z0FNRVVDSVFEMFZFazd1LzNvMU1LQzRZa2h1em12WjlGMG83b1UzZ3FrUko1N0prWWpKd0lnClJR
      QWFmTEtSVkk5QU1md2t3eWk3aWl5N0pYQ3BoKyswVHNvTlB0Z1hJd289Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1
      ZGl0b3IyTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0
      b3IyTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggAGhESDwoLYXVkaXRvcjJN
      U1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRv
      cjJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZB
      ZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyIt
      CgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZ
      QmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpKChBPcmRlcmVyQWRk
      cmVzc2VzEjYSGwoZb3JkZXJlcjEub3JkZXJlci1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIO
      CAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlu
      cyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoA
      CgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
