apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a7e9892a5136f4fa8b1cda6ba31b358b-1780904258.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIE3bPlE5SAWV2BXBbM1A8sZLPWeOE9OkdA/oznP9z1eyEtpcCtdcCtRcCngKWggBEAEaBgiA
      qMqXBiIKc3lzY2hhbm5lbCpANWZiNWZjOGViMDc4NzVmMTRiN2U0OTJiNTUxYmY4MmYzNWQwNmIz
      NjUzYThmZDQ4ZTE4ZWE1YTBjNDU1YmFmYhIaEhj9aPOlT24SYa8ZX66RH8hESckUKIZskXkS11sK
      1FsS0VsSmyoKB09yZGVyZXISjyoSihYKCm9yZGVyZXJNU1AS+xUalxQKA01TUBKPFBKEFBKBFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVVBsZnNiN3A5RU1qYUZYc25yUVhXVUtZdktRSXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURreE5qSTFNREphRncweU5UQTFNamt4TmpJMU1ESmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRnb1NrUkRjeE9Lc2JDV1gxRCtzb25I
      MlhBeUxGTnJvRUhTMWhKemlMWVdTcGJYU2JtNVZyU3pnOGRFaWZmCkVRQ2lWNVBjdUMxN0VBY3ZM
      QnMzTEVEYW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVcVA3NWR3SnVSQ21zWDJtUnpCMW9WQ2lVWlBjd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdBUGY5aWEyaWRkWHRWRklRcjZxWi9EL3BvUVRpdnhUckJNREZGUVV0MjhVQ0lB
      UkpGTFNlCms1a1hJWUt6NkdHb0VpOTJ1c2dOcXB0dFJrQnhxTCtXTGpyZgotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKSCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMVRDQ0FueWdB
      d0lCQWdJVVBVaVBPYTUrd0FPUkdFdlFhQXF1MnZDSEdHd3dDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TURreE5qTXdNREJhRncweU16QTRNRGt4TmpNMU1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJM
      TjdxOGJVQlZ3WnNQNmxrNDBSOTltaUVyRzBBRUhvMWQvWk9VV1ovblpUCk5ueCtrWGZqUkNMb0VH
      Z2c2c1AvcGhhZDM5QmVrTzd1K3hyKzdIeHJEdDZqZ2dFUU1JSUJEREFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV6NHVTMS9HZW01bmh4LzQzWVhv
      eQpqL0dRNkRJd0h3WURWUjBqQkJnd0ZvQVVxUDc1ZHdKdVJDbXNYMm1SekIxb1ZDaVVaUGN3SkFZ
      RFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROVGcxTm1Oa1pqaGpOQzAxYWpWMGREQ0JoUVlJS2dN
      RUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYlds
      dUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdJUkZEb3hhQUMyMVkKc0tZWFdPYXc2enVnQ0pG
      YzErbHlEOTdFZGdzL3RYWUNJQUMxM21HdkloTDFjWUVQcHpVVUs5ODBlN2phbXBFTgp2WWQ2VmZx
      N2kzT20KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVUGxmc2I3cDlFTWphRlhz
      bnJRWFdVS1l2S1FJd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNRGt4TmpJ
      MU1ESmFGdzB5TlRBMU1qa3hOakkxTURKYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEps
      Y2pFWApNQlVHQTFVRUF3d09ZMkV1YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DCkFBVGdvU2tSRGN4T0tzYkNXWDFEK3NvbkgyWEF5TEZOcm9FSFMxaEp6aUxZ
      V1NwYlhTYm01VnJTemc4ZEVpZmYKRVFDaVY1UGN1QzE3RUFjdkxCczNMRURhbzBJd1FEQVBCZ05W
      SFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVxUDc1
      ZHdKdVJDbXNYMm1SekIxb1ZDaVVaUGN3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0FQZjlpYTJp
      ZGRYdFZGSVFyNnFaL0QvcG9RVGl2eFRyQk1ERkZRVXQyOFVDSUFSSkZMU2UKazVrWElZS3o2R0dv
      RWk5MnVzZ05xcHR0UmtCeHFMK1dManJmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1TUBABGgZBZG1pbnMi
      NwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMi
      MwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyIzCgdX
      cml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zKgZBZG1pbnMa
      IgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoC
      MnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRp
      ZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIRErcRCghldGNkcmFm
      dBKqEQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQzhqQ0NBcG1nQXdJQkFnSVVJZ3BZcENDaVNmTjZDZzhYSU9GbUZvOTQzQmt3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFR
      RERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1Ea3hOak13TURCYUZ3MHlNekE0TURr
      eE5qTTFNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0
      eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdW
      eVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29a
      SXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWVpVGJscHl4RU44V2o3TlhyUUttbmU4dCt6K0RJcklR
      UUppdQpDdGxHYzFDekNZcmhDNzdqbWxJTC9nZHRmOU1nQWRiV1EweGdxSVZHQ0hhUndnYVJWcU9D
      QVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNE
      QVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVWtHbjBkeHJC
      ZTYwNHcrRUp5RDQrNHRnamNMRXdId1lEVlIwagpCQmd3Rm9BVXFQNzVkd0p1UkNtc1gybVJ6QjFv
      VkNpVVpQY3dPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5
      WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYw
      ZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxF
      SWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxj
      aUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQjYvMGE1TnVMVnM1L3U0MC9uVVFTbzZjek9l
      dDR4QkticlBvVlEKdEJWVElnSWdDSDRTYTE4OUkxTW54aitkd0NlK0tiSUd6SDhwaHNNbGwxWWtt
      di8wMkhJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVUlncFlwQ0NpU2ZONkNnOFhJT0ZtRm85NDNCa3dD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURW
      UVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURreE5qTXdNREJhRncweU16QTRN
      RGt4TmpNMU1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRN
      QzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXla
      R1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApL
      b1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZWlUYmxweXhFTjhXajdOWHJRS21uZTh0K3orREly
      SVFRSml1CkN0bEdjMUN6Q1lyaEM3N2ptbElML2dkdGY5TWdBZGJXUTB4Z3FJVkdDSGFSd2dhUlZx
      T0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJR
      Y0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVa0duMGR4
      ckJlNjA0dytFSnlENCs0dGdqY0xFd0h3WURWUjBqCkJCZ3dGb0FVcVA3NWR3SnVSQ21zWDJtUnpC
      MW9WQ2lVWlBjd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dt
      OXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0lt
      RjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRF
      bEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhK
      bGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCNi8wYTVOdUxWczUvdTQwL25VUVNvNmN6
      T2V0NHhCS2JyUG9WUQp0QlZUSWdJZ0NINFNhMTg5STFNbnhqK2R3Q2UrS2JJR3pIOHBoc01sbDFZ
      a212LzAySEk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAga
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlk
      YXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMS8y4K
      C0NvbnNvcnRpdW1zEuMuEpguChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL5LRLMFgoLYXVk
      aXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQi9UQ0NBYUtnQXdJQkFnSVVhRUl3TDlOM1JrenFtM0V2ZnVxOGIw
      UENwZG93Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3dPVEUyTWpZeE9G
      b1hEVEkxTURVeU9URTJNall4T0Zvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUViTEpXYmNYWEVLWEplN2RLT1dHaVRpbmVPMDg1cldiZW9heS9zL2tKWkNZ
      dTJLdUpSeVN2d1RRQwpmQ2o5akh4emRTbDVHTFJidXExTEN2aWJleENlMjZOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQUZVcDl1
      NkQ0WWEraWtoTWQ2d0dhMDJLcCt3TUFvR0NDcUcKU000OUJBTUNBMGtBTUVZQ0lRRHc1WW4zUTd6
      bUdtbk4wSmhMQ3FTZXVNdDBpRUhyRDRQdGFHajkwTFIzdmdJaApBSi9pc0R5azlsQ2R5QSthckN4
      WHppY0lRV0ROU2k4Q29Qd1BWenJQdE5RUQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJVUNBeFlEUjBEb0tV
      dDlOV2hvcnF1R1FYaTJzY3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURn
      d09URTJNek13TUZvWERUSXpNRGd3T1RFMk16Z3dNRm93ZWpFTE1Ba0dBMVVFQmhNQ1EwZ3hHakFZ
      CkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdoQmRXUnBkRzl5
      TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRFYk1Ca0dBMVVF
      QXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUUxL21Lc1A1YlR6TDV6bDlvCjNwRUp4a0p5N1ErdGFmMDB1Q01iaDdYV2hGK25FeVpS
      dTU4K3F2bXh1TDMxZmNZd09VeTlERC9XK2V6MTNpK3AKSVl4QXA2T0NBUm93Z2dFV01BNEdBMVVk
      RHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJSYnhSZzJSNFpl
      aStuNWNsRE5DSXZTc0NRSnl6QWZCZ05WSFNNRUdEQVdnQlFCVktmYnVnK0dHdm9wCklUSGVzQm10
      TmlxZnNEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzT1dNME4yWTJZMlE0TFRneU1uQjAK
      TUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFa
      U0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWVhWa2FYUnZj
      akVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5TVMxdVpYUWlM
      Q0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFJNXpI
      aHpZNjJRajAxaGUzdGYzU3A0R0V2V2FqYTFtZCtCWQovb3RjbDM2dEFpQnBsMzVGT1lkcWRUV21C
      NFIrUmdabDBzbjdKMmlpaG1nS3o5YmJXaEdqUUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      CkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9UQ0NB
      YUtnQXdJQkFnSVVhRUl3TDlOM1JrenFtM0V2ZnVxOGIwUENwZG93Q2dZSUtvWkl6ajBFQXdJdwpY
      REVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1CNFgKRFRJeU1EZ3dPVEUyTWpZeE9Gb1hEVEkxTURVeU9URTJNall4T0Zvd1hE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUViTEpXYmNYWEVL
      WEplN2RLT1dHaVRpbmVPMDg1cldiZW9heS9zL2tKWkNZdTJLdUpSeVN2d1RRQwpmQ2o5akh4emRT
      bDVHTFJidXExTEN2aWJleENlMjZOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhR
      OEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQUZVcDl1NkQ0WWEraWtoTWQ2d0dhMDJLcCt3TUFv
      R0NDcUcKU000OUJBTUNBMGtBTUVZQ0lRRHc1WW4zUTd6bUdtbk4wSmhMQ3FTZXVNdDBpRUhyRDRQ
      dGFHajkwTFIzdmdJaApBSi9pc0R5azlsQ2R5QSthckN4WHppY0lRV0ROU2k4Q29Qd1BWenJQdE5R
      UQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYI
      ARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgII
      ABoREg8KC2F1ZGl0b3IxTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMqBkFkbWlucxLMFgoLYXVkaXRvcjJNU1ASvBYa
      1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVLRGxMZThDQ29pbS81VnVYN3V2dnFmWmVUVnN3Q2dZSUtv
      Wkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3dPVEUyTWpjek5Gb1hEVEkxTURVeU9U
      RTJNamN6TkZvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFn
      QUVBWjhBMFJKRGJHU2hkZlNONUhMV1FjcEE4VG9VcjdPV0J3em8vOFRDdzd4WVdtUlZEK1oxVEVP
      MgpFN2pJVFYzblBYeUp4RXpRYlJsTkpNbWI3eE1LTmFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdF
      Qi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGSk9vbno2M1V3Y1pWUUJJQnoy
      TW9Zb1FqcEdoTUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lDcmdIalB6WTd1bXlQcmgzM1JoNGtF
      UlFwNU04SDBxTVRleVdBNGZQQnRkQWlFQQpycWo0dXdLVkQ3bVhiY3dmREVNQzBFcGJTWVZaR1lo
      SU8wZzVTVkFyU0xnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOVRDQ0FwdWdBd0lCQWdJVU4yTVZ3eW5DNklaZlBKMEsrMzJLK1pW
      cXBmNHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpF
      WU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURnd09URTJNelV3TUZv
      WERUSXpNRGd3T1RFMk5EQXdNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFaCkJnTlZCQWNURWpV
      eExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2Y2pJeEh6QU0KQmdO
      VkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05WQkFNTUVrRmtiV2x1
      UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRXZ1
      WVEwYzdxQkowVm5BCjRORHZXUlM4eHBhczkyKzdrd1k5MXBiZGs5c20rcGF4VVQ2WFlNS0xOYTUx
      RURWcnRyWjBYVFRRQ0dVNXpEOFYKUWVTamlST2pnZ0VhTUlJQkZqQU9CZ05WSFE4QkFmOEVCQU1D
      QjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVXAzY1dSN3BSZ2JManNWTnR5NkZT
      eC9ZVk15UXdId1lEVlIwakJCZ3dGb0FVazZpZlByZFRCeGxWCkFFZ0hQWXloaWhDT2thRXdKQVlE
      VlIwUkJCMHdHNElaWTJFdGRHOXZiSE10TlRrM1pEVmpZelE1TkMxcmRuUjAKWnpDQmp3WUlLZ01F
      QlFZSENBRUVnWUo3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaApaRzFw
      YmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1GMVpHbDBiM0l5SWl3aWFHWXVS
      VzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlYVmthWFJ2Y2pJdGJtVjBJaXdpYUdZdVZIbHda
      U0k2SW1Ga2JXbHUKSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ2dWakZiT1Y5SWIyRisz
      TzY2cXRPTjV1WTY1Z2pkUGg4LwpYY2I3UkJ4WWNBSWdkUEI0Z2NHWHJZb2NuZG5oRnc3bHF4NmJB
      Z1VnTDNTdDZ5Qk1TbThFMStVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZT
      SEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVL
      RGxMZThDQ29pbS81VnVYN3V2dnFmWmVUVnN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdE
      d1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1C
      NFgKRFRJeU1EZ3dPVEUyTWpjek5Gb1hEVEkxTURVeU9URTJNamN6TkZvd1hERUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1G
      a3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVBWjhBMFJKRGJHU2hkZlNONUhMV1Fj
      cEE4VG9VcjdPV0J3em8vOFRDdzd4WVdtUlZEK1oxVEVPMgpFN2pJVFYzblBYeUp4RXpRYlJsTkpN
      bWI3eE1LTmFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0Fh
      WXdIUVlEVlIwT0JCWUVGSk9vbno2M1V3Y1pWUUJJQnoyTW9Zb1FqcEdoTUFvR0NDcUcKU000OUJB
      TUNBMGdBTUVVQ0lDcmdIalB6WTd1bXlQcmgzM1JoNGtFUlFwNU04SDBxTVRleVdBNGZQQnRkQWlF
      QQpycWo0dXdLVkQ3bVhiY3dmREVNQzBFcGJTWVZaR1loSU8wZzVTVkFyU0xnPQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxINCgth
      dWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoREg8KC2F1ZGl0
      b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1
      ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMS
      CAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMaSgoQT3JkZXJlckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVy
      ZXItbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoK
      CAoEVjJfMBIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5z
      Gi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoA
      CgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
