apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a7e9892a5136f4fa8b1cda6ba31b358b-1780904258.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBSOykVRJDVuoblmpG/u8tZrq9z1dNnI9PjCcFhdoZbWEuJcCt9cCtxcCngKWggBEAEaBgi3
      gcqXBiIKc3lzY2hhbm5lbCpAMzVhOTNjYWYzZTVhNGM2YzNiMGFlZmY0OGEzMzI4ZjU5N2JiMjRk
      ODA3YTAyMTRhMTQ1NGI3OTFiYzMyNWNkMxIaEhhxL/SqqGu7Y02tK9vLFyHqJnIXcuN5xaUS31sK
      3FsS2VsSpyoKB09yZGVyZXISmyoSlhYKCm9yZGVyZXJNU1AShxYaoxQKA01TUBKbFBKQFBKNFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVVFrb3krTHRaNXhhRm54OWFjUGhuKzQyUWpxTXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURreE5UTTFNRFphRncweU5UQTFNamt4TlRNMU1EWmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFlQTRqY3ZaRjBnYVp6ZUJEOUNwTEVS
      V1F0NGZscEdJSmo2YUdlTlN4ZXlTazJGVFFzYVpWREhrTFFVMEQ1CnIra0EyTENXTURGVW1EVlhQ
      YVNFNHR6d28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVQ1QxSi82c0lvVVRaZVhldG1OdDZhaVJxdEw0d0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdOcCtqb3V1UHJKMVo4YkZBSXN2aTRGbVplS05CVjZWQk9ZMXZ2dEF2ZFRJQ0lR
      Q1pmSHNpCmZFT3UvODZPeXVCSVhUQzZCaEZIMGJRQStQTFhWNG5jek9SK0JnPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoilggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFqQ0NB
      bnlnQXdJQkFnSVVMd2lVK3gwdGRPMTlUTzNQVjRUVlY5Tnl1TU13Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1Ea3hOVE0wTURCYUZ3MHlNekE0TURreE5UTTVNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCQTAxdGdydnRDR0p4QjVzQXNMSnNIZFR2UC82MVBjTlR6c3RlNml4aGptRgpEaGZueDVqT1gw
      Tm9EV3Z6bEs0NmRXWVRlYVZSVVJ5QzloYkdYUnNpSi9LamdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVMnhMaDljaUc3WWxMY2lq
      eFhmVXMKRmtHYnhIa3dId1lEVlIwakJCZ3dGb0FVQ1QxSi82c0lvVVRaZVhldG1OdDZhaVJxdEw0
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TlRnMU5tTmtaamhqTkMwME5IZzRjekNCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUkwd1NJc0cvODFmCjV4MDBPTmRnL3ZO
      aDJlRTB4MVNoUTJ4Vi96YUNCZ0FJQWlBTTlmb3ZqaTIxVUZrVTlOQmNCTjFGLy9nVWhnVDAKV3FZ
      OFlwTXN6WGdHcVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK
      6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVRa295K0x0
      WjV4YUZueDlhY1Bobis0MlFqcU13Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpB
      NE1Ea3hOVE0xTURaYUZ3MHlOVEExTWpreE5UTTFNRFphTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3
      RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dI
      VDNKa1pYSmxjakVYCk1CVUdBMVVFQXd3T1kyRXViM0prWlhKbGNpMXVaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRZUE0amN2WkYwZ2FaemVCRDlDcExFUldRdDRmbHBHSUpq
      NmFHZU5TeGV5U2syRlRRc2FaVkRIa0xRVTBENQpyK2tBMkxDV01ERlVtRFZYUGFTRTR0endvMEl3
      UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRF
      RmdRVUNUMUovNnNJb1VUWmVYZXRtTnQ2YWlScXRMNHdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUln
      TnAram91dVBySjFaOGJGQUlzdmk0Rm1aZUtOQlY2VkJPWTF2dnRBdmRUSUNJUUNaZkhzaQpmRU91
      Lzg2T3l1QklYVEM2QmhGSDBiUUErUExYVjRuY3pPUitCZz09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRl
      cmVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJN
      U1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRt
      aW5zKgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxrUEQoNQ29u
      c2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9yZGVyZXIxLm9yZGVyZXItbmV0EIo3
      GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVR05pT0oz
      VlZQbDIyeTN6R0JNeHI2WFdETnVjd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1q
      QTRNRGt4TlRNME1EQmFGdzB5TXpBNE1Ea3hOVE01TURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJz
      d0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdW
      eVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05
      eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVtdTJBdEc4
      RHArMkJBY2k4MTZyTVRBallhdjZrQVo3KzA2NVEKTVdZQ2tLNTRiNEJkL1VwbHVWRExpUWNlNkV1
      U1ZZbnB1VGZDSWNvN2FXbmQ2VjN4aDZPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURB
      ZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJ
      d0FEQWRCZ05WSFE0RUZnUVU4SW5MNzJPU3hTSTZ6MWYzOU1YSUtIbVdRMjB3SHdZRFZSMGoKQkJn
      d0ZvQVVDVDFKLzZzSW9VVFplWGV0bU50NmFpUnF0TDR3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEps
      Y2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0
      TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFp
      TENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVB
      b28wdVU2dkFXbHFvTzZheVVqNjFlNFdiRDdVZXBieGlKZlB1CjJFbGNYcjBDSUFKZkdmei9mSjFF
      RURFMUdnWHFtTjhUQmErNm9uUHFOYVhkL2hWL3orQ3UKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NBcG1nQXdJQkFnSVVHTmlP
      SjNWVlBsMjJ5M3pHQk14cjZYV0ROdWN3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkK
      TWpBNE1Ea3hOVE0wTURCYUZ3MHlNekE0TURreE5UTTVNREJhTUcweEN6QUpCZ05WQkFZVEFrZENN
      UnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXla
      R1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhM
      bTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRW11MkF0
      RzhEcCsyQkFjaTgxNnJNVEFqWWF2NmtBWjcrMDY1UQpNV1lDa0s1NGI0QmQvVXBsdVZETGlRY2U2
      RXVTVllucHVUZkNJY283YVduZDZWM3hoNk9DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURx
      REFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9C
      QUl3QURBZEJnTlZIUTRFRmdRVThJbkw3Mk9TeFNJNnoxZjM5TVhJS0htV1EyMHdId1lEVlIwagpC
      Qmd3Rm9BVUNUMUovNnNJb1VUWmVYZXRtTnQ2YWlScXRMNHdPd1lEVlIwUkJEUXdNb0lVYjNKa1pY
      SmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVky
      OXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlq
      b2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpY
      UWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFp
      RUFvbzB1VTZ2QVdscW9PNmF5VWo2MWU0V2JEN1VlcGJ4aUpmUHUKMkVsY1hyMENJQUpmR2Z6L2ZK
      MUVFREUxR2dYcW1OOFRCYSs2b25QcU5hWGQvaFYveitDdQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEY
      gIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVz
      dHJpY3Rpb25zEggaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIq
      Cg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxIN
      CAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      KgZBZG1pbnMS7y4KC0NvbnNvcnRpdW1zEt8uEpQuChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1
      bRL1LRLIFgoLYXVkaXRvcjFNU1ASuBYa0BQKA01TUBLIFBK9FBK6FAoLYXVkaXRvcjFNU1AS7QUt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVlZXdNeldIeTNq
      STUwTWNtbHBNU1NYb2R1Smt3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RB
      aEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1E
      Z3dPVEUxTXpZeU0xb1hEVEkxTURVeU9URTFNell5TTFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUV0clBYbTM4NzNYWExsVnU0eW0ySWNiS0dmVWhRanN0
      aFJ0cGNndEYwZ3hVZVYwZ1o2OW05WjdnUwpJVEpKa0lEU3BiT2Z6ZGRyT0hQZGxiaWYxVWFiZmFO
      Q01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIw
      T0JCWUVGTmZBOTE4Z2xzZ0FIUW9xdmtBSjJYSHNpcFhnTUFvR0NDcUcKU000OUJBTUNBMGdBTUVV
      Q0lDa3c0Qm5YeGpQOTAxc2NFOUV4Y2hyeEJxVWxCMm9pd2x3MU1FMTkwaVVEQWlFQQovekpYSndS
      Z1ZPZjJwR25BMXU0MnkyUUdwWHJNYUFwQ0VqUVBqblB6Z0k4PQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwcWdBd0lCQWdJ
      VVhxUzNQZFhrMnJnRXJPc2l0by8wcTZVazNlc3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFV
      RUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJF
      d0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYw
      TUI0WApEVEl5TURnd09URTFNell3TUZvWERUSXpNRGd3T1RFMU5ERXdNRm93ZWpFTE1Ba0dBMVVF
      QmhNQ1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFL
      RXdoQmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5
      TVRFYk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBD
      QVFZSUtvWkl6ajBEQVFjRFFnQUV6UTlTd0MwakpZdHFKK205CkxBK2ZGemNMVktyeHB3YzlueWs1
      TWdYejArRm9ibm1LUUI4cGR2Y2VPS1BUaEg3YXQ1cktSazlvbDBkYitQaHkKLzN4dHNhT0NBUm93
      Z2dFV01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FX
      QkJUL1Eycmp3UWswdlprYXJTZ21iVllkZUJxVElUQWZCZ05WSFNNRUdEQVdnQlRYd1BkZklKYklB
      QjBLCktyNUFDZGx4N0lxVjREQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzT1dNME4yWTJZ
      MlE0TFd3NE5YWmoKTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBi
      bWwwSWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJ
      am9pWVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBk
      Rzl5TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURS
      d0F3UkFJZ1hEOVFtRloyN3U3Zml1OUNlcjZtZ04zUHkwejZaTllHQ3NMLwpPSEhacWkwQ0lHMTJh
      Z3lOd3hKWVhraUwyOGUxcHZtM2hFdTBmS3Q1QlJUYURtTWJIQjBxCi0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL0RDQ0FhS2dBd0lCQWdJVWVld016V0h5M2pJNTBNY21scE1TU1hvZHVKa3dDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURnd09URTFNell5TTFvWERUSTFNRFV5T1RFMU16
      WXlNMW93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRXRy
      UFhtMzg3M1hYTGxWdTR5bTJJY2JLR2ZVaFFqc3RoUnRwY2d0RjBneFVlVjBnWjY5bTlaN2dTCklU
      SkprSURTcGJPZnpkZHJPSFBkbGJpZjFVYWJmYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZOZkE5MThnbHNnQUhRb3F2a0FKMlhI
      c2lwWGdNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUNrdzRCblh4alA5MDFzY0U5RXhjaHJ4QnFV
      bEIyb2l3bHcxTUUxOTBpVURBaUVBCi96SlhKd1JnVk9mMnBHbkExdTQyeTJRR3BYck1hQXBDRWpR
      UGpuUHpnSTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNQoGQWRtaW5zEisS
      IQgBEh0SCBIGCAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50
      EikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikS
      HwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9y
      Mk1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVWRhOWxmckRJRlREaDV5OUxPTW9OZ3I1NmhU
      RXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURnd09URTFNemMwTVZvWERU
      STFNRFV5T1RFMU16YzBNVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRUxRMm5zbUVCMXpmc2Ntajg1c0M2V3Vrekl0YXQ1eGhFVHNSaWJiV1VjNFVZK0pn
      MjdDdkdnZmVWCjEvRUVxR3N0NCtDalJ5MTU1S2xTQUpwWkNMMk5rNk5DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZIcXVndHVwUmE1
      V3VzMXQ1dXp4MFZsdm4yanBNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFEWGtLZitmcjduTjNp
      ZXdYWC9qWmFGTWRhZzliVzl1cHlZME5JOVVaWG5XUUloCkFKVXlPNWhieU5pWk50cnBYalNZUjVS
      eTlqYUZONWlnQjA5WkdtMEoySWtGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXB1Z0F3SUJBZ0lVSmg0RzN0Y3pYS21tTTgv
      VWFOMmd3SUorWE5Vd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3T1RF
      MU16Z3dNRm9YRFRJek1EZ3dPVEUxTkRNd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdO
      VkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4
      SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1N
      RWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VI
      QTBJQUJBV2FXRG5MVFFSbTU1VHMKSlBxNnpvaGJRSUpLU2hRT2c4cEV4b2NYYjBkZWdidWVva1Vq
      ZTZDRE1HN2dIQTgzZ296aGw1Y0hZTlFoSUNQcApxU2d6WTZDamdnRWFNSUlCRmpBT0JnTlZIUThC
      QWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVUTBsNjVWdTNEQi8z
      S29IWXArYzhRS2F1VHBJd0h3WURWUjBqQkJnd0ZvQVVlcTZDMjZsRnJsYTYKelczbTdQSFJXVytm
      YU9rd0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXROVGszWkRWall6UTVOQzEyT0hKbQpOVENC
      andZSUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlM
      Q0poClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJ
      aXdpYUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lh
      R1l1Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUMzZUV6cWJ5
      OG1wRnFZUTk1djczUkttK3B0eWU3aTkzNVB0Cm5BSDRJL2hJQWlCOVVBUzdUVkRHOTNwdWRlb2RP
      cTBZaEZmYVNXTGNadTg4bzdST1h6QnkxZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4K
      BFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dB
      d0lCQWdJVWRhOWxmckRJRlREaDV5OUxPTW9OZ3I1NmhURXdDZ1lJS29aSXpqMEVBd0l3ClhERUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUI0WApEVEl5TURnd09URTFNemMwTVZvWERUSTFNRFV5T1RFMU16YzBNVm93WERFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUxRMm5zbUVCMXpmc2Nt
      ajg1c0M2V3Vrekl0YXQ1eGhFVHNSaWJiV1VjNFVZK0pnMjdDdkdnZmVWCjEvRUVxR3N0NCtDalJ5
      MTU1S2xTQUpwWkNMMk5rNk5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFm
      OEVCQU1DQWFZd0hRWURWUjBPQkJZRUZIcXVndHVwUmE1V3VzMXQ1dXp4MFZsdm4yanBNQW9HQ0Nx
      RwpTTTQ5QkFNQ0Ewa0FNRVlDSVFEWGtLZitmcjduTjNpZXdYWC9qWmFGTWRhZzliVzl1cHlZME5J
      OVVaWG5XUUloCkFKVXlPNWhieU5pWk50cnBYalNZUjVSeTlqYUZONWlnQjA5WkdtMEoySWtGCi0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYI
      ARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoR
      Eg8KC2F1ZGl0b3IyTVNQEAEaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGlj
      eRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxpKChBPcmRlcmVyQWRkcmVzc2VzEjYSGwoZb3JkZXJl
      cjEub3JkZXJlci1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0
      aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2
      GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucyIi
      CgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRt
      aW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5z
      Gg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
