apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a7e9892a5136f4fa8b1cda6ba31b358b-1780904258.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBhzlkMq0xnTMUG9zMO+pAHVGQhNJjHbnyffSFVwUk5XEtpcCtdcCtRcCngKWggBEAEaBgiK
      /NGXBiIKc3lzY2hhbm5lbCpAYzFkZTRiNDNmYzA5YTNmMWQ4ODgyNDg1NWE5YmMzOWIyZTA1Y2Nh
      OWFiODVlOTYzZTkyN2FmMmUyYzY1OGQ1YxIaEhgwBDYD7CA5qagmV6CUrpeNoTzXbcw5V5MS11sK
      1FsS0VsSmyoKB09yZGVyZXISjyoSihYKCm9yZGVyZXJNU1AS+xUalxQKA01TUBKPFBKEFBKBFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVVRxcFBLbTVyUDRnOTNaVnEzVmxQNS81a0ZYb3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRFd016UXdNemhhRncweU5UQTFNekV3TXpRd016aGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFUTndTNzZ0eC9ydzg2TWNSVDlEK0Ns
      MlZSRiswSDRldFVUMGFQcnYyK3ZKSER3RUkydW5yeUxkeWlEeGN0ClE4TVZHKy81QVZvTHhpMWNM
      NklCclhxRG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVOWhBVU01aVVVY0xmcVBrK0lPamorQi9hWHpZd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdSbTk2RmN4RGFab2xkOEttWVU5Y0RaYjM4QThuU2c3WWpZL3RlQVJwaDBnQ0lC
      ZEJrNDhkCkljV3pWbEFXTVM3NTZrdUFFa0t6a01seGxLRHl0K1dYQlNNbAotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKSCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMVRDQ0FueWdB
      d0lCQWdJVURMSERlTXJDLzZjdWpYUldkNUk4OHJKbHJNVXdDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TVRFd016UTNNREJhRncweU16QTRNVEV3TXpVeU1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJE
      YTVzc2tKTDF4d0dLakZDb2d5d0pOMGRIdWF3ZUpoKzUxeVM4QlVtKzAyCnRnNlp0L1pGNGV3VDVv
      NllpTGsyRE1uN3NyQ0hiZSt4ajZLUnVMaGdITnlqZ2dFUU1JSUJEREFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVDTkpBQWNFLzZuVUZteU5sczFV
      MwphTU9PMWhFd0h3WURWUjBqQkJnd0ZvQVU5aEFVTTVpVVVjTGZxUGsrSU9qaitCL2FYell3SkFZ
      RFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROVGcxTm1Oa1pqaGpOQzEyT1hwa2NEQ0JoUVlJS2dN
      RUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYlds
      dUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdFaXZVZ0Yrd05GQ00KZFFEQzdWOHMyVmppQ0ZU
      ZHMwTFJRRVgweEdvTWlXSUNJQTdEZjVoREVmNDgvNTRtbmFVdVJRM0JWekF6dWxkMwo2aFJQNFJH
      U0tOWUIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVVHFwUEttNXJQNGc5M1pW
      cTNWbFA1LzVrRlhvd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVEV3TXpR
      d016aGFGdzB5TlRBMU16RXdNelF3TXpoYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEps
      Y2pFWApNQlVHQTFVRUF3d09ZMkV1YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DCkFBUVROd1M3NnR4L3J3ODZNY1JUOUQrQ2wyVlJGKzBINGV0VVQwYVBydjIr
      dkpIRHdFSTJ1bnJ5TGR5aUR4Y3QKUThNVkcrLzVBVm9MeGkxY0w2SUJyWHFEbzBJd1FEQVBCZ05W
      SFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVU5aEFV
      TTVpVVVjTGZxUGsrSU9qaitCL2FYell3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ1JtOTZGY3hE
      YVpvbGQ4S21ZVTljRFpiMzhBOG5TZzdZalkvdGVBUnBoMGdDSUJkQms0OGQKSWNXelZsQVdNUzc1
      Nmt1QUVrS3prTWx4bEtEeXQrV1hCU01sCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyIz
      CgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zIjQKBkFk
      bWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMa
      IgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoC
      MnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRp
      ZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIRErcRCghldGNkcmFm
      dBKqEQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQzh6Q0NBcG1nQXdJQkFnSVVLcWw3Zk9uR0YrWjI5TnpKc2JhanFLdWY1ZGN3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFR
      RERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1URXdNelEzTURCYUZ3MHlNekE0TVRF
      d016VXlNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0
      eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdW
      eVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29a
      SXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUlhTmNQK3poWnlnc2dHMzZWNHQwNHkvMDNnVStYaEl4
      bkMzRgpmZkJHR2wvL1h1TXp1K1dxay9TUW1qRm5maHZTK0MvbWtlOWtEdEhxdWZzdCtqNTJDS09D
      QVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNE
      QVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVTVWTTdwM216
      elVzak1mSmVUL2hjT05yNnpHUXdId1lEVlIwagpCQmd3Rm9BVTloQVVNNWlVVWNMZnFQaytJT2pq
      K0IvYVh6WXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5
      WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYw
      ZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxF
      SWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxj
      aUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFwT0tqRFlmWDAvNElzdHhzTkNCMVlCS2ph
      aFJTMmFudjhrR0cKVzdydHNXUUNJRlVJWEJJNWNMTS9EdG9NN0M3NStLR3ZnWllTYWo2SktadXdn
      ckd2RnV0cQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJVUtxbDdmT25HRitaMjlOekpzYmFqcUt1ZjVkY3dD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURW
      UVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRFd016UTNNREJhRncweU16QTRN
      VEV3TXpVeU1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRN
      QzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXla
      R1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApL
      b1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSWFOY1AremhaeWdzZ0czNlY0dDA0eS8wM2dVK1ho
      SXhuQzNGCmZmQkdHbC8vWHVNenUrV3FrL1NRbWpGbmZodlMrQy9ta2U5a0R0SHF1ZnN0K2o1MkNL
      T0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJR
      Y0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVNVZNN3Az
      bXp6VXNqTWZKZVQvaGNPTnI2ekdRd0h3WURWUjBqCkJCZ3dGb0FVOWhBVU01aVVVY0xmcVBrK0lP
      amorQi9hWHpZd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dt
      OXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0lt
      RjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRF
      bEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhK
      bGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXBPS2pEWWZYMC80SXN0eHNOQ0IxWUJL
      amFoUlMyYW52OGtHRwpXN3J0c1dRQ0lGVUlYQkk1Y0xNL0R0b003Qzc1K0tHdmdaWVNhajZKS1p1
      d2dyR3ZGdXRxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAga
      BkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIO
      CAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1pbnMS8y4K
      C0NvbnNvcnRpdW1zEuMuEpguChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL5LRLMFgoLYXVk
      aXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVNSnVQUFdFRDQ1aGloRTJ2TlBNbFZL
      UXE2WkV3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hNVEF6TkRFMU5G
      b1hEVEkxTURVek1UQXpOREUxTkZvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUUyUHFuWk5KK2liZkI4VGF3aXI4LzI2Wm4zdWkvb0Z1bDR0U1Awd0xLWTly
      cUpYNE5YTDFJT2xrYQp3d29aaXYvcVp0S0VEWVBSVTd2OERHZkJlTnR4V3FOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGSEdkb1hY
      KytxdzNYbUJxTk90QXdleCtmQTZ5TUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lCZ3BkVmpyUnht
      cXQ3ZWZWWkRsWm9YcmRJRXI3blJKa29KZ01LK1c2WkJtQWlFQQprL3VSQ1ZBSmZSeDhSbW5NdFFG
      cTBDc2h0aVZaWkVZSTN2eElUbWNJazZrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJVUJYaXMvR0QyQjEx
      Q25McVZPOWg0M2RzSmNnRXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURn
      eE1UQXpORGt3TUZvWERUSXpNRGd4TVRBek5UUXdNRm93ZWpFTE1Ba0dBMVVFQmhNQ1EwZ3hHakFZ
      CkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdoQmRXUnBkRzl5
      TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRFYk1Ca0dBMVVF
      QXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVVT2x2WXI0c1pUTVB4OGxUCjM3eFZSeldibTZqckJISVpyVzA4dVRTc2Y1K2gzR1hI
      SURYV0NTNGY1bWcrdlFXVkxhKzR1NjMweWtlcStkQ1IKVjlHN0VhT0NBUm93Z2dFV01BNEdBMVVk
      RHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJRdDFkUUl4U0s2
      cmlTenpzR0xRNVFGd2tpZzZqQWZCZ05WSFNNRUdEQVdnQlJ4bmFGMS92cXNOMTVnCmFqVHJRTUhz
      Zm53T3NqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzT1dNME4yWTJZMlE0TFdONE5XZzIK
      TUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFa
      U0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWVhWa2FYUnZj
      akVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5TVMxdVpYUWlM
      Q0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFMaktj
      RWdZR3Nma3MzckdhTlFTV2VDZ3VGWW1TdklvRnVDZQpjMHBnZ2N3VUFpQmxIL1VYSGE5cU9ZdGZk
      U0Q5c0JBQWhydk9hY1cxWHN0ZFdhdDhvcFMweFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      CkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NB
      YUtnQXdJQkFnSVVNSnVQUFdFRDQ1aGloRTJ2TlBNbFZLUXE2WkV3Q2dZSUtvWkl6ajBFQXdJdwpY
      REVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hNVEF6TkRFMU5Gb1hEVEkxTURVek1UQXpOREUxTkZvd1hE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUUyUHFuWk5KK2li
      ZkI4VGF3aXI4LzI2Wm4zdWkvb0Z1bDR0U1Awd0xLWTlycUpYNE5YTDFJT2xrYQp3d29aaXYvcVp0
      S0VEWVBSVTd2OERHZkJlTnR4V3FOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhR
      OEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGSEdkb1hYKytxdzNYbUJxTk90QXdleCtmQTZ5TUFv
      R0NDcUcKU000OUJBTUNBMGdBTUVVQ0lCZ3BkVmpyUnhtcXQ3ZWZWWkRsWm9YcmRJRXI3blJKa29K
      Z01LK1c2WkJtQWlFQQprL3VSQ1ZBSmZSeDhSbW5NdFFGcTBDc2h0aVZaWkVZSTN2eElUbWNJazZr
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsS
      CBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIG
      CAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARIC
      CAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMqBkFkbWlucxLMFgoLYXVkaXRvcjJNU1ASvBYa
      1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVHZGtyWUtaNDBxcnVLYkNVb29ZN3NUWHZuRGd3Q2dZSUtv
      Wkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hNVEF6TkRNeE1Gb1hEVEkxTURVek1U
      QXpORE14TUZvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFn
      QUVPTFdncmpUZWJ4ako2MHNMWGVtZmFzRVNzenQyZzRpTkFYVlU3WXZ0VWNYT0NLZndxNHQ5cERK
      QgpycW15cThPOVdOTDd2cjdLejN4cjQvU2NtNUJTWktOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdF
      Qi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGUG1xbDcvaENwbm5KaW9nb2RF
      ZGNBbTdLeGo2TUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lIN2ZYazFjS2lGTDdubFZFVi80QmYv
      YVBBVS8yVUlKU3BHSFNpciswdytOQWlBMAoya2p6UGE4WTBUR1lNWTBUQ3IwVUw3WlJNY3Uyd29p
      WXlsdlM2cU1GQkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwdWdBd0lCQWdJVWVuWlljMW9HZUVJUDE0cFhaRzg3SHgx
      OVNNc3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpF
      WU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE1UQXpOVEV3TUZv
      WERUSXpNRGd4TVRBek5UWXdNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFaCkJnTlZCQWNURWpV
      eExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2Y2pJeEh6QU0KQmdO
      VkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05WQkFNTUVrRmtiV2x1
      UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTVdx
      NkRpVkRueFd3aWFDCnVoRWM2M05nU2wyQnZCM1M2TnVZUy9QY2ZXOVBXY3JSdXhEenZuaVdMbXd6
      R0wvUVRJQm9WYzlzNzRGaVB6WTQKVHQyYVAvYWpnZ0VhTUlJQkZqQU9CZ05WSFE4QkFmOEVCQU1D
      QjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVU8wY3NmMUJYVG1uVzhDVVFwb2pa
      dW9pb3pORXdId1lEVlIwakJCZ3dGb0FVK2FxWHYrRUttZWNtCktpQ2gwUjF3Q2JzckdQb3dKQVlE
      VlIwUkJCMHdHNElaWTJFdGRHOXZiSE10TlRrM1pEVmpZelE1TkMxemQzRnUKYlRDQmp3WUlLZ01F
      QlFZSENBRUVnWUo3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaApaRzFw
      YmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1GMVpHbDBiM0l5SWl3aWFHWXVS
      VzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlYVmthWFJ2Y2pJdGJtVjBJaXdpYUdZdVZIbHda
      U0k2SW1Ga2JXbHUKSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lIdis4NUNPQitEOVh4SlBq
      ZHJGYjgwUkc5cUFkTGdLQU1UUgorekFJcjBMZUFpQmxDRCtCelBDaWIySXlHUXk5RGVXU2xyam9h
      cndrZUsvMmhOK2pVOVkrcFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZT
      SEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVH
      ZGtyWUtaNDBxcnVLYkNVb29ZN3NUWHZuRGd3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdE
      d1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1C
      NFgKRFRJeU1EZ3hNVEF6TkRNeE1Gb1hEVEkxTURVek1UQXpORE14TUZvd1hERUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1G
      a3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVPTFdncmpUZWJ4ako2MHNMWGVtZmFz
      RVNzenQyZzRpTkFYVlU3WXZ0VWNYT0NLZndxNHQ5cERKQgpycW15cThPOVdOTDd2cjdLejN4cjQv
      U2NtNUJTWktOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0Fh
      WXdIUVlEVlIwT0JCWUVGUG1xbDcvaENwbm5KaW9nb2RFZGNBbTdLeGo2TUFvR0NDcUcKU000OUJB
      TUNBMGNBTUVRQ0lIN2ZYazFjS2lGTDdubFZFVi80QmYvYVBBVS8yVUlKU3BHSFNpciswdytOQWlB
      MAoya2p6UGE4WTBUR1lNWTBUQ3IwVUw3WlJNY3Uyd29pWXlsdlM2cU1GQkE9PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxINCgth
      dWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoREg8KC2F1ZGl0
      b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1
      ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMS
      CAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5z
      Gi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaSgoQT3JkZXJl
      ckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoA
      CgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
