apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a7e9892a5136f4fa8b1cda6ba31b358b-1780904258.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIGGcNs6H/28eh8metsRxvxbLFDy3BeVPJWXlTP5sPjRHEuJcCt9cCtxcCngKWggBEAEaBgj2
      zseXBiIKc3lzY2hhbm5lbCpANjNlMWM1MDZmYTQ1NDU1ZDI2ZmM5Y2FlYmU0MzhmMmU3OTFjYWE4
      M2RmODVhYTU1YTc2Y2NkNmM5NTY4MzdiMRIaEhiG2A5IP/SGrPI+iaYhfHEoPu9oT40zmmgS31sK
      3FsS2VsSpyoKB09yZGVyZXISmyoSlhYKCm9yZGVyZXJNU1AShxYaoxQKA01TUBKbFBKQFBKNFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVVY4MlkyRkFxRVo1VjFSWENYTWFOMVZJYlNkY3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURrd05ETTFNek5hRncweU5UQTFNamt3TkRNMU16TmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJEa0Z2TXVaSDZJYWtWaW9NM3d0SG5j
      U3FsL29vUFBDZDJDeHNEN09QZkFtNDNvc0RDcFF1VU53S2EvcmFSCjBOZTdZbW8rczFnRlVlTWl4
      WnRLU013a28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVd2xuMFJwdkNwRGMxUldBQk1jTmlDSTFSZFZrd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWhBT0M4NHVBUkxKNEJDZ2lQSWpvVUJyWTBDRTFvTWQzK0hvcGdrMDc3ZzBXekFp
      QnZZSnNDCjdNQjM2aGE4bTR2cWhEVlExNkJxU2RTSjRjSGNWSlJjSzN2NDRnPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoilggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFqQ0NB
      bnlnQXdJQkFnSVVlWWlYS1JPc0dVY3kzVmFqZS9mejJMazUrd0l3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1Ea3dORFF3TURCYUZ3MHlNekE0TURrd05EUTFNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCTUlIOG9aTFB1ejlPaFNPUlpRK25McXdERjlMMmppamdjbzlRbE9HQmppMQpEdEVBUXdMdldt
      ZVNtT3ltbDlyYmdsMmlNb1FkcHRIOHJ3NWZrY0IrRVZTamdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVeW92bCs4ejZSTHdkNzVS
      NUFaS04KM2ErYXdwSXdId1lEVlIwakJCZ3dGb0FVd2xuMFJwdkNwRGMxUldBQk1jTmlDSTFSZFZr
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TlRnMU5tTmtaamhqTkMxdU5uTTJPVENCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUxtSnRGZEpIWG1lCk5nZXJ2SHJUbWNm
      OFpzSVFZSStvTFdJVXEzREYvTUo2QWlBaTZhSVdlb0syeFY4Z3hEUUxFT2ZTemthd25NUmsKbys4
      M1p4YXE5Mm1tZ2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK
      6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVWODJZMkZB
      cUVaNVYxUlhDWE1hTjFWSWJTZGN3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpB
      NE1Ea3dORE0xTXpOYUZ3MHlOVEExTWprd05ETTFNek5hTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3
      RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dI
      VDNKa1pYSmxjakVYCk1CVUdBMVVFQXd3T1kyRXViM0prWlhKbGNpMXVaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFSRGtGdk11Wkg2SWFrVmlvTTN3dEhuY1NxbC9vb1BQQ2Qy
      Q3hzRDdPUGZBbTQzb3NEQ3BRdVVOd0thL3JhUgowTmU3WW1vK3MxZ0ZVZU1peFp0S1NNd2tvMEl3
      UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRF
      RmdRVXdsbjBScHZDcERjMVJXQUJNY05pQ0kxUmRWa3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlo
      QU9DODR1QVJMSjRCQ2dpUElqb1VCclkwQ0Uxb01kMytIb3BnazA3N2cwV3pBaUJ2WUpzQwo3TUIz
      NmhhOG00dnFoRFZRMTZCcVNkU0o0Y0hjVkpSY0szdjQ0Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1T
      UBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVy
      TVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hU
      aW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxok
      CgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIR
      ErcRCghldGNkcmFmdBKqEQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzhqQ0NBcG1nQXdJQkFnSVVNQTdpNHlDM01pSk1CUHQxVVBQ
      S3hCb2p6OGd3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21W
      eU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1Ea3dORFF3TURC
      YUZ3MHlNekE0TURrd05EUTFNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJ
      MU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05W
      CkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYw
      TUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXlxUFdMUDliZ1ZJdUMwaUpOcDZI
      Wjd4TmVMZllZcjZOeklaSgpDU2FPOXlEUHpuT3oxckduZnVFZHlmU2lJWkRwV2hLWnNvRUM1SjNS
      THByVU81V1FJS09DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFV
      QmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRF
      RmdRVUhYRlVxWThjdmxUQ0JJNjhPbXB6VUswY1k0RXdId1lEVlIwagpCQmd3Rm9BVXdsbjBScHZD
      cERjMVJXQUJNY05pQ0kxUmRWa3dPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEps
      Y2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcK
      QndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXli
      MnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJ
      am9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQWI4TDlZU2dnQmo5R0M4
      WldWMGs2M3VzMGtzSDVkY1J4c1cyK1oKY0g1djhRSWdKdExmWm9rTktxdE5BVi9xYis3eXdyNzBw
      QWFFSXRheVpVQ0V3RDFiMFVBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVU1BN2k0eUMzTWlKTUJQdDFV
      UFBLeEJvano4Z3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxj
      bVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURrd05EUXdN
      REJhRncweU16QTRNRGt3TkRRMU1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhF
      eEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0Jn
      TlYKQkFzVEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJt
      VjBNRmt3RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFeXFQV0xQOWJnVkl1QzBpSk5w
      NkhaN3hOZUxmWVlyNk56SVpKCkNTYU85eURQem5PejFyR25mdUVkeWZTaUlaRHBXaEtac29FQzVK
      M1JMcHJVTzVXUUlLT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZq
      QVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhR
      NEVGZ1FVSFhGVXFZOGN2bFRDQkk2OE9tcHpVSzBjWTRFd0h3WURWUjBqCkJCZ3dGb0FVd2xuMFJw
      dkNwRGMxUldBQk1jTmlDSTFSZFZrd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pY
      SmxjaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFV
      RwpCd2dCQkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1
      eWIyeHNiV1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhC
      bElqb2liM0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBYjhMOVlTZ2dCajlH
      QzhaV1YwazYzdXMwa3NINWRjUnhzVzIrWgpjSDV2OFFJZ0p0TGZab2tOS3F0TkFWL3FiKzd5d3I3
      MHBBYUVJdGF5WlVDRXdEMWIwVUE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1z
      EAoYASAFKICAgAgaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIi
      CgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5z
      KgZBZG1pbnMS7y4KC0NvbnNvcnRpdW1zEt8uEpQuChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1
      bRL1LRLIFgoLYXVkaXRvcjFNU1ASuBYa0BQKA01TUBLIFBK9FBK6FAoLYXVkaXRvcjFNU1AS7QUt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVieUh6V2txendM
      YTJNcHNzVGhUS3ZxOXROWFl3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RB
      aEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1E
      Z3dPVEEwTXpZMU1Gb1hEVEkxTURVeU9UQTBNelkxTUZvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUV1ZXNJWjBNb1NaK1Q5WHRybVpTZ0RnOUJBbm8vTnp4
      UFFBY3N5OUI1cUVLdWRxZ1RiL2hYYVdrdgpOVmxybUhzSDkrUWluQXNGY3l3MVNLelpDekk4QktO
      Q01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIw
      T0JCWUVGSDlMLzRsOTF6Q1cvT1B5VHBBZ2hrL0tZUG11TUFvR0NDcUcKU000OUJBTUNBMGdBTUVV
      Q0lRQ3N6Z2kzUjYzMGdJWlF5c0xnTmJ4S0lzdWJxWlp5YjhycmpIRmI4N3kxa3dJZwpHZnVUMmY3
      K2tLR3lSbkp4SGNtYzV5V0xBaVdqNGhsZkM5b3NqeFo3KzhRPQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwcWdBd0lCQWdJ
      VVpycHlwN3RTM1B5Q2R5cDBlbkprV2NMeGVCb3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFV
      RUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJF
      d0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYw
      TUI0WApEVEl5TURnd09UQTBOREl3TUZvWERUSXpNRGd3T1RBME5EY3dNRm93ZWpFTE1Ba0dBMVVF
      QmhNQ1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFL
      RXdoQmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5
      TVRFYk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBD
      QVFZSUtvWkl6ajBEQVFjRFFnQUVWVWtpUHZPNTA1WklkZVZKCnQwNEg4U3prdS81UHVVMG5OSHNl
      VDFaYVIrY29UTysyaTFEU3k3NHZWR3MvVEpwYndWRkdtOFFad1J5WFNHQUwKOGhDblBLT0NBUm93
      Z2dFV01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FX
      QkJUcjJwUi9iNlNKMEFyVkw3TDk4c2JUOVNsVkdEQWZCZ05WSFNNRUdEQVdnQlIvUy8rSmZkY3ds
      dnpqCjhrNlFJSVpQeW1ENXJqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzT1dNME4yWTJZ
      MlE0TFdSNk5tZG0KTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBi
      bWwwSWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJ
      am9pWVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBk
      Rzl5TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURS
      d0F3UkFJZ2F3c01mOFRpdVBxL1dLcFM5QmE2WnpoUkFEeE91ZlhSR0NiUApDdk9hYThZQ0lBWjVQ
      a1h2NjdSV3pwRW9YTjV4c2czZE9pQ0N4VCt1a3BFZGRQQStkWElFCi0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL0RDQ0FhS2dBd0lCQWdJVWJ5SHpXa3F6d0xhMk1wc3NUaFRLdnE5dE5YWXdDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURnd09UQTBNelkxTUZvWERUSTFNRFV5T1RBME16
      WTFNRm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRXVl
      c0laME1vU1orVDlYdHJtWlNnRGc5QkFuby9OenhQUUFjc3k5QjVxRUt1ZHFnVGIvaFhhV2t2Ck5W
      bHJtSHNIOStRaW5Bc0ZjeXcxU0t6WkN6SThCS05DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZIOUwvNGw5MXpDVy9PUHlUcEFnaGsv
      S1lQbXVNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFDc3pnaTNSNjMwZ0laUXlzTGdOYnhLSXN1
      YnFaWnliOHJyakhGYjg3eTFrd0lnCkdmdVQyZjcra0tHeVJuSnhIY21jNXlXTEFpV2o0aGxmQzlv
      c2p4WjcrOFE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNQoGQWRtaW5zEisS
      IQgBEh0SCBIGCAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50
      EikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikS
      HwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9y
      Mk1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVVhPTEIyeEtuQmZWS3NpbXlrRHpDZlNNVWx5
      UXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURnd09UQTBNemd3TlZvWERU
      STFNRFV5T1RBME16Z3dOVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRVNiNlU1VktGSERJNUhEbG9LU0h1TEd0bzZCOTNDUllLTEs1NmhDSS9MUk45SnhP
      TE8yWDI1USs0CnIwYW1VM25Xbys3bk1YU1V3VEJPNmlaV0NGR0RWcU5DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZITi9HcUh5NGtP
      T1Ric0FwSjRrMDZTRjI0TWpNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFEUzVoTTlDWWpoOXBT
      amJjWFpaVXRXQk1vdTBvWnR6TXpHUmxOVTN4S0dlUUlnCklkNTg4dm9ya1dFSGVKb2p0dXl1UlRG
      bW9tanZkaUw5L3ppNUlQbUxvUVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXB1Z0F3SUJBZ0lVZmdNbXRhUlY5UnN6amNi
      dnJjZmNxbS95OXRzd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3T1RB
      ME5EUXdNRm9YRFRJek1EZ3dPVEEwTkRrd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdO
      VkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4
      SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1N
      RWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VI
      QTBJQUJDWG1YVmNld3Z5cTNySG8KRlo5dWs5QytaZ0x0eUlBeWdMR3p3N2R0MVA5S01WVTZZc1FO
      VkhXVHcrZHVpTlptbVF4MDRjc2I3MTZvNGlHdAp2OTlJbmEramdnRWFNSUlCRmpBT0JnTlZIUThC
      QWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVaHZFeWRIWUwzem5U
      U2dKOUxrQUVxdzJFcXJjd0h3WURWUjBqQkJnd0ZvQVVjMzhhb2ZMaVE0NU4KdXdDa25pVFRwSVhi
      Z3lNd0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXROVGszWkRWall6UTVOQzFyTWprNQpkRENC
      andZSUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlM
      Q0poClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJ
      aXdpYUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lh
      R1l1Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUZXY1FpdktG
      YnA0QnFZUkZHR2gzaXJIbTFQMWIzRkdGUmlNCmY3Z3hlU25ZQWlCU1Z2NnF2K3loajhVSERZOWF4
      WDVjRkk3d2ZSTVJZdXRLOEIxV2RrbnRuQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4K
      BFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dB
      d0lCQWdJVVhPTEIyeEtuQmZWS3NpbXlrRHpDZlNNVWx5UXdDZ1lJS29aSXpqMEVBd0l3ClhERUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUI0WApEVEl5TURnd09UQTBNemd3TlZvWERUSTFNRFV5T1RBME16Z3dOVm93WERFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRVNiNlU1VktGSERJNUhE
      bG9LU0h1TEd0bzZCOTNDUllLTEs1NmhDSS9MUk45SnhPTE8yWDI1USs0CnIwYW1VM25Xbys3bk1Y
      U1V3VEJPNmlaV0NGR0RWcU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFm
      OEVCQU1DQWFZd0hRWURWUjBPQkJZRUZITi9HcUh5NGtPT1Ric0FwSjRrMDZTRjI0TWpNQW9HQ0Nx
      RwpTTTQ5QkFNQ0EwZ0FNRVVDSVFEUzVoTTlDWWpoOXBTamJjWFpaVXRXQk1vdTBvWnR6TXpHUmxO
      VTN4S0dlUUlnCklkNTg4dm9ya1dFSGVKb2p0dXl1UlRGbW9tanZkaUw5L3ppNUlQbUxvUVU9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYI
      ARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoR
      Eg8KC2F1ZGl0b3IyTVNQEAEaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGlj
      eRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxpKChBPcmRlcmVyQWRkcmVzc2VzEjYSGwoZb3JkZXJl
      cjEub3JkZXJlci1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0
      aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2
      GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucyIi
      CgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRt
      aW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5z
      Gg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
