apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIPN9AStRCLY261iMYWHvkDg28HoMK5m4N7TR8TKI8TgyEt5cCttcCthcCngKWggBEAEaBgi3
      0L+XBiIKc3lzY2hhbm5lbCpANjAzNjUwOTUzOGQ0YzAxNmQ3MjA5ZTY0NTVjMmM0YWI4ZDQwZTNh
      NjE2MWZmZjJjMjRkNjBiYzhkMmZmYjBlMxIaEhjbMDIvhNYwxp/PRQd5ColkgHBtpGfXq6wS21sK
      2FsS1VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVVdhVi83MHVkeDJlWWhBM3ZHUlBkNXBEeHpjNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURjeE5UUTVOVFZhRncweU5UQTFNamN4TlRRNU5UVmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFUTUZCQU1hTXE1VkJBaXNTdlI0WVZt
      U2tWdS9mQk9LKzltWmhMMHYxVnl2UzBSdmVtN1lmeVErb254NlpLClpTUFdIUXpudWVtS1B6NnV4
      VUpQQTArZW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVeksrNSs0WWYrYWV6Slgxajk2VXQyendOdm1Vd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdlbzJSRXZPN09TOVA3OHJWRVdEa1dpL3U5c1p5R3lNVXNmNlJwQytXT2ZVQ0lR
      REl3REpkCmdTc1NlYTFNM3ZFMzV3V0R4WmVwTlp4UU56Y1picTAvVkh4K3hnPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFUQ0NB
      bnlnQXdJQkFnSVVMSCs1RTNQOXJwMkNwYmgxa0IxenFrRmlqYm93Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1EY3hOVFUxTURCYUZ3MHlNekE0TURjeE5qQXdNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCTHd4REhpZStNYTVBSDhsVFVac2VNWnltN2YyaHdFZ21vOXEwVXVJR1lZSApzK2JrYzFMY1g1
      aEYwOGxiWG93MXNkSzl5S0ZGNGd6SmYvYmdCOHkvTzM2amdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVK1oxWmI4bzFWdE9GbWhx
      cjhaaW0KUGVFNW5Pc3dId1lEVlIwakJCZ3dGb0FVeksrNSs0WWYrYWV6Slgxajk2VXQyendOdm1V
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TnprNU5EWmlPVFUxWWkxNGFuZHpkakNCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnSEtZR1BLbVlEQzJNCmpmNHIyczJEYW01
      dm5zaTVCREF1QWI3bmg4WllTaFFDSUVQV2RqWHpDRzdPL2FEUjkyYUxuWS9WNWpnWTdacWsKMUVt
      RytqQllRYXVlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVdhVi83MHVkeDJl
      WWhBM3ZHUlBkNXBEeHpjNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURj
      eE5UUTVOVFZhRncweU5UQTFNamN4TlRRNU5UVmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVFUTUZCQU1hTXE1VkJBaXNTdlI0WVZtU2tWdS9mQk9LKzltWmhM
      MHYxVnl2UzBSdmVtN1lmeVErb254NlpLClpTUFdIUXpudWVtS1B6NnV4VUpQQTArZW8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      eksrNSs0WWYrYWV6Slgxajk2VXQyendOdm1Vd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdlbzJS
      RXZPN09TOVA3OHJWRVdEa1dpL3U5c1p5R3lNVXNmNlJwQytXT2ZVQ0lRREl3REpkCmdTc1NlYTFN
      M3ZFMzV3V0R4WmVwTlp4UU56Y1picTAvVkh4K3hnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRlcmVyTVNQEAEa
      BkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMS
      FBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIRErcRCghldGNkcmFmdBKq
      EQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQzhqQ0NBcG1nQXdJQkFnSVVXYlM1Mk96a3VSaTlCYm1STXBiTEZsV2IzK0V3Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERB
      NWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1EY3hOVFUxTURCYUZ3MHlNekE0TURjeE5q
      QXdNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15
      OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpY
      SXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpq
      MENBUVlJS29aSXpqMERBUWNEUWdBRUNRUHp2clJId3FwdGhCNkNZWExXdkZoK3pjUlVjQ1RUZjVJ
      ZApIK2VyeUlOdEQvT1Fnb2t5cUJvUEtmSzVTSk4wVkhMSWh5Tit1M1NTemQ2c2ZFVWVRYU9DQVNn
      d2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZ
      SUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVXBHckphdGk1clJX
      V3I1K0tqa0NCWU55UWt1b3dId1lEVlIwagpCQmd3Rm9BVXpLKzUrNFlmK2FlekpYMWo5NlV0Mnp3
      TnZtVXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdW
      eVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhK
      eklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpv
      aWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5
      CmZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQndna2FLNGs1NVJrd1dodHhDVGNKMFFCNlRMczRj
      emNCYng0anAKcHA4WjBnSWdKYjJJc3RrWGNKa3BCeWxha3oxOFRLZHB5OG9zKzBUV3JoSFl5YkNQ
      RVFJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVVdiUzUyT3prdVJpOUJibVJNcGJMRmxXYjMrRXdDZ1lJ
      S29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFE
      REE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURjeE5UVTFNREJhRncweU16QTRNRGN4
      TmpBd01EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4
      TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXlaR1Z5
      WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApLb1pJ
      emowQ0FRWUlLb1pJemowREFRY0RRZ0FFQ1FQenZyUkh3cXB0aEI2Q1lYTFd2RmgremNSVWNDVFRm
      NUlkCkgrZXJ5SU50RC9PUWdva3lxQm9QS2ZLNVNKTjBWSExJaHlOK3UzU1N6ZDZzZkVVZVFhT0NB
      U2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RB
      UVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVcEdySmF0aTVy
      UldXcjUrS2prQ0JZTnlRa3Vvd0h3WURWUjBqCkJCZ3dGb0FVeksrNSs0WWYrYWV6Slgxajk2VXQy
      endOdm1Vd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dtOXla
      R1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0ltRjBk
      SEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJ
      am9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhKbGNp
      SjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCd2drYUs0azU1Umt3V2h0eENUY0owUUI2VExz
      NGN6Y0JieDRqcApwcDhaMGdJZ0piMklzdGtYY0prcEJ5bGFrejE4VEtkcHk4b3MrMFRXcmhIWXli
      Q1BFUUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAgaBkFk
      bWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQS
      DhIECgIycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFk
      bWlucxLvLgoLQ29uc29ydGl1bXMS3y4SlC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvUt
      EsgWCgthdWRpdG9yMU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dBd0lCQWdJVWIrRXg0N3VWSDFUc05Y
      ekNmNmYrazhxV0c1Y3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURnd056
      RTFOVEV4TTFvWERUSTFNRFV5TnpFMU5URXhNMW93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRWkvRmVmc1R1NytUOE56S014MGZZRjZkelprVm90VDdOSEJy
      TGRGK280WTFJU0hZSVowSFY4K0lqCm1leHdmeDN3RFN6SHdmOW5uSWJKTkJhaXpYRTM1S05DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZDZzRYTWxTejQ0NkJOWVJpR3JpTFhsYS9IT25NQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUN6
      NTMybEJYK2o0TnpOR01waVlqdk1ZYWJ1NDd5THdiWUZMQ3RKek05eDlBaUFQCmo2cXZXRDBRS0ZF
      akhncEFTR1p4Uk9wWWZIQVVoK2ZabEg0LzZqdUdVdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVVk1u
      YWsvY0FsZUNNbnNHMk5RenRObmUyMk1rd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd3TnpFMU5UWXdNRm9YRFRJek1EZ3dOekUyTURFd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRVh2TVRVeElkSTJvVE5Bd0EKNDE0L081ekpBYUF6b3J2QTlxL1hWNXdD
      b1B1b0RVOXpjdGU1QmE1RUc3cjVYZFB2MVRnNEFkSGJRaXBsMXJnNQpoRWpuRmFPQ0FSa3dnZ0VW
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlNP
      YWw4Ujk3SGFGOUZ6N3NvclcwekwrUmZnY1RBZkJnTlZIU01FR0RBV2dCUW9PRnpKVXMrT09nVFcK
      RVlocTRpMTVXdnh6cHpBakJnTlZIUkVFSERBYWdoaGpZUzEwYjI5c2N5MWlPR1ppWkdZM1kyUXRO
      VFkxYkhNdwpnWThHQ0NvREJBVUdCd2dCQklHQ2V5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlP
      aUowY25WbElpd2lZV1J0CmFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmhk
      V1JwZEc5eU1TSXNJbWhtTGtWdWNtOXMKYkcxbGJuUkpSQ0k2SWtGa2JXbHVRR0YxWkdsMGIzSXhM
      VzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZB
      aUVBNG5tY1hrZEp5RmxwdFNNR1FNNVRPU1B4ZElOazVPcDQ5QmV0ClNjaFFQaTBDSUVpeDZ5Tk92
      djYwVy83WmZSRzNvc3l6V2x4M0hQWFJVQlcwSDlUSFkrNTYKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIr
      ekNDQWFLZ0F3SUJBZ0lVYitFeDQ3dVZIMVRzTlh6Q2Y2ZitrOHFXRzVjd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd3TnpFMU5URXhNMW9YRFRJMU1EVXlOekUxTlRFeE0x
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFaS9GZWZz
      VHU3K1Q4TnpLTXgwZllGNmR6WmtWb3RUN05IQnJMZEYrbzRZMUlTSFlJWjBIVjgrSWoKbWV4d2Z4
      M3dEU3pId2Y5bm5JYkpOQmFpelhFMzVLTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkNnNFhNbFN6NDQ2Qk5ZUmlHcmlMWGxhL0hP
      bk1Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNJQ3o1MzJsQlgrajROek5HTXBpWWp2TVlhYnU0N3lM
      d2JZRkxDdEp6TTl4OUFpQVAKajZxdldEMFFLRkVqSGdwQVNHWnhST3BZZkhBVWgrZlpsSDQvNmp1
      R1V3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8I
      ARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIb
      EggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIG
      CAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJBZ0lVUU5oTmNzamF0Sk53KzlVZWRiZmc1U2xnZmVRd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3TnpFMU5USXlPVm9YRFRJMU1E
      VXlOekUxTlRJeU9Wb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFSGRSSTFic1Ftbk1ncXhtUVVQUlZka1dFVFF3TFJ1YWVobGZYZ25rQUJGUklocGNyamxG
      YmFNUysKRnFjSVpHaUp3WmMzN1JRbzZuV1F1N1lBY3lIZEJxTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRk1MYm9nVGREZklMZDBN
      TUFjeWZOWnZVb0g5Zk1Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNJQmlmWWJ3Z3M4MVl3MHlLUEZS
      OGN1SWVWalNZMytmQXRiVnV3dVNMMUxIU0FpQTIKZm84aWthMVhtSDVSd2o5VEFLT1phN2VCQVFq
      S0ZEKytnSFBqZUpzUHZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHFnQXdJQkFnSVVWaktHcnZKeks5Zk4rSng0MXVx
      NTVURFNIUU13Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3dOekUxTlRr
      d01Gb1hEVEl6TURnd056RTJNRFF3TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      QkdTdDJ1MUU0bVYyZFlYSAo1ZStKNmdRQ0NaOFhVSzg5RjM3U3FOdXlzdXYyWXpLeW9adXV5aUw0
      WGQ1LzZ4STZrQUx6RlJHaXZ5K2tRK2FmCnNQaVR5N21qZ2dFWk1JSUJGVEFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVVaRTdycXNPd1MxNlRPc1hK
      dHZGRUpIRVlVWkl3SHdZRFZSMGpCQmd3Rm9BVXd0dWlCTjBOOGd0MwpRd3dCeko4MW05U2dmMTh3
      SXdZRFZSMFJCQnd3R29JWVkyRXRkRzl2YkhNdFpHWmlZMk0wWXpRMExYQjROamgyCk1JR1BCZ2dx
      QXdRRkJnY0lBUVNCZ25zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmsK
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVlYVmthWFJ2Y2pJaUxDSm9a
      aTVGYm5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQmhkV1JwZEc5eU1pMXVaWFFpTENKb1ppNVVl
      WEJsSWpvaVlXUnRhVzRpCmZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTU1qa1dwUlRaeTlX
      MjQzZDBmaTh4WjRYVHVRRW02V0F5NEkKTWxTc2ZuRWZBaUJ2MFVjV2F2Rjdjdloyd1QycGxDdGt5
      ZTIwNmhkMEcyN000TnErcE56eUNBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJB
      Z0lVUU5oTmNzamF0Sk53KzlVZWRiZmc1U2xnZmVRd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd3TnpFMU5USXlPVm9YRFRJMU1EVXlOekUxTlRJeU9Wb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFSGRSSTFic1Ftbk1ncXhtUVVQ
      UlZka1dFVFF3TFJ1YWVobGZYZ25rQUJGUklocGNyamxGYmFNUysKRnFjSVpHaUp3WmMzN1JRbzZu
      V1F1N1lBY3lIZEJxTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRk1MYm9nVGREZklMZDBNTUFjeWZOWnZVb0g5Zk1Bb0dDQ3FHClNN
      NDlCQU1DQTBjQU1FUUNJQmlmWWJ3Z3M4MVl3MHlLUEZSOGN1SWVWalNZMytmQXRiVnV3dVNMMUxI
      U0FpQTIKZm84aWthMVhtSDVSd2o5VEFLT1phN2VCQVFqS0ZEKytnSFBqZUpzUHZ3PT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAa
      ERIPCgthdWRpdG9yMk1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAa
      DxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
