apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://143.198.247.194:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaINQ/Zg0oFozgkBNr/f+0zgzjGicJKW9RyaJa8d3lCJbHEuJcCt9cCtxcCngKWggBEAEaBgif
      9ueXBiIKc3lzY2hhbm5lbCpANDI2NDMzNmU3YmQwMzI5ZGM5ODgzZTU4MGZmYjdmZDk0ODdmNmE3
      MTI1YzU5MjkwYWQ3MjBmYTg1NjA5NDRjOBIaEhhq/+UB1fv/kf/n9BXXrcNP8wxzIQAKiZcS31sK
      3FsS2VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVVF1KzFCN1FSUXN1Z3JmdllvMWE1c2o5RzNJb3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRVd056STFOVFJhRncweU5UQTJNRFF3TnpJMU5UUmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJYbU84dEI0WGFKNVEwQTJTeVhqcyta
      MkFFajZYNUhkSUFraTFDb3JEM2d4VVoyb2MrKzJWU2RSSnpPOFVQCklPK0JXUG82MjhObEtZeE1z
      bzVlTHIwSG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVdStFckgrOEdnR2lieSt1ajJqOVM3R0RCZnJnd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdUSUVRTFpsQUtxbDFqUFNJTlBuRWdaWTlDSnlVRkNLNlYzSjdpMy9SN3k4Q0lR
      Qzg3SzNUCnU2VUFzKzVoT0FBSU1wWEhRSlQzcmZjMFc5bVYwcS9jdWpDOHBRPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFUQ0NB
      bnlnQXdJQkFnSVVScmpab3pZZlhleUxBWGxScTdhTXpXYTR4aUV3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UVXdOek14TURCYUZ3MHlNekE0TVRVd056TTJNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCTHpDWDhQZkdtbDBOUGJvRENRNzNZTGY4d1Q2SnUzK2QwYTFMQUQxdys5SAorMXo4TEpuTHN6
      UE5pNTF0NUlDcElYejF6bkdVdS9vL3hHZ24vWmJxV2tXamdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVWGdtVnpkYWFZMnJFRHhy
      bnFIYTEKUy9lTnBJZ3dId1lEVlIwakJCZ3dGb0FVdStFckgrOEdnR2lieSt1ajJqOVM3R0RCZnJn
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TmprMU5EaGtPR05qTmkxbVkzWnNkRENCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnREVsZkVQYjlZYWl0CnZ1MnEvaWFIQThw
      S1M0YnhBOU92NUl3SVorSG5KS1FDSUhQVlVGMTJnTmNIODYyYVBkRWpSenNDdEtpR3FGRisKUTl1
      ZWdXU1FOVWM4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVF1KzFCN1FSUXN1
      Z3JmdllvMWE1c2o5RzNJb3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRV
      d056STFOVFJhRncweU5UQTJNRFF3TnpJMU5UUmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVJYbU84dEI0WGFKNVEwQTJTeVhqcytaMkFFajZYNUhkSUFraTFD
      b3JEM2d4VVoyb2MrKzJWU2RSSnpPOFVQCklPK0JXUG82MjhObEtZeE1zbzVlTHIwSG8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      dStFckgrOEdnR2lieSt1ajJqOVM3R0RCZnJnd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdUSUVR
      TFpsQUtxbDFqUFNJTlBuRWdaWTlDSnlVRkNLNlYzSjdpMy9SN3k4Q0lRQzg3SzNUCnU2VUFzKzVo
      T0FBSU1wWEhRSlQzcmZjMFc5bVYwcS9jdWpDOHBRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRt
      aW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVv
      dXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENh
      cGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa1BEKDUNvbnNlbnN1c1R5cGUSwhEStxEK
      CGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVyLW5ldBCKNxq6CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVU03YUpsT2NrRWIydWhpeW1xNFNtQ200
      b3NaQXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJj
      d0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRVd056TXhNREJhRncw
      eU16QTRNVFV3TnpNMk1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFz
      VEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3
      RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOXdEZ0d5aW10V3pJRTBHMG1zMFIrRTVk
      WEZvTXpvc2hjMndGCmdGM0NtYjBjWk8wWi9OdkV4ektjdkRSdVlnaFVPSFQ4elQrZmw0dTZNU29P
      a1Y5RU9xT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dy
      QmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FV
      VFhyRkMyam10MmVybWhSdlkwMHFnVHVRVkdrd0h3WURWUjBqCkJCZ3dGb0FVdStFckgrOEdnR2li
      eSt1ajJqOVM3R0RCZnJnd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dC
      QkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2li
      M0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCQjJXbGRhN05JKzNzcHVXellH
      VFN0MnZuby9KQjN2eTVxdzlITApFd1NUR1FJZ2ZoREFrVGs1ai9rMVdqTlVSRXRrUzVXVUJxSFZJ
      alhXbkQ5WTB1UTFzTGc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBtZ0F3SUJBZ0lVTTdhSmxPY2tFYjJ1aGl5bXE0U21D
      bTRvc1pBd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVFV3TnpNeE1EQmFG
      dzB5TXpBNE1UVXdOek0yTURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFN
      UzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpC
      QXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1G
      a3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUU5d0RnR3lpbXRXeklFMEcwbXMwUitF
      NWRYRm9Nem9zaGMyd0YKZ0YzQ21iMGNaTzBaL052RXh6S2N2RFJ1WWdoVU9IVDh6VCtmbDR1Nk1T
      b09rVjlFT3FPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJn
      Z3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVUWHJGQzJqbXQyZXJtaFJ2WTAwcWdUdVFWR2t3SHdZRFZSMGoKQkJnd0ZvQVV1K0VySCs4R2dH
      aWJ5K3VqMmo5UzdHREJmcmd3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNp
      MXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3
      Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpv
      aWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJCMldsZGE3TkkrM3NwdVd6
      WUdUU3Qydm5vL0pCM3Z5NXF3OUhMCkV3U1RHUUlnZmhEQWtUazVqL2sxV2pOVVJFdGtTNVdVQnFI
      VklqWFduRDlZMHVRMXNMZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFk
      bWlucxLzLgoLQ29uc29ydGl1bXMS4y4SmC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvkt
      EswWCgthdWRpdG9yMU1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVUlrNGdHZDNIQjBYaUNK
      bGNoK3hFaTZxWkdmVXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE5U
      QTNNamN4T0ZvWERUSTFNRFl3TkRBM01qY3hPRm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRU93dmwrQ0ZyQXArYW1zZVhJcGw3NldyTmNGYnVKc0M4WmV4
      bTFvSHp3SEJPMDU3SU92dlZ6R3lyClVoSERKaHc0T3FFUG9TS2RLa1BQNWpMQW9GcmM0YU5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZCdnpDaktGYThnYXEzcnYzbmMxSVdtN0NnOURNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFD
      ODVZTGE0VXkrQWN4MDFuOURiaGd3LzEzZi80Q3JhN2FJWnRHcndzdFJiUUloCkFLVngxb0Y4dEl6
      aW53YVpCeTduT2gzNHRrbU5iT1RlSDRSOEJVTWRNME8yCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIr4ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXBxZ0F3SUJBZ0lVWWl0
      eTM3bkN3WE1JYW0rSGVTbDV1bHBrZ3VFd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd4TlRBM05ETXdNRm9YRFRJek1EZ3hOVEEzTkRnd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRUZPUWg4R05FWjE4a2RlT0QKa2dkYUdyTlozZXlpbHVGUWl1bHRUSncx
      cDEyNVB1bUI4NWdVc2FTa3NudXl2TVdwVlNGZDdZUkdOMUd5S3hZcgpnUCtybDZPQ0FSb3dnZ0VX
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlFm
      c2xCOU5MRXdYQ2wzZk0rNWNBQU1oR20yTHpBZkJnTlZIU01FR0RBV2dCUWI4d295aFd2SUdxdDYK
      Nzk1M05TRnB1d29QUXpBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDNORFZtTnpoa1lqWmlM
      VGg0TWpkbwpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqRWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      UzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdS
      UUloQUwvQ2xoNDVCUmVndEpBNEpzZGN2TXl1TGZrRkF0dUxQTlhoClE0clZYYlpJQWlBU1llS3oz
      NSs3WjhNWVlORkFPSGxCMUJRcjhHbk80b1NTYzQ1YzhJZjlzQT09Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL1RDQ0FhS2dBd0lCQWdJVUlrNGdHZDNIQjBYaUNKbGNoK3hFaTZxWkdmVXdDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE5UQTNNamN4T0ZvWERUSTFNRFl3TkRBM01q
      Y3hPRm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRU93
      dmwrQ0ZyQXArYW1zZVhJcGw3NldyTmNGYnVKc0M4WmV4bTFvSHp3SEJPMDU3SU92dlZ6R3lyClVo
      SERKaHc0T3FFUG9TS2RLa1BQNWpMQW9GcmM0YU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZCdnpDaktGYThnYXEzcnYzbmMxSVdt
      N0NnOURNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFDODVZTGE0VXkrQWN4MDFuOURiaGd3LzEz
      Zi80Q3JhN2FJWnRHcndzdFJiUUloCkFLVngxb0Y4dEl6aW53YVpCeTduT2gzNHRrbU5iT1RlSDRS
      OEJVTWRNME8yCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHV3JpdGVycxIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgB
      Eh0SCBIGCAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikS
      HwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9y
      Mk1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dBd0lCQWdJVVdsTmpzVGkxSkFhV041R0JLSDZGamlIcDNB
      TXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE5UQTNNamcwTVZvWERU
      STFNRFl3TkRBM01qZzBNVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRW1ENng5ZUFxZFQ5MFEreDltVmhlUzJsYjY4bm5lcjR4elk5WWJRaWUyaExudjIv
      VEVDelVLcUlkClJOWkdsVkc3aDBPbzU1c2ZWSVo0MEExRmYzRW9GNk5DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZDbUxUMXJWV3ow
      ZTRwSG1DdWl5aUI2S215Q0xNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUd6ekFObndUcmUrdS9k
      emU4Q2xnbG4zTCtzTFlvd01SUWpIUnRtTmU4aWZBaUF1CmNmWXdacVMwbXZHbWg1T0M4aE16Y1Ju
      WWsyYXE5N3BXdURGblpxbDJ4UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXB1Z0F3SUJBZ0lVSk1mbFdMODZzMFJ6WWhJ
      QjI0STVHQytKcUpnd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TlRB
      M05EWXdNRm9YRFRJek1EZ3hOVEEzTlRFd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdO
      VkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4
      SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1N
      RWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VI
      QTBJQUJGZDRsdGhLVktxdFFNbE4KeFFKK2N4Unk5NW9jdDZCREtqWnZ3STE1SDNkSFlGZys2ZUFl
      bmcrMjhBakFPQUc1T1FqK2xyRkNUdHJGak8veApaY2tTM2R5amdnRWFNSUlCRmpBT0JnTlZIUThC
      QWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVckxodVRGNDIraThH
      cWVyTE1NSEQ3V2RKdnJFd0h3WURWUjBqQkJnd0ZvQVVLWXRQV3RWYlBSN2kKa2VZSzZMS0lIb3Fi
      SUlzd0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXRObVkyWXpZMlpEVmtOQzF5WmpoegpOVENC
      andZSUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlM
      Q0poClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJ
      aXdpYUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lh
      R1l1Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUEwWFJXRXhh
      WitXSXJFcDh4a1ZjYVBjSUFGTHlsN3QyVUNLCkZiNFRMUEtFQWlCN0FvbTF2eWpDUTBXbE1CYmRy
      eXdtRHRSOEFlaHdpRkJ5UGI0UTNSYldJZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4K
      BFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dB
      d0lCQWdJVVdsTmpzVGkxSkFhV041R0JLSDZGamlIcDNBTXdDZ1lJS29aSXpqMEVBd0l3ClhERUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUI0WApEVEl5TURneE5UQTNNamcwTVZvWERUSTFNRFl3TkRBM01qZzBNVm93WERFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRW1ENng5ZUFxZFQ5MFEr
      eDltVmhlUzJsYjY4bm5lcjR4elk5WWJRaWUyaExudjIvVEVDelVLcUlkClJOWkdsVkc3aDBPbzU1
      c2ZWSVo0MEExRmYzRW9GNk5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFm
      OEVCQU1DQWFZd0hRWURWUjBPQkJZRUZDbUxUMXJWV3owZTRwSG1DdWl5aUI2S215Q0xNQW9HQ0Nx
      RwpTTTQ5QkFNQ0EwY0FNRVFDSUd6ekFObndUcmUrdS9kemU4Q2xnbG4zTCtzTFlvd01SUWpIUnRt
      TmU4aWZBaUF1CmNmWXdacVMwbXZHbWg1T0M4aE16Y1JuWWsyYXE5N3BXdURGblpxbDJ4UT09Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggA
      GhESDwoLYXVkaXRvcjJNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIGCAES
      AggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGlj
      eRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhAS
      Bgj/////DxoGQWRtaW5zGkoKEE9yZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVy
      LW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5z
      Gg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
