apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a7e9892a5136f4fa8b1cda6ba31b358b-1780904258.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIMbLfSyngQnz+fuQGLQhBpWf2YSgpfzIJVfZSpw8+2cJEt5cCttcCthcCngKWggBEAEaBgjV
      pseXBiIKc3lzY2hhbm5lbCpANjUwMDE0NjJkYjI5N2FmNWUxOGEyMDBkMTBlMmQ3OGUxMjZmYjIy
      YzdkZDJlNDJlZmEyNWY5NzA3MGEyOWYzYhIaEhiyA3CUNS/XfklWRunVGh5KkWFkiDcYi/US21sK
      2FsS1VsSnyoKB09yZGVyZXISkyoSjhYKCm9yZGVyZXJNU1AS/xUamxQKA01TUBKTFBKIFBKFFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVWV0TGN4YzBNbStnMmNGRTErZDA5SEdsbFk1OHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURrd016RXdOVE5hRncweU5UQTFNamt3TXpFd05UTmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJrNExWSEhwK3V0eGR2N1JwbUJCc25G
      dkh0NnV1bjdHK3gxZWI2aHdlRHNWb2IvWVRTcEdQTXI4OW5Ka25tCks1aUxQQ1FwTzNVT0dzY0FV
      NTlnRE9CTW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVc2Q5WFRic280eWFqQVdsUUIxcXVRV3lSTG9Fd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdUM2U4QlRjWGdHcW8xNDl0VzRBbUpxR1RJdHZkMklQSDVYN3pPOVlsbkpzQ0lG
      RWZ5L0tDCkxiVHZReE81YVgrUnBQTlFSNExWdE1Uc2V2WEVwU1ZZbS9rbwotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKWCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMWpDQ0FueWdB
      d0lCQWdJVUlIK0EwRzV3aEdBSmhPdTgwM2ZIWHU3c3J1UXdDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TURrd016RTBNREJhRncweU16QTRNRGt3TXpFNU1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJK
      ci9JVHBHaDFwK2Eva1llYmV0RkQ3b3JoSEkwRUd3cjJ2TEdsTlBZQ2NnCk5VMFlqcGVKejlFSlV0
      WnA2WXhJT2pKQ1lBV0xIakNIOVBoN2hYWU5KSHFqZ2dFUU1JSUJEREFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV4VE5hTlM0clp3TXhZOW00YldN
      SApFQ3pjaW1Bd0h3WURWUjBqQkJnd0ZvQVVzZDlYVGJzbzR5YWpBV2xRQjFxdVFXeVJMb0V3SkFZ
      RFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROVGcxTm1Oa1pqaGpOQzFrWW5NMU5EQ0JoUVlJS2dN
      RUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYlds
      dUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTVRIL0NQRkNLWGIKZkZSNnBkczExNjFWUDFW
      TUp0eUt3dUZtaHQyN2tiTkZBaUFhSHpEZWR2WnNFWHJ6NElqTWFWRkUrYVBlTWFlbgpNZHRCSzA2
      aG9Idzh5Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrlBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVWV0TGN4YzBNbStn
      MmNGRTErZDA5SEdsbFk1OHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURr
      d016RXdOVE5hRncweU5UQTFNamt3TXpFd05UTmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVJrNExWSEhwK3V0eGR2N1JwbUJCc25Gdkh0NnV1bjdHK3gxZWI2
      aHdlRHNWb2IvWVRTcEdQTXI4OW5Ka25tCks1aUxQQ1FwTzNVT0dzY0FVNTlnRE9CTW8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      c2Q5WFRic280eWFqQVdsUUIxcXVRV3lSTG9Fd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdUM2U4
      QlRjWGdHcW8xNDl0VzRBbUpxR1RJdHZkMklQSDVYN3pPOVlsbkpzQ0lGRWZ5L0tDCkxiVHZReE81
      YVgrUnBQTlFSNExWdE1Uc2V2WEVwU1ZZbS9rbwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoG
      QWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRt
      aW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMi
      MwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyoGQWRt
      aW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIO
      EgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJp
      bGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRj
      ZHJhZnQSqhEKkxEKFG9yZGVyZXIxLm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVRnVrV0M2b0wrOVc1VVZiZnJCMXhxaUt1U2w4
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNRGt3TXpFME1EQmFGdzB5TXpB
      NE1Ea3dNekU1TURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4
      dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5
      eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lI
      CktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUU5cUVKS0JYUmovbGFua1B0Y2JaU2lKR3VMR3VO
      S1cyQ0tIM2QKYUlVa0MrSUN3MktMY2FOMHJKUmNUU1FISDlpRXFkVTZBdUkrWlNjV245dEJ4aWo0
      bUtPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VG
      QlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVUrOTBj
      aGxVUDJiU090a2h4WFFBUU1GaTZOMlF3SHdZRFZSMGoKQkJnd0ZvQVVzZDlYVGJzbzR5YWpBV2xR
      QjFxdVFXeVJMb0V3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFND
      R205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3
      SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUK
      ZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmta
      WEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBMFRyRUJ5OEgwUFdDanZKVWdEU2lE
      SmZzcWNELzFCTDdBUHM2ClJFbWV5c2tDSUVPSXBzcnFEclFVdFFGQzFRK1doZkg5Q1ZHMUN2T0pj
      M0FUTllneW1QMVcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQzh6Q0NBcG1nQXdJQkFnSVVGdWtXQzZvTCs5VzVVVmJmckIxeHFpS3VT
      bDh3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dG
      UVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1Ea3dNekUwTURCYUZ3MHlN
      ekE0TURrd016RTVNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFN
      Qzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RC
      Mjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3
      WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRTlxRUpLQlhSai9sYW5rUHRjYlpTaUpHdUxH
      dU5LVzJDS0gzZAphSVVrQytJQ3cyS0xjYU4wckpSY1RTUUhIOWlFcWRVNkF1SStaU2NXbjl0Qnhp
      ajRtS09DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJn
      RUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVSs5
      MGNobFVQMmJTT3RraHhYUUFRTUZpNk4yUXdId1lEVlIwagpCQmd3Rm9BVXNkOVhUYnNvNHlhakFX
      bFFCMXF1UVd5UkxvRXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpY
      U0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJG
      eDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNK
      a1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUEwVHJFQnk4SDBQV0NqdkpVZ0RT
      aURKZnNxY0QvMUJMN0FQczYKUkVtZXlza0NJRU9JcHNycURyUVV0UUZDMVErV2hmSDlDVkcxQ3ZP
      SmMzQVROWWd5bVAxVwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiA
      gIAIGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tW
      YWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1Jl
      YWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      EvMuCgtDb25zb3J0aXVtcxLjLhKYLgoaQ2FyYm9uQWNjb3VudGluZ0NvbnNvcnRpdW0S+S0SzBYK
      C2F1ZGl0b3IxTVNQErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IxTVNQEu0FLS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvVENDQWFLZ0F3SUJBZ0lVVlJaN05pY2dCT3dLZXJIWTFy
      SVVPMkFEanFJd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJB
      Z01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRH
      OXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd3T1RBek1U
      TXdPVm9YRFRJMU1EVXlPVEF6TVRNd09Wb3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJB
      Z01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBECkFRY0RRZ0FFVGREK29SZmxwZVhrYjJkakl2b2hWSW9mUnRwa1Y5aHgyV1M5SmNy
      QnNSUy9xbk5ZL01zcmVOQ0sKaGNyVVQzYURWUDRFZnB2TUhKaEN2NDdnM3BDcUpLTkNNRUF3RHdZ
      RFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRksx
      R0Rid1E1WjdBaDY3Mis2aElycWVOYXpFdk1Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUURTZ3ZI
      UUh2L21TdkNFRnBwTnlBU1FTSW11NDZRZ1lLeDZsLzRtZ01xTHpBSWgKQU1YdEJERDZiYm94TGgv
      M1VLcEc3dzJZTzU5ZTQ5a1pSNEdYWnJjVGl3ZTYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi
      vggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHFnQXdJQkFnSVVkazF2OXhq
      VmkzQlB0clRRQmdOSXpZYU5PVnN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBn
      eER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFR
      S0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJ
      eU1EZ3dPVEF6TVRZd01Gb1hEVEl6TURnd09UQXpNakV3TUZvd2VqRUxNQWtHQTFVRUJoTUNRMGd4
      R2pBWQpCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SRXdEd1lEVlFRS0V3aEJkV1Jw
      ZEc5eU1URWZNQXdHCkExVUVDeE1GWVdSdGFXNHdEd1lEVlFRTEV3aGhkV1JwZEc5eU1URWJNQmtH
      QTFVRUF3d1NRV1J0YVc1QVlYVmsKYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      emowREFRY0RRZ0FFWDZaMERnc0RzRHdXcEhrOQpRc3h2YW05eWY2dXNjcU4vUXZLdEkyWExaT3Ux
      NkV2L21uWjZnVzBsODdWalpWVGFUcDNpU3F3RmVDSUN3R2JOClovaUtQYU9DQVJvd2dnRVdNQTRH
      QTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCUll2Yk9r
      aHh3bTJ1OXhDeXhOZFpFcGh4alROekFmQmdOVkhTTUVHREFXZ0JTdFJnMjhFT1dld0lldQo5dnVv
      U0s2bmpXc3hMekFrQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kwM09XTTBOMlkyWTJRNExYRm9h
      R0pzCk1JR1BCZ2dxQXdRRkJnY0lBUVNCZ25zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmsKYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVlYVmth
      WFJ2Y2pFaUxDSm9aaTVGYm5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQmhkV1JwZEc5eU1TMXVa
      WFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpCmZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhB
      TEdwMDQxb1FkUldndlJ2dUUxS3hTdDk4K3gxUnVubFpwbloKaFB3ZXJoUzFBaUJEcE5rUUVPUE96
      MVJkeFFQOEtOMlQzR0s1cFVBUHd5ZlNrNmNSNGxjQm9RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      VENDQWFLZ0F3SUJBZ0lVVlJaN05pY2dCT3dLZXJIWTFySVVPMkFEanFJd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd3T1RBek1UTXdPVm9YRFRJMU1EVXlPVEF6TVRNd09W
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFVGREK29S
      ZmxwZVhrYjJkakl2b2hWSW9mUnRwa1Y5aHgyV1M5SmNyQnNSUy9xbk5ZL01zcmVOQ0sKaGNyVVQz
      YURWUDRFZnB2TUhKaEN2NDdnM3BDcUpLTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRksxR0Rid1E1WjdBaDY3Mis2aElycWVOYXpF
      dk1Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUURTZ3ZIUUh2L21TdkNFRnBwTnlBU1FTSW11NDZR
      Z1lLeDZsLzRtZ01xTHpBSWgKQU1YdEJERDZiYm94TGgvM1VLcEc3dzJZTzU5ZTQ5a1pSNEdYWnJj
      VGl3ZTYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAES
      HRIIEgYIARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIf
      CAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAES
      GxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJBZ0lVU2xod2xXSmtIT3Q5dHJwUWgwL2Y5WG1aaFNRd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3T1RBek1UUXlOMW9YRFRJMU1E
      VXlPVEF6TVRReU4xb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFZUNYd2E0QllwaFBnVnZZblJYM2dMdkpyYkxOVXlQMC9yVEMrZzlJbTlJQko0M3IxZGtW
      UnYzSFcKRGdpWThHcys3bWFCVG8zR2IxcHFDSlo1RFZ2TE1LTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRktMbmwrZjAzWG5NUG9n
      OFR2OTlEU1JsZWRTdE1Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJUUNKYnNZalZmaEVYNG8xUjFj
      Um5xMnRKK2RpbW05aHZsR1pCWm9YcmJ1TTBRSWcKTWR6V3dXZWtCU1ZqeDRUNEVqZWxVMHlBbzA0
      UVZlQmc2OEc2WjVOTDQ4WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHVnQXdJQkFnSVVadmtSbS9GOXJkaitpZS9yUUdG
      eGhVVWtXb0l3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3dPVEF6TVRn
      d01Gb1hEVEl6TURnd09UQXpNak13TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      QkVIT3FUTkVMRCtrNkUyNQo2eHJ6TXBSb0c3aVJoaEZSenl5UkFiaGEyQXlYL3pqRThMVHJVTXpz
      NlltRHIydWJxNXhUUGJwVHhibWlZUVNWCjFnM0FRRUNqZ2dFYU1JSUJGakFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVVHNWp2VWtoUWcwcjRCZGpY
      Y05XekFmcE5QZFV3SHdZRFZSMGpCQmd3Rm9BVW91ZVg1L1RkZWN3KwppRHhPLzMwTkpHVjUxSzB3
      SkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE5UazNaRFZqWXpRNU5DMXdkMnR5CmJqQ0Jqd1lJ
      S2dNRUJRWUhDQUVFZ1lKN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmgK
      WkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNkltRjFaR2wwYjNJeUlpd2lh
      R1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFXNUFZWFZrYVhSdmNqSXRibVYwSWl3aWFHWXVW
      SGx3WlNJNkltRmtiV2x1CkluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJRFlWcHZwcEg0LzNo
      aGJBenFvRkNxMHcxa2srY1NYVHBtbXEKVEc1aHk1QmtBaUJKUVByNGxyY3U2Vk94RDVvT003Y3Nu
      dzFnZTc3MFhEcmU3NnY4N0kyeDRBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJB
      Z0lVU2xod2xXSmtIT3Q5dHJwUWgwL2Y5WG1aaFNRd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd3T1RBek1UUXlOMW9YRFRJMU1EVXlPVEF6TVRReU4xb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFZUNYd2E0QllwaFBnVnZZblJY
      M2dMdkpyYkxOVXlQMC9yVEMrZzlJbTlJQko0M3IxZGtWUnYzSFcKRGdpWThHcys3bWFCVG8zR2Ix
      cHFDSlo1RFZ2TE1LTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRktMbmwrZjAzWG5NUG9nOFR2OTlEU1JsZWRTdE1Bb0dDQ3FHClNN
      NDlCQU1DQTBnQU1FVUNJUUNKYnNZalZmaEVYNG8xUjFjUm5xMnRKK2RpbW05aHZsR1pCWm9YcmJ1
      TTBRSWcKTWR6V3dXZWtCU1ZqeDRUNEVqZWxVMHlBbzA0UVZlQmc2OEc2WjVOTDQ4WT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggAGg8S
      DQoLYXVkaXRvcjJNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAaERIPCgth
      dWRpdG9yMk1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
