apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBgfX/wJIg3YAeSJINayhjL82lv2yQ9bS8Bq84/xJ18iEt5cCttcCthcCngKWggBEAEaBgiA
      /vaXBiIKc3lzY2hhbm5lbCpAMTcxMWZmODYyZDQ4YWE3NzFmYTVkNjU4MzMzOTFlMmYyODc1ODZi
      ZjlhYjUzMTVkYTVhZjM4OTc2MWMyZjg0YhIaEhiQpfgShknzOZkzyiXnBOWjBUNsguJhHioS21sK
      2FsS1VsS7y4KC0NvbnNvcnRpdW1zEt8uEpQuChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL1
      LRLIFgoLYXVkaXRvcjFNU1ASuBYa0BQKA01TUBLIFBK9FBK6FAoLYXVkaXRvcjFNU1AS7QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9UQ0NBYUtnQXdJQkFnSVVVVHRzNGxxUjFUSGVO
      Y0x4VjZkdEpyYkdYVGN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJk
      V1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hP
      REEwTVRjeE0xb1hEVEkxTURZd056QTBNVGN4TTFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpC
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpq
      MENBUVlJS29aSXpqMEQKQVFjRFFnQUVjbzdRaVNZNnFGa2VFcVQ4NzlDWVFERnRMOEdnR0U5QXRX
      VUlxNXo4Y1daMFpwUlRUZGQwcGhLcAovVFpLV2Y1c3pHU3FmVk5qVWVvbUc3NS9jdzBpWDZOQ01F
      QXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JC
      WUVGRSt1U0lqczRzcGJubGk4SFo0eWFGektFR3lrTUFvR0NDcUcKU000OUJBTUNBMGtBTUVZQ0lR
      RENxdnNtTEFoQ043WGZoRStGaXhwb3pqWWtsOXdxdlVWc1B4SEVFMEZFMEFJaApBTjBHbm9KdHMy
      SjR6eVp1WkVzeXhxTVgzcGJDV0JIM3hwU0xKZjZLODNjUgotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwcWdBd0lCQWdJVU9a
      WUFtcmZQYkNVMk1yK2hWL0xmOEE0enpYc3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJo
      TUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0
      WApEVEl5TURneE9EQTBNVGN3TUZvWERUSXpNRGd4T0RBME1qSXdNRm93ZWpFTE1Ba0dBMVVFQmhN
      Q1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdo
      QmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRF
      Yk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBEQVFjRFFnQUVtSGJiWi9UM0VUNGtNSzRtCkczeExIRDR2cUhRY1JZREI3dlhXZklh
      WUpkNG1SUTBnVXNBNFBzbS9xcHhycHdwRWVNVWVoY0hQZnN6T2NYOTIKVm9Zem9xT0NBUm93Z2dF
      V01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJT
      SmtJTFRkNTVSKzZlVGFGQ3B0eW5la1lwNndUQWZCZ05WSFNNRUdEQVdnQlJQcmtpSTdPTEtXNTVZ
      CnZCMmVNbWhjeWhCc3BEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAxTlRkbVltWTNZalky
      TFRZeWMzWnUKTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWww
      SWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      WVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5
      TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURSd0F3
      UkFJZ2J3NzI2MFVNd1djUXQ0MzV2dHJEQVJ0NzRIOGplRGwxcUw1WQoyN3phWVRNQ0lFaEVtRFR5
      RUU1eUtLZVkrYkhGcWZjQ2JvelJyNGJkclNCUy80enJtZWFLCi0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlC
      L1RDQ0FhS2dBd0lCQWdJVVVUdHM0bHFSMVRIZU5jTHhWNmR0SnJiR1hUY3dDZ1lJS29aSXpqMEVB
      d0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZ
      WFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE9EQTBNVGN4TTFvWERUSTFNRFl3TnpBME1UY3hN
      MW93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZ
      WFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRWNvN1Fp
      U1k2cUZrZUVxVDg3OUNZUURGdEw4R2dHRTlBdFdVSXE1ejhjV1owWnBSVFRkZDBwaEtwCi9UWktX
      ZjVzekdTcWZWTmpVZW9tRzc1L2N3MGlYNk5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0Jn
      TlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZFK3VTSWpzNHNwYm5saThIWjR5YUZ6S0VH
      eWtNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFEQ3F2c21MQWhDTjdYZmhFK0ZpeHBvempZa2w5
      d3F2VVZzUHhIRUUwRkUwQUloCkFOMEdub0p0czJKNHp5WnVaRXN5eHFNWDNwYkNXQkgzeHBTTEpm
      Nks4M2NSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgB
      Eh0SCBIGCAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikS
      HwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsS
      CBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9yMk1T
      UBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVWJuam9uWFZnUXFacEgwY0R5WDA4TE80WTlIb3dD
      Z1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdB
      MVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE9EQTBNVGd5TVZvWERUSTFN
      RFl3TnpBME1UZ3lNVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdB
      MVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApB
      UWNEUWdBRW9KSXdNZ1dlb0NWNjZXU2hnTkdqeDB0ZkpiTks5N0szOTF0aVBVTVZvL2hPaXlqdkpQ
      YWZMcGZXCjl0amhmMk80Skt6MURpbjRyUTZ0VGI3RG14clFqYU5DTUVBd0R3WURWUjBUQVFIL0JB
      VXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZBUElmdUxNc3ZMVElm
      SWhzdDB5OG5nYXQyZ0ZNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFDQ1pUZDR5VE50ZlJ0dEdF
      ck9VejJHM2JCYWhoWnZEWkU1V3JjVWZ5NFZxUUloCkFKZlZiT3lhZ1VvSVdxR3ptM01BRHlSU291
      ZEpvSStGaW1idE5Rb0toS21DCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXB1Z0F3SUJBZ0lVRUJQYXZDREhKVW9XZ0UrTXJG
      TDFkVWNLalRRd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRH
      OXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4T0RBME1U
      a3dNRm9YRFRJek1EZ3hPREEwTWpRd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdOVkJB
      Y1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4SHpB
      TQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1NRWtG
      a2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJ
      QUJBTjA1dDN3N1NvemNoWFIKaUFyQVRHV2J4WEdRdmRoWTl5SHpZT0h5aDc1K2hOUysxSlIzeEtq
      K3g2WnNTTTBldTdkL2xJNmxneTBPV0NGNwpEOFljVVNpamdnRWFNSUlCRmpBT0JnTlZIUThCQWY4
      RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVaVhCNkJsWXRFcENEWndx
      VkxvdHRPMHdQb0tNd0h3WURWUjBqQkJnd0ZvQVVBOGgrNHN5eTh0TWgKOGlHeTNUTHllQnEzYUFV
      d0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXROemRpWXpVME9XUTROQzF3WkhCegpORENCandZ
      SUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlMQ0po
      ClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJaXdp
      YUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lhR1l1
      Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUhURzJqakJxZ21Y
      L0RRb0RSdzN2TW9Wc3FIellxUlAxVkIyCjAwUnhWNGJmQWlCNWxNM2xYcnRKRVJBem03cEpEYmR0
      V1RCK2tEbS9pY1Qyczd5TmZHVHVaUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNI
      QTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lC
      QWdJVWJuam9uWFZnUXFacEgwY0R5WDA4TE80WTlIb3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRi
      bVYwTUI0WApEVEl5TURneE9EQTBNVGd5TVZvWERUSTFNRFl3TnpBME1UZ3lNVm93WERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRi
      bVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRW9KSXdNZ1dlb0NWNjZXU2hn
      TkdqeDB0ZkpiTks5N0szOTF0aVBVTVZvL2hPaXlqdkpQYWZMcGZXCjl0amhmMk80Skt6MURpbjRy
      UTZ0VGI3RG14clFqYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVC
      QU1DQWFZd0hRWURWUjBPQkJZRUZBUElmdUxNc3ZMVElmSWhzdDB5OG5nYXQyZ0ZNQW9HQ0NxRwpT
      TTQ5QkFNQ0Ewa0FNRVlDSVFDQ1pUZDR5VE50ZlJ0dEdFck9VejJHM2JCYWhoWnZEWkU1V3JjVWZ5
      NFZxUUloCkFKZlZiT3lhZ1VvSVdxR3ptM01BRHlSU291ZEpvSStGaW1idE5Rb0toS21DCi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYI
      ARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAa
      DxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoREg8K
      C2F1ZGl0b3IyTVNQEAEaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRIn
      EgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcv
      Q2hhbm5lbC9PcmRlcmVyL0FkbWlucxKjKgoHT3JkZXJlchKXKhKSFgoKb3JkZXJlck1TUBKDFhqf
      FAoDTVNQEpcUEowUEokUCgpvcmRlcmVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIrRENDQVo2Z0F3SUJBZ0lVZHlqWFJsZDN0MERwcGxYNWNzYlFCd21TdW9jd0NnWUlLb1pJ
      emowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVq
      WVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVGd3TkRFMk1EaGFGdzB5TlRBMk1EY3dOREUy
      TURoYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05W
      QkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEpsY2pFWApNQlVHQTFVRUF3d09ZMkV1
      YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUzV1Wm5U
      ckx1QzlmY0hhV2IvMTZiU1E0em5xQkVERHNPOUJHWU1DTXd1VmRBTVVnejBPZkFCMkllR2JQbzgK
      WUthQTlqN0hHR1paN0NTK2k5TWVEU1FibzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdB
      MVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVV3ZUo3TThSNjFGa2tFRldwcGZyQXNjL2ZC
      QW93Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJZ1lDOGNWTkpSSlZBcjUrSVJuampTbU1SSmduV2sz
      WTgvWE02WWlUazJhdFFDSVFEakNWbE4KSndNWk1MM21kVTFiTDJYbU5DSFJXRE01RHowc3RQa0k2
      VGpMWlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKSCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDMURDQ0FudWdBd0lCQWdJVUIzUUkwTHgwMXRiamZFK0NhN0w3bFFBaGV1Z3dD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURW
      UVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRnd05ERTJNREJhRncweU16QTRN
      VGd3TkRJeE1EQmFNR2d4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRN
      QzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmti
      V2x1TVJvd0dBWURWUVFEREJGQlpHMXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJNR1ZmblBRbHBKbGtyd3ptK0Y2RE9heXBsTDRHc0RUdGRBd1Bw
      OGUrbnpXCkJETVIraEh1eWYwU1U5bXA3R2Fac24xVzk4K0YzSkgrdHpOSDFQcVFFaDJqZ2dFUE1J
      SUJDekFPQmdOVkhROEIKQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVpcFpFVUVVakx1NENCZUlVS3Zwbgo0MVBDWFNzd0h3WURWUjBqQkJnd0ZvQVV3ZUo3TThSNjFG
      a2tFRldwcGZyQXNjL2ZCQW93SXdZRFZSMFJCQnd3CkdvSVlZMkV0ZEc5dmJITXRZelJrWWpnM05q
      ZGlMV1E1YmpWb01JR0ZCZ2dxQXdRRkJnY0lBUVI1ZXlKaGRIUnkKY3lJNmV5SmhZbUZqTG1sdWFY
      UWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cApZWFJwYjI0aU9p
      SWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnZjbVJsY21WeUxXNWxkQ0lzCklt
      aG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQjlUc0pSRkR0
      TU9WNEwKQWhvT2VlazNpais5eW9IUmlBbjdkNG1RVlZjWklRSWdaWC94dUJVY3dFSFV2cy9BdTAz
      U21YUHY3dkxKZlBFVgowNnN5c2ZBRWx3QT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoE
      U0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3
      SUJBZ0lVZHlqWFJsZDN0MERwcGxYNWNzYlFCd21TdW9jd0NnWUlLb1pJemowRUF3SXcKV2pFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1
      bGREQWVGdzB5Ck1qQTRNVGd3TkRFMk1EaGFGdzB5TlRBMk1EY3dOREUyTURoYU1Gb3hDekFKQmdO
      VkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpF
      UU1BNEdBMVVFQ2d3SFQzSmtaWEpsY2pFWApNQlVHQTFVRUF3d09ZMkV1YjNKa1pYSmxjaTF1WlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUzV1Wm5Uckx1QzlmY0hhV2IvMTZi
      U1E0em5xQkVERHNPOUJHWU1DTXd1VmRBTVVnejBPZkFCMkllR2JQbzgKWUthQTlqN0hHR1paN0NT
      K2k5TWVEU1FibzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJ
      QnBqQWRCZ05WSFE0RUZnUVV3ZUo3TThSNjFGa2tFRldwcGZyQXNjL2ZCQW93Q2dZSUtvWkl6ajBF
      CkF3SURTQUF3UlFJZ1lDOGNWTkpSSlZBcjUrSVJuampTbU1SSmduV2szWTgvWE02WWlUazJhdFFD
      SVFEakNWbE4KSndNWk1MM21kVTFiTDJYbU5DSFJXRE01RHowc3RQa0k2VGpMWlE9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAES
      AggAGg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAa
      DhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwK
      Cm9yZGVyZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRl
      cmVyTVNQEAEaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRt
      aW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9u
      cxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxrUEQoNQ29u
      c2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9yZGVyZXIxLm9yZGVyZXItbmV0EIo3
      GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVRjRkZFQ0
      b2R5anoxai9nQVJERi9WZ21uOVlNd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1q
      QTRNVGd3TkRFMk1EQmFGdzB5TXpBNE1UZ3dOREl4TURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJz
      d0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdW
      eVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05
      eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVldm1BQnUy
      c3BuRU9oK1J5Sm9MajlHSGJ1Lzg1enZaR2U4TXQKRS84Tks1dVA0MHZQT0hBQXlDUTU1aXF2RlVL
      bUJtT0MveEVXbDBrVVhJVnA4cGI2T2FPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURB
      ZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJ
      d0FEQWRCZ05WSFE0RUZnUVVYL2l3bHFLK1JLTlNram5JNE1wbnc3RHR3Z1F3SHdZRFZSMGoKQkJn
      d0ZvQVV3ZUo3TThSNjFGa2tFRldwcGZyQXNjL2ZCQW93T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEps
      Y2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0
      TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFp
      TENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVB
      eDI2bGZ6YWNnTTRCNGwvSGlaVHJlcEJ5TEtpd2gxYlBkNHRRCisxRW1xdE1DSURwZFFZbkpScDl4
      dkpYTHphcG55WGI4YUYvWTdwaklhaWlzRm1wQXZtb08KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NBcG1nQXdJQkFnSVVGNGRk
      VDRvZHlqejFqL2dBUkRGL1ZnbW45WU13Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkK
      TWpBNE1UZ3dOREUyTURCYUZ3MHlNekE0TVRnd05ESXhNREJhTUcweEN6QUpCZ05WQkFZVEFrZENN
      UnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXla
      R1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhM
      bTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWV2bUFC
      dTJzcG5FT2grUnlKb0xqOUdIYnUvODV6dlpHZThNdApFLzhOSzV1UDQwdlBPSEFBeUNRNTVpcXZG
      VUttQm1PQy94RVdsMGtVWElWcDhwYjZPYU9DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURx
      REFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9C
      QUl3QURBZEJnTlZIUTRFRmdRVVgvaXdscUsrUktOU2tqbkk0TXBudzdEdHdnUXdId1lEVlIwagpC
      Qmd3Rm9BVXdlSjdNOFI2MUZra0VGV3BwZnJBc2MvZkJBb3dPd1lEVlIwUkJEUXdNb0lVYjNKa1pY
      SmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVky
      OXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlq
      b2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpY
      UWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFp
      RUF4MjZsZnphY2dNNEI0bC9IaVpUcmVwQnlMS2l3aDFiUGQ0dFEKKzFFbXF0TUNJRHBkUVluSlJw
      OXh2SlhMemFwbnlYYjhhRi9ZN3BqSWFpaXNGbXBBdm1vTwotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFk
      ZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
