apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a7e9892a5136f4fa8b1cda6ba31b358b-1780904258.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIKShFkCvFIl0Bv2+h6x5He2LUnNgPjCQkDFw1vqIk+fBEuZcCuNcCuBcCngKWggBEAEaBgij
      2dGXBiIKc3lzY2hhbm5lbCpAZTcxYjc4NjA2MDgwODkxODVkZjg3OGFlNGVhYWIzZjRiNGY5NTk2
      ODIyMWFkMGU0YzllNzE3NDg3ZDA2ZWQyYxIaEhjS91o2qyTeBAh6LNQzOaEaAmZslCtweG4S41sK
      4FsS3VsSpyoKB09yZGVyZXISmyoSlhYKCm9yZGVyZXJNU1AShxYaoxQKA01TUBKbFBKQFBKNFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVUphRlRwRitGU0o1UUhuK2taNEJwNWVuUFZWWXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRFd01qTXdNakJhRncweU5UQTFNekV3TWpNd01qQmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRTL3o4VWNqaC9OVlY3cG81bHZHZlFN
      SFFaRG5iWkI2N2ZqejJXMkpKT2lRNFY2aWZGQ094TUE4bmZLU2ZqCmRkSDZDb3NuK0puT0pkMmc1
      ZGNBNG9ab28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVbzNldldLNzNtbk9kSW05bTEvc1RSalJBYVdRd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdFMVF5MklKU01NWE90V2dpWTlOaXg0MDlRZjdYRlc2WmlPOENWeXY3MDlBQ0lR
      RHg2LytHCnBYK1JSaTIycEJIT2tEZU40Mk9kTG9PcDZyaHlzNDhBMVdXQ253PT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoilggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFqQ0NB
      bnlnQXdJQkFnSVVOQ3ZqMVptWk15enhDbVRQVHVyN2lVR2JnZ0F3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1URXdNak15TURCYUZ3MHlNekE0TVRFd01qTTNNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCTXYwR1Nzb0NmcllTeEhKMVpFaGgvZUZrZSt0ZER0d3ZVMnVlSEQyMFlBMQpzZ3RMMFFuWVZt
      M256ZlduT3dnelNYZ1QyNWovekdiM2ZoODlmdW5JcmwramdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVVGhuczgzM2VoR0RkYUMv
      NUFjajcKVTJ3dHpwc3dId1lEVlIwakJCZ3dGb0FVbzNldldLNzNtbk9kSW05bTEvc1RSalJBYVdR
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TlRnMU5tTmtaamhqTkMxNmQyUnRORENCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVBOcE11N3MxVU9KCk9RUVRXK3ZTU250
      L2ZrYy9QV3h3czlQcUJkWXhNZVV5QWlBaUhwU0toWnRiQ005ajAvdjVIS2szRlJPN2wzdXUKckJL
      M2VJc1VpUnZhMGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK
      6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVKYUZUcEYr
      RlNKNVFIbitrWjRCcDVlblBWVll3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpB
      NE1URXdNak13TWpCYUZ3MHlOVEExTXpFd01qTXdNakJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3
      RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dI
      VDNKa1pYSmxjakVYCk1CVUdBMVVFQXd3T1kyRXViM0prWlhKbGNpMXVaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUUy96OFVjamgvTlZWN3BvNWx2R2ZRTUhRWkRuYlpCNjdm
      anoyVzJKSk9pUTRWNmlmRkNPeE1BOG5mS1NmagpkZEg2Q29zbitKbk9KZDJnNWRjQTRvWm9vMEl3
      UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRF
      RmdRVW8zZXZXSzczbW5PZEltOW0xL3NUUmpSQWFXUXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUln
      RTFReTJJSlNNTVhPdFdnaVk5Tml4NDA5UWY3WEZXNlppTzhDVnl2NzA5QUNJUUR4Ni8rRwpwWCtS
      UmkyMnBCSE9rRGVONDJPZExvT3A2cmh5czQ4QTFXV0Nudz09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1T
      UBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVy
      TVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hU
      aW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxok
      CgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIR
      ErcRCghldGNkcmFmdBKqEQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzhUQ0NBcG1nQXdJQkFnSVVQNFVEMzVMSTQvR0VNdHF3d2Ro
      QWJJUUhKTnN3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21W
      eU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1URXdNak15TURC
      YUZ3MHlNekE0TVRFd01qTTNNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJ
      MU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05W
      CkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYw
      TUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVY4Y3dYa0Z6TWhlb1VyWG80dytk
      cnE0UnVXek5KU1hPTkEwZwp4eXpUNjEvcGRvRmJ5MmVKN1RFNzRSOTFkMngwcWw2SnluRUhHeUJS
      OTRxbmQ3ZEFGcU9DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFV
      QmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRF
      RmdRVTR1Rkk5eFg4Q1ZkclhIc1pwOWNMVzd5RTNVb3dId1lEVlIwagpCQmd3Rm9BVW8zZXZXSzcz
      bW5PZEltOW0xL3NUUmpSQWFXUXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEps
      Y2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcK
      QndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXli
      MnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJ
      am9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05HQURCREFoOUJCc29WeTdlNk5Hd0hl
      WHlJSzExZXRQaE5pc2dBSG8yYXVKaWEKSGJNYkFpQkdzSzBKR1QrWmNjMUVYeEd4aEpISTdDR0ZX
      elBwa21rSExVekE3YVQ3dHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOFRDQ0FwbWdBd0lCQWdJVVA0VUQzNUxJNC9HRU10cXd3
      ZGhBYklRSEpOc3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxj
      bVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRFd01qTXlN
      REJhRncweU16QTRNVEV3TWpNM01EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhF
      eEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0Jn
      TlYKQkFzVEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJt
      VjBNRmt3RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVjhjd1hrRnpNaGVvVXJYbzR3
      K2RycTRSdVd6TkpTWE9OQTBnCnh5elQ2MS9wZG9GYnkyZUo3VEU3NFI5MWQyeDBxbDZKeW5FSEd5
      QlI5NHFuZDdkQUZxT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZq
      QVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhR
      NEVGZ1FVNHVGSTl4WDhDVmRyWEhzWnA5Y0xXN3lFM1Vvd0h3WURWUjBqCkJCZ3dGb0FVbzNldldL
      NzNtbk9kSW05bTEvc1RSalJBYVdRd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pY
      SmxjaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFV
      RwpCd2dCQkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1
      eWIyeHNiV1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhC
      bElqb2liM0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkdBREJEQWg5QkJzb1Z5N2U2Tkd3
      SGVYeUlLMTFldFBoTmlzZ0FIbzJhdUppYQpIYk1iQWlCR3NLMEpHVCtaY2MxRVh4R3hoSkhJN0NH
      Rld6UHBrbWtITFV6QTdhVDd0dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1z
      EAoYASAFKICAgAgaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIi
      CgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5z
      KgZBZG1pbnMS8y4KC0NvbnNvcnRpdW1zEuMuEpguChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1
      bRL5LRLMFgoLYXVkaXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVFdHRvdGZRdENC
      QXJiSkUvbkh6Q056eDBjYkF3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RB
      aEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1E
      Z3hNVEF5TXpFek5Wb1hEVEkxTURVek1UQXlNekV6TlZvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVPdDg0ZU5wYi95YVBUbjQ5WkFoM2thQlR4TzQ1cmFR
      akdiNnMrbnVOQnVKVVh1RTNtK3hieXR5VgpFeGc4aFJzYVJ4aDdISVZkVko5VWRsbTh1Nm1TUHFO
      Q01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIw
      T0JCWUVGQlVaZVV5L1kwM05ldXQvR2FxSnJVTkxJKy9VTUFvR0NDcUcKU000OUJBTUNBMGdBTUVV
      Q0lGcUlaSnNobm4yUGFEUzRFRmdHZlFnaGtYR3pUSG9UOUxDdnMvSjhsemxmQWlFQQp2R0ZZYTZi
      dlZYUHc4NFNCVHBHYlAzK2J3N3JYQ0wvZVVpckJoMVR1L2JBPQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tCiK+CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJ
      VVZGZGdNWk5ZbmdBMWJ6dkVBcTBHZDVRY3FQVXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFV
      RUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJF
      d0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYw
      TUI0WApEVEl5TURneE1UQXlNelF3TUZvWERUSXpNRGd4TVRBeU16a3dNRm93ZWpFTE1Ba0dBMVVF
      QmhNQ1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFL
      RXdoQmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5
      TVRFYk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBD
      QVFZSUtvWkl6ajBEQVFjRFFnQUVnYjZOaElhVTJabmRDbjFBCkZsUjFFNTEzMmNDcFNzamw3R0Nm
      QjQ4cUVSd3NBd2FIQTRiVnRub1BneG1oS0lyQlRGYXZCZ2lodG9CYWU1M0kKbWN2YlhhT0NBUm93
      Z2dFV01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FX
      QkJSTlRWbDBYT0dvcHRsVlVDcW5FOURIalNMRkp6QWZCZ05WSFNNRUdEQVdnQlFWR1hsTXYyTk56
      WHJyCmZ4bXFpYTFEU3lQdjFEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzT1dNME4yWTJZ
      MlE0TFdKNGQzRjYKTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBi
      bWwwSWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJ
      am9pWVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBk
      Rzl5TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURT
      QUF3UlFJaEFJT0xwNVFiTmpqT1ZueWc3RlNrOEFNcGFtZ0ZieWNLeFhZVwpRU3E0T3VqdkFpQXpk
      NDZFYUQ5N1F5bmU3UnNFZE5paDhZdjJHSVg2LytpY1BLU2FNWTNCMUE9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVFdHRvdGZRdENCQXJiSkUvbkh6Q056eDBjYkF3Q2dZSUtv
      Wkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hNVEF5TXpFek5Wb1hEVEkxTURVek1U
      QXlNekV6TlZvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFn
      QUVPdDg0ZU5wYi95YVBUbjQ5WkFoM2thQlR4TzQ1cmFRakdiNnMrbnVOQnVKVVh1RTNtK3hieXR5
      VgpFeGc4aFJzYVJ4aDdISVZkVko5VWRsbTh1Nm1TUHFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdF
      Qi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQlVaZVV5L1kwM05ldXQvR2Fx
      SnJVTkxJKy9VTUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lGcUlaSnNobm4yUGFEUzRFRmdHZlFn
      aGtYR3pUSG9UOUxDdnMvSjhsemxmQWlFQQp2R0ZZYTZidlZYUHc4NFNCVHBHYlAzK2J3N3JYQ0wv
      ZVVpckJoMVR1L2JBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1dyaXRl
      cnMSKRIfCAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjUKBkFkbWlucxIr
      EiEIARIdEggSBggBEgIIABoREg8KC2F1ZGl0b3IxTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVu
      dBIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMqBkFkbWlucxLMFgoLYXVk
      aXRvcjJNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVOWTR5eU4zaGFMdzUrY0tBUlZwV3Az
      WG4zajR3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1q
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hNVEF5TXpJMU1W
      b1hEVEkxTURVek1UQXlNekkxTVZvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1q
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUVWcDZUeEV1d3VxQUYvakloUEFVWVhLYVlJTFJqWStMYS9WbGhFVWlHZTFw
      SUVKY09wOXR2TzQ2UwpiZ1l4TlNoZmFCbTVyREp3TGJjOUE3QVRiMUFHdjZOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGT1pvMmtK
      dTlxTW9lK1ZCTDRidTFzN3hrZ08zTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lDQUZ3UGl4RGEv
      WjF3QURQQmJBZVF0QkRXUDBielAxVHVnNlFlUTQ2bUVxQWlBKwpmbWpuZkF5NHBRc2FqTmo1Yjgw
      RTB4SUlQb3dMNmFOQ2JnMUhTNWRmdlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOVRDQ0FwdWdBd0lCQWdJVURuN3N5bzRXTzFp
      ODNjUXpabVJkOUFZSG8wb3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURn
      eE1UQXlNemN3TUZvWERUSXpNRGd4TVRBeU5ESXdNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFa
      CkJnTlZCQWNURWpVeExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2
      Y2pJeEh6QU0KQmdOVkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05W
      QkFNTUVrRmtiV2x1UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5
      QXdFSEEwSUFCQjN1MEtWMWlhdFFqdWk1CjBvK3BGZkFRMUNiemhrT2psUlpEbnBwOStOdEx1TnI2
      UUlNQklBandraEJPbHpZTHN3SmpSME9NaUVyZ0xnUTIKZS9iWEUwR2pnZ0VhTUlJQkZqQU9CZ05W
      SFE4QkFmOEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVWFISjAvN0Zu
      WmlDTEl5L0FOampKVk0xOTlzd3dId1lEVlIwakJCZ3dGb0FVNW1qYVFtNzJveWg3CjVVRXZodTdX
      enZHU0E3Y3dKQVlEVlIwUkJCMHdHNElaWTJFdGRHOXZiSE10TlRrM1pEVmpZelE1TkMxcWFEVncK
      ZHpDQmp3WUlLZ01FQlFZSENBRUVnWUo3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlk
      V1VpTENKaApaRzFwYmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1GMVpHbDBi
      M0l5SWl3aWFHWXVSVzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlYVmthWFJ2Y2pJdGJtVjBJ
      aXdpYUdZdVZIbHdaU0k2SW1Ga2JXbHUKSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ3pM
      K2dBN3QxNWxxR2V0UFRtU1VETFg4MTlrcVh0WTRlSQpJdllKV0xWS0JBSWdYaU9OMTVBWmRRem1i
      UE1LYUszWjZiMUtDeGpqRmRGSGk1WDZ5Y1ovMWFNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      CkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQit6Q0NB
      YUtnQXdJQkFnSVVOWTR5eU4zaGFMdzUrY0tBUlZwV3AzWG4zajR3Q2dZSUtvWkl6ajBFQXdJdwpY
      REVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hNVEF5TXpJMU1Wb1hEVEkxTURVek1UQXlNekkxTVZvd1hE
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVWcDZUeEV1d3Vx
      QUYvakloUEFVWVhLYVlJTFJqWStMYS9WbGhFVWlHZTFwSUVKY09wOXR2TzQ2UwpiZ1l4TlNoZmFC
      bTVyREp3TGJjOUE3QVRiMUFHdjZOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhR
      OEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGT1pvMmtKdTlxTW9lK1ZCTDRidTFzN3hrZ08zTUFv
      R0NDcUcKU000OUJBTUNBMGNBTUVRQ0lDQUZ3UGl4RGEvWjF3QURQQmJBZVF0QkRXUDBielAxVHVn
      NlFlUTQ2bUVxQWlBKwpmbWpuZkF5NHBRc2FqTmo1YjgwRTB4SUlQb3dMNmFOQ2JnMUhTNWRmdlE9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggS
      BggBEgIIABoREg8KC2F1ZGl0b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIb
      EggSBggBEgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggS
      BggBEgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Q
      b2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0Fk
      bWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNI
      QTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1p
      bnMaSgoQT3JkZXJlckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFk
      bWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
