apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaILqrU+tu/lE5IAPZdve+x8tDZFAf/FZSvU6bomvCXrsyEtpcCtdcCtRcCngKWggBEAEaBgjQ
      nL+XBiIKc3lzY2hhbm5lbCpAZjdiYmZjZmRjOGU4MzhhZThmNmU4ZTViMGU1ZDQwMTZiMWQyOTlh
      MjM3ZWFkMmM0ZDVlNjc1YWJiMTk3ZjBhYhIaEhhuH0H4MweI0ZAB05j5rSDSi7iKokORc0US11sK
      1FsS0VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lC
      QWdJVVZmNUliRFB4WkhnejBSdUxFaWZZNkdlMkIzZ3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURjeE5ESTNNakphRncweU5UQTFNamN4TkRJM01qSmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVQzUTR5SlVRaHo4aFRTK0NqR2N6WXFz
      WGgwLzZTU2o5VmlVNjNML1RTcFllYWppVC9UTytacWE1U2c2NkdICmlKc0J3cHZvckJTbk90eXBK
      VjZhMTV6Sm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVeGxiUk1qYzVsSGpjME9TL29Uenp3MitqVUZJd0NnWUlLb1pJemowRQpB
      d0lEU1FBd1JnSWhBSlpZN1VlbmJ5d0RsaDdJMXRhV0dTN3p0NXhNUldHZzl3a1hBTWhZLzYwTUFp
      RUFzOVNyCnVPRnpkaDZOYitLZjA0ay9Dc0xBSSthTytKTUJmaHRHK29GVVV1Yz0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFUQ0NB
      bnlnQXdJQkFnSVVWUXhZQUFUV3NBV29UWEhtY1YvWVBpZEJNejB3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1EY3hOREk1TURCYUZ3MHlNekE0TURjeE5ETTBNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCSk9nWDVvS1REWnZFeVBmU05sVGFGQ2h1YXlEYkthWHZrR1NoOVUzQW1iWgpyMS80VkIzMENx
      Tk5JcUl0enRlRW9uZ0J5d0l4N1pwOWdtUXFhcmRpT0FXamdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVMHozbkZmOWtZOFJ1c0sz
      YkRSMGwKWnlEUW55a3dId1lEVlIwakJCZ3dGb0FVeGxiUk1qYzVsSGpjME9TL29Uenp3MitqVUZJ
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TnprNU5EWmlPVFUxWWkwMk5UVmpkekNCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVERKSmdpb09PZW1ZClZqQjVYWTJXdWsv
      TzRPZVNWelFDMFViQVMyR0UrdVFDSURVaTF5WElNQTFWVFcyV3pRWDhIcmcyOTk5N0dPZHQKTDZZ
      R1FCaUwzbC9mCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lCQWdJVVZmNUliRFB4Wkhn
      ejBSdUxFaWZZNkdlMkIzZ3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURj
      eE5ESTNNakphRncweU5UQTFNamN4TkRJM01qSmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVQzUTR5SlVRaHo4aFRTK0NqR2N6WXFzWGgwLzZTU2o5VmlVNjNM
      L1RTcFllYWppVC9UTytacWE1U2c2NkdICmlKc0J3cHZvckJTbk90eXBKVjZhMTV6Sm8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      eGxiUk1qYzVsSGpjME9TL29Uenp3MitqVUZJd0NnWUlLb1pJemowRQpBd0lEU1FBd1JnSWhBSlpZ
      N1VlbmJ5d0RsaDdJMXRhV0dTN3p0NXhNUldHZzl3a1hBTWhZLzYwTUFpRUFzOVNyCnVPRnpkaDZO
      YitLZjA0ay9Dc0xBSSthTytKTUJmaHRHK29GVVV1Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJN
      U1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1TUBABGgZBZG1pbnMq
      BkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9yZGVyZXIx
      Lm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBt
      Z0F3SUJBZ0lVUG1kZmVYZ25jMUpFLzRCakErd3Z6MjVHU2ZRd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5
      TFc1bGREQWVGdzB5Ck1qQTRNRGN4TkRJNU1EQmFGdzB5TXpBNE1EY3hORE0wTURCYU1HMHhDekFK
      QmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFP
      QmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1U
      Rkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVxb1hoaVhZUURUYzcvVzlMRnBzdGE0NDc2QkNBbmlkcnVScDkKS0JIbDNXYmhLcWdn
      Z1NmQVJ1dGVOTnVNYitFMFJkOVdSekFNclNxNFE3VFFEeXdyb0tPQ0FTZ3dnZ0VrTUE0RwpBMVVk
      RHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdE
      QVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV0WDU3ZStGODR2SDNpY2Y0NGYyMjVQRXFo
      bW93SHdZRFZSMGoKQkJnd0ZvQVV4bGJSTWpjNWxIamMwT1Mvb1R6encyK2pVRkl3T3dZRFZSMFJC
      RFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNi
      M0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1a
      bWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXVi
      M0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9Q
      UVFEQWdOSEFEQkVBaUJQZG1FaEZKSFhxamR5TzFiWGkxMXIyeG5rMjBSSzM3T0RzSWVqCmJJS0JF
      QUlnWUoxeEwxRHdobkczWFc1b0V5STZwQ0dKcXUvM3NpRmMxbVQxUExGS1pOUT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzhqQ0NB
      cG1nQXdJQkFnSVVQbWRmZVhnbmMxSkUvNEJqQSt3dnoyNUdTZlF3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1EY3hOREk1TURCYUZ3MHlNekE0TURjeE5ETTBNREJhTUcweEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJB
      TVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpq
      MERBUWNEUWdBRXFvWGhpWFlRRFRjNy9XOUxGcHN0YTQ0NzZCQ0FuaWRydVJwOQpLQkhsM1diaEtx
      Z2dnU2ZBUnV0ZU5OdU1iK0UwUmQ5V1J6QU1yU3E0UTdUUUR5d3JvS09DQVNnd2dnRWtNQTRHCkEx
      VWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJ
      d0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVXRYNTdlK0Y4NHZIM2ljZjQ0ZjIyNVBF
      cWhtb3dId1lEVlIwagpCQmd3Rm9BVXhsYlJNamM1bEhqYzBPUy9vVHp6dzIralVGSXdPd1lEVlIw
      UkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1W
      c2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pF
      dWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtq
      T1BRUURBZ05IQURCRUFpQlBkbUVoRkpIWHFqZHlPMWJYaTExcjJ4bmsyMFJLMzdPRHNJZWoKYklL
      QkVBSWdZSjF4TDFEd2huRzNYVzVvRXlJNnBDR0pxdS8zc2lGYzFtVDFQTEZLWk5RPQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hT
      aXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlu
      cxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLrLgoLQ29uc29ydGl1bXMS2y4SkC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvEt
      EsgWCgthdWRpdG9yMU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVVYxcVp0Q2Q5SE9RcHI1
      WE0wVHZOMTJ3eWZjVXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURnd056
      RTBNamd6T1ZvWERUSTFNRFV5TnpFME1qZ3pPVm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRWQ2M3ZtcEdsSkU2TzBNd0FYenh5Y1JBcGpWK1o5TXlRTzho
      Tk5uNDFrNi9XWHh1RkErdG1md1poCmZhcW8zek5nRWlJVWlzOFJLYjBPdzNuWlNnak1aYU5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZCSmJiZUFjTnpoSXZhMlJNdmcwRDJtQ0NOUEFNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFD
      cWlDUXcxZHlVZyt3eUxMSHBPWUV0MDk4ZkhhbEphbmg1RjlrcW1hWUtNZ0loCkFOTFVpL3pGSkR6
      eCtMRjlWVzFXRzNSeGJETnBpQmpzcktBTXlzbW40d3VCCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBtZ0F3SUJBZ0lVTEtu
      d1BLK3ArQXhPQWhIQ0p1TmxxZnVac29rd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd3TnpFME16QXdNRm9YRFRJek1EZ3dOekUwTXpVd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRVJtSTRyekJlRU5XMm92bGUKZEVRdWtROTcwUGtaWXdCc1MwaTFBb1BY
      cFpEMFdZUS92blhuQWxsK1U2QTlUb0FmaGRCUjBNSWdWL09UT1hvRwpRRUF2ZEtPQ0FSa3dnZ0VW
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlRE
      TmZyL293UjZ2bTRrTktuNFg4TVZ4TlllYXpBZkJnTlZIU01FR0RBV2dCUVNXMjNnSERjNFNMMnQK
      a1RMNE5BOXBnZ2pUd0RBakJnTlZIUkVFSERBYWdoaGpZUzEwYjI5c2N5MWlPR1ppWkdZM1kyUXRi
      RGw0YkhZdwpnWThHQ0NvREJBVUdCd2dCQklHQ2V5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlP
      aUowY25WbElpd2lZV1J0CmFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmhk
      V1JwZEc5eU1TSXNJbWhtTGtWdWNtOXMKYkcxbGJuUkpSQ0k2SWtGa2JXbHVRR0YxWkdsMGIzSXhM
      VzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOQpmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVB
      aUJLQXRjSVZHV0RBSDVudWg3aEIwcmVIZ01zV2crME1BRmt3ZXI1CnV6aFllUUlnY21rbTRTWHpT
      enRtQjBmTk51UFROM1U5aW9URVVHcGRpNmdISTFGaDZnYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      VENDQWFLZ0F3SUJBZ0lVVjFxWnRDZDlIT1FwcjVYTTBUdk4xMnd5ZmNVd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd3TnpFME1qZ3pPVm9YRFRJMU1EVXlOekUwTWpnek9W
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFZDYzdm1w
      R2xKRTZPME13QVh6eHljUkFwalYrWjlNeVFPOGhOTm40MWs2L1dYeHVGQSt0bWZ3WmgKZmFxbzN6
      TmdFaUlVaXM4UktiME93M25aU2dqTVphTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkJKYmJlQWNOemhJdmEyUk12ZzBEMm1DQ05Q
      QU1Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUUNxaUNRdzFkeVVnK3d5TExIcE9ZRXQwOThmSGFs
      SmFuaDVGOWtxbWFZS01nSWgKQU5MVWkvekZKRHp4K0xGOVZXMVdHM1J4YkROcGlCanNyS0FNeXNt
      bjR3dUIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAES
      HRIIEgYIARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIf
      CAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAES
      GxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMSyBYKC2F1ZGl0b3IyTVNQ
      ErgWGtAUCgNNU1ASyBQSvRQSuhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJBZ0lVTE8xbFBoUmZKQXpDUEdKdkQxNGkrc1pQeUdnd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3TnpFME1qazFOVm9YRFRJMU1E
      VXlOekUwTWprMU5Wb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFZk5BRm5NbjhjWWRhZlpLUW9ZclBMOGxuZURXNmNhVzJNMjZBRXNhSHB3R09Nc05SN0xU
      Zi9WQ1oKaGMyTUNUWWFFVzZtbzJtdWNVSDhEWGI2WDVFMHU2TkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRk5DaHU4MjlwTnJGU3Fq
      MVkweHZSL0pZQ1lzWk1Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJRDZxalJ0VzdGYUFKTkxmbVlZ
      czlvUW10cmN5L0d5bWo1Si9lU2liakxBTkFpRUEKcHhhZFFJK0FDYjJkZDg5Yk4xbzV4a25kZUlV
      SnN5cTNTYTNJTXhwazlrQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NBcHFnQXdJQkFnSVVlRlR3OElmNXg2TndHUE91ZzJI
      M2pkYWx2Wm93Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3dOekUwTXpJ
      d01Gb1hEVEl6TURnd056RTBNemN3TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      QkVjRFpndUZaeURiU2tyaQp1ME95WGtmbnBtZnpHL0NVTXhWWTljQWxOKzVPUG0yeldlSjVEREhW
      V0JVRThUVzBSelhrT2o0SmcvQlgzN29UCmYrY3lRRUdqZ2dFWk1JSUJGVEFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVU3bTRramxla0dPU2xBSWlo
      Yml5WS9ZdEk0VXN3SHdZRFZSMGpCQmd3Rm9BVTBLRzd6YjJrMnNWSwpxUFZqVEc5SDhsZ0ppeGt3
      SXdZRFZSMFJCQnd3R29JWVkyRXRkRzl2YkhNdFpHWmlZMk0wWXpRMExYcDNOREo2Ck1JR1BCZ2dx
      QXdRRkJnY0lBUVNCZ25zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmsK
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVlYVmthWFJ2Y2pJaUxDSm9a
      aTVGYm5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQmhkV1JwZEc5eU1pMXVaWFFpTENKb1ppNVVl
      WEJsSWpvaVlXUnRhVzRpCmZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdKUmZrZHBST2ZQa0JF
      SXlHdmo1SWRHQVoyczJWWWJQNmE5THYKTGxqbmYvWUNJR1BkNjVwRGlDWVVDbFB6VUc0TzB5aUEy
      ZisrbGV0cWFlOFI0T2RKWjJiMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZT
      SEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVM
      TzFsUGhSZkpBekNQR0p2RDE0aStzWlB5R2d3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdE
      d1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1C
      NFgKRFRJeU1EZ3dOekUwTWprMU5Wb1hEVEkxTURVeU56RTBNamsxTlZvd1hERUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1G
      a3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVmTkFGbk1uOGNZZGFmWktRb1lyUEw4
      bG5lRFc2Y2FXMk0yNkFFc2FIcHdHT01zTlI3TFRmL1ZDWgpoYzJNQ1RZYUVXNm1vMm11Y1VIOERY
      YjZYNUUwdTZOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0Fh
      WXdIUVlEVlIwT0JCWUVGTkNodTgyOXBOckZTcWoxWTB4dlIvSllDWXNaTUFvR0NDcUcKU000OUJB
      TUNBMGdBTUVVQ0lENnFqUnRXN0ZhQUpOTGZtWVlzOW9RbXRyY3kvR3ltajVKL2VTaWJqTEFOQWlF
      QQpweGFkUUkrQUNiMmRkODliTjFvNXhrbmRlSVVKc3lxM1NhM0lNeHBrOWtBPQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoREg8K
      C2F1ZGl0b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggBEgIIABoP
      Eg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggSBggBEgIIABoPEg0K
      C2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1
      ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMS
      CAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5z
      Gi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaSgoQT3JkZXJl
      ckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoA
      CgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
