apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: devorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaICmhNaXet2atlVY475W+I44gYNsloj8HMpTtQUrWu/TBEt5cCttcCthcCngKWggBEAEaBgiO
      krqXBiIKc3lzY2hhbm5lbCpANzYxZmE5NjJiODg0NTRkN2ZkMjkwOTE2NGVmNDY0MTkyNDMzZDdl
      YTUxNjQ3NzNmMDhjYjA0MmExNjA3YmIwZhIaEhjB3M5A9RnObPaccAnqjBYjMtqwbaoOFkAS21sK
      2FsS1VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVVdWSTFIRVpab281dm5ocG1rV051Nk9Tdld3RXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURZeE1UQTRNamRhRncweU5UQTFNall4TVRBNE1qZGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJQRkFlQXp0Zzg4T0x3aUdSb3Bodmdr
      TG5nNC9rQkZSdjhsVmsvOXlSaTZ2Q2JDNlNWc1RHeTN0U1dzWkcrCm5pNHQ0b0RvaGJMQTl1cy9C
      RUNqN3ZObW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVbGpuaXJoZkpwZTl1Z1VNYm5KOU5sYVJiSFRZd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdJMFJsb0UzbVY5dmd0UTUxSnFwZGVuSERkUzEydnJ6NGJGa2tXZDBoSFcwQ0lR
      QzlrN0F4ClJNSnZmRyttNjdzM2J3NGdwQlltVkdCQm14ZjhqZ0NMZ1VpQzdBPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFEQ0NB
      bnVnQXdJQkFnSVVSTkg3SkMvMFRSTnJOcUZoeWpqSTJiOGNzWW93Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1EWXhNVEV4TURCYUZ3MHlNekE0TURZeE1URTJNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCSkJxRXJlU0tFWFhIYUlVYzgxRURuK1N5Qkkvdm1mdkU4NW5jVnNnU1NaOApPdnA0QlBENVNQ
      a2dSYzhOZUNUMzE0WU1ZN210RFVtYUlsOFltY2kzRktxamdnRVBNSUlCQ3pBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVRGpwcnMrSTNMZGlkcDE2
      dEc4cHUKSCtEb092NHdId1lEVlIwakJCZ3dGb0FVbGpuaXJoZkpwZTl1Z1VNYm5KOU5sYVJiSFRZ
      d0l3WURWUjBSQkJ3dwpHb0lZWTJFdGRHOXZiSE10TlRsbU9EVTNZMlkwTFhKcU1uaHdNSUdGQmdn
      cUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJcwpJbWhtTGxSNWNHVWlPaUpoWkcx
      cGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFTOW9RK2JWdkhmSmpTCnZKd0Q1Ny9xaE9l
      ZHF2T0d1YkhTV2VqTTRkaEFlUUlnTkkwcGR3WEptU09aS2hZWVFtTzRKTmJiWVZKZ1FYcUgKa01H
      SUtEb2dwU289Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVdWSTFIRVpab281
      dm5ocG1rV051Nk9Tdld3RXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURZ
      eE1UQTRNamRhRncweU5UQTFNall4TVRBNE1qZGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVJQRkFlQXp0Zzg4T0x3aUdSb3BodmdrTG5nNC9rQkZSdjhsVmsv
      OXlSaTZ2Q2JDNlNWc1RHeTN0U1dzWkcrCm5pNHQ0b0RvaGJMQTl1cy9CRUNqN3ZObW8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      bGpuaXJoZkpwZTl1Z1VNYm5KOU5sYVJiSFRZd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdJMFJs
      b0UzbVY5dmd0UTUxSnFwZGVuSERkUzEydnJ6NGJGa2tXZDBoSFcwQ0lRQzlrN0F4ClJNSnZmRytt
      NjdzM2J3NGdwQlltVkdCQm14ZjhqZ0NMZ1VpQzdBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRlcmVyTVNQEAEa
      BkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVv
      dXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENh
      cGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa1BEKDUNvbnNlbnN1c1R5cGUSwhEStxEK
      CGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVyLW5ldBCKNxq6CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVU9Gck1oY3NjWVplUkR5b1FYb2xmcVZD
      WWpvWXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJj
      d0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURZeE1URXhNREJhRncw
      eU16QTRNRFl4TVRFMk1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFz
      VEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3
      RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbVBKYjNiSXk5MG0rRkY0WERuYmUxQUw2
      WUlnYWRJeUxuQ1BRCkNMUHgzWDdzRERmU2taSlNlOHpackhPU05WS3JJVG5NQ0VWYXhNL29uak95
      U2FpYWJhT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dy
      QmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FV
      RnlUVHM4RUZGbDdxeVFxSHJVMXF1WWFCajI0d0h3WURWUjBqCkJCZ3dGb0FVbGpuaXJoZkpwZTl1
      Z1VNYm5KOU5sYVJiSFRZd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dC
      QkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2li
      M0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBdFgyOVhPQ3dnUHJvT1NadWJt
      UTc5MmFtOUw2ejFuVm02SzNWcgo0VU9DUWdJZ2JWL3A1enR3QXNWVTcwQlZTWjYvZW1uV1FObjdO
      WHpGcnpSMXFJZEQ4bms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBtZ0F3SUJBZ0lVT0ZyTWhjc2NZWmVSRHlvUVhvbGZx
      VkNZam9Zd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNRFl4TVRFeE1EQmFG
      dzB5TXpBNE1EWXhNVEUyTURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFN
      UzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpC
      QXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1G
      a3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVtUEpiM2JJeTkwbStGRjRYRG5iZTFB
      TDZZSWdhZEl5TG5DUFEKQ0xQeDNYN3NERGZTa1pKU2U4elpySE9TTlZLcklUbk1DRVZheE0vb25q
      T3lTYWlhYmFPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJn
      Z3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVGeVRUczhFRkZsN3F5UXFIclUxcXVZYUJqMjR3SHdZRFZSMGoKQkJnd0ZvQVVsam5pcmhmSnBl
      OXVnVU1ibko5TmxhUmJIVFl3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNp
      MXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3
      Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpv
      aWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUF0WDI5WE9Dd2dQcm9PU1p1
      Ym1RNzkyYW05TDZ6MW5WbTZLM1ZyCjRVT0NRZ0lnYlYvcDV6dHdBc1ZVNzBCVlNaNi9lbW5XUU5u
      N05YekZyelIxcUlkRDhuaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Js
      b2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJ
      CgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLvLgoLQ29uc29ydGl1bXMS3y4SlC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvUt
      EswWCgthdWRpdG9yMk1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVWZIc1llRlRHOHJOWGpn
      b3lLMldXdWNZSk9RUXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURnd05q
      RXhNVEV3TVZvWERUSTFNRFV5TmpFeE1URXdNVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRW96UkpTUERBUXVRZFNJUzNsMmpCZ3R5ZlIvczRZbVhoRTll
      SGsxbDN1cmNIU01jZVpWbElHR0FsCmxwOU90a3JYZ0kraEcvaXBTRm5hU0FxWE9GcWlRYU5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZQNVdvbndrbGh4RXZWTG5MTXFvVVBhY2RRbGxNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFE
      eUluYkw1YXBMWWlUNU5zUENOa2UwZ1FBTllCN1hmQ05OcmxicTNWVTJVQUlnCkhrZlJ2V2xXWnRo
      U2t1VmtjZTN0OGJxNkhGd0RSZ2hITDF3R3A5SDhKaHc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIr4ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQXB1Z0F3SUJBZ0lVVmRx
      SjA4NjNDUzhoTWtMajZncko4OElkL0Vvd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRY
      CkRUSXlNRGd3TmpFeE1Ua3dNRm9YRFRJek1EZ3dOakV4TWpRd01Gb3dlekVMTUFrR0ExVUVCaE1D
      UjBJeEd6QVoKQmdOVkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1J
      UVhWa2FYUnZjakl4SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4
      R3pBWkJnTlZCQU1NRWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VH
      Q0NxR1NNNDlBd0VIQTBJQUJHSXJodHJFWFJNUGtHOWYKemkxeDlleThPWm5IYU9aNTBhdSs1MU1s
      QlFja0ZRa3lidjFtb1JuZ1J1MWs3UDB4bXI2RWZpUkZvSmtMYU9lQwp1R1BBTFgyamdnRWFNSUlC
      RmpBT0JnTlZIUThCQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FV
      MklyN1FOMXpmL2dYUDhFN2ZlQ2ppdVdaZUFVd0h3WURWUjBqQkJnd0ZvQVUvbGFpZkNTV0hFUzkK
      VXVjc3lxaFE5cHgxQ1dVd0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXROelprTkRjNE9EUTJO
      QzEwTnpoNApZakNCandZSUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBk
      Q0k2SW5SeWRXVWlMQ0poClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJ
      bUYxWkdsMGIzSXlJaXdpYUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZj
      akl0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FN
      RVVDSVFER2diZTMrWmtoNEh2YmlKOFdOS251Z3YzRlF0cGRGS3RGClEweFhyWmUxUHdJZ0ZrZ29m
      alYxbU1waGphbkhjcUczazBqcDBpMXNEYXpGeW8ycGZPSzcxMlE9Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL0RDQ0FhS2dBd0lCQWdJVWZIc1llRlRHOHJOWGpnb3lLMldXdWNZSk9RUXdDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURnd05qRXhNVEV3TVZvWERUSTFNRFV5TmpFeE1U
      RXdNVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRW96
      UkpTUERBUXVRZFNJUzNsMmpCZ3R5ZlIvczRZbVhoRTllSGsxbDN1cmNIU01jZVpWbElHR0FsCmxw
      OU90a3JYZ0kraEcvaXBTRm5hU0FxWE9GcWlRYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZQNVdvbndrbGh4RXZWTG5MTXFvVVBh
      Y2RRbGxNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFEeUluYkw1YXBMWWlUNU5zUENOa2UwZ1FB
      TllCN1hmQ05OcmxicTNWVTJVQUlnCkhrZlJ2V2xXWnRoU2t1VmtjZTN0OGJxNkhGd0RSZ2hITDF3
      R3A5SDhKaHc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNQoGQWRtaW5zEisS
      IQgBEh0SCBIGCAESAggAGhESDwoLYXVkaXRvcjJNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50
      EikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikS
      HwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyoGQWRtaW5zEsgWCgthdWRpdG9y
      MU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVU1nRytDaFdqV25JUEFlVFNJb004SHBzVUJI
      OHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURnd05qRXhNRGswTlZvWERU
      STFNRFV5TmpFeE1EazBOVm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRTcrYmZ5ZjRjS1ExSnQ2YnRKVzROZVFXVDMwWnpVT1RUcFRnOGxvZkxsVnlMWFU2
      U2gvUHNZL1BiCmhTaTJMaTVCcUo2UnpkWmxBNnhtQmc1M0R6WThjNk5DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZQZ1BjdXpFbzgy
      b2VOOWhGaEZMckVKZlpReVdNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFDZEM1aVo1TmFhWnBk
      QXRYTHVIK3ByUk1CNmJacnhRZXlNR0ZuWWF5YUZqUUloCkFJN3JBSUlFd01MQmlnZWUwSG5paUNP
      aXVwUU9FS3lCZ2ROUGQyOHkreFAxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBxZ0F3SUJBZ0lVRGpFR21XRFhBZWZDNlRM
      bWQyNmZ6emI2NFl3d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdO
      VkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd3TmpF
      eE1UY3dNRm9YRFRJek1EZ3dOakV4TWpJd01Gb3dlakVMTUFrR0ExVUVCaE1DUTBneEdqQVkKQmdO
      VkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hCZFdScGRHOXlNVEVm
      TUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEViTUJrR0ExVUVBd3dT
      UVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNE
      UWdBRStyT3JMbU9ITWxtdjRNaGYKZVpSc0g3ZWhrRk5HdmxNRUZjV1VlNU5lSnpJZE1iNW5PTENw
      VGJYVzh4YzJBd3pUSGFsSjVTVVlLVUh3cVBkKworOXJQanFPQ0FSb3dnZ0VXTUE0R0ExVWREd0VC
      L3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlRiRjNoUDFkOVBxMXkv
      NmhBdXFVN2JkNVFhckRBZkJnTlZIU01FR0RBV2dCVDREM0xzeEtQTnFIamYKWVJZUlM2eENYMlVN
      bGpBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDJPR1ptTnpZMVpqazJMWGhpYzJ3MgpNSUdQ
      QmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJ
      bUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZWFZrYVhSdmNqRWlM
      Q0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlNUzF1WlhRaUxDSm9a
      aTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVzNpMnprQmZv
      VWw5UnRzQzc0aE5EbCtGWEVCRk8zQjNZV0lnCjgrMEV0UHNDSUF0d1p5Y2JBaTBNdkZRZmx3b3BU
      VHJNRVAvMTY4ams4L0NoalcwV3lMaGQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvVENDQWFLZ0F3SUJB
      Z0lVTWdHK0NoV2pXbklQQWVUU0lvTThIcHNVQkg4d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJt
      VjBNQjRYCkRUSXlNRGd3TmpFeE1EazBOVm9YRFRJMU1EVXlOakV4TURrME5Wb3dYREVMTUFrR0Ex
      VUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFNytiZnlmNGNLUTFKdDZidEpX
      NE5lUVdUMzBaelVPVFRwVGc4bG9mTGxWeUxYVTZTaC9Qc1kvUGIKaFNpMkxpNUJxSjZSemRabEE2
      eG1CZzUzRHpZOGM2TkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRlBnUGN1ekVvODJvZU45aEZoRkxyRUpmWlF5V01Bb0dDQ3FHClNN
      NDlCQU1DQTBrQU1FWUNJUUNkQzVpWjVOYWFacGRBdFhMdUgrcHJSTUI2YlpyeFFleU1HRm5ZYXlh
      RmpRSWgKQUk3ckFJSUV3TUxCaWdlZTBIbmlpQ09pdXBRT0VLeUJnZE5QZDI4eSt4UDEKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggAGg8S
      DQoLYXVkaXRvcjFNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAaERIPCgth
      dWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1p
      bnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhh
      c2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaSgoQT3JkZXJlckFkZHJlc3NlcxI2EhsK
      GW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
