apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIDWUIlHfUuvuCMyuyOzDgjf50KBZ72tv//JPTH+y+6VeEt5cCttcCthcCngKWggBEAEaBgiq
      7/uXBiIKc3lzY2hhbm5lbCpAOThiMmIwZTY2MGQ5NzJmOTc2ZjAwMDkzYzVmZmExMGZlZWQ0OTI0
      YTM0MTdjN2QyOTY3OTg2ODk1MjU4NWFkYxIaEhiyCqLQhl7g6UtAthe5krxz2bPt02R4+ZQS21sK
      2FsS1VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVVloNDZDbGZjbUFXYjhjNENyMFZtejl3L0prOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRrd01qSTJNemxhRncweU5UQTJNRGd3TWpJMk16bGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRncmxaYlJEQ0tPb21DT2lCaFY0ZG9C
      bW9DK0pqaGVIcjl1cE0zMTlrMG1ZbzZUblhWUWNLQi9jZ2JjMWZTCldRekxha1Y1dFdNWVY4QXlO
      NkZRckd0U28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVbERIS2drRlFPd0MyTnB4eGZqUUxFbDhGSnNJd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWhBSXROczlNdXErelJKRWdOUGZQWnV2Y2NOM2Y5Q1NNclgxZHgrNEdvTGNhL0Fp
      QVFBQ1BSClhjKzdpU1lTc3orU0RTVEE1S3J2bmUremtuM1p2OEI5dkJkNGRnPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFEQ0NB
      bnVnQXdJQkFnSVVJUDd0Q080NU83L1pEUXJUcTMvUHQ3N0Vicll3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1Ua3dNakk0TURCYUZ3MHlNekE0TVRrd01qTXpNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCTE4zQjhVc0FxMU14VnIxLzdJeWJLZ1lsbmIwd0VJVTJwdFdkcW5OZWYxcQpPUEVNL3hBejVC
      NG92RXJzRkN2MmExSEx2ajMyeWk3VzIxM01PWmRlYXBhamdnRVBNSUlCQ3pBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVNDNEajI3ZHlJWGsrWnFC
      YkhZOXMKSkJtWWV5VXdId1lEVlIwakJCZ3dGb0FVbERIS2drRlFPd0MyTnB4eGZqUUxFbDhGSnNJ
      d0l3WURWUjBSQkJ3dwpHb0lZWTJFdGRHOXZiSE10WXpSa1lqZzNOamRpTFdoeFkzTjNNSUdGQmdn
      cUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJcwpJbWhtTGxSNWNHVWlPaUpoWkcx
      cGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFLaklBeDJLaVBqRDhzCk9BeDNiY2hsa2tB
      Vm4zRjRGZFFmek11REhZUHdPUUlnVE1HVFRNYWNhMzdISVIzSHdaZXdSQXAyUUlhRjR3aVcKSUJ5
      YjBBUzhZczQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVloNDZDbGZjbUFX
      YjhjNENyMFZtejl3L0prOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRr
      d01qSTJNemxhRncweU5UQTJNRGd3TWpJMk16bGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVRncmxaYlJEQ0tPb21DT2lCaFY0ZG9CbW9DK0pqaGVIcjl1cE0z
      MTlrMG1ZbzZUblhWUWNLQi9jZ2JjMWZTCldRekxha1Y1dFdNWVY4QXlONkZRckd0U28wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      bERIS2drRlFPd0MyTnB4eGZqUUxFbDhGSnNJd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBSXRO
      czlNdXErelJKRWdOUGZQWnV2Y2NOM2Y5Q1NNclgxZHgrNEdvTGNhL0FpQVFBQ1BSClhjKzdpU1lT
      c3orU0RTVEE1S3J2bmUremtuM1p2OEI5dkJkNGRnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJN
      U1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1TUBABGgZBZG1pbnMq
      BkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVv
      dXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENh
      cGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa1BEKDUNvbnNlbnN1c1R5cGUSwhEStxEK
      CGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVyLW5ldBCKNxq6CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJVWFTSHJvSkU4Y0lBbHZJMWw1NHdRNnJ6
      cnBEWXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJj
      d0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRrd01qSTRNREJhRncw
      eU16QTRNVGt3TWpNek1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFz
      VEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3
      RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFMDlwanUvREZ2aDBBam51QTBEMWZrYXNY
      QzFhTzJoQ1dVM1FmCmNoaWgwQytjWU11RERGRFoyTHJiZDcrM3prYzZJK29oQitlSFJKUXhTajVJ
      emhHVkdhT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dy
      QmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FV
      R0lmbnNVM0htekowcm1NT3ZMN2NlcjJ5eE9Fd0h3WURWUjBqCkJCZ3dGb0FVbERIS2drRlFPd0My
      TnB4eGZqUUxFbDhGSnNJd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dC
      QkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2li
      M0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTIvYzdhRXRuSW9FaE1Za2VS
      c3htTjRHRUh0Q2tFa042cGg4NQpjbTJKbGNvQ0lBOUNZRHFzYmJ2M0ovK1RnTzNwNmZ1R2RYQlBm
      SlBUZ0s2M05JUGUvUWhsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVYVNIcm9KRThjSUFsdkkxbDU0d1E2
      cnpycERZd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVGt3TWpJNE1EQmFG
      dzB5TXpBNE1Ua3dNak16TURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFN
      UzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpC
      QXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1G
      a3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUwOXBqdS9ERnZoMEFqbnVBMEQxZmth
      c1hDMWFPMmhDV1UzUWYKY2hpaDBDK2NZTXVEREZEWjJMcmJkNyszemtjNkkrb2hCK2VIUkpReFNq
      NUl6aEdWR2FPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJn
      Z3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVHSWZuc1UzSG16SjBybU1Pdkw3Y2VyMnl4T0V3SHdZRFZSMGoKQkJnd0ZvQVVsREhLZ2tGUU93
      QzJOcHh4ZmpRTEVsOEZKc0l3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNp
      MXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3
      Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpv
      aWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBMi9jN2FFdG5Jb0VoTVlr
      ZVJzeG1ONEdFSHRDa0VrTjZwaDg1CmNtMkpsY29DSUE5Q1lEcXNiYnYzSi8rVGdPM3A2ZnVHZFhC
      UGZKUFRnSzYzTklQZS9RaGwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Js
      b2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJ
      CgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLvLgoLQ29uc29ydGl1bXMS3y4SlC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvUt
      EsgWCgthdWRpdG9yMU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVU8vNS9mR1JpTFFnbjBo
      U2FOOUoraVhpbENnVXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE9U
      QXlNamMxTlZvWERUSTFNRFl3T0RBeU1qYzFOVm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRWJBVUMyeWQyY1ZCdGJhQlNtRER2S3QrcGNFVnZrYlJYQ3BM
      OTVjS3dWRmJac1haSUUzWmFiaHg3CjcyejhEYnFHa083OWF5ODBOOEFiUWdlVVVwcmdwS05DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZEVnVzQ2wyelBEdVREclpJWHVaZXRWTXJiajlNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFE
      aWJLdXVibDM5d1FlTW9yc1hXQmR4MmZMdCtSNitiSGNDam4vYnJGT01kQUloCkFPdzAwMmhGVVgv
      ZXFBZ0NTdVQ3YUM4emZWdUE1SkpFYnZ5THM3dGhSV0R1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBxZ0F3SUJBZ0lVY01u
      TTlGM1VoK1p5Y0tiYlliY1RvaVdkbFE4d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd4T1RBeU16RXdNRm9YRFRJek1EZ3hPVEF5TXpZd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRXFhS3FaOTBnYXBNSktvVDgKeVhsTCtCRjRhemZUVWZhK3RHOXhEUzFs
      eTdYRVloazdPKy85OXZmZi95V1Q0aS8rbDN4cmhkR1V2a2tJRHdpaQpTZDY5MktPQ0FSb3dnZ0VX
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlRH
      ZlNabXJheDl5VEhLQ3dpV1BsWUFON3YyZ3pBZkJnTlZIU01FR0RBV2dCUTFickFwZHN6dzdrdzYK
      MlNGN21YclZUSzI0L1RBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDFOVGRtWW1ZM1lqWTJM
      V0kyZURRMQpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqRWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      UzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdS
      QUlnYlNScjB6OUIveVVObWRSNHJ4dGRmUkt4WGwxdnF2MEZlMUVvCklSVGJ1NXNDSUVGcng0ZHBC
      ZXhGb3F2U29FckxsT0VjdlFvbERJMFNqU05oTmlXRlRhR3QKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      VENDQWFLZ0F3SUJBZ0lVTy81L2ZHUmlMUWduMGhTYU45SitpWGlsQ2dVd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd4T1RBeU1qYzFOVm9YRFRJMU1EWXdPREF5TWpjMU5W
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFYkFVQzJ5
      ZDJjVkJ0YmFCU21ERHZLdCtwY0VWdmtiUlhDcEw5NWNLd1ZGYlpzWFpJRTNaYWJoeDcKNzJ6OERi
      cUdrTzc5YXk4ME44QWJRZ2VVVXByZ3BLTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkRWdXNDbDJ6UER1VERyWklYdVpldFZNcmJq
      OU1Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUURpYkt1dWJsMzl3UWVNb3JzWFdCZHgyZkx0K1I2
      K2JIY0Nqbi9ickZPTWRBSWgKQU93MDAyaEZVWC9lcUFnQ1N1VDdhQzh6ZlZ1QTVKSkVidnlMczd0
      aFJXRHUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8I
      ARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIb
      EggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIG
      CAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJBZ0lVSXEvSGNoN05MOTU0M2tJTGY2ak5TNDgyNjZzd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4T1RBeU1qa3hNbG9YRFRJMU1E
      WXdPREF5TWpreE1sb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFdnIvWEg2dzlnMkpuQU5kb3RFQnRPVXRSYzhTaUJCR3V1UmdnSGZWc09IRnBDV1JhelY4
      RER6ZjYKekx2UGZXb0RuTWtDUHNla2R6YzljWTkvYVArNE42TkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkF0MEcvVTdhOWl4dEEw
      dHMxRjhuVitkSDVmYU1Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNJR1RYRjlyUUdQL0h3QjVpOHBM
      WnIydWZoSGREaGNDY2JhZXlHcUwrR1RzTUFpQWUKNDlYa0N3dFFsY2ZvbEZEb2F2aHRxZitMbVdk
      NDNJbUFYc1p5MFVvNjBnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHVnQXdJQkFnSVVXUkVJRUlTdDNhMzVpZjVHaWJ5
      WVo5emtQYlV3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hPVEF5TXpN
      d01Gb1hEVEl6TURneE9UQXlNemd3TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      QkFoNlNqbGR4SWphNjRiQwp5VXhpM2NiUzREL0pVaTJpZml4U3pMb1F0VEtjbkJHQ3ZRN2pGU3Z4
      WGxWanpLdnMwWWIwR3E0ekYzY2dzanI1Ck44bU13cW1qZ2dFYU1JSUJGakFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVV3OTRiTCtBQlFjV1BITWtm
      aHVONkpFN2R6UVV3SHdZRFZSMGpCQmd3Rm9BVUMzUWI5VHRyMkxHMApEUzJ6VVh5ZFg1MGZsOW93
      SkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE56ZGlZelUwT1dRNE5DMXlaR1IwCmVqQ0Jqd1lJ
      S2dNRUJRWUhDQUVFZ1lKN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmgK
      WkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNkltRjFaR2wwYjNJeUlpd2lh
      R1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFXNUFZWFZrYVhSdmNqSXRibVYwSWl3aWFHWXVW
      SGx3WlNJNkltRmtiV2x1CkluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJRFhrSENkakVnWDNi
      WkZENUlrWnpWNXI4Y0REcXRzQXNaSWQKeTNSWU9MK01BaUJ6dkQvZFJhdDQxbnRDSVNPellobTZq
      N0J6V0VZWEFDd21qVWtPdEpRcHhBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJB
      Z0lVSXEvSGNoN05MOTU0M2tJTGY2ak5TNDgyNjZzd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd4T1RBeU1qa3hNbG9YRFRJMU1EWXdPREF5TWpreE1sb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFdnIvWEg2dzlnMkpuQU5kb3RF
      QnRPVXRSYzhTaUJCR3V1UmdnSGZWc09IRnBDV1JhelY4RER6ZjYKekx2UGZXb0RuTWtDUHNla2R6
      YzljWTkvYVArNE42TkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRkF0MEcvVTdhOWl4dEEwdHMxRjhuVitkSDVmYU1Bb0dDQ3FHClNN
      NDlCQU1DQTBjQU1FUUNJR1RYRjlyUUdQL0h3QjVpOHBMWnIydWZoSGREaGNDY2JhZXlHcUwrR1Rz
      TUFpQWUKNDlYa0N3dFFsY2ZvbEZEb2F2aHRxZitMbVdkNDNJbUFYc1p5MFVvNjBnPT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggAGg8S
      DQoLYXVkaXRvcjJNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAaERIPCgth
      dWRpdG9yMk1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
