apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIPg+lYeVRIKS8oLmg07IfsRUxduD7u/x+hYmTo/4OQkaEtpcCtdcCtRcCngKWggBEAEaBgjj
      z/mXBiIKc3lzY2hhbm5lbCpAZDZiNmQ2Y2Y0NGVhYTc3MGQ1NjIwMjdmMzFjMzhjYWEzZmMxOTJj
      M2IxM2NhNzIyNzQ2MTJjNjZjZmMyMDFiYxIaEhjbjBMsl+Vx8IsGaNHNKwzt9TlRl6BQPxES11sK
      1FsS0VsSmyoKB09yZGVyZXISjyoSihYKCm9yZGVyZXJNU1AS+xUalxQKA01TUBKPFBKEFBKBFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVWFwMEhGbzc3bUkreTg4d2Jsd1ByMzhDM1N5OHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRneE5qRTNORFJhRncweU5UQTJNRGN4TmpFM05EUmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJpdnRGMlIzcllqV1ZmbkVhanpnWUJC
      a0tCTlIzT0UyckZIeERjdldrU3pxMiswbUlJREhCbExrdUFJdmx0CjhJbDRYV1JiS0Z2ajJIdmhJ
      UHlsZXJGOW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVaE9wU0RVSXJuU3YvaVMxaTR3M24vTCtGd3lZd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdiTGo5SVdvYmt4Zk1vcTNyNjJBRzhvY2V1M2wxeFZ2aUFKTk9nOTJoeldrQ0lB
      UjFnVnpXCitDWEZqc0FDemdSVGhldW9PL283QnRLVk15QVNKRyt5VmNWVgotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKSCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMURDQ0FudWdB
      d0lCQWdJVVpjVlRtY1hDR2xoQVBhQTFaVjAvTElKRXJyQXdDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TVRneE5qRTJNREJhRncweU16QTRNVGd4TmpJeE1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJO
      MGIvYlowWXc5eXBSRXN1V2ZsMkNLTko3WkRqeWwyeW55Q2VqYzhvUDBTCm1aSTc2SDdhS0VHb0VW
      dDZUL25QU2VLbnZoSVlsTHgvSHY4cDVpWEJuektqZ2dFUE1JSUJDekFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV1VTJqK3dpQmI5Nzl4RkQycVpG
      eQpOaGJYM3djd0h3WURWUjBqQkJnd0ZvQVVoT3BTRFVJcm5Tdi9pUzFpNHczbi9MK0Z3eVl3SXdZ
      RFZSMFJCQnd3CkdvSVlZMkV0ZEc5dmJITXRZelJrWWpnM05qZGlMV001TldKa01JR0ZCZ2dxQXdR
      RkJnY0lBUVI1ZXlKaGRIUnkKY3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0
      aU9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cApZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1
      MFNVUWlPaUpCWkcxcGJrQnZjbVJsY21WeUxXNWxkQ0lzCkltaG1MbFI1Y0dVaU9pSmhaRzFwYmlK
      OWZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQXhxUXg5bGx6SHUvTkQKYm5BZElRekhmbEZ5dWZv
      ckhJcFBaeTdGTlhNekl3SWdXQzlMSVg2S1NCMEtWaTExK01QMlIxajk3NWV4M0dCQQpENlFEMHB2
      ZFQwaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVYXAwSEZvNzdtSSt5ODh3
      Ymx3UHIzOEMzU3k4d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVGd4TmpF
      M05EUmFGdzB5TlRBMk1EY3hOakUzTkRSYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEps
      Y2pFWApNQlVHQTFVRUF3d09ZMkV1YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DCkFBUml2dEYyUjNyWWpXVmZuRWFqemdZQkJrS0JOUjNPRTJyRkh4RGN2V2tT
      enEyKzBtSUlESEJsTGt1QUl2bHQKOElsNFhXUmJLRnZqMkh2aElQeWxlckY5bzBJd1FEQVBCZ05W
      SFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVoT3BT
      RFVJcm5Tdi9pUzFpNHczbi9MK0Z3eVl3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ2JMajlJV29i
      a3hmTW9xM3I2MkFHOG9jZXUzbDF4VnZpQUpOT2c5Mmh6V2tDSUFSMWdWelcKK0NYRmpzQUN6Z1JU
      aGV1b08vbzdCdEtWTXlBU0pHK3lWY1ZWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyIz
      CgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zIjQKBkFk
      bWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMa
      HgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEgga
      BkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5z
      dXNUeXBlEsIRErcRCghldGNkcmFmdBKqEQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NBcG1nQXdJQkFnSVVGZGd4amhYbndQ
      UzJSMlpUbERkajBaZTJ2dVl3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6
      QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RB
      ZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1U
      Z3hOakUyTURCYUZ3MHlNekE0TVRneE5qSXhNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZ
      RApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJ
      eEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdW
      eVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXViYVIzR1FaTTJP
      ZEMvSHpBckVyNlp3eGlNdkZObUZsN3ptTgp6MmZQQk10Nk90dVNOU21UVThTbGxXTXNDd29FU3Js
      N1d1c0h1RGtzUXFXL1JZMVphYU9DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdO
      VkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURB
      ZEJnTlZIUTRFRmdRVXkybDBENUlxdUlvN3VNMFZQUU1uYjNNN21qa3dId1lEVlIwagpCQmd3Rm9B
      VWhPcFNEVUlyblN2L2lTMWk0dzNuL0wrRnd5WXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1
      CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dH
      Q0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdp
      YUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pv
      Wmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFxSmZi
      ODFkb3MwcHdHWU9rdytScGQ5Qk1mdmlyY1VCdy9UR2oKVTJPaEJhUUNJQWVmV0F4MitPZ1prdGQr
      U2FtNWJxY2d6aDNNdVhMWUFpWmQyTnlKYXBQQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6
      CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJVUZkZ3hqaFhu
      d1BTMlIyWlRsRGRqMFplMnZ1WXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4
      RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFL
      REFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0
      TVRneE5qRTJNREJhRncweU16QTRNVGd4TmpJeE1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dH
      UVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnla
      WEl4RURBT0JnTlYKQkFzVEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXla
      R1Z5WlhJdGJtVjBNRmt3RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFdWJhUjNHUVpN
      Mk9kQy9IekFyRXI2Wnd4aU12Rk5tRmw3em1OCnoyZlBCTXQ2T3R1U05TbVRVOFNsbFdNc0N3b0VT
      cmw3V3VzSHVEa3NRcVcvUlkxWmFhT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRC
      Z05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdB
      REFkQmdOVkhRNEVGZ1FVeTJsMEQ1SXF1SW83dU0wVlBRTW5iM003bWprd0h3WURWUjBqCkJCZ3dG
      b0FVaE9wU0RVSXJuU3YvaVMxaTR3M24vTCtGd3lZd093WURWUjBSQkRRd01vSVViM0prWlhKbGNq
      RXUKYjNKa1pYSmxjaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1H
      Z0dDQ29EQkFVRwpCd2dCQkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlp
      d2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxD
      Sm9aaTVVZVhCbElqb2liM0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXFK
      ZmI4MWRvczBwd0dZT2t3K1JwZDlCTWZ2aXJjVUJ3L1RHagpVMk9oQmFRQ0lBZWZXQXgyK09nWmt0
      ZCtTYW01YnFjZ3poM011WExZQWlaZDJOeUphcFBDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      EhIKBTUwMG1zEAoYASAFKICAgAgaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlk
      YXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMS8y4K
      C0NvbnNvcnRpdW1zEuMuEpguChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL5LRLMFgoLYXVk
      aXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQi9UQ0NBYUtnQXdJQkFnSVVKRGJaeHoxT1RXY0N3WGlXZzhWSUh6
      OUJ1VHN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hPREUyTVRnME9W
      b1hEVEkxTURZd056RTJNVGcwT1Zvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUVnd0V0NmZGbDRBRmJjNUQyNUhtaWxVeW5mNUx1Z29QbElsT3NkWUZhNFp3
      UkhKSXlWRHdnOHFuUgplVVJvWk13czc4T0Z2QW9ST2hJclhpcW1QdXkrWDZOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGR2FZN3M2
      QlBUWEswRmpLTkQ5MDR2clRyU1ZpTUFvR0NDcUcKU000OUJBTUNBMGtBTUVZQ0lRQzZGVkFpcnMx
      SkRJM3ZlRGd5WVRtVW9VUi8yVkptZ1pWUXZ1UmRlakxWaHdJaApBTGpZQ3FtNXZ3RWRxckxKOTRU
      dTJUR05lKzlWc2ZHYm5BaFFHc2F4a3BtRgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJVURYZDh0RGVDaWN0
      djdybVBQd2N6YWd1R3JzQXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURn
      eE9ERTJNVGN3TUZvWERUSXpNRGd4T0RFMk1qSXdNRm93ZWpFTE1Ba0dBMVVFQmhNQ1EwZ3hHakFZ
      CkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdoQmRXUnBkRzl5
      TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRFYk1Ca0dBMVVF
      QXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVhYk1YMmpBa1RGWkxqWWxFCmVrMG01M2VVbjhmVDFDM3VQOTJlZkppMFFiMHBUeThM
      OE80Y1hVZTB1TnZFTlp2ZGhSaDMrVDlsU0tVU2hMUDIKYzVGV3FLT0NBUm93Z2dFV01BNEdBMVVk
      RHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJTbHYrZk9OUUVv
      dWMzaExtbDBWd2s2dXI4Wld6QWZCZ05WSFNNRUdEQVdnQlJtbU83T2dUMDF5dEJZCnlqUS9kT0w2
      MDYwbFlqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAxTlRkbVltWTNZalkyTFhGbU9YcDAK
      TUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFa
      U0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWVhWa2FYUnZj
      akVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5TVMxdVpYUWlM
      Q0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFOcElL
      ci9WYmQra1hhQ2tkTzVtMDQ1dHZLcDgrLzdNQUJjbwprcklsb1hNekFpQnVmSWs5cm4xd29WZ2Iy
      UFJUQ1FudUc0ZisvMm5yak02b1ZpUGZ1YUtpVlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      CkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9UQ0NB
      YUtnQXdJQkFnSVVKRGJaeHoxT1RXY0N3WGlXZzhWSUh6OUJ1VHN3Q2dZSUtvWkl6ajBFQXdJdwpY
      REVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hPREUyTVRnME9Wb1hEVEkxTURZd056RTJNVGcwT1Zvd1hE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVnd0V0NmZGbDRB
      RmJjNUQyNUhtaWxVeW5mNUx1Z29QbElsT3NkWUZhNFp3UkhKSXlWRHdnOHFuUgplVVJvWk13czc4
      T0Z2QW9ST2hJclhpcW1QdXkrWDZOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhR
      OEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGR2FZN3M2QlBUWEswRmpLTkQ5MDR2clRyU1ZpTUFv
      R0NDcUcKU000OUJBTUNBMGtBTUVZQ0lRQzZGVkFpcnMxSkRJM3ZlRGd5WVRtVW9VUi8yVkptZ1pW
      UXZ1UmRlakxWaHdJaApBTGpZQ3FtNXZ3RWRxckxKOTRUdTJUR05lKzlWc2ZHYm5BaFFHc2F4a3Bt
      RgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsS
      CBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIG
      CAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARIC
      CAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMqBkFkbWlucxLMFgoLYXVkaXRvcjJNU1ASvBYa
      1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVhcGlpb2pUaHd1dzNkZXFIMGxXMkU0Z25ZeFl3Q2dZSUtv
      Wkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hPREUyTVRrMU5Gb1hEVEkxTURZd056
      RTJNVGsxTkZvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFn
      QUV6MkZlalluK1VNRnhGZXVNSk12aGRnQmE1T3lCRUxneGg1RDdmRVBIV2V3SHhKSXJpWlUwV0Vm
      Ygo0a1dDOXV6V0Zkc2gyR3BLemtXaS9JUDFXcHdUNnFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdF
      Qi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQWV1eGpiVW84Z3MwRDFwRmYw
      T3lmbkZ4YzZjTUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lFY1hyd0o3U1dZYWpUZWpPWmNzZ3NR
      d0VieFlTVnNpd1ArTVBDV01PVUhHQWlFQQprQmUwNDIxNCtLby9IVHBmQStNbzB4ci9OS2dTejVZ
      RDFvaWVzYmpDc1ZzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwdWdBd0lCQWdJVVZCbE1MaU10YkVkN3g5ODBoNmlzcGZ1
      cHREa3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpF
      WU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE9ERTJNVGt3TUZv
      WERUSXpNRGd4T0RFMk1qUXdNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFaCkJnTlZCQWNURWpV
      eExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2Y2pJeEh6QU0KQmdO
      VkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05WQkFNTUVrRmtiV2x1
      UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSlMy
      QTFhRE14WUJROHo2CmpzRE42VUJ3alVmSmd5MEFHOW0wU3hmWDdwYmFaV1MwMWpvSkt1VHlXZEFY
      OXd6YWpuanZlRC9XdUpSckVYeXQKcVFwbEwzT2pnZ0VhTUlJQkZqQU9CZ05WSFE4QkFmOEVCQU1D
      QjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVUlpQkNhdnAvZWl5dSs5YWdYUGpp
      TnBrWlhEUXdId1lEVlIwakJCZ3dGb0FVQjY3R050U2p5Q3pRClBXa1YvUTdKK2NYRnpwd3dKQVlE
      VlIwUkJCMHdHNElaWTJFdGRHOXZiSE10TnpkaVl6VTBPV1E0TkMxa2FtSmsKYkRDQmp3WUlLZ01F
      QlFZSENBRUVnWUo3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaApaRzFw
      YmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1GMVpHbDBiM0l5SWl3aWFHWXVS
      VzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlYVmthWFJ2Y2pJdGJtVjBJaXdpYUdZdVZIbHda
      U0k2SW1Ga2JXbHUKSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lEQlF6UXNHclFpc3ZScUNZ
      UkUweHRWL3JDWkFaRnExREVnbQp2UVRub1FaVkFpQk9Fanlrdk4yNDFuUnF2SEVGQWs2NjM5QURH
      Qll0YklnQk5nanhaL0UwOXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZT
      SEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVh
      cGlpb2pUaHd1dzNkZXFIMGxXMkU0Z25ZeFl3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdE
      d1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1C
      NFgKRFRJeU1EZ3hPREUyTVRrMU5Gb1hEVEkxTURZd056RTJNVGsxTkZvd1hERUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1G
      a3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUV6MkZlalluK1VNRnhGZXVNSk12aGRn
      QmE1T3lCRUxneGg1RDdmRVBIV2V3SHhKSXJpWlUwV0VmYgo0a1dDOXV6V0Zkc2gyR3BLemtXaS9J
      UDFXcHdUNnFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0Fh
      WXdIUVlEVlIwT0JCWUVGQWV1eGpiVW84Z3MwRDFwRmYwT3lmbkZ4YzZjTUFvR0NDcUcKU000OUJB
      TUNBMGdBTUVVQ0lFY1hyd0o3U1dZYWpUZWpPWmNzZ3NRd0VieFlTVnNpd1ArTVBDV01PVUhHQWlF
      QQprQmUwNDIxNCtLby9IVHBmQStNbzB4ci9OS2dTejVZRDFvaWVzYmpDc1ZzPQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoREg8KC2F1
      ZGl0b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggBEgIIABoPEg0K
      C2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1
      ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMS
      CAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5z
      Gi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaSgoQT3JkZXJl
      ckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoA
      CgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
