apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://143.198.247.194:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIPGmnADhal6DbL3THbaqx1TOkosEEPRorSj8oWrwHkQ6EtZcCtNcCtBcCngKWggBEAEaBgjX
      2uiXBiIKc3lzY2hhbm5lbCpAYTAwNzlmZGI5OWFjYTVlNmZjZTRjMjZmYjBmZWYyMDVlZDEzOTc4
      YmQ1NDUxZDUzZTgxNzY3YjUxMzZkNjA0NRIaEhhCuiVWVWzU9sxyspsAawd6dw0uZFiCG1IS01sK
      0FsSzVsSmyoKB09yZGVyZXISjyoSihYKCm9yZGVyZXJNU1AS+xUalxQKA01TUBKPFBKEFBKBFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVWNRQUVGa3Z2QnA1djA2TGdsOG03eHBMWEozVXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRVeE1UQTVNamxhRncweU5UQTJNRFF4TVRBNU1qbGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFnQytyRjltcUFIbUFOUHkrd3hLM05l
      RlV1OHM2dzBRM2JmRno3MWVlOXhUWEw4OS9vcUxYZWUyWDcrOElYCnNFNnJyei9IVUYzTXFFbUpE
      TzJVQmJ0Tm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVaStkaEFIcVhsWk9pZCtoTkhEWmk4TUs5eGkwd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdCS1pQL2d3MXFDajhUSWc2dEI5d2lYdjNkTXU3TTZSL01QdXQwVE8xczgwQ0lB
      cjExRXpPClVPK3F0YitoaFdVa1dMRnpZOGMwd2ZrRlFUVDJKMVIyYkQrYgotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKSCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMVRDQ0FueWdB
      d0lCQWdJVUdSOGxDZVBXd2sxUW9CWWkwVUdsZGZvdVpxZ3dDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TVRVeE1URTFNREJhRncweU16QTRNVFV4TVRJd01EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJG
      enJweVhRTHJReW4vVUZkaWZpK1RKYk53cVJIVWNJdnFrRW9XUDh6ZGY4Clk2c1hmTm9QTCtxQjlI
      MHlWVWxJUmNuR044OEJlRlBORmVyYk1uMlJVcnFqZ2dFUU1JSUJEREFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVZRHZ2ZzFxbWpRZzFMa2V4Qk1a
      dwpMZm1wdUNjd0h3WURWUjBqQkJnd0ZvQVVpK2RoQUhxWGxaT2lkK2hOSERaaThNSzl4aTB3SkFZ
      RFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROamsxTkRoa09HTmpOaTFpYWprMVpqQ0JoUVlJS2dN
      RUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYlds
      dUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdGbUFTellaN3JyV3IKYUkvM28xTWNkNlM5UktF
      YW5HeitrL2l3VCtnZ09vOENJQzV2ZjV3bUtIaDdSUHVjbVdHelZmUnlpNnpLMi9XeApDMDMwMmtV
      TUx4NHEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVY1FBRUZrdnZCcDV2MDZM
      Z2w4bTd4cExYSjNVd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVFV4TVRB
      NU1qbGFGdzB5TlRBMk1EUXhNVEE1TWpsYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEps
      Y2pFWApNQlVHQTFVRUF3d09ZMkV1YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DCkFBUWdDK3JGOW1xQUhtQU5QeSt3eEszTmVGVXU4czZ3MFEzYmZGejcxZWU5
      eFRYTDg5L29xTFhlZTJYNys4SVgKc0U2cnJ6L0hVRjNNcUVtSkRPMlVCYnRObzBJd1FEQVBCZ05W
      SFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVpK2Ro
      QUhxWGxaT2lkK2hOSERaaThNSzl4aTB3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0JLWlAvZ3cx
      cUNqOFRJZzZ0Qjl3aVh2M2RNdTdNNlIvTVB1dDBUTzFzODBDSUFyMTFFek8KVU8rcXRiK2hoV1Vr
      V0xGelk4YzB3ZmtGUVRUMkoxUjJiRCtiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyI0
      CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRlcmVyTVNQEAEaBkFkbWlucyI3CgtF
      bmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyIzCgdS
      ZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zKgZBZG1pbnMa
      1BEKDUNvbnNlbnN1c1R5cGUSwhEStxEKCGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVy
      LW5ldBCKNxq6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJ
      VVFnQjBRbllDTGFLbmJwdDQ2VUZ5YUZFbFMzd3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFl
      RncweQpNakE0TVRVeE1URTFNREJhRncweU16QTRNVFV4TVRJd01EQmFNRzB4Q3pBSkJnTlZCQVlU
      QWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9U
      QjA5eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5
      WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FF
      S2xGcWd2UmVkbmVXaFBiVlVtWHJxb2dsN0s4a21uSlJ1cGM5CklwelBpRjNQRDF6TFA4cC90ZTZM
      ZWo3ZFA0dVFqL0pub01STU9DbW90UHZmZzl6b1I2T0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FF
      QXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBU
      QVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVbGdYN1c5UVlxTWdmckVsVk9XVWg0NXhMTlk4d0h3WURW
      UjBqCkJCZ3dGb0FVaStkaEFIcVhsWk9pZCtoTkhEWmk4TUs5eGkwd093WURWUjBSQkRRd01vSVVi
      M0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZ
      V3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBh
      Vzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxj
      aTF1WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTklB
      REJGQWlFQXVYYlg2cTVXSTAvNnhuSnI1eFNCMHhHUWVTbjJISmtqUWppaQpoTnZDKytjQ0lBdWI2
      SmNNM21leS9IUVJtTEJvRHdLRHlPSGxONitQZU5ZWnZBU05GVGZRCi0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJB
      Z0lVUWdCMFFuWUNMYUtuYnB0NDZVRnlhRkVsUzN3d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGRE
      QWVGdzB5Ck1qQTRNVFV4TVRFMU1EQmFGdzB5TXpBNE1UVXhNVEl3TURCYU1HMHhDekFKQmdOVkJB
      WVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJB
      b1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpH
      VnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFn
      QUVLbEZxZ3ZSZWRuZVdoUGJWVW1YcnFvZ2w3SzhrbW5KUnVwYzkKSXB6UGlGM1BEMXpMUDhwL3Rl
      NkxlajdkUDR1UWovSm5vTVJNT0Ntb3RQdmZnOXpvUjZPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93
      UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZS
      MFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVsZ1g3VzlRWXFNZ2ZyRWxWT1dVaDQ1eExOWTh3SHdZ
      RFZSMGoKQkJnd0ZvQVVpK2RoQUhxWGxaT2lkK2hOSERaaThNSzl4aTB3T3dZRFZSMFJCRFF3TW9J
      VWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5
      allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdG
      MGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhK
      bGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdO
      SUFEQkZBaUVBdVhiWDZxNVdJMC82eG5KcjV4U0IweEdRZVNuMkhKa2pRamlpCmhOdkMrK2NDSUF1
      YjZKY00zbWV5L0hRUm1MQm9Ed0tEeU9IbE42K1BlTlladkFTTkZUZlEKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICACBoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsI
      ChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hh
      bm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlk
      YXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMS7y4K
      C0NvbnNvcnRpdW1zEt8uEpQuChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL1LRLIFgoLYXVk
      aXRvcjFNU1ASuBYa0BQKA01TUBLIFBK9FBK6FAoLYXVkaXRvcjFNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVUSDU3bnkvSU0zMUVRb0hYZW04eGdw
      blZTbk13Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hOVEV4TVRBMU0x
      b1hEVEkxTURZd05ERXhNVEExTTFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUVtdTdSRlo5MUErUUlweDdkamI3bE04MnpuTHpmVDY1UExuREtIdlZQbCty
      cENLZEVhclFiQ3N0MQoxcWJESWozaFhhSkY3T2djak91NUVXRVdJSmtEbWFOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGTGNCWWN3
      QmtwMWFJaUZua1dYYmZrdGo0Qm1XTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lCYjlTajFlYkJs
      YlJWL2tDV1g0dDZZL1lreG9CL1RKM1lvK3luQ1FUMW8xQWlBRQpENGtRYlBGY2pGeXVDbzNsV3hk
      WTlNV0ZkWnZ1SGtiWklpaWIxcVl3SHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwcWdBd0lCQWdJVUZ3STRDRC85NG1J
      bGlFVkl6dllOYkZyL0xIQXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURn
      eE5URXhNVGN3TUZvWERUSXpNRGd4TlRFeE1qSXdNRm93ZWpFTE1Ba0dBMVVFQmhNQ1EwZ3hHakFZ
      CkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdoQmRXUnBkRzl5
      TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRFYk1Ca0dBMVVF
      QXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVHMDFuZEJkZkEzU2JuM3JpCmkrWlRQZmtnZmZUMldpeGpGd3BpOTB5czc2UUVEamww
      NDBrYTZ3a0VpQ2RySHNudVYrWURHVkRQNk1Xd2FFdnUKWE8xb2JhT0NBUm93Z2dFV01BNEdBMVVk
      RHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJReWs2T1hUdUVB
      UmZQckllTGRrYVNFRXRPMmxqQWZCZ05WSFNNRUdEQVdnQlMzQVdITUFaS2RXaUloClo1RmwyMzVM
      WStBWmxqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzTkRWbU56aGtZalppTFRoak9HNXMK
      TUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFa
      U0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWVhWa2FYUnZj
      akVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5TVMxdVpYUWlM
      Q0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ0F0ZEpJ
      OVd5VHBUcldkTDhaOVB6d2J5VFVRMHN1K0x4SmtmUwpBT2NvTmhVQ0lGK1J4MmRjSlNXQ0tITUFU
      OHVSQllLS1p5QVl1a1dGbWpxMm5YdnAyZzBnCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4K
      BFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dB
      d0lCQWdJVVRINTdueS9JTTMxRVFvSFhlbTh4Z3BuVlNuTXdDZ1lJS29aSXpqMEVBd0l3ClhERUxN
      QWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFX
      Tm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      RXRibVYwTUI0WApEVEl5TURneE5URXhNVEExTTFvWERUSTFNRFl3TkRFeE1UQTFNMW93WERFTE1B
      a0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFX
      Tm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      RXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRW11N1JGWjkxQStRSXB4
      N2RqYjdsTTgyem5MemZUNjVQTG5ES0h2VlBsK3JwQ0tkRWFyUWJDc3QxCjFxYkRJajNoWGFKRjdP
      Z2NqT3U1RVdFV0lKa0RtYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFm
      OEVCQU1DQWFZd0hRWURWUjBPQkJZRUZMY0JZY3dCa3AxYUlpRm5rV1hiZmt0ajRCbVdNQW9HQ0Nx
      RwpTTTQ5QkFNQ0EwY0FNRVFDSUJiOVNqMWViQmxiUlYva0NXWDR0NlkvWWt4b0IvVEozWW8reW5D
      UVQxbzFBaUFFCkQ0a1FiUEZjakZ5dUNvM2xXeGRZOU1XRmRadnVIa2JaSWlpYjFxWXdIdz09Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggA
      GhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIGCAES
      AggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9yMk1TUBK8FhrUFAoD
      TVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL0RDQ0FhS2dBd0lCQWdJVU10ZzdyNjcwTFB4N2pHZjhUZHUwNkF4ZjVsMHdDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE5URXhNVEl4TkZvWERUSTFNRFl3TkRFeE1U
      SXhORm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRXZn
      T0ZpcURCT0lEaUczQXJsWGJPdFdBbHhnRTZkdWJmNDFjUGFQQlFCaEFVZzRxVERRV3MxMUlhCkRZ
      VHlmUlVmeEZIRUlGakdqRENDK1RRQnZtV0NkcU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZPam9VVlBjT0Y1dnBwcVcvQzE2WXhT
      MTZBQ0FNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFEejdXQWlwaVNvalM2T1h2UWpSTk1uR1Qv
      dk01U2p6WGpBd2x2RjNWNTMzd0lnClhSaVpkQUZpWDE5RjBkMEJMZHdUbTZYa2RVbEoydkpWc2pI
      dUx5ZlpWaG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM5RENDQXB1Z0F3SUJBZ0lVTGtpQmJodm5TTmhzTDhMRUtlbWY0UDdpS01R
      d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZ
      R0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TlRFeE1qQXdNRm9YRFRJ
      ek1EZ3hOVEV4TWpVd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdOVkJBY1RFalV4TGpV
      d0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4SHpBTQpCZ05WQkFz
      VEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1NRWtGa2JXbHVRR0Yx
      ClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEMHhzYVgx
      RXM2R1paU20KaUc0YTduai9TY1ExYkpkaFg0cFpwWU9rcjNGeWN4R0hEOE5IbzZad01jcUJyak84
      T0dDcWRWaktIblo4NUR6dwpHSzBsaHlTamdnRWFNSUlCRmpBT0JnTlZIUThCQWY4RUJBTUNCNEF3
      REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVdTFsY05RWHlUNkhDTERYZExYMElHVjBB
      Q1I0d0h3WURWUjBqQkJnd0ZvQVU2T2hSVTl3NFhtK20KbXBiOExYcGpGTFhvQUlBd0pBWURWUjBS
      QkIwd0c0SVpZMkV0ZEc5dmJITXRObVkyWXpZMlpEVmtOQzFqTW1wNApaekNCandZSUtnTUVCUVlI
      Q0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlMQ0poClpHMXBiaUk2
      SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJaXdpYUdZdVJXNXkK
      YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJ
      bUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUVOOFArZmZQYmNMc2pUNnJqTEt4
      MHJ5eVNmcWxMSTJDSlhuCmVCdmdOSUNXQWlCKzUzVnFUL3NtM1V6b1N4d3ZXaTk2N1pOK2E0M3RV
      MkJBOHJZWkNsK3E4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1
      NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVU10Zzdy
      NjcwTFB4N2pHZjhUZHUwNkF4ZjVsMHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURW
      UVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApE
      VEl5TURneE5URXhNVEl4TkZvWERUSTFNRFl3TkRFeE1USXhORm93WERFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZR
      UUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3
      WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRXZnT0ZpcURCT0lEaUczQXJsWGJPdFdBbHhn
      RTZkdWJmNDFjUGFQQlFCaEFVZzRxVERRV3MxMUlhCkRZVHlmUlVmeEZIRUlGakdqRENDK1RRQnZt
      V0NkcU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hR
      WURWUjBPQkJZRUZPam9VVlBjT0Y1dnBwcVcvQzE2WXhTMTZBQ0FNQW9HQ0NxRwpTTTQ5QkFNQ0Ew
      Z0FNRVVDSVFEejdXQWlwaVNvalM2T1h2UWpSTk1uR1Qvdk01U2p6WGpBd2x2RjNWNTMzd0lnClhS
      aVpkQUZpWDE5RjBkMEJMZHdUbTZYa2RVbEoydkpWc2pIdUx5ZlpWaG89Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggAGhESDwoLYXVk
      aXRvcjJNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIGCAESAggAGg8SDQoL
      YXVkaXRvcjJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVk
      aXRvcjJNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRv
      cjJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZB
      ZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyIt
      CgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZ
      QmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpKChBPcmRlcmVyQWRk
      cmVzc2VzEjYSGwoZb3JkZXJlcjEub3JkZXJlci1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIO
      CAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlu
      cyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoA
      CgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
