apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: devorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIB0VzhquAz8+HD6EzVJt+6s7szBWeomL7gyB2gIPzhDhEt5cCttcCthcCngKWggBEAEaBgjx
      ob2XBiIKc3lzY2hhbm5lbCpANjRkYjc1YTQ2MzkwN2Q3N2M3Y2Q3MDI0MjZkNzgyMjc4YmEzMTZj
      ZGU0OTgyMDRhZmVmZDFmNjIxMzE0ZDcxYhIaEhjbDDP2GhDJj3T7Cqhh0ttzKqw/wDaZx3MS21sK
      2FsS1VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVUZvUGdET3ljTlMrbWJhY012SWhLN3FFMnJhSXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURjd05UQXlNRFphRncweU5UQTFNamN3TlRBeU1EWmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVQybitYUFR2SFF0MFBuRGZ5dlZIMDRE
      K0Y3K1UxdTFTM2NZbUJRZjhJSE03T3Z2WnN4MnlKZGZNYzZ3R1gwCksza0p6cXgrTGtoaHpDYjF6
      VGszSWQrSG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVS2VuWTlyZnh1ekQ5U3N3bTZNeDNlcnBuLzFzd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdSTFFvVTlRUWpjRDZadlFFeFZMalcvNW9OOG9uUFNndUpqTHl1bVFXUGdNQ0lR
      Qzh4K2x2CnNqYzVwMWl5SHkyNmFSYXJOUHBBZ0E0d0EweEV4ckJSVFdjblZBPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFEQ0NB
      bnVnQXdJQkFnSVVIcE5VWUY0UmxwV3dNV1dsY2dOeWVwZEZTZFl3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1EY3dOVEEzTURCYUZ3MHlNekE0TURjd05URXlNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCUFpZU0VtazRzRG5nVTRMNTVlSkh5LzYySlNmZ2psU1JCY25FNmJZOVpzWQpBaThjbmZFN0lD
      V1p0V3RTdVVrYS9iZHAyVzFQTko0ZnBwbTNLU2Rla3JHamdnRVBNSUlCQ3pBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVNzB3eVU5YTd5MC8yUjh1
      QzA3ZVQKZlVCdXAyZ3dId1lEVlIwakJCZ3dGb0FVS2VuWTlyZnh1ekQ5U3N3bTZNeDNlcnBuLzFz
      d0l3WURWUjBSQkJ3dwpHb0lZWTJFdGRHOXZiSE10TlRsbU9EVTNZMlkwTFhCNmJtWnRNSUdGQmdn
      cUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJcwpJbWhtTGxSNWNHVWlPaUpoWkcx
      cGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUIzTnBTeGJpZE1mZUhWCmpvclR3cnZ6c2U0
      MjZWZDBVdm05cFJ5VGFjRXZYQUlnYUVlMVFnaVd3dnkzdGxZbFUxREsxWVF5SjJTSTNjUmIKNUFU
      YTFWclN5Qmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUZvUGdET3ljTlMr
      bWJhY012SWhLN3FFMnJhSXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURj
      d05UQXlNRFphRncweU5UQTFNamN3TlRBeU1EWmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVQybitYUFR2SFF0MFBuRGZ5dlZIMDREK0Y3K1UxdTFTM2NZbUJR
      ZjhJSE03T3Z2WnN4MnlKZGZNYzZ3R1gwCksza0p6cXgrTGtoaHpDYjF6VGszSWQrSG8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      S2VuWTlyZnh1ekQ5U3N3bTZNeDNlcnBuLzFzd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdSTFFv
      VTlRUWpjRDZadlFFeFZMalcvNW9OOG9uUFNndUpqTHl1bVFXUGdNQ0lRQzh4K2x2CnNqYzVwMWl5
      SHkyNmFSYXJOUHBBZ0E0d0EweEV4ckJSVFdjblZBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1TUBABGgZBZG1pbnMi
      NwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9yZGVyZXIx
      Lm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBt
      Z0F3SUJBZ0lVU1kya1ZwNzNMZDhObXBZR2x3aC9WZGxxQ1lZd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5
      TFc1bGREQWVGdzB5Ck1qQTRNRGN3TlRBM01EQmFGdzB5TXpBNE1EY3dOVEV5TURCYU1HMHhDekFK
      QmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFP
      QmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1U
      Rkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVyS29vWXliWlA4ZUZvRXZyV0kxY0pTNWtqS0x2UjZVQ2p5ZjEKYWJOVXJVQTFLSTVq
      elZyMkVSVmgwOFlYNTU2eGNLdjBJZTZxM3FLY2hDMXEyeDNHenFPQ0FTZ3dnZ0VrTUE0RwpBMVVk
      RHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdE
      QVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVtZlZXRnJsTHViNytWZWxPS200M1diOVcv
      Vm93SHdZRFZSMGoKQkJnd0ZvQVVLZW5ZOXJmeHV6RDlTc3dtNk14M2VycG4vMXN3T3dZRFZSMFJC
      RFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNi
      M0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1a
      bWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXVi
      M0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9Q
      UVFEQWdOSEFEQkVBaUEweHE5Ty9HQ2IzZW56eWhBY1NRWkhJQ2dFaHJFVlhUQU1pTTZCCkczZ3BL
      UUlnWHd4N29WQTBPdERNYjNGR0w2KzJ6ZVRKREp4dkVCVUN1MUpnQ1dNZG44dz0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzhqQ0NB
      cG1nQXdJQkFnSVVTWTJrVnA3M0xkOE5tcFlHbHdoL1ZkbHFDWVl3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1EY3dOVEEzTURCYUZ3MHlNekE0TURjd05URXlNREJhTUcweEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJB
      TVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpq
      MERBUWNEUWdBRXJLb29ZeWJaUDhlRm9FdnJXSTFjSlM1a2pLTHZSNlVDanlmMQphYk5VclVBMUtJ
      NWp6VnIyRVJWaDA4WVg1NTZ4Y0t2MEllNnEzcUtjaEMxcTJ4M0d6cU9DQVNnd2dnRWtNQTRHCkEx
      VWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJ
      d0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVW1mVldGcmxMdWI3K1ZlbE9LbTQzV2I5
      Vy9Wb3dId1lEVlIwagpCQmd3Rm9BVUtlblk5cmZ4dXpEOVNzd202TXgzZXJwbi8xc3dPd1lEVlIw
      UkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1W
      c2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pF
      dWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtq
      T1BRUURBZ05IQURCRUFpQTB4cTlPL0dDYjNlbnp5aEFjU1FaSElDZ0VockVWWFRBTWlNNkIKRzNn
      cEtRSWdYd3g3b1ZBME90RE1iM0ZHTDYrMnplVEpESnh2RUJVQ3UxSmdDV01kbjh3PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hT
      aXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlu
      cxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Js
      b2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJ
      CgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLvLgoLQ29uc29ydGl1bXMS3y4SlC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvUt
      EsgWCgthdWRpdG9yMU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dBd0lCQWdJVWFxSjZ0OWQzRmVZVU8x
      ZUNSeTVrbzZrSVpjOHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURnd056
      QTFNRE15TWxvWERUSTFNRFV5TnpBMU1ETXlNbG93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRU1OYUVpMWRVcmh4TEcyMWhXYXVGZU1vZm1UUUw0UXBBWjly
      aU9GRTVVc3V6VmFCeUNMQU0zZ3pjCk9SUWZiS0FkQ1k5N0JEZlRRV1hlSmkya1V0WnZTcU5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZPTmZmOHM0RE9sZEZsK2JjOFpDa0Q3UnQvTDVNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUNv
      ayt1S3RONVoyYkNPamtXeG1HakJYclZMWlp2aEZGelpmcURuRnhpVnlBaUJtCnFZN2FzcndpRk9Y
      Sy9QM0ttMmRobE1GdTc4c2pmRHZMeWR6bnRxdkdrUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBxZ0F3SUJBZ0lVTFEy
      NWZsemdxSUVBbWN2bDFveG5WR3FYN3lBd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd3TnpBMU1EZ3dNRm9YRFRJek1EZ3dOekExTVRNd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRTF2bmhScVd5OHI5aEhmeTcKL1dYbGFuNVZ2V3dqMnMxVmtJWUNKclFJ
      c0xLcTFuSW8wSm9aN0JxTC9EN2ZXdEU2d1lGeEVBL2R3TUhDVFRmKwpHYzlxb3FPQ0FSb3dnZ0VX
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlRR
      UklCQm5ZbDdZMkFaTzdacFBTUnVCQWZEVHpBZkJnTlZIU01FR0RBV2dCVGpYMy9MT0F6cFhSWmYK
      bTNQR1FwQSswYmZ5K1RBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDJPR1ptTnpZMVpqazJM
      V3R5Wm5GcgpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqRWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      UzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdS
      QUlnWmR5MzBWL3ltVlVuVFl4bG1lTHBTVm96WjQvYmpWRXIrME8yCmtGd203QjhDSUFjYlp2R09a
      eW11b1l5czhlcFRVRDFjZG12MFlwZWFMeWkvQ1pmV2grQlEKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIr
      ekNDQWFLZ0F3SUJBZ0lVYXFKNnQ5ZDNGZVlVTzFlQ1J5NWtvNmtJWmM4d0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd3TnpBMU1ETXlNbG9YRFRJMU1EVXlOekExTURNeU1s
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFTU5hRWkx
      ZFVyaHhMRzIxaFdhdUZlTW9mbVRRTDRRcEFaOXJpT0ZFNVVzdXpWYUJ5Q0xBTTNnemMKT1JRZmJL
      QWRDWTk3QkRmVFFXWGVKaTJrVXRadlNxTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRk9OZmY4czRET2xkRmwrYmM4WkNrRDdSdC9M
      NU1Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNJQ29rK3VLdE41WjJiQ09qa1d4bUdqQlhyVkxaWnZo
      RkZ6WmZxRG5GeGlWeUFpQm0KcVk3YXNyd2lGT1hLL1AzS20yZGhsTUZ1NzhzamZEdkx5ZHpudHF2
      R2tRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsS
      CBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYI
      ARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJBZ0lVWHZPTkZJNXR6aUN5eDBnOWp3RWJzK3RPWkQ0d0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3TnpBMU1EUXpPRm9YRFRJMU1E
      VXlOekExTURRek9Gb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFWCtCa0JpdE5QUTh1ZmFlOGM3c1B3QXBDUlFZVCtqYkFxRFcwR3hLNTJZNkFQMEppZk5I
      bkRsblAKQ3lTSU9pZk1QWFFKNlltM0xBaU1kYmR1dzUxR3BhTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRk5lVXBUWm56ZzJScVFv
      bXJvaTlZY1hJU2Y0L01Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNJQ2U2RXY1VDlVMlVmdGtHQk81
      RlZtSndFbzRsaUoxMFNqTjNrcVpPRWcxTUFpQXgKa1k3eUtaV2tUUGZSVEpMR05RSjNsbzBuTmVl
      cTI3VG5VZmRsZWVEb2RBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlUQ0NBcHVnQXdJQkFnSVVNTk5KZmdYcktmUm1LSE9lOS90
      bXlkNXRySWN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3dOekExTVRF
      d01Gb1hEVEl6TURnd056QTFNVFl3TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      QkV1YnBjTXN2RG1jT3BBTwpHR2NpR3hveGFZVUp5WE9lYUgzdk04a1g5OXhvQUkxeTBjNlg5Mytv
      QktoSVVjSHJOVmh4NTFRUHFHVUlGYVNQCkNoMnRXN2FqZ2dFYU1JSUJGakFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVVCaHllK2hrUlJPelEwalFw
      YXB1Mkk4Ujd0ZEl3SHdZRFZSMGpCQmd3Rm9BVTE1U2xObWZPRFpHcApDaWF1aUwxaHhjaEovajh3
      SkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE56WmtORGM0T0RRMk5DMXdjV3hpCmR6Q0Jqd1lJ
      S2dNRUJRWUhDQUVFZ1lKN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmgK
      WkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNkltRjFaR2wwYjNJeUlpd2lh
      R1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFXNUFZWFZrYVhSdmNqSXRibVYwSWl3aWFHWXVW
      SGx3WlNJNkltRmtiV2x1CkluMTlNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJUUNKSy8xeHpYVXNC
      SGc5QldWb2hNcWVRc2VvbkpVTmlpY0gKMUl0MitPTTlsd0lnSHErRWtJL0ZMbGxZMVdtbUpHSlFh
      UjNzdFhkeG5adURJenFEZ0dHcGh6ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJB
      Z0lVWHZPTkZJNXR6aUN5eDBnOWp3RWJzK3RPWkQ0d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd3TnpBMU1EUXpPRm9YRFRJMU1EVXlOekExTURRek9Gb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFWCtCa0JpdE5QUTh1ZmFlOGM3
      c1B3QXBDUlFZVCtqYkFxRFcwR3hLNTJZNkFQMEppZk5IbkRsblAKQ3lTSU9pZk1QWFFKNlltM0xB
      aU1kYmR1dzUxR3BhTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRk5lVXBUWm56ZzJScVFvbXJvaTlZY1hJU2Y0L01Bb0dDQ3FHClNN
      NDlCQU1DQTBjQU1FUUNJQ2U2RXY1VDlVMlVmdGtHQk81RlZtSndFbzRsaUoxMFNqTjNrcVpPRWcx
      TUFpQXgKa1k3eUtaV2tUUGZSVEpMR05RSjNsbzBuTmVlcTI3VG5VZmRsZWVEb2RBPT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAa
      ERIPCgthdWRpdG9yMk1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAa
      DxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
