apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIAygV5uqZdJ5Y9UmKU3xVqHCdGhwLN6bPDEfGvfJ61XOEuJcCt9cCtxcCngKWggBEAEaBgjr
      8vaXBiIKc3lzY2hhbm5lbCpANWFhYTEyODBkNzUwNGU5OTMzNjdlNjI0NzhmNDFhYWFhMjA1NTA4
      ZWQ0NzYzM2VmZjZhOGFhNTMwNDJjM2E4YRIaEhjZRsNUW2CActdaPGOQugU89ioiZII6qHoS31sK
      3FsS2VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lC
      QWdJVU5kc1p0a25FUHdncVAra0xTMDBuUHB3bVo0NHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRnd016VXpNVEZhRncweU5UQTJNRGN3TXpVek1URmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVROYWQvVForZGp6KzZVN0FSNE1PRFpY
      N2doS2xqV0lsZ29HTVFJa1gxU0tGQXd6R3ZzVFNmZ2xOSlNTc3VzCjZ5ZUphUm1FdlEwcFJwNTZM
      L0ptRjB1Um8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVSHU3M3JCdGpPdmJJRlVvT1JyLzh0SUVMQTFRd0NnWUlLb1pJemowRQpB
      d0lEU1FBd1JnSWhBSU1VTVpzNm5tZDJST0VQeGp0ZE5YN0lzemR4dG5oRk55cjRvcjBIQ1hLeEFp
      RUEybmI1CkRkYjhueGl0MWs5N3ZGTFd3eEQ4UFUxMlplUDM0QkNkcE1pMHRsQT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFEQ0NB
      bnVnQXdJQkFnSVVPUVNDRWVzOG9Tc0l0TE82NTlidnRPT2pJbmN3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UZ3dNelV5TURCYUZ3MHlNekE0TVRnd016VTNNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCTlk1aURBWnY4MkQ0MmlzWFZhOUNHQy9xNUFLU3lXa01tckxiVGFaRldnYgpCUjU4ZTNQdHlp
      MmFXeDBxb1c3VWJpdk11RmZrMnB1bUl3YVFlK0p4TzdlamdnRVBNSUlCQ3pBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVUGRha2JFMWxuUkd1Q0Jm
      cFFMSUcKcnlpSXFid3dId1lEVlIwakJCZ3dGb0FVSHU3M3JCdGpPdmJJRlVvT1JyLzh0SUVMQTFR
      d0l3WURWUjBSQkJ3dwpHb0lZWTJFdGRHOXZiSE10WXpSa1lqZzNOamRpTFdKeGFuTjBNSUdGQmdn
      cUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJcwpJbWhtTGxSNWNHVWlPaUpoWkcx
      cGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFiS1ZzckhaRTk3Zm0wCm8xQVlzaXh2OFJB
      a09UUyt2THJqWDFZVHJnV0Ryd0lnTjZVVWNobHVJTkNQK0dLU3VKbVB2T0xaMUpGamRXNGMKUzI0
      NW5KRHFHZ289Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lCQWdJVU5kc1p0a25FUHdn
      cVAra0xTMDBuUHB3bVo0NHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRn
      d016VXpNVEZhRncweU5UQTJNRGN3TXpVek1URmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVROYWQvVForZGp6KzZVN0FSNE1PRFpYN2doS2xqV0lsZ29HTVFJ
      a1gxU0tGQXd6R3ZzVFNmZ2xOSlNTc3VzCjZ5ZUphUm1FdlEwcFJwNTZML0ptRjB1Um8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      SHU3M3JCdGpPdmJJRlVvT1JyLzh0SUVMQTFRd0NnWUlLb1pJemowRQpBd0lEU1FBd1JnSWhBSU1V
      TVpzNm5tZDJST0VQeGp0ZE5YN0lzemR4dG5oRk55cjRvcjBIQ1hLeEFpRUEybmI1CkRkYjhueGl0
      MWs5N3ZGTFd3eEQ4UFUxMlplUDM0QkNkcE1pMHRsQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRt
      aW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVv
      dXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENh
      cGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa1BEKDUNvbnNlbnN1c1R5cGUSwhEStxEK
      CGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVyLW5ldBCKNxq6CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJVURweXJXSDBBLzR0N2hscG1uQ3FHeFdQ
      MXBid3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJj
      d0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRnd016VXlNREJhRncw
      eU16QTRNVGd3TXpVM01EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFz
      VEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3
      RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUmdmclFPWFJkSnRQL0IxSUl5MjRUYkVZ
      Z0ZMK3dsL29wVXVICmZvOUMxV0YrYzByYVN6UkFRZTFYUmxQaDVSMWVzUjk5a2RHVWI2Q2RDT3Bz
      MVYxdXBhT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dy
      QmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FV
      TnozRTJDWUtHeWZUeE85TjRtNjB6TXlTb1N3d0h3WURWUjBqCkJCZ3dGb0FVSHU3M3JCdGpPdmJJ
      RlVvT1JyLzh0SUVMQTFRd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dC
      QkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2li
      M0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTdBKzgyKzBaeVlHSGJlNTB2
      QjJ0d3I3SW5HZFhBZCt5empFVQo0clBRampjQ0lIOW5BUnBERjIwZFVrRGVOdEYzekYxLzN5aU5z
      dWdycUZYZ3Fkbk9aczdBCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVRHB5cldIMEEvNHQ3aGxwbW5DcUd4
      V1AxcGJ3d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVGd3TXpVeU1EQmFG
      dzB5TXpBNE1UZ3dNelUzTURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFN
      UzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpC
      QXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1G
      a3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVSZ2ZyUU9YUmRKdFAvQjFJSXkyNFRi
      RVlnRkwrd2wvb3BVdUgKZm85QzFXRitjMHJhU3pSQVFlMVhSbFBoNVIxZXNSOTlrZEdVYjZDZENP
      cHMxVjF1cGFPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJn
      Z3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVOejNFMkNZS0d5ZlR4TzlONG02MHpNeVNvU3d3SHdZRFZSMGoKQkJnd0ZvQVVIdTczckJ0ak92
      YklGVW9PUnIvOHRJRUxBMVF3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNp
      MXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3
      Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpv
      aWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBN0ErODIrMFp5WUdIYmU1
      MHZCMnR3cjdJbkdkWEFkK3l6akVVCjRyUFFqamNDSUg5bkFScERGMjBkVWtEZU50RjN6RjEvM3lp
      TnN1Z3JxRlhncWRuT1pzN0EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Js
      b2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJ
      CgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLzLgoLQ29uc29ydGl1bXMS4y4SmC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvkt
      EswWCgthdWRpdG9yMU1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dBd0lCQWdJVWFlTVlINDBZVXRCVzY1
      RVRGaEZzZGFFUFdJb3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE9E
      QXpOVFF4TjFvWERUSTFNRFl3TnpBek5UUXhOMW93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRU1qekZUUGxtbnZwbjVJUUtiMnFwUW9NVGFFZjdlVEVRNmta
      d09hNWpiOHFYS3hjRUdjYXF2cGVBCmxoaHduNzBYY0J3LzE2UHJBWlc3Vyt3WDNraWIrYU5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZEV2lscCtmQlhZRFo5MFVodzNxU080a213NUJNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUQv
      emw5NmgyM1A1TWtHOW9UZ3c2STRDSEJDbFhlbUVHVEFIWUwrd0d1cW5BaUEyCm9iUVoyb2lsYWtT
      QUJZZEs5WC84Q09wUnVvSStXaDlGQ2tKdmU2aHkxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIr4ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXBxZ0F3SUJBZ0lVV1Nu
      KytqUEhtY2QvVlhVc241QnVRdFhJR0FZd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd4T0RBek5UUXdNRm9YRFRJek1EZ3hPREF6TlRrd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRTlTeDdUd3JRVFNKTFFmN1kKNmpON0xhS2JQNnpYcE4yQ2VoelZENmVn
      VEc1QWJkbmlwZXVFa0c3QkJPT3lkT284VmFVQnRzN0hLWG5TWlgvMApINmQ0QjZPQ0FSb3dnZ0VX
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlJi
      c2xtQkl1RHlZeG04bUNMYWlkSktCWTFBQkRBZkJnTlZIU01FR0RBV2dCUTFvcGFmbndWMkEyZmQK
      RkljTjZranVKSnNPUVRBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDFOVGRtWW1ZM1lqWTJM
      WFI2YldkMgpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqRWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      UzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdS
      UUloQUpwVHpoUENIM0hucG9SYTJLVkUyNDIweWFuRFZqQ3E2V29RCkZ3M0o3alNzQWlCS0tTbFNO
      UGc0N05OdTdGb01aTE9CSkNtcW84YVF1b3hvWVdUSENwajZtQT09Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCK3pDQ0FhS2dBd0lCQWdJVWFlTVlINDBZVXRCVzY1RVRGaEZzZGFFUFdJb3dDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE9EQXpOVFF4TjFvWERUSTFNRFl3TnpBek5U
      UXhOMW93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRU1q
      ekZUUGxtbnZwbjVJUUtiMnFwUW9NVGFFZjdlVEVRNmtad09hNWpiOHFYS3hjRUdjYXF2cGVBCmxo
      aHduNzBYY0J3LzE2UHJBWlc3Vyt3WDNraWIrYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZEV2lscCtmQlhZRFo5MFVodzNxU080
      a213NUJNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUQvemw5NmgyM1A1TWtHOW9UZ3c2STRDSEJD
      bFhlbUVHVEFIWUwrd0d1cW5BaUEyCm9iUVoyb2lsYWtTQUJZZEs5WC84Q09wUnVvSStXaDlGQ2tK
      dmU2aHkxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHV3JpdGVycxIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgB
      Eh0SCBIGCAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikS
      HwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9y
      Mk1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVVJXWFpzd2pNVDhnU2FwR09zeFh5NkVuZVBv
      c3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE9EQXpOVFV5TWxvWERU
      STFNRFl3TnpBek5UVXlNbG93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRVVneGlEWkljLzVDeFZwMEE0bGlURlBETW5FYmFYNXgrWTVUVlY2NUZpdFpNTklm
      K0RmZHhuSXZLCjB1Y015ZmxyVEJQOHlWbk5XZm9mQXZJSHNGczlPS05DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZEanBidnQwTGdt
      Q0Zia1hTOS9pZjJ0WlhRcGJNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSURRR2pqQnlCekY4TUpI
      MzBNNS9SaVVwdWNpb0QybmdCekhRcFdEbGdJQ1lBaUVBCmxTOU9CQjlkb3N3KzdTR2xsazlSTDl3
      WkRWY044S0d4aDRlUGR1VGlJMHc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXB1Z0F3SUJBZ0lVWXA5SVdUQ3dzUUlnVTVE
      UUplejN2SnhhZFZBd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4T0RB
      ek5UVXdNRm9YRFRJek1EZ3hPREEwTURBd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdO
      VkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4
      SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1N
      RWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VI
      QTBJQUJEbkttdVFkMC80Mml0VkcKMlpiSUE2L0JSV1JBOXYzZWFLeXdQcUYxNFhYQWJNODhHNVoz
      R0R6a0VDdFQ3b1lEN1NxZnI0MW81TDlRaW5uNQpOWGVSWmphamdnRWFNSUlCRmpBT0JnTlZIUThC
      QWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVSWpoMzF5Nks2ZGxV
      bDhYYnoxaFBTb01VWHFvd0h3WURWUjBqQkJnd0ZvQVVPT2x1KzNRdUNZSVYKdVJkTDMrSi9hMWxk
      Q2xzd0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXROemRpWXpVME9XUTROQzE0Y21ocwpiVENC
      andZSUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlM
      Q0poClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJ
      aXdpYUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lh
      R1l1Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUF0N005Rlpw
      L09peGtJS1dNSWtZQkdkUzE2ZHVpYUtlS2ZPCjZ4TzB4NFYrQWlCOXZ6YVpFeWx4Rk96eG1pVEw3
      NlRwNjN2ZmFhYXkvZnhyb3Mvazhhd0V5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4K
      BFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dB
      d0lCQWdJVVJXWFpzd2pNVDhnU2FwR09zeFh5NkVuZVBvc3dDZ1lJS29aSXpqMEVBd0l3ClhERUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUI0WApEVEl5TURneE9EQXpOVFV5TWxvWERUSTFNRFl3TnpBek5UVXlNbG93WERFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRVVneGlEWkljLzVDeFZw
      MEE0bGlURlBETW5FYmFYNXgrWTVUVlY2NUZpdFpNTklmK0RmZHhuSXZLCjB1Y015ZmxyVEJQOHlW
      bk5XZm9mQXZJSHNGczlPS05DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFm
      OEVCQU1DQWFZd0hRWURWUjBPQkJZRUZEanBidnQwTGdtQ0Zia1hTOS9pZjJ0WlhRcGJNQW9HQ0Nx
      RwpTTTQ5QkFNQ0EwZ0FNRVVDSURRR2pqQnlCekY4TUpIMzBNNS9SaVVwdWNpb0QybmdCekhRcFdE
      bGdJQ1lBaUVBCmxTOU9CQjlkb3N3KzdTR2xsazlSTDl3WkRWY044S0d4aDRlUGR1VGlJMHc9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAES
      AggAGhESDwoLYXVkaXRvcjJNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIG
      CAESAggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAES
      AggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGlj
      eRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhAS
      Bgj/////DxoGQWRtaW5zGkoKEE9yZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVy
      LW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5z
      Gg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
