apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a4bad08484d15460788deef3b35cce0b-1271918739.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaINiBDnVApsn/Ssoe80o98ecOEsBLakf9YBpzQf9hhLLWEtZcCtNcCtBcCngKWggBEAEaBgiz
      qOSXBiIKc3lzY2hhbm5lbCpANTRjYjkxMGI4OGRmODA1MzMwZTE1OGM4OWJlMmY2M2I3YjE2Mjg2
      Njk3NWFlMTMzZjcyNmQyODVjYWJkMjNjNhIaEhgMKt4qRlNPBYWSy2JTk4r2HUTzg2LQGasS01sK
      0FsSzVsSmyoKB09yZGVyZXISjyoSihYKCm9yZGVyZXJNU1AS+xUalxQKA01TUBKPFBKEFBKBFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVVcrSDVBWTZZY0dtQnlZUjZNSjJMbmJBL2FqVXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRReE5URTJNREZhRncweU5UQTJNRE14TlRFMk1ERmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVN0ZzZIMTMwcDVHVE5zSWpVZGpLWDVW
      MiswTi9sUEpyZXQvTStUNkdURUpwOVN5c0xneHk3NFIxMnhqNFhkCmZCU05DOTRZSHYxOHhka2s3
      WHNNYktJMW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVL0FSRm5JMlJOOWtJNzBWc2JCa0p0RFVPVGNvd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdOcGN6NGJuMVhOZkRmbUU5TzBBc2FTSzJjWGZycEtrc0haZ3MzUmtVQXNnQ0lH
      ZmhjZ2hGCjd4ZFhIaEtVRmFncUI3eER2M043b0UwU0duV2YyeVcrbHBpVwotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKSCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMVRDQ0FueWdB
      d0lCQWdJVVNUeFRhUGNYSEoyem8rak9OV0kvSXZNc0Ura3dDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TVRReE5URTRNREJhRncweU16QTRNVFF4TlRJek1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJI
      SkwvU2loOWRYOWwxM211OHBDWnpBUEFyUkh6a3Z5aEc2c3U2ZkFOMktTCnYwZ3dZL0xDbFg1YXph
      eGdLUkltdmpOanJaYm42aWpHL0U2amNGckhJQWlqZ2dFUU1JSUJEREFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV3VDdWaHRCYW15UXFFcmNiaS9Z
      dApRbVoyLzU0d0h3WURWUjBqQkJnd0ZvQVUvQVJGbkkyUk45a0k3MFZzYkJrSnREVU9UY293SkFZ
      RFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROMkkyWXprNVpqWmtOQzF1ZERWNmJEQ0JoUVlJS2dN
      RUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYlds
      dUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdYYUlhZ0tVc2pKbDkKRjlpZHR3M2N5SU85YzFi
      eHBXUDlKUHBwNTlIRVZYVUNJRGZWU3ZNVDRKQ1V0RFRjOEc2dkNQaUh2bE94S2IrNAo0K0k3ODc3
      dUJZS3EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVVytINUFZNlljR21CeVlS
      Nk1KMkxuYkEvYWpVd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVFF4TlRF
      Mk1ERmFGdzB5TlRBMk1ETXhOVEUyTURGYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEps
      Y2pFWApNQlVHQTFVRUF3d09ZMkV1YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DCkFBU3RnNkgxMzBwNUdUTnNJalVkaktYNVYyKzBOL2xQSnJldC9NK1Q2R1RF
      SnA5U3lzTGd4eTc0UjEyeGo0WGQKZkJTTkM5NFlIdjE4eGRrazdYc01iS0kxbzBJd1FEQVBCZ05W
      SFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVUvQVJG
      bkkyUk45a0k3MFZzYkJrSnREVU9UY293Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ05wY3o0Ym4x
      WE5mRGZtRTlPMEFzYVNLMmNYZnJwS2tzSFpnczNSa1VBc2dDSUdmaGNnaEYKN3hkWEhoS1VGYWdx
      Qjd4RHYzTjdvRTBTR25XZjJ5VytscGlXCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyIz
      CgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zIjQKBkFk
      bWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMa
      IgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoC
      MnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRp
      ZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIRErcRCghldGNkcmFm
      dBKqEQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQzhqQ0NBcG1nQXdJQkFnSVVZdWtKWXUxcHZSS1ZrV1k2cjR1WWhQOUZ4bWN3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFR
      RERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1UUXhOVEU0TURCYUZ3MHlNekE0TVRR
      eE5USXpNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0
      eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdW
      eVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29a
      SXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWpBRS9BMEZLcUdSODdRaS8raEduZnlaSitHZ0Vtd01O
      NzBpcwoxNkVMOVZHbnI4VFdQTkMweDlQbGFLOWd0WWtWOSs0KzRIS2swaFFYUmIyZWduend4Nk9D
      QVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNE
      QVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVUFvQ1U0MTVw
      azJnL00ycVo4SmRmelBNWFBMMHdId1lEVlIwagpCQmd3Rm9BVS9BUkZuSTJSTjlrSTcwVnNiQmtK
      dERVT1Rjb3dPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5
      WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYw
      ZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxF
      SWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxj
      aUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQXlqS3NkSko4cTlsbVc3bTNjWktzVWFqOTZP
      d2x2QWRSamIwL3cKSGlWTGp3SWdMeUpreUlSazBZQnhzRDFFQzArVk0yZ0hRcFR4dW1lOTJNcm9I
      Q0FjNHVRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVVl1a0pZdTFwdlJLVmtXWTZyNHVZaFA5RnhtY3dD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURW
      UVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRReE5URTRNREJhRncweU16QTRN
      VFF4TlRJek1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRN
      QzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXla
      R1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApL
      b1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFakFFL0EwRktxR1I4N1FpLytoR25meVpKK0dnRW13
      TU43MGlzCjE2RUw5VkducjhUV1BOQzB4OVBsYUs5Z3RZa1Y5KzQrNEhLazBoUVhSYjJlZ256d3g2
      T0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJR
      Y0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVQW9DVTQx
      NXBrMmcvTTJxWjhKZGZ6UE1YUEwwd0h3WURWUjBqCkJCZ3dGb0FVL0FSRm5JMlJOOWtJNzBWc2JC
      a0p0RFVPVGNvd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dt
      OXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0lt
      RjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRF
      bEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhK
      bGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBeWpLc2RKSjhxOWxtVzdtM2NaS3NVYWo5
      Nk93bHZBZFJqYjAvdwpIaVZMandJZ0x5Smt5SVJrMFlCeHNEMUVDMCtWTTJnSFFwVHh1bWU5Mk1y
      b0hDQWM0dVE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAga
      BkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcS
      DQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlu
      cyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMS7y4K
      C0NvbnNvcnRpdW1zEt8uEpQuChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL1LRLMFgoLYXVk
      aXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVTS0VhczI4dURMWGhvTUUvUW8xUTFG
      NkFUTnN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hOREUxTVRjeE5s
      b1hEVEkxTURZd016RTFNVGN4Tmxvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUVTaEVZS2JBUDJhWGNzby9zbk1BbXlmd1ozRHFMQmwrOWlSdnc5WlJhVHQv
      YkhLOXBYek9lWnIxVApZeFgrR3J3Rmd3WjhkdG9HcUNDME8yek8vYjNCcWFOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGSXJsc1F5
      T3VyOG12elo0TTBDcDFodzVZckNiTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lEU1VHQzlwNnFF
      MGk1bW5pbjY3N3V3SUFON2pLTFFRUzVjU0JYdC9mSUNzQWlCZApJVmtFVVdKSVd5cCtnMytFUzAx
      emU4cXhpQUZ3VXB2WDZxYlNxMThMMVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJVUFnc0pQTC9iMTND
      NFZDOGpTamtEbDRFdU1VOHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURn
      eE5ERTFNVGt3TUZvWERUSXpNRGd4TkRFMU1qUXdNRm93ZWpFTE1Ba0dBMVVFQmhNQ1EwZ3hHakFZ
      CkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdoQmRXUnBkRzl5
      TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRFYk1Ca0dBMVVF
      QXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVHbFVCejJHSG1tbWQ1enMyCjNIMlErRWNCNm1wUHdKMFdSODNPOHU2MjYzR1FGMWpT
      YWgvTnVOSkhNSDNpSlFnSkQ2M25OaFU1UTZ1ejVNYjEKbUZadUlLT0NBUm93Z2dFV01BNEdBMVVk
      RHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJSczV1TXFyNFVG
      WG5WNlBicUo5cE4xblM3c2FEQWZCZ05WSFNNRUdEQVdnQlNLNWJFTWpycS9KcjgyCmVETkFxZFlj
      T1dLd216QWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAyWkdZNVlqUTBPR1JpTFhGMGJtTm0K
      TUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFa
      U0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWVhWa2FYUnZj
      akVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5TVMxdVpYUWlM
      Q0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFPTFpT
      SVFrd1Izamt0NUZkaFQxVEZvNWVNMzBaTEUvSDRoRApWaDNEK2R6MkFpQUJtUkl3RnBmNXJPOUhI
      SlpPZXdPTm1nRFZCUzhEeEF1bVVyWlBZOHpMVUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      CkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQit6Q0NB
      YUtnQXdJQkFnSVVTS0VhczI4dURMWGhvTUUvUW8xUTFGNkFUTnN3Q2dZSUtvWkl6ajBFQXdJdwpY
      REVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hOREUxTVRjeE5sb1hEVEkxTURZd016RTFNVGN4Tmxvd1hE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVTaEVZS2JBUDJh
      WGNzby9zbk1BbXlmd1ozRHFMQmwrOWlSdnc5WlJhVHQvYkhLOXBYek9lWnIxVApZeFgrR3J3Rmd3
      WjhkdG9HcUNDME8yek8vYjNCcWFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhR
      OEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGSXJsc1F5T3VyOG12elo0TTBDcDFodzVZckNiTUFv
      R0NDcUcKU000OUJBTUNBMGNBTUVRQ0lEU1VHQzlwNnFFMGk1bW5pbjY3N3V3SUFON2pLTFFRUzVj
      U0JYdC9mSUNzQWlCZApJVmtFVVdKSVd5cCtnMytFUzAxemU4cXhpQUZ3VXB2WDZxYlNxMThMMVE9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYI
      ARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgII
      ABoREg8KC2F1ZGl0b3IxTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMqBkFkbWlucxLIFgoLYXVkaXRvcjJNU1ASuBYa
      0BQKA01TUBLIFBK9FBK6FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQi9UQ0NBYUtnQXdJQkFnSVVFWlpSY0xpM1lleDh4ZUMzanV4TUl5Wnh2a2N3Q2dZSUtv
      Wkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hOREUxTVRnek5Gb1hEVEkxTURZd016
      RTFNVGd6TkZvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFn
      QUVOcEtRd2JUWjMxZXJMSkMyK0gxRFExKzh2YlRFS2xmNU8ya0pBM0E5Z1g1TWFCeklPTDZ6UzB2
      RApiK2RSMmEyT2N6SFhjRG1WVWNjOFZqWFZuN3ZXMmFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdF
      Qi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGTTR0ODV4OTFpZHl2VHpybG43
      RHBlcHFnaStxTUFvR0NDcUcKU000OUJBTUNBMGtBTUVZQ0lRQytkMU1pT2c2T1FwYW5xZEgvZnRt
      QWczamJhVlkrV1JIaE5FSnFpWGNzNUFJaApBSkV1UEFvTStoZk1HNkg1cEdvbXFJeWJhc1FtTEN3
      dDcyVnV4T09tUVE5QgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwcWdBd0lCQWdJVUdDODJLeTI3M21uOVFtK3lobW1Hd2lJ
      THNTSXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpF
      WU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE5ERTFNakV3TUZv
      WERUSXpNRGd4TkRFMU1qWXdNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFaCkJnTlZCQWNURWpV
      eExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2Y2pJeEh6QU0KQmdO
      VkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05WQkFNTUVrRmtiV2x1
      UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSzlC
      UThOR2NxQUJVdThUCmdIbHV6L0l0T25BWnNMV2owM05WWTcrRC9iOUE0dFJabjEwdVhQekphMmJX
      VzUyRmFHOTI4YTNaRFNPTFBnb3gKNGM1dDk3S2pnZ0VaTUlJQkZUQU9CZ05WSFE4QkFmOEVCQU1D
      QjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVVVNQmlQdzZwTWV3cnNxTlFzWU9t
      M3JEeEZvd3dId1lEVlIwakJCZ3dGb0FVemkzem5IM1dKM0s5ClBPdVdmc09sNm1xQ0w2b3dJd1lE
      VlIwUkJCd3dHb0lZWTJFdGRHOXZiSE10T0RjMlpqWTBaRGc0TFhOM04yMTMKTUlHUEJnZ3FBd1FG
      QmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1GawpiV2x1
      SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWVhWa2FYUnZjaklpTENKb1ppNUZi
      bkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5TWkxdVpYUWlMQ0pvWmk1VWVYQmxJ
      am9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ2ZieFdNZ21wd1drSENPNWFo
      Mk9hQ3NKWm01UTlkRDdSUlMragp6c2xuSkdzQ0lEL1paRzFUeC9NUjVjUTI4QXdUWW01K0NCNEpZ
      enhXMWNlYXZ0b015TlRPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1
      NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVUVaWlJj
      TGkzWWV4OHhlQzNqdXhNSXlaeHZrY3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURW
      UVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApE
      VEl5TURneE5ERTFNVGd6TkZvWERUSTFNRFl3TXpFMU1UZ3pORm93WERFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZR
      UUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3
      WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRU5wS1F3YlRaMzFlckxKQzIrSDFEUTErOHZi
      VEVLbGY1TzJrSkEzQTlnWDVNYUJ6SU9MNnpTMHZECmIrZFIyYTJPY3pIWGNEbVZVY2M4VmpYVm43
      dlcyYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hR
      WURWUjBPQkJZRUZNNHQ4NXg5MWlkeXZUenJsbjdEcGVwcWdpK3FNQW9HQ0NxRwpTTTQ5QkFNQ0Ew
      a0FNRVlDSVFDK2QxTWlPZzZPUXBhbnFkSC9mdG1BZzNqYmFWWStXUkhoTkVKcWlYY3M1QUloCkFK
      RXVQQW9NK2hmTUc2SDVwR29tcUl5YmFzUW1MQ3d0NzJWdXhPT21RUTlCCi0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAaDxINCgth
      dWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxINCgthdWRp
      dG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoREg8KC2F1ZGl0b3Iy
      TVNQEAEaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZB
      ZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyIt
      CgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxpKChBPcmRlcmVyQWRkcmVzc2VzEjYSGwoZb3JkZXJlcjEub3JkZXJlci1u
      ZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRW
      Ml8wEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZ
      QmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucyIiCgdSZWFkZXJzEhcS
      DQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlu
      cyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoA
      CgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
