apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-cacerts-job
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: orderer
      component_name: orderer-net
      namespace: orderer-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      authpath: devorderer-net-auth
      secretcryptoprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/orderer-net/ca/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.orderer-net
