apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://ae7339fc62cc9405db5036312ef6a0e5-1510386643.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIAcXrNLBIprzt8BeO9jfH8BpRB7SaTXZfu3qBwqB862kEuJcCt9cCtxcCngKWggBEAEaBgi/
      temXBiIKc3lzY2hhbm5lbCpAOWJlZDRhNjRjNjYwMzJiNjc0MmEzZTM5M2QxZTI1MjI3NmIyZGZl
      NWVjMmEwZGRiNGI0NTY5NTVmMDMwNTc4NBIaEhjESZAmpFaHVIMzCev7Nh/aLZ6d8k1sggsS31sK
      3FsS2VsS7y4KC0NvbnNvcnRpdW1zEt8uEpQuChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL1
      LRLIFgoLYXVkaXRvcjFNU1ASuBYa0BQKA01TUBLIFBK9FBK6FAoLYXVkaXRvcjFNU1AS7QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVkU1lFdCtEWTNOWlJp
      RFdkZFZyZi96L1p3T1l3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJk
      V1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hO
      VEV6TkRRME9Gb1hEVEkxTURZd05ERXpORFEwT0Zvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpC
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpq
      MENBUVlJS29aSXpqMEQKQVFjRFFnQUVIVVR2T0hjTzRQeERsSTN6SUY3eFM1ZmhBMDRXQnR3MGxM
      cTdMU2hPblpmNDhBV3BLL1pQSnVFRgpRRkE5R1I0U1lyMlRSNGp4NUcvVUZYRE9EUVVGVktOQ01F
      QXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JC
      WUVGQSt2Vk5EbXB0SG1SMSt4VS8ySjdrN240NXZyTUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lG
      Z1dHTWVOb2hFS3l1U0dXSTNncmRUSU5ySURvNzR0ZnhhS1I2dWpHSHE4QWlFQQp3QkZybkFqc2Z0
      QmJLOVZxRTd3WXVCUGNGMU5VMTVyamlNaHhSeHZ2RE9BPQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOFRDQ0FwbWdBd0lCQWdJVUpD
      WksrR1B3dUw1eWtlRk5qUzVjbFhWUnRWc3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJo
      TUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0
      WApEVEl5TURneE5URXpOVEV3TUZvWERUSXpNRGd4TlRFek5UWXdNRm93ZWpFTE1Ba0dBMVVFQmhN
      Q1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdo
      QmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRF
      Yk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBEQVFjRFFnQUVJSXJDK01HYzlDWmNucVl3CnhZeEdlYU1mZlNmMi9oNUZZY0FqVmhU
      WFFPKzdTVzdsTjdCckhRaGp0RDJSczQ1cEJ0YU5wWmlZU1gzZ1JHd3kKOEhGYks2T0NBUmt3Z2dF
      Vk1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJS
      MFI1WmNUWE5IaFRGRjFNMlhFZnpvYWd0a3NUQWZCZ05WSFNNRUdEQVdnQlFQcjFUUTVxYlI1a2Rm
      CnNWUDlpZTVPNStPYjZ6QWpCZ05WSFJFRUhEQWFnaGhqWVMxMGIyOXNjeTFpT1dOaVltWmlaR1F0
      TjJkbmRtTXcKZ1k4R0NDb0RCQVVHQndnQkJJR0NleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFp
      T2lKMGNuVmxJaXdpWVdSdAphVzRpT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpo
      ZFdScGRHOXlNU0lzSW1obUxrVnVjbTlzCmJHMWxiblJKUkNJNklrRmtiV2x1UUdGMVpHbDBiM0l4
      TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkdBREJE
      QWg5c0FKVi9WUmJKMVZtVmVaeUJrazhrTGk2M0YrdDRZeDN2ZERNTwpJakFVQWlCemlEUmtvOGx4
      U2lObGpHOHdLbUJXY051NWdZV0IxYWxhMDhFSWYwSm5PZz09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlC
      L0RDQ0FhS2dBd0lCQWdJVWRTWUV0K0RZM05aUmlEV2RkVnJmL3ovWndPWXdDZ1lJS29aSXpqMEVB
      d0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZ
      WFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE5URXpORFEwT0ZvWERUSTFNRFl3TkRFek5EUTBP
      Rm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZ
      WFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUhVVHZP
      SGNPNFB4RGxJM3pJRjd4UzVmaEEwNFdCdHcwbExxN0xTaE9uWmY0OEFXcEsvWlBKdUVGClFGQTlH
      UjRTWXIyVFI0ang1Ry9VRlhET0RRVUZWS05DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0Jn
      TlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZBK3ZWTkRtcHRIbVIxK3hVLzJKN2s3bjQ1
      dnJNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUZnV0dNZU5vaEVLeXVTR1dJM2dyZFRJTnJJRG83
      NHRmeGFLUjZ1akdIcThBaUVBCndCRnJuQWpzZnRCYks5VnFFN3dZdUJQY0YxTlUxNXJqaU1oeFJ4
      dnZET0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgB
      Eh0SCBIGCAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikS
      HwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsS
      CBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9yMk1T
      UBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVVA3eHdSMmx2U2l6VmlmaU9Oemo2VExUdTZHNHdD
      Z1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdB
      MVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE5URXpORFl4TUZvWERUSTFN
      RFl3TkRFek5EWXhNRm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdB
      MVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApB
      UWNEUWdBRTd0b1gySXNYVjdIQnhuNlk5VnNtdTRhVCs4SWRUYnpzRDNtamlpQTFXeWN2eDk2eVJV
      QWxaODVECkZCQU0yRHhTb29uVlhaZGJDYWF5bVFkYWRGMVJjS05DTUVBd0R3WURWUjBUQVFIL0JB
      VXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZEVzBiQmdBckp0Ry84
      UHNnQWk0dEJqTUxvRHdNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFEU2FzcFNwc0lVVlh5SytL
      TmhxTW9qYjVlNW05QndKSmpSRkZzWDlqWjcyQUloCkFJa1hTaWRDdTBuQVVQUVZMTEtmYVBWK3o5
      dDZHYncrbU1mdFJIeUtDM2VFCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQXB1Z0F3SUJBZ0lVWEZSTkk0NDJza3prRUs1OURC
      ZFBSaFVzaVJNd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRH
      OXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TlRFME16
      UXdNRm9YRFRJek1EZ3hOVEUwTXprd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdOVkJB
      Y1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4SHpB
      TQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1NRWtG
      a2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJ
      QUJJaFpVS1ArUno2WTdlV1EKVkg3Z2U4UE14Z09BNExIM3B1OFl6a1RBSXpjaVdMdi9xekRZTlFT
      OVdwWFNpb3Vra0FrU0tBR3RnSWM0aEttcwpvb09FL1UramdnRWFNSUlCRmpBT0JnTlZIUThCQWY4
      RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVNEpPVytqMTk1eUs3N0Qr
      WTBMN3RGSUYvbzJzd0h3WURWUjBqQkJnd0ZvQVVOYlJzR0FDc20wYi8Kdyt5QUNMaTBHTXd1Z1BB
      d0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXRPRFUxTldabVlqaGlOaTB5ZERjMQpPVENCandZ
      SUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlMQ0po
      ClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJaXdp
      YUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lhR1l1
      Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEOUtobGdTTGJ3
      Mm1jdXA4OEMzR1Z4Y3l0eHVBaktnWmNMCkhkVTRJWGpMUXdJZ01GU2FZL3NoUzR4YVp5bWI3NmJs
      TTM2YnBjd2lCNDFXVUhPKzB2a2VQNjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNI
      QTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lC
      QWdJVVA3eHdSMmx2U2l6VmlmaU9Oemo2VExUdTZHNHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRi
      bVYwTUI0WApEVEl5TURneE5URXpORFl4TUZvWERUSTFNRFl3TkRFek5EWXhNRm93WERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRi
      bVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRTd0b1gySXNYVjdIQnhuNlk5
      VnNtdTRhVCs4SWRUYnpzRDNtamlpQTFXeWN2eDk2eVJVQWxaODVECkZCQU0yRHhTb29uVlhaZGJD
      YWF5bVFkYWRGMVJjS05DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVC
      QU1DQWFZd0hRWURWUjBPQkJZRUZEVzBiQmdBckp0Ry84UHNnQWk0dEJqTUxvRHdNQW9HQ0NxRwpT
      TTQ5QkFNQ0Ewa0FNRVlDSVFEU2FzcFNwc0lVVlh5SytLTmhxTW9qYjVlNW05QndKSmpSRkZzWDlq
      WjcyQUloCkFJa1hTaWRDdTBuQVVQUVZMTEtmYVBWK3o5dDZHYncrbU1mdFJIeUtDM2VFCi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggBEgII
      ABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggAGhES
      DwoLYXVkaXRvcjJNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggAGg8S
      DQoLYXVkaXRvcjJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRIn
      EgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcv
      Q2hhbm5lbC9PcmRlcmVyL0FkbWlucxKnKgoHT3JkZXJlchKbKhKWFgoKb3JkZXJlck1TUBKHFhqj
      FAoDTVNQEpsUEpAUEo0UCgpvcmRlcmVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIrVENDQVo2Z0F3SUJBZ0lVTGxJcWFwejZGSVBUQVpGdG1oMTdJQ21SelBFd0NnWUlLb1pJ
      emowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVq
      WVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVFV4TXpRek16SmFGdzB5TlRBMk1EUXhNelF6
      TXpKYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05W
      QkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEpsY2pFWApNQlVHQTFVRUF3d09ZMkV1
      YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVCtJQTBv
      cU5jc0VvZTJqM0VuMVdjbUZQSFF4TEZBa3BKMjBkQjIwdWZvSlF6cTA0L2c1UnlDUk1PMzFtaXAK
      ZUd1ZmljcmlWc21uMEYvOGF6ZnpycUk2bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdB
      MVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVDZ201K2R1MG5MdmpYbXJjbzE5SlVRTWt4
      bVl3Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJaEFJZGh1WEpoYXlnczU2YWRMKzc3emVEOU5vckh6
      TkZCcFQzN0lKVENxNCtBQWlFQW1EMUwKamFlMVBjSTJHbmxUYU1yZ1BwQXBEQzBENE5NQmZSSGdL
      ZGdQMVI0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKWCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDMWpDQ0FueWdBd0lCQWdJVU1WS3RKWUNPeG96cDhrb0F1SjRsQUV3RDM2WXdD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURW
      UVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRVeE16VXdNREJhRncweU16QTRN
      VFV4TXpVMU1EQmFNR2d4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRN
      QzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmti
      V2x1TVJvd0dBWURWUVFEREJGQlpHMXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJJTk5COGdveW1lUlV2K0N6am91aGtXcTYybTNRYjl5MjdJZVQ3
      bnY1MTRBCkRWOUtXamllQ1Fadm5ELzJqNERRcGswU2FUM1RmenR3aWV2L3J3NElXSDJqZ2dFUU1J
      SUJEREFPQmdOVkhROEIKQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVtNlo4WDhMRUp0RGN6RU51VXI4Ugpmd01pVTJZd0h3WURWUjBqQkJnd0ZvQVVDZ201K2R1MG5M
      dmpYbXJjbzE5SlVRTWt4bVl3SkFZRFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROamMzWmprNVlq
      WmpaQzAyT1dwcU5UQ0JoUVlJS2dNRUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJt
      bDBJam9pZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlq
      b2lJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxD
      Sm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBUEtyMi9M
      bktiaGsKcmtBbFRoUlBybzF1b2FGSkZYZUJGY0ZMNHRQNFJwc2dBaUJUMGtidzVjMEdUNDdwcE5S
      a2FxYk9QR0Z4VDE1WgoyTVpEbGFqT2IyYk5wdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      Qg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0Fa
      NmdBd0lCQWdJVUxsSXFhcHo2RklQVEFaRnRtaDE3SUNtUnpQRXdDZ1lJS29aSXpqMEVBd0l3Cldq
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5
      dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21W
      eUxXNWxkREFlRncweQpNakE0TVRVeE16UXpNekphRncweU5UQTJNRFF4TXpRek16SmFNRm94Q3pB
      SkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1S
      dmJqRVFNQTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kx
      dVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVQrSUEwb3FOY3NFb2UyajNF
      bjFXY21GUEhReExGQWtwSjIwZEIyMHVmb0pRenEwNC9nNVJ5Q1JNTzMxbWlwCmVHdWZpY3JpVnNt
      bjBGLzhhemZ6cnFJNm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dR
      RUF3SUJwakFkQmdOVkhRNEVGZ1FVQ2dtNStkdTBuTHZqWG1yY28xOUpVUU1reG1Zd0NnWUlLb1pJ
      emowRQpBd0lEU1FBd1JnSWhBSWRodVhKaGF5Z3M1NmFkTCs3N3plRDlOb3JIek5GQnBUMzdJSlRD
      cTQrQUFpRUFtRDFMCmphZTFQY0kyR25sVGFNcmdQcEFwREMwRDROTUJmUkhnS2RnUDFSND0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAES
      AggAGg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAa
      DhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoK
      b3JkZXJlck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIM
      CgpvcmRlcmVyTVNQGgZBZG1pbnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAa
      BkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmlj
      dGlvbnMSCBoGQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa1BEK
      DUNvbnNlbnN1c1R5cGUSwhEStxEKCGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVyLW5l
      dBCKNxq6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVUQx
      U3BRNzkvdzhBWCsvM1g5YnQza2Nnejh1a3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncw
      eQpNakE0TVRVeE16VXdNREJhRncweU16QTRNVFV4TXpVMU1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtk
      Q01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5
      eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJ
      eExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFS1A0
      Y1pGRlBGT0c4Z2QrM0hmQ3d4T29pN3pPZkt2ZURvQW1UCkgvRmlZRjdZRDRuNzNDU1ZEYlZ0K3BZ
      SS9yc0NjKzJjU1BsRGp3akFzYldZeThib0RhT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJ
      RHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFI
      L0JBSXdBREFkQmdOVkhRNEVGZ1FVYzd0Z0o3NXE3dnFtSGtqUlBEUEIzRzZweEpNd0h3WURWUjBq
      CkJCZ3dGb0FVQ2dtNStkdTBuTHZqWG1yY28xOUpVUU1reG1Zd093WURWUjBSQkRRd01vSVViM0pr
      WlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1
      WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1
      WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJF
      QWlBWVl3N2huM2VMVjBwTWsxSnY1MjU2VWxXOXhPeXhFREl6ZE80dwpFMmNwMlFJZ2JnZHFtN0NY
      L1EzUFhld1dQUlA2dDc3NGl3Uzl3L3Nqb01sbHREVi9QYTQ9Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBtZ0F3SUJBZ0lV
      RDFTcFE3OS93OEFYKy8zWDlidDNrY2d6OHVrd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVF
      QmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3
      RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVG
      dzB5Ck1qQTRNVFV4TXpVd01EQmFGdzB5TXpBNE1UVXhNelUxTURCYU1HMHhDekFKQmdOVkJBWVRB
      a2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RC
      MDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnla
      WEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVL
      UDRjWkZGUEZPRzhnZCszSGZDd3hPb2k3ek9mS3ZlRG9BbVQKSC9GaVlGN1lENG43M0NTVkRiVnQr
      cFlJL3JzQ2MrMmNTUGxEandqQXNiV1l5OGJvRGFPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVB
      d0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRB
      UUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVjN3RnSjc1cTd2cW1Ia2pSUERQQjNHNnB4Sk13SHdZRFZS
      MGoKQkJnd0ZvQVVDZ201K2R1MG5MdmpYbXJjbzE5SlVRTWt4bVl3T3dZRFZSMFJCRFF3TW9JVWIz
      SmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allX
      d3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFX
      OXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNp
      MXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSEFE
      QkVBaUFZWXc3aG4zZUxWMHBNazFKdjUyNTZVbFc5eE95eEVESXpkTzR3CkUyY3AyUUlnYmdkcW03
      Q1gvUTNQWGV3V1BSUDZ0Nzc0aXdTOXcvc2pvTWxsdERWL1BhND0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICACBoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZB
      ZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2
      GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpK
      ChBPcmRlcmVyQWRkcmVzc2VzEjYSGwoZb3JkZXJlcjEub3JkZXJlci1uZXQ6NzA1MBoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucyIi
      CgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1Jl
      YWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      Gg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
