apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIC+F5+VUDo2oBB1yc8kNFunbv2kjbYtPRGvNsLhblSfKEt5cCttcCthcCngKWggBEAEaBgiB
      q/iXBiIKc3lzY2hhbm5lbCpAMjZjMGYzNmIxM2MzODNiOWVjYjI2Y2ExMzg0ZTU3NGIwOTY1YWZk
      YmVhMWJjNTRmM2Q2NjE0YzlhMzM1OTA5YhIaEhjU7zQlwZGiaBgPYDHZ2wYAufZGvgesFSYS21sK
      2FsS1VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVUJhR05McTR3dG5xQTUxbEUxeS9WMnpaRDhtRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRneE1ESXdNemhhRncweU5UQTJNRGN4TURJd016aGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNnbTFqQ3pRaEY2cEZvTkhsaW93VE0y
      U1NER0NIRWJ4Y285QUJYUHh0aWlab3hkN0dhOW9oT3E3M1NnRDNiClhtZEwvYTVlVEFvK3kyNVpZ
      T3dNcysyWm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVRGxiR0oveDlsOC9vLytxMUllVW0veWxIMTRnd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWhBTjRjZEdZSjVTMmdQZm9va00rNnJzbHBzVkRiU3M1NnRHdC81ZU5vNG5tR0Fp
      QXladkdMClNja1huSDVoNGpxZ0Z0R1Mvd2dGU1hENWFiVHlTSFpHQmpraHp3PT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFUQ0NB
      bnVnQXdJQkFnSVVVRklaRUNpR1ZpRTNFVm5rcWxxMGhhYVJ3bTh3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UZ3hNREkyTURCYUZ3MHlNekE0TVRneE1ETXhNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCRVJGdXE0R2hZM29OcW9QMzEvWlBjTjZPd01tVjN1RlRnajhEdkk4VS9OZApnSnNwUFkzeXEz
      czdMKzI4UTNHYVhoSnh2Q3l1YnpXM0dEVHJ2Vmhzbml1amdnRVBNSUlCQ3pBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVak0rZDVLUUpMcXk4dXc3
      L01tUHIKQ3ArNWk1MHdId1lEVlIwakJCZ3dGb0FVRGxiR0oveDlsOC9vLytxMUllVW0veWxIMTRn
      d0l3WURWUjBSQkJ3dwpHb0lZWTJFdGRHOXZiSE10WXpSa1lqZzNOamRpTFRsdVpqWXlNSUdGQmdn
      cUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJcwpJbWhtTGxSNWNHVWlPaUpoWkcx
      cGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBaktoQ1VxYkc4OEpxCmNKaDVHZlRrU29E
      MDF1QlhZTWJyMDBZU08wWFQyelVDSUNtMXVzc0FJS2VBaXFnRGdrTXlTR1htMElJcWZ6Zm8KYS9r
      TlZyczl6SzNxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUJhR05McTR3dG5x
      QTUxbEUxeS9WMnpaRDhtRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRn
      eE1ESXdNemhhRncweU5UQTJNRGN4TURJd016aGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVNnbTFqQ3pRaEY2cEZvTkhsaW93VE0yU1NER0NIRWJ4Y285QUJY
      UHh0aWlab3hkN0dhOW9oT3E3M1NnRDNiClhtZEwvYTVlVEFvK3kyNVpZT3dNcysyWm8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      RGxiR0oveDlsOC9vLytxMUllVW0veWxIMTRnd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBTjRj
      ZEdZSjVTMmdQZm9va00rNnJzbHBzVkRiU3M1NnRHdC81ZU5vNG5tR0FpQXladkdMClNja1huSDVo
      NGpxZ0Z0R1Mvd2dGU1hENWFiVHlTSFpHQmpraHp3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRlcmVyTVNQEAEa
      BkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVv
      dXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENh
      cGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa1BEKDUNvbnNlbnN1c1R5cGUSwhEStxEK
      CGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVyLW5ldBCKNxq6CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJVVZtdlhtMEtYNHhQMWRPZWJQcU5uNS8z
      WmlOQXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJj
      d0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRneE1ESTJNREJhRncw
      eU16QTRNVGd4TURNeE1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFz
      VEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3
      RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVW5WTTg3Vkorc0E4VG9OTUJ2Mjh3T0Vo
      K2ZKalNjV0R1c29xCmZ1VFVoQmlqU0c3RTZGK2V4dURQWC9xUUNuUnhQb2tSZ0FNWldDbU81Y1ZO
      RWlRV1lxT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dy
      QmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FV
      UkkvK0thcVg3UFJhcTA2K2o0RHBMdENmazFRd0h3WURWUjBqCkJCZ3dGb0FVRGxiR0oveDlsOC9v
      LytxMUllVW0veWxIMTRnd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dC
      QkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2li
      M0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTBQdDhMMWRNcnlaQThZb2hL
      ejhJaWg0aGhZOHp4d01tRjl5dAp5TERCcGZrQ0lHNVhoUUpiZXh6SUk2eVZXZFErU2lDYmFsVUo2
      a3o1NFpTTlFsak5tWmN3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVVm12WG0wS1g0eFAxZE9lYlBxTm41
      LzNaaU5Bd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVGd4TURJMk1EQmFG
      dzB5TXpBNE1UZ3hNRE14TURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFN
      UzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpC
      QXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1G
      a3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVVblZNODdWSitzQThUb05NQnYyOHdP
      RWgrZkpqU2NXRHVzb3EKZnVUVWhCaWpTRzdFNkYrZXh1RFBYL3FRQ25SeFBva1JnQU1aV0NtTzVj
      Vk5FaVFXWXFPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJn
      Z3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVSSS8rS2FxWDdQUmFxMDYrajREcEx0Q2ZrMVF3SHdZRFZSMGoKQkJnd0ZvQVVEbGJHSi94OWw4
      L28vK3ExSWVVbS95bEgxNGd3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNp
      MXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3
      Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpv
      aWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBMFB0OEwxZE1yeVpBOFlv
      aEt6OElpaDRoaFk4enh3TW1GOXl0CnlMREJwZmtDSUc1WGhRSmJleHpJSTZ5VldkUStTaUNiYWxV
      SjZrejU0WlNOUWxqTm1aY3cKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFk
      bWlucxLvLgoLQ29uc29ydGl1bXMS3y4SlC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvUt
      EsgWCgthdWRpdG9yMU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dBd0lCQWdJVVdzcVdvOUw2Yk1wanMy
      SDNxaDVPbVhWMlVjOHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE9E
      RXdNakUwTlZvWERUSTFNRFl3TnpFd01qRTBOVm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRVFyc0diZTNVVFQ3elkxdnRmNlhIeTBXLzFCS0tLVE9GZVRl
      RVMxZTJlT0NGWW5Gcit6ZFYyMWhwCnJoWlVRSjVsL1hnN0NQZHpoRTc3SFpSQk1jRWtsS05DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZFU0gxRkJWcjVwS3JwWXlNLytPdUkraVFLTGlNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUJE
      bk51dW1KU2toTU4yN0VqbDBVNm1EQ3V6VEFhWEUvVU9hekVDeWZLZ2ZBaUJrCmQwb1NKVEZoTll4
      VG5zTFlvb3l3RVRSdHVVSlhwWVpCNTlHVVEwVWNkdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBxZ0F3SUJBZ0lVSXpG
      NVhSY2kxV2VRRmRvM3d4M1B2OWtZbG1Zd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd4T0RFd01qY3dNRm9YRFRJek1EZ3hPREV3TXpJd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRUpWY0RrVkVGTEQvUkY4WFcKWWxFc1ZNWTJ0cm5pSk1mcjcwMEl4N1cy
      Rzg2eVVQa0tFdWNhTnJld3B2VE41dnFrcEdKNTFSbk4yUEF5S0k0awpVRUY4aTZPQ0FSb3dnZ0VX
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlR6
      YXV6UklUYWFOK1ppTmY2UGhxOGphdlJnOFRBZkJnTlZIU01FR0RBV2dCUkVoOVJRVmErYVNxNlcK
      TWpQL2pyaVBva0NpNGpBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDFOVGRtWW1ZM1lqWTJM
      WE56Y3pVMQpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqRWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      UzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdS
      QUlnYWx2SnoyWmtEUWE5OHYrOXlxNy92WCtCcU9BbmZqcTZ2NFBWCnkwUlZqcW9DSUVGMU14cUFv
      MzRyMmdmV3pEYVl2VDF1dDQ5RkpzY1FIVHozWTE4L2hIRFUKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIr
      ekNDQWFLZ0F3SUJBZ0lVV3NxV285TDZiTXBqczJIM3FoNU9tWFYyVWM4d0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd4T0RFd01qRTBOVm9YRFRJMU1EWXdOekV3TWpFME5W
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFUXJzR2Jl
      M1VUVDd6WTF2dGY2WEh5MFcvMUJLS0tUT0ZlVGVFUzFlMmVPQ0ZZbkZyK3pkVjIxaHAKcmhaVVFK
      NWwvWGc3Q1BkemhFNzdIWlJCTWNFa2xLTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkVTSDFGQlZyNXBLcnBZeU0vK091SStpUUtM
      aU1Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNJQkRuTnV1bUpTa2hNTjI3RWpsMFU2bURDdXpUQWFY
      RS9VT2F6RUN5ZktnZkFpQmsKZDBvU0pURmhOWXhUbnNMWW9veXdFVFJ0dVVKWHBZWkI1OUdVUTBV
      Y2R3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAES
      HRIIEgYIARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIf
      CAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAES
      GxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIvVENDQWFLZ0F3SUJBZ0lVRGpQNi9NR3pBdjRac0ZDR0ZmSXVtRjZiTm5Bd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4T0RFd01qSTFNVm9YRFRJMU1E
      WXdOekV3TWpJMU1Wb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFaStkRlNvbHg1SzVRZCtVQS9oeldhK3UvV2RJTTFNTXFYc3FIbU50bkJ5Q1VJR2tJMVEx
      d1FoaTEKNmM1VjdnRzN3bVJGQTRoTWxkMDE3alRYdkhXZmVhTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkJMOVhId2w5MTRnNjY2
      bzR6bjNsSHFBOW9EYU1Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUUNsV1BDQUNIcDY1YXprWms4
      bzBISmNIamZISG9xaS8vSXVKbmZFU0NmcER3SWgKQU03RkkrSHZTRlZmWjhYUFZ0RkMvZW9jVEd0
      TVNaelVrZmlCMFMzT1MrNysKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHVnQXdJQkFnSVVKYkNsRlJ1UWthWnA5MFVZSjA0
      WkdBSWRZL1V3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hPREV3TWpn
      d01Gb1hEVEl6TURneE9ERXdNek13TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      QkdSd3VaNzRnRlhobnF2Ngo2Z2o1YTBYd3VUYW52eGJZZWEwK0xheGdmTHNlY0dxK2o0dVI5UXRK
      dmNtYWpxUnZhYTBDRXpIeERaS05qZ0trClc5TjRUZUdqZ2dFYU1JSUJGakFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVVPQ0FaSGpLQ05iaUJqaWhm
      M3FoL2RqdVdVcFV3SHdZRFZSMGpCQmd3Rm9BVUV2MWNmQ1gzWGlEcgpycWpqT2ZlVWVvRDJnTm93
      SkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE56ZGlZelUwT1dRNE5DMWljamt5CmN6Q0Jqd1lJ
      S2dNRUJRWUhDQUVFZ1lKN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmgK
      WkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNkltRjFaR2wwYjNJeUlpd2lh
      R1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFXNUFZWFZrYVhSdmNqSXRibVYwSWl3aWFHWXVW
      SGx3WlNJNkltRmtiV2x1CkluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJRWZvQVJVNXFQL0Vx
      TFU0M3JiTWEyUU9ybHA4VVMyVlRxQjEKalAxRDEzZlFBaUEwWWF0R093ck16bURZNnlyQzBjQzBt
      L01sUm5wWHk4Wmg2Q0crY09oMHlRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvVENDQWFLZ0F3SUJB
      Z0lVRGpQNi9NR3pBdjRac0ZDR0ZmSXVtRjZiTm5Bd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd4T0RFd01qSTFNVm9YRFRJMU1EWXdOekV3TWpJMU1Wb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFaStkRlNvbHg1SzVRZCtVQS9o
      eldhK3UvV2RJTTFNTXFYc3FIbU50bkJ5Q1VJR2tJMVExd1FoaTEKNmM1VjdnRzN3bVJGQTRoTWxk
      MDE3alRYdkhXZmVhTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRkJMOVhId2w5MTRnNjY2bzR6bjNsSHFBOW9EYU1Bb0dDQ3FHClNN
      NDlCQU1DQTBrQU1FWUNJUUNsV1BDQUNIcDY1YXprWms4bzBISmNIamZISG9xaS8vSXVKbmZFU0Nm
      cER3SWgKQU03RkkrSHZTRlZmWjhYUFZ0RkMvZW9jVEd0TVNaelVrZmlCMFMzT1MrNysKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAa
      ERIPCgthdWRpdG9yMk1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAa
      DxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
