apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a7e9892a5136f4fa8b1cda6ba31b358b-1780904258.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIP1pf5JSCwC9WjuzAd9UexSMgxmH2iWolI2F7gMxHpgQEuZcCuNcCuBcCngKWggBEAEaBgj/
      0syXBiIKc3lzY2hhbm5lbCpAYjMyMzJkYzYzNzY0NzNhZmU5MjVlNDFhZjYyMGVkOTI1ZjViYzIw
      NWZmMjI1MWM0M2ZjOGIyNGJmNDYyZjdlORIaEhi8wucwMRjrs9NTiFIyIj1bwmPwpi6nFJ0S41sK
      4FsS3VsS8y4KC0NvbnNvcnRpdW1zEuMuEpguChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL5
      LRLMFgoLYXVkaXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVHOE1hYVdzbkI3UlBt
      cm1kQ1V3WExQNEh0bXN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJk
      V1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hN
      REF6TXpVME0xb1hEVEkxTURVek1EQXpNelUwTTFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpC
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpq
      MENBUVlJS29aSXpqMEQKQVFjRFFnQUV0bkVCQk1nd2padmp5YytTL2U4L3VrN29sUUY5YUlKcVRS
      RG5sQ2YzMk5lRU9qZTUxVEFkZGJiSgpVYkFBSVp3QVdlV1FCUVFuNDV2alNDRG9JSFBpZXFOQ01F
      QXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JC
      WUVGRGwxNExZRjlrVlpkOFZuU3VVL3J4MTh4Z1lMTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lE
      MlFybDVYZmpGUTFmb1lvdkQ4SXRTQVVMWThvSjJBMUpGMEVzQzk2SzNPQWlBSwpuUGZlcXdzWFpL
      dEdkWTJ3aGVGQURxTkRNeGp6ajlKQXRLRzJCY1Zyd1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiK+CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJVVd1
      TWhKNzFMTWl1Yi9uVzhQSnAycDdxQS92SXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJo
      TUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0
      WApEVEl5TURneE1EQXpNell3TUZvWERUSXpNRGd4TURBek5ERXdNRm93ZWpFTE1Ba0dBMVVFQmhN
      Q1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdo
      QmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRF
      Yk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBEQVFjRFFnQUUrYk5OOWluMkgzcExyQmhNCmFhNEM5dndyZGR5eHhXS0xxYzluRzZu
      WTJuNUlOQUk3aC9ZK1dTQzQvUjB4UVBpR1dIRUxEYnBjMVVGT285cjcKeDNlc2VxT0NBUm93Z2dF
      V01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJR
      ZUtOZHZ2Vnd3OGJ3eXBua1lLeFVQVFZVTXJUQWZCZ05WSFNNRUdEQVdnQlE1ZGVDMkJmWkZXWGZG
      ClowcmxQNjhkZk1ZR0N6QWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzT1dNME4yWTJZMlE0
      TFdOcWFITnUKTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWww
      SWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      WVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5
      TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURTQUF3
      UlFJaEFNRFNjRmVlc0dSSHZWbE5ZNGR0L3FWL3pkNmJHdXpRdUhyUwo3ZnhqVlhFTEFpQVdiTCtW
      OG1WOGYybmd1MUUyZkhvMmk0bERYejF3RXJWVlYzQkdrME14M3c9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQit6Q0NBYUtnQXdJQkFnSVVHOE1hYVdzbkI3UlBtcm1kQ1V3WExQNEh0bXN3Q2dZSUtvWkl6
      ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZ
      MkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hNREF6TXpVME0xb1hEVEkxTURVek1EQXpN
      elUwTTFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZ
      MkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUV0
      bkVCQk1nd2padmp5YytTL2U4L3VrN29sUUY5YUlKcVRSRG5sQ2YzMk5lRU9qZTUxVEFkZGJiSgpV
      YkFBSVp3QVdlV1FCUVFuNDV2alNDRG9JSFBpZXFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96
      QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGRGwxNExZRjlrVlpkOFZuU3VVL3J4
      MTh4Z1lMTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lEMlFybDVYZmpGUTFmb1lvdkQ4SXRTQVVM
      WThvSjJBMUpGMEVzQzk2SzNPQWlBSwpuUGZlcXdzWFpLdEdkWTJ3aGVGQURxTkRNeGp6ajlKQXRL
      RzJCY1Zyd1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjUKBkFkbWlucxIr
      EiEIARIdEggSBggBEgIIABoREg8KC2F1ZGl0b3IxTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVu
      dBIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8I
      ARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMqBkFkbWlucxLMFgoLYXVkaXRv
      cjJNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVkeFRDWDVTdHdHTE9BT2RwOUo3WWRSK1kx
      bHd3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlN
      QllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hNREF6TXpjd01Wb1hE
      VEkxTURVek1EQXpNemN3TVZvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlN
      QllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpq
      MEQKQVFjRFFnQUVocCsxMlVTNmpQUDhGalJ3NnVxTUJjU0FiSExZZTZwZG9UcU5sWUNEZjZpdldW
      c3h3b2RNNWlSNgpSQklzcU14S3VmaWdqYU5VdkJ6cng0bW0ybGJlTnFOQ01FQXdEd1lEVlIwVEFR
      SC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGUEkzQ0x1RWpJ
      QlhWV3Zmc0RheStQU2xkMDF1TUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lIdnI4cldxUjF4SFI1
      RktYRTU5ZjNWZUFQTW1hZVdsQnFFUjJOYy9zK1NsQWlFQQo4cXFuWnl2dUZoSDRPSVQxK1duTEJI
      YjZGT0d6cmhMVUIzUTNkSGZKdDBnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwdWdBd0lCQWdJVUtWSnBRbUZtc3p6bUdX
      NGxZWVAzK2tEbmUvOHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE1E
      QXpNemd3TUZvWERUSXpNRGd4TURBek5ETXdNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFaCkJn
      TlZCQWNURWpVeExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2Y2pJ
      eEh6QU0KQmdOVkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05WQkFN
      TUVrRmtiV2x1UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdF
      SEEwSUFCSUh0N0s1V3lzaXd3cXlRCmZqTHlHUi9GSVBHNk5GbHZVZ1FEczBMcTZrOUZMdWh5dnhh
      aFl6cTF0eEdoL2JBZEFyMkwwRnhPNlQwWDQ5aXAKUXJ3SGVSMmpnZ0VhTUlJQkZqQU9CZ05WSFE4
      QkFmOEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVTNwYUltV25yNnpK
      RWYrTnZnWGNCa2lwVkdRNHdId1lEVlIwakJCZ3dGb0FVOGpjSXU0U01nRmRWCmE5K3dOckw0OUtW
      M1RXNHdKQVlEVlIwUkJCMHdHNElaWTJFdGRHOXZiSE10TlRrM1pEVmpZelE1TkMxalpHUncKWWpD
      Qmp3WUlLZ01FQlFZSENBRUVnWUo3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1Vp
      TENKaApaRzFwYmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1GMVpHbDBiM0l5
      SWl3aWFHWXVSVzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlYVmthWFJ2Y2pJdGJtVjBJaXdp
      YUdZdVZIbHdaU0k2SW1Ga2JXbHUKSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lDN0pPek9p
      SHJVbmJ3ejhISFRoejA0c1J2RjNoSkFvaDRRRApBWW5qQ2ZFVUFpQklKMnVoU2E1T2xZRnpLSWFq
      VGRTdTNXMjJrQVcrYzFhSkY1OFA1cEhzUVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIO
      CgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtn
      QXdJQkFnSVVkeFRDWDVTdHdHTE9BT2RwOUo3WWRSK1kxbHd3Q2dZSUtvWkl6ajBFQXdJdwpYREVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZj
      akl0Ym1WME1CNFgKRFRJeU1EZ3hNREF6TXpjd01Wb1hEVEkxTURVek1EQXpNemN3TVZvd1hERUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZj
      akl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVocCsxMlVTNmpQUDhG
      alJ3NnVxTUJjU0FiSExZZTZwZG9UcU5sWUNEZjZpdldWc3h3b2RNNWlSNgpSQklzcU14S3VmaWdq
      YU5VdkJ6cng0bW0ybGJlTnFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJB
      ZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGUEkzQ0x1RWpJQlhWV3Zmc0RheStQU2xkMDF1TUFvR0ND
      cUcKU000OUJBTUNBMGdBTUVVQ0lIdnI4cldxUjF4SFI1RktYRTU5ZjNWZUFQTW1hZVdsQnFFUjJO
      Yy9zK1NsQWlFQQo4cXFuWnl2dUZoSDRPSVQxK1duTEJIYjZGT0d6cmhMVUIzUTNkSGZKdDBnPQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYI
      ARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoR
      Eg8KC2F1ZGl0b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggBEgII
      ABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xp
      Y3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlu
      cyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMSpyoKB09yZGVyZXISmyoSlhYKCm9yZGVyZXJNU1AS
      hxYaoxQKA01TUBKbFBKQFBKNFAoKb3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlCK1RDQ0FaNmdBd0lCQWdJVVgvNFpxenNkRk5hNTlXbVVhV0lhYU56dkRHSXdDZ1lJ
      S29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFE
      REE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRBd016TTBNalphRncweU5UQTFNekF3
      TXpNME1qWmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFO
      QmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dP
      WTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVQ3
      VmlvaVdwUzB0amY0RERCaGhES0EyUGFxWUVTLzAyRVFlelhUTFRFNmU1RjZFbGZSeFk2cUM5dHV1
      K2ExCmdrYXJUR3JDdnFSTyt5Z2tqMU9IZ2VkOW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9N
      QTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVVWdHeDlpM2puczJUckh6aTRkbFp3
      aFRLWlpVd0NnWUlLb1pJemowRQpBd0lEU1FBd1JnSWhBSUpxQkZLZEgrdlhHM09Zb1ZBY080elMw
      bW10N0xZM1hhZm52TU1SQUU5bkFpRUErRGtCCmNVVTk5YkRJYlkvSEMxNUorT2F2a0U4dnIrY2dG
      OW5YQXhVRXlvaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoilggtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQzFqQ0NBbnlnQXdJQkFnSVVScHZHRDRYSWdGUzdNT2hyS0N5UjZDZnFD
      MDB3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dG
      UVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1UQXdNek0xTURCYUZ3MHlN
      ekE0TVRBd016UXdNREJhTUdneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFN
      Qzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RC
      V0ZrYldsdU1Sb3dHQVlEVlFRRERCRkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NN
      NDkKQWdFR0NDcUdTTTQ5QXdFSEEwSUFCSENNeFd5WTJZNERLY3IyV2Z2M051Nk9PY09iTlJaWHA5
      NkJ4dEJSYmhjagprQ0o5RWc3Y0hVWVFnajJEMDNXT1BrTHhTdkVSckNhOFc0bDlnZk85SHhXamdn
      RVFNSUlCRERBT0JnTlZIUThCCkFmOEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhR
      NEVGZ1FVVm5qS2twQnc4dGxSM0pLeERoaHMKeGxmQnNVb3dId1lEVlIwakJCZ3dGb0FVVWdHeDlp
      M2puczJUckh6aTRkbFp3aFRLWlpVd0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TlRnMU5t
      TmtaamhqTkMxemEyWnRlakNCaFFZSUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5
      NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFX
      OXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhR
      aQpMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVBE
      WlArbVBSRkQvClBNM1hOT3lhTG9aRWdjek1IQ1MySVgrK1RXUG1XZjQ1QWlBR3RQRnhoWWdGQVQ5
      ZWNteGIveTFsVjhpRE5HcXcKcDhGNDR6UCtoSkxYUUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitU
      Q0NBWjZnQXdJQkFnSVVYLzRacXpzZEZOYTU5V21VYVdJYWFOenZER0l3Q2dZSUtvWkl6ajBFQXdJ
      dwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21S
      bGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1UQXdNek0wTWpaYUZ3MHlOVEExTXpBd016TTBNalphTUZv
      eEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4
      dmJtUnZiakVRTUE0R0ExVUVDZ3dIVDNKa1pYSmxjakVYCk1CVUdBMVVFQXd3T1kyRXViM0prWlhK
      bGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUN1Zpb2lXcFMwdGpm
      NEREQmhoREtBMlBhcVlFUy8wMkVRZXpYVExURTZlNUY2RWxmUnhZNnFDOXR1dSthMQpna2FyVEdy
      Q3ZxUk8reWdrajFPSGdlZDlvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VC
      Ci93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVVnR3g5aTNqbnMyVHJIemk0ZGxad2hUS1paVXdDZ1lJ
      S29aSXpqMEUKQXdJRFNRQXdSZ0loQUlKcUJGS2RIK3ZYRzNPWW9WQWNPNHpTMG1tdDdMWTNYYWZu
      dk1NUkFFOW5BaUVBK0RrQgpjVVU5OWJESWJZL0hDMTVKK09hdmtFOHZyK2NnRjluWEF4VUV5b2s9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIG
      CAESAggAGhASDgoKb3JkZXJlck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhII
      EgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggB
      EgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggA
      Gg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zKgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRW
      Ml8wEgAaBkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9y
      ZGVyZXIxLm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4
      ekNDQXBtZ0F3SUJBZ0lVTmFuQVBYdE4wbHJVczNHVjMyd3VXTmR4UUw4d0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNt
      UmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVEF3TXpNMU1EQmFGdzB5TXpBNE1UQXdNelF3TURCYU1H
      MHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2Iy
      NHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJn
      TlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtv
      Wkl6ajBEQVFjRFFnQUVVUUFjYzQzb084cVk1MVRJWml4TGo5bTRBWmJaUmk0ck5QR0MKdHFlQS96
      K01sMUd4VEsyMG85ZVRPN1ZVY0lvc2ZZU25tRnZaVXhUd0E4NlVhQnBzWnFPQ0FTZ3dnZ0VrTUE0
      RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFV
      SEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVjSDZ4WnJBL05HOG5tNC9UdWhH
      R0toVUw3UzB3SHdZRFZSMGoKQkJnd0ZvQVVVZ0d4OWkzam5zMlRySHppNGRsWndoVEtaWlV3T3dZ
      RFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1S
      bGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1o
      bUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhK
      bGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdn
      cWhrak9QUVFEQWdOSUFEQkZBaUVBN2dIcWxPR1pHTktOd2I1dmV6RGpWbFp4c2pjc28xLzkxSjln
      CjNHWlovOHNDSUZMZ0twWDF0dyt1OGZUNzBkaEtIV3ZiYXFzd2FzOU9iQW16Z0hJcWRjLzQKLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      Qzh6Q0NBcG1nQXdJQkFnSVVOYW5BUFh0TjBsclVzM0dWMzJ3dVdOZHhRTDh3Q2dZSUtvWkl6ajBF
      QXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2
      Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1UQXdNek0xTURCYUZ3MHlNekE0TVRBd016UXdNREJh
      TUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVr
      YjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFi
      QmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRVVRQWNjNDNvTzhxWTUxVElaaXhMajltNEFaYlpSaTRyTlBHQwp0cWVB
      L3orTWwxR3hUSzIwbzllVE83VlVjSW9zZllTbm1GdlpVeFR3QTg2VWFCcHNacU9DQVNnd2dnRWtN
      QTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJC
      UVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVWNINnhackEvTkc4bm00L1R1
      aEdHS2hVTDdTMHdId1lEVlIwagpCQmd3Rm9BVVVnR3g5aTNqbnMyVHJIemk0ZGxad2hUS1paVXdP
      d1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhM
      bVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJ
      bWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmta
      WEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtC
      Z2dxaGtqT1BRUURBZ05JQURCRkFpRUE3Z0hxbE9HWkdOS053YjV2ZXpEalZsWnhzamNzbzEvOTFK
      OWcKM0daWi84c0NJRkxnS3BYMXR3K3U4ZlQ3MGRoS0hXdmJhcXN3YXM5T2JBbXpnSElxZGMvNAot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJ
      QmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMa
      BkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMS
      CgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoG
      QWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNI
      QTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1p
      bnMaSgoQT3JkZXJlckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1p
      bnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoK
      BkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFk
      bWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
