apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: devorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaICLv97v4SbjgvoYTX6QEE6nBg0z29mJ4l3wl/D4scgyMEt5cCttcCthcCngKWggBEAEaBgiz
      qrqXBiIKc3lzY2hhbm5lbCpANGYxZmRmYjQ3NjU0ZDExZGRhNDRiOGI4OGZlNTU2MGI4ZDYzZDA5
      MzFjMDFkODE3ZTgwZmQ0NmFmMzU3OTY2MRIaEhhDJtxHtR0+ISYBOqBDoWoml56Guqv6ESES21sK
      2FsS1VsS7y4KC0NvbnNvcnRpdW1zEt8uEpQuChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL1
      LRLIFgoLYXVkaXRvcjFNU1ASuBYa0BQKA01TUBLIFBK9FBK6FAoLYXVkaXRvcjFNU1AS7QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9UQ0NBYUtnQXdJQkFnSVVNZ0crQ2hXalduSVBB
      ZVRTSW9NOEhwc1VCSDh3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJk
      V1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3dO
      akV4TURrME5Wb1hEVEkxTURVeU5qRXhNRGswTlZvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpC
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpq
      MENBUVlJS29aSXpqMEQKQVFjRFFnQUU3K2JmeWY0Y0tRMUp0NmJ0Slc0TmVRV1QzMFp6VU9UVHBU
      Zzhsb2ZMbFZ5TFhVNlNoL1BzWS9QYgpoU2kyTGk1QnFKNlJ6ZFpsQTZ4bUJnNTNEelk4YzZOQ01F
      QXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JC
      WUVGUGdQY3V6RW84Mm9lTjloRmhGTHJFSmZaUXlXTUFvR0NDcUcKU000OUJBTUNBMGtBTUVZQ0lR
      Q2RDNWlaNU5hYVpwZEF0WEx1SCtwclJNQjZiWnJ4UWV5TUdGbllheWFGalFJaApBSTdyQUlJRXdN
      TEJpZ2VlMEhuaWlDT2l1cFFPRUt5QmdkTlBkMjh5K3hQMQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwcWdBd0lCQWdJVURq
      RUdtV0RYQWVmQzZUTG1kMjZmenpiNjRZd3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJo
      TUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0
      WApEVEl5TURnd05qRXhNVGN3TUZvWERUSXpNRGd3TmpFeE1qSXdNRm93ZWpFTE1Ba0dBMVVFQmhN
      Q1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdo
      QmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRF
      Yk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBEQVFjRFFnQUUrck9yTG1PSE1sbXY0TWhmCmVaUnNIN2Voa0ZOR3ZsTUVGY1dVZTVO
      ZUp6SWRNYjVuT0xDcFRiWFc4eGMyQXd6VEhhbEo1U1VZS1VId3FQZCsKKzlyUGpxT0NBUm93Z2dF
      V01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJU
      YkYzaFAxZDlQcTF5LzZoQXVxVTdiZDVRYXJEQWZCZ05WSFNNRUdEQVdnQlQ0RDNMc3hLUE5xSGpm
      CllSWVJTNnhDWDJVTWxqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAyT0dabU56WTFaamsy
      TFhoaWMydzIKTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWww
      SWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      WVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5
      TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURSd0F3
      UkFJZ1czaTJ6a0Jmb1VsOVJ0c0M3NGhORGwrRlhFQkZPM0IzWVdJZwo4KzBFdFBzQ0lBdHdaeWNi
      QWkwTXZGUWZsd29wVFRyTUVQLzE2OGprOC9DaGpXMFd5TGhkCi0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlC
      L1RDQ0FhS2dBd0lCQWdJVU1nRytDaFdqV25JUEFlVFNJb004SHBzVUJIOHdDZ1lJS29aSXpqMEVB
      d0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZ
      WFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURnd05qRXhNRGswTlZvWERUSTFNRFV5TmpFeE1EazBO
      Vm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZ
      WFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRTcrYmZ5
      ZjRjS1ExSnQ2YnRKVzROZVFXVDMwWnpVT1RUcFRnOGxvZkxsVnlMWFU2U2gvUHNZL1BiCmhTaTJM
      aTVCcUo2UnpkWmxBNnhtQmc1M0R6WThjNk5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0Jn
      TlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZQZ1BjdXpFbzgyb2VOOWhGaEZMckVKZlpR
      eVdNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFDZEM1aVo1TmFhWnBkQXRYTHVIK3ByUk1CNmJa
      cnhRZXlNR0ZuWWF5YUZqUUloCkFJN3JBSUlFd01MQmlnZWUwSG5paUNPaXVwUU9FS3lCZ2ROUGQy
      OHkreFAxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQS
      KRIfCAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIf
      CAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAES
      GxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggS
      BggBEgIIABoREg8KC2F1ZGl0b3IxTVNQEAEaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9yMk1T
      UBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVWZIc1llRlRHOHJOWGpnb3lLMldXdWNZSk9RUXdD
      Z1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdB
      MVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURnd05qRXhNVEV3TVZvWERUSTFN
      RFV5TmpFeE1URXdNVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdB
      MVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApB
      UWNEUWdBRW96UkpTUERBUXVRZFNJUzNsMmpCZ3R5ZlIvczRZbVhoRTllSGsxbDN1cmNIU01jZVpW
      bElHR0FsCmxwOU90a3JYZ0kraEcvaXBTRm5hU0FxWE9GcWlRYU5DTUVBd0R3WURWUjBUQVFIL0JB
      VXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZQNVdvbndrbGh4RXZW
      TG5MTXFvVVBhY2RRbGxNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFEeUluYkw1YXBMWWlUNU5z
      UENOa2UwZ1FBTllCN1hmQ05OcmxicTNWVTJVQUlnCkhrZlJ2V2xXWnRoU2t1VmtjZTN0OGJxNkhG
      d0RSZ2hITDF3R3A5SDhKaHc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQXB1Z0F3SUJBZ0lVVmRxSjA4NjNDUzhoTWtMajZn
      cko4OElkL0Vvd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRH
      OXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3TmpFeE1U
      a3dNRm9YRFRJek1EZ3dOakV4TWpRd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdOVkJB
      Y1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4SHpB
      TQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1NRWtG
      a2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJ
      QUJHSXJodHJFWFJNUGtHOWYKemkxeDlleThPWm5IYU9aNTBhdSs1MU1sQlFja0ZRa3lidjFtb1Ju
      Z1J1MWs3UDB4bXI2RWZpUkZvSmtMYU9lQwp1R1BBTFgyamdnRWFNSUlCRmpBT0JnTlZIUThCQWY4
      RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVMklyN1FOMXpmL2dYUDhF
      N2ZlQ2ppdVdaZUFVd0h3WURWUjBqQkJnd0ZvQVUvbGFpZkNTV0hFUzkKVXVjc3lxaFE5cHgxQ1dV
      d0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXROelprTkRjNE9EUTJOQzEwTnpoNApZakNCandZ
      SUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlMQ0po
      ClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJaXdp
      YUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lhR1l1
      Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFER2diZTMrWmto
      NEh2YmlKOFdOS251Z3YzRlF0cGRGS3RGClEweFhyWmUxUHdJZ0ZrZ29malYxbU1waGphbkhjcUcz
      azBqcDBpMXNEYXpGeW8ycGZPSzcxMlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNI
      QTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lC
      QWdJVWZIc1llRlRHOHJOWGpnb3lLMldXdWNZSk9RUXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRi
      bVYwTUI0WApEVEl5TURnd05qRXhNVEV3TVZvWERUSTFNRFV5TmpFeE1URXdNVm93WERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRi
      bVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRW96UkpTUERBUXVRZFNJUzNs
      MmpCZ3R5ZlIvczRZbVhoRTllSGsxbDN1cmNIU01jZVpWbElHR0FsCmxwOU90a3JYZ0kraEcvaXBT
      Rm5hU0FxWE9GcWlRYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVC
      QU1DQWFZd0hRWURWUjBPQkJZRUZQNVdvbndrbGh4RXZWTG5MTXFvVVBhY2RRbGxNQW9HQ0NxRwpT
      TTQ5QkFNQ0EwZ0FNRVVDSVFEeUluYkw1YXBMWWlUNU5zUENOa2UwZ1FBTllCN1hmQ05OcmxicTNW
      VTJVQUlnCkhrZlJ2V2xXWnRoU2t1VmtjZTN0OGJxNkhGd0RSZ2hITDF3R3A5SDhKaHc9Ci0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggBEgII
      ABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggAGhES
      DwoLYXVkaXRvcjJNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggAGg8S
      DQoLYXVkaXRvcjJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRIn
      EgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcv
      Q2hhbm5lbC9PcmRlcmVyL0FkbWlucxKjKgoHT3JkZXJlchKXKhKSFgoKb3JkZXJlck1TUBKDFhqf
      FAoDTVNQEpcUEowUEokUCgpvcmRlcmVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIrRENDQVo2Z0F3SUJBZ0lVV1ZJMUhFWlpvbzV2bmhwbWtXTnU2T1N2V3dFd0NnWUlLb1pJ
      emowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVq
      WVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNRFl4TVRBNE1qZGFGdzB5TlRBMU1qWXhNVEE0
      TWpkYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05W
      QkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEpsY2pFWApNQlVHQTFVRUF3d09ZMkV1
      YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUlBGQWVB
      enRnODhPTHdpR1JvcGh2Z2tMbmc0L2tCRlJ2OGxWay85eVJpNnZDYkM2U1ZzVEd5M3RTV3NaRysK
      bmk0dDRvRG9oYkxBOXVzL0JFQ2o3dk5tbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdB
      MVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVsam5pcmhmSnBlOXVnVU1ibko5TmxhUmJI
      VFl3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJZ0kwUmxvRTNtVjl2Z3RRNTFKcXBkZW5IRGRTMTJ2
      cno0YkZra1dkMGhIVzBDSVFDOWs3QXgKUk1KdmZHK202N3MzYnc0Z3BCWW1WR0JCbXhmOGpnQ0xn
      VWlDN0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKSCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDMURDQ0FudWdBd0lCQWdJVVJOSDdKQy8wVFJOck5xRmh5ampJMmI4Y3NZb3dD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURW
      UVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURZeE1URXhNREJhRncweU16QTRN
      RFl4TVRFMk1EQmFNR2d4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRN
      QzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmti
      V2x1TVJvd0dBWURWUVFEREJGQlpHMXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJKQnFFcmVTS0VYWEhhSVVjODFFRG4rU3lCSS92bWZ2RTg1bmNW
      c2dTU1o4Ck92cDRCUEQ1U1BrZ1JjOE5lQ1QzMTRZTVk3bXREVW1hSWw4WW1jaTNGS3FqZ2dFUE1J
      SUJDekFPQmdOVkhROEIKQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVEanBycytJM0xkaWRwMTZ0RzhwdQpIK0RvT3Y0d0h3WURWUjBqQkJnd0ZvQVVsam5pcmhmSnBl
      OXVnVU1ibko5TmxhUmJIVFl3SXdZRFZSMFJCQnd3CkdvSVlZMkV0ZEc5dmJITXROVGxtT0RVM1ky
      WTBMWEpxTW5od01JR0ZCZ2dxQXdRRkJnY0lBUVI1ZXlKaGRIUnkKY3lJNmV5SmhZbUZqTG1sdWFY
      UWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cApZWFJwYjI0aU9p
      SWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnZjbVJsY21WeUxXNWxkQ0lzCklt
      aG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQVM5b1ErYlZ2
      SGZKalMKdkp3RDU3L3FoT2VkcXZPR3ViSFNXZWpNNGRoQWVRSWdOSTBwZHdYSm1TT1pLaFlZUW1P
      NEpOYmJZVkpnUVhxSAprTUdJS0RvZ3BTbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoE
      U0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3
      SUJBZ0lVV1ZJMUhFWlpvbzV2bmhwbWtXTnU2T1N2V3dFd0NnWUlLb1pJemowRUF3SXcKV2pFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1
      bGREQWVGdzB5Ck1qQTRNRFl4TVRBNE1qZGFGdzB5TlRBMU1qWXhNVEE0TWpkYU1Gb3hDekFKQmdO
      VkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpF
      UU1BNEdBMVVFQ2d3SFQzSmtaWEpsY2pFWApNQlVHQTFVRUF3d09ZMkV1YjNKa1pYSmxjaTF1WlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUlBGQWVBenRnODhPTHdpR1JvcGh2
      Z2tMbmc0L2tCRlJ2OGxWay85eVJpNnZDYkM2U1ZzVEd5M3RTV3NaRysKbmk0dDRvRG9oYkxBOXVz
      L0JFQ2o3dk5tbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJ
      QnBqQWRCZ05WSFE0RUZnUVVsam5pcmhmSnBlOXVnVU1ibko5TmxhUmJIVFl3Q2dZSUtvWkl6ajBF
      CkF3SURTQUF3UlFJZ0kwUmxvRTNtVjl2Z3RRNTFKcXBkZW5IRGRTMTJ2cno0YkZra1dkMGhIVzBD
      SVFDOWs3QXgKUk1KdmZHK202N3MzYnc0Z3BCWW1WR0JCbXhmOGpnQ0xnVWlDN0E9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAa
      DhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwK
      Cm9yZGVyZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRl
      cmVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9y
      ZGVyZXJNU1AaBkFkbWlucyoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMa
      HwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRW
      Ml8wEgAaBkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9y
      ZGVyZXIxLm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4
      akNDQXBtZ0F3SUJBZ0lVT0ZyTWhjc2NZWmVSRHlvUVhvbGZxVkNZam9Zd0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNt
      UmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNRFl4TVRFeE1EQmFGdzB5TXpBNE1EWXhNVEUyTURCYU1H
      MHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2Iy
      NHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJn
      TlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtv
      Wkl6ajBEQVFjRFFnQUVtUEpiM2JJeTkwbStGRjRYRG5iZTFBTDZZSWdhZEl5TG5DUFEKQ0xQeDNY
      N3NERGZTa1pKU2U4elpySE9TTlZLcklUbk1DRVZheE0vb25qT3lTYWlhYmFPQ0FTZ3dnZ0VrTUE0
      RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFV
      SEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVGeVRUczhFRkZsN3F5UXFIclUx
      cXVZYUJqMjR3SHdZRFZSMGoKQkJnd0ZvQVVsam5pcmhmSnBlOXVnVU1ibko5TmxhUmJIVFl3T3dZ
      RFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1S
      bGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1o
      bUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhK
      bGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdn
      cWhrak9QUVFEQWdOSEFEQkVBaUF0WDI5WE9Dd2dQcm9PU1p1Ym1RNzkyYW05TDZ6MW5WbTZLM1Zy
      CjRVT0NRZ0lnYlYvcDV6dHdBc1ZVNzBCVlNaNi9lbW5XUU5uN05YekZyelIxcUlkRDhuaz0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      QzhqQ0NBcG1nQXdJQkFnSVVPRnJNaGNzY1laZVJEeW9RWG9sZnFWQ1lqb1l3Q2dZSUtvWkl6ajBF
      QXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2
      Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1EWXhNVEV4TURCYUZ3MHlNekE0TURZeE1URTJNREJh
      TUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVr
      YjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFi
      QmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRW1QSmIzYkl5OTBtK0ZGNFhEbmJlMUFMNllJZ2FkSXlMbkNQUQpDTFB4
      M1g3c0REZlNrWkpTZTh6WnJIT1NOVktySVRuTUNFVmF4TS9vbmpPeVNhaWFiYU9DQVNnd2dnRWtN
      QTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJC
      UVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVUZ5VFRzOEVGRmw3cXlRcUhy
      VTFxdVlhQmoyNHdId1lEVlIwagpCQmd3Rm9BVWxqbmlyaGZKcGU5dWdVTWJuSjlObGFSYkhUWXdP
      d1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhM
      bVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJ
      bWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmta
      WEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtC
      Z2dxaGtqT1BRUURBZ05IQURCRUFpQXRYMjlYT0N3Z1Byb09TWnVibVE3OTJhbTlMNnoxblZtNksz
      VnIKNFVPQ1FnSWdiVi9wNXp0d0FzVlU3MEJWU1o2L2VtbldRTm43Tlh6RnJ6UjFxSWREOG5rPQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJ
      QmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlu
      cxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
