apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://143.198.247.194:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIOT1VEVP0AsnEbrDzZGcZ9XtvNGKNG0TSLbzZbuq70XQEuZcCuNcCuBcCngKWggBEAEaBgj8
      wuiXBiIKc3lzY2hhbm5lbCpAMDdkZDA0YWEwYThiYWJiN2YyZmRhMjY5YmE3NDc3OGFjYzk3MDZj
      OTNkZWU0YTFmMmU1NzllZDEzZWQwNmM2MRIaEhhUPBI0PRE0QEp7hOCP9/mott+zXts5d1YS41sK
      4FsS3VsSpyoKB09yZGVyZXISmyoSlhYKCm9yZGVyZXJNU1AShxYaoxQKA01TUBKbFBKQFBKNFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lC
      QWdJVWJHMWUvd3VpYlhwNkV3SGwyZFdRQ3JXdmcrRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRVeE1ESXlORGRhRncweU5UQTJNRFF4TURJeU5EZGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJhZ1p3NThzeU9qUlJtOUZ0Sm1MTFBv
      V1Y4K0tuQnhjNGN3YTRKaUo0S1FQbWhvN0R1V3lVeGxUcDhFQlFMCnNidFpaTHJEVGJRdWVCTTQy
      RTJRSTM3UG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVdXAvcEc5dW5MSVdHUFV6UWhndGt2Z1VVTlhFd0NnWUlLb1pJemowRQpB
      d0lEU1FBd1JnSWhBUDQxR0VubnMyN3lTVXI0bDd3Zm5wREJ1dWZheEg1dm1yZ2ZqZnhOMERiS0Fp
      RUFtWEdOCkxUVHU5QXZudU9Mb09HTm4zTExCdVhoZUNYMS91VGhRZmc3d3hpZz0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoilggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFqQ0NB
      bnlnQXdJQkFnSVVHNjVqM3ZFS2JnVnBjRHU3Mll1YXVJNDhVQTR3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UVXhNREkwTURCYUZ3MHlNekE0TVRVeE1ESTVNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCSjlRUnAxWCtZSlBzRUpUNVd6S3NtblZnUEx6N2xYaWVqQ29pcjR3dTdxMgo3dUtUVjZzMnQv
      d3N5TDJiN2FRenFwMkRBU2I2SmVvdEp2ZWl4b3FPK0FtamdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVWTdrWlBFQk1TUDl3Mnlz
      UjN5Ty8KNUJHcXlpOHdId1lEVlIwakJCZ3dGb0FVdXAvcEc5dW5MSVdHUFV6UWhndGt2Z1VVTlhF
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TmprMU5EaGtPR05qTmkxdWVuTnpaekNCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUpmMW51eUhsbDFvCk9HWGZpUXdWaEZF
      TjJ0NmhKOHpKMzZCTWF3SEJ5WGJHQWlCeExZZ2VYK2xuT0toQnZLUmpncmJpUGducUVsYW4KTFFy
      eU1kM3o1KzQwM2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK
      6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVViRzFlL3d1
      aWJYcDZFd0hsMmRXUUNyV3ZnK0V3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpB
      NE1UVXhNREl5TkRkYUZ3MHlOVEEyTURReE1ESXlORGRhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3
      RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dI
      VDNKa1pYSmxjakVYCk1CVUdBMVVFQXd3T1kyRXViM0prWlhKbGNpMXVaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFSYWdadzU4c3lPalJSbTlGdEptTExQb1dWOCtLbkJ4YzRj
      d2E0SmlKNEtRUG1obzdEdVd5VXhsVHA4RUJRTApzYnRaWkxyRFRiUXVlQk00MkUyUUkzN1BvMEl3
      UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRF
      RmdRVXVwL3BHOXVuTElXR1BVelFoZ3RrdmdVVU5YRXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0lo
      QVA0MUdFbm5zMjd5U1VyNGw3d2ZucERCdXVmYXhINXZtcmdmamZ4TjBEYktBaUVBbVhHTgpMVFR1
      OUF2bnVPTG9PR05uM0xMQnVYaGVDWDEvdVRoUWZnN3d4aWc9Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJN
      U1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRt
      aW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hU
      aW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxok
      CgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIR
      ErcRCghldGNkcmFmdBKqEQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NBcG1nQXdJQkFnSVVVR0FtSGFyeFFkOEk5WDZoeTdZ
      WWFvNk1lT2N3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21W
      eU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1UVXhNREkwTURC
      YUZ3MHlNekE0TVRVeE1ESTVNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJ
      MU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05W
      CkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYw
      TUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVlnTklDeFJnYTBacldlZnNBZDlU
      OTlJOHN3eElXSVkreTNDNwpZUXo4WHRMenVQQ2NhNEIyeWs5SWJnV1BOTjBFL3lhWHlWaUM0Snk2
      VDdMMk5OdzVnNk9DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFV
      QmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRF
      RmdRVVdtSkhxWUU1a3JiZHFYalI3aS9sa0sxazNkVXdId1lEVlIwagpCQmd3Rm9BVXVwL3BHOXVu
      TElXR1BVelFoZ3RrdmdVVU5YRXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEps
      Y2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcK
      QndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXli
      MnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJ
      am9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUEwMW96TklMcEZiY2Zu
      d25JaUpXYTNORmpISnJMdlFMLzF5bUEKZnVqRHRYWUNJRHJHU0ZKbE5lbXZNU0RnY1lhNFFsN3lR
      L3Q2UE4xRjcvRFFOY3hrQTI0WQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJVVVHQW1IYXJ4UWQ4STlYNmh5
      N1lZYW82TWVPY3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxj
      bVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRVeE1ESTBN
      REJhRncweU16QTRNVFV4TURJNU1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhF
      eEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0Jn
      TlYKQkFzVEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJt
      VjBNRmt3RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFWWdOSUN4UmdhMFpyV2Vmc0Fk
      OVQ5OUk4c3d4SVdJWSt5M0M3CllRejhYdEx6dVBDY2E0QjJ5azlJYmdXUE5OMEUveWFYeVZpQzRK
      eTZUN0wyTk53NWc2T0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZq
      QVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhR
      NEVGZ1FVV21KSHFZRTVrcmJkcVhqUjdpL2xrSzFrM2RVd0h3WURWUjBqCkJCZ3dGb0FVdXAvcEc5
      dW5MSVdHUFV6UWhndGt2Z1VVTlhFd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pY
      SmxjaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFV
      RwpCd2dCQkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1
      eWIyeHNiV1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhC
      bElqb2liM0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTAxb3pOSUxwRmJj
      Zm53bklpSldhM05GakhKckx2UUwvMXltQQpmdWpEdFhZQ0lEckdTRkpsTmVtdk1TRGdjWWE0UWw3
      eVEvdDZQTjFGNy9EUU5jeGtBMjRZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1z
      EAoYASAFKICAgAgaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIq
      Cg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxIN
      CAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      KgZBZG1pbnMS8y4KC0NvbnNvcnRpdW1zEuMuEpguChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1
      bRL5LRLMFgoLYXVkaXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVaMDVVeGNaVGl0
      aXR6d01RYlBOOHRqRkxrWFF3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RB
      aEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1E
      Z3hOVEV3TWpReE0xb1hEVEkxTURZd05ERXdNalF4TTFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUV6Wkp2MUhMT1YvbGlGd3pwVVpYYzhWeUdkbjlSY0dJ
      bGExSDJ2NXNTb1piVW53Y0t1SUZyRUF3OQo5VDZtQ2hZTW9XQWNIWGFlZXpPdExEdk5xR1d3S0tO
      Q01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIw
      T0JCWUVGQmVnS0NraXBiTk1hV2VYSFVzK2xpaklsTmZHTUFvR0NDcUcKU000OUJBTUNBMGNBTUVR
      Q0lBMFBVWWg2NnpkcUJTTlFXb25mclNVVkdmeTVJNzY0dHZyY2hQbWJhUHZEQWlBawp4WnE5U1do
      aGJreXlHK3NUS2sxVUR1U0d5Rk8rRjV6WVgwYkNCTTBFa2c9PQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tCiK+CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJ
      VVdBY2I2REszTEFvam9xeWZyaEtoZWNPZlVqRXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFV
      RUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJF
      d0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYw
      TUI0WApEVEl5TURneE5URXdNamN3TUZvWERUSXpNRGd4TlRFd016SXdNRm93ZWpFTE1Ba0dBMVVF
      QmhNQ1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFL
      RXdoQmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5
      TVRFYk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBD
      QVFZSUtvWkl6ajBEQVFjRFFnQUUvOEdjVGhOemtuK21XUy9UCkp5SjVvSFVoOURjVUxOWENNQlVr
      Q2k2NGR4ZVMxcUZaa2hVQTdXMWlKRkI2cWxwSUJaZnRpeDJVa05ablZMVUgKLzFBOEQ2T0NBUm93
      Z2dFV01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FX
      QkJRdW9vN0VWTysvUlZaeVNUblRvcnVoWHA5MkdqQWZCZ05WSFNNRUdEQVdnQlFYb0NncElxV3pU
      R2xuCmx4MUxQcFlveUpUWHhqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzTkRWbU56aGtZ
      alppTFRjME4yaG8KTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBi
      bWwwSWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJ
      am9pWVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBk
      Rzl5TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURT
      QUF3UlFJaEFNbTh4cXZiRDRLeDd0M2dtT3YzN3hiWGRucGFnK25Scm1qSgp3OHE2MTFWYUFpQWtz
      WlpGUU1NVUNRVFdLdzNpQmFtQnozZ295OHV2aW4ybmN4WUZ2Z3FtUVE9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVaMDVVeGNaVGl0aXR6d01RYlBOOHRqRkxrWFF3Q2dZSUtv
      Wkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hOVEV3TWpReE0xb1hEVEkxTURZd05E
      RXdNalF4TTFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFn
      QUV6Wkp2MUhMT1YvbGlGd3pwVVpYYzhWeUdkbjlSY0dJbGExSDJ2NXNTb1piVW53Y0t1SUZyRUF3
      OQo5VDZtQ2hZTW9XQWNIWGFlZXpPdExEdk5xR1d3S0tOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdF
      Qi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQmVnS0NraXBiTk1hV2VYSFVz
      K2xpaklsTmZHTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lBMFBVWWg2NnpkcUJTTlFXb25mclNV
      VkdmeTVJNzY0dHZyY2hQbWJhUHZEQWlBawp4WnE5U1doaGJreXlHK3NUS2sxVUR1U0d5Rk8rRjV6
      WVgwYkNCTTBFa2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1dyaXRl
      cnMSKRIfCAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjUKBkFkbWlucxIr
      EiEIARIdEggSBggBEgIIABoREg8KC2F1ZGl0b3IxTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVu
      dBIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMqBkFkbWlucxLMFgoLYXVk
      aXRvcjJNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVaeWEzUDFSb1l0N3NINzVBQlVtTEYv
      UW9RUFV3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1q
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hOVEV3TWpVME5s
      b1hEVEkxTURZd05ERXdNalUwTmxvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1q
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUUzNkxkeGk5T3VzS3NEZUFFdUJvcEtIWFRJWmtObklLcEpOV0ZXRkxvK0lH
      ZlcvZGRNU01XNW5xMAoreURTajA3TjNCem10aXpZUnJvTVBLb1BKU0h5dHFOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQ0hkODJ0
      cE9LemluMjhNM0lnRjlKRFB6VXExTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lGMmk0ZEJNdzlK
      Y2pLQi9vMW83cXY3M0tKcE9FUHU1QXFYRnVnOW1XWFVRQWlCVwp5ZkpYb1BoLzEwZkloU2dPZ1Ex
      UzlaMjV0YTBxcTU4RnlzVXBReTZWS1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOVRDQ0FwdWdBd0lCQWdJVUJwV2l0dVlFN205
      QzVhRitDV1NudVhwOCtXb3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURn
      eE5URXdNekF3TUZvWERUSXpNRGd4TlRFd016VXdNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFa
      CkJnTlZCQWNURWpVeExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2
      Y2pJeEh6QU0KQmdOVkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05W
      QkFNTUVrRmtiV2x1UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5
      QXdFSEEwSUFCUHFCc1JxWjA3NG15UW9pCmJ6Y1RjYzBDUHBlYWJ2OERmN1Y2bWsrbWNhNm9ZUHpm
      YWExY1ZCUWd6SzViV1dGblpVRlBiZ29lcVZIQ3VySjkKQk5pclhEeWpnZ0VhTUlJQkZqQU9CZ05W
      SFE4QkFmOEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVW0weTFlN28r
      SlgvSXNPK1E5ZEplVXV1UVNUa3dId1lEVlIwakJCZ3dGb0FVSWQzemEyazRyT0tmCmJ3emNpQVgw
      a00vTlNyVXdKQVlEVlIwUkJCMHdHNElaWTJFdGRHOXZiSE10Tm1ZMll6WTJaRFZrTkMxeWQyeDIK
      Y2pDQmp3WUlLZ01FQlFZSENBRUVnWUo3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlk
      V1VpTENKaApaRzFwYmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1GMVpHbDBi
      M0l5SWl3aWFHWXVSVzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlYVmthWFJ2Y2pJdGJtVjBJ
      aXdpYUdZdVZIbHdaU0k2SW1Ga2JXbHUKSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRRFlz
      VjQ0ejZvQ1BPU3hiUHR3cngvdWk2YUhFRTBOSXF2UgpHaVZGbHpBM3JRSWdOZGFuZ21LZVFyQmpq
      R0xUVWh1Z1owWTk1NStFMkdHOGJGeVlXZ2MxRkZnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      CkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQit6Q0NB
      YUtnQXdJQkFnSVVaeWEzUDFSb1l0N3NINzVBQlVtTEYvUW9RUFV3Q2dZSUtvWkl6ajBFQXdJdwpY
      REVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hOVEV3TWpVME5sb1hEVEkxTURZd05ERXdNalUwTmxvd1hE
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUUzNkxkeGk5T3Vz
      S3NEZUFFdUJvcEtIWFRJWmtObklLcEpOV0ZXRkxvK0lHZlcvZGRNU01XNW5xMAoreURTajA3TjNC
      em10aXpZUnJvTVBLb1BKU0h5dHFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhR
      OEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQ0hkODJ0cE9LemluMjhNM0lnRjlKRFB6VXExTUFv
      R0NDcUcKU000OUJBTUNBMGNBTUVRQ0lGMmk0ZEJNdzlKY2pLQi9vMW83cXY3M0tKcE9FUHU1QXFY
      RnVnOW1XWFVRQWlCVwp5ZkpYb1BoLzEwZkloU2dPZ1ExUzlaMjV0YTBxcTU4RnlzVXBReTZWS1E9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggS
      BggBEgIIABoREg8KC2F1ZGl0b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIb
      EggSBggBEgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggS
      BggBEgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Q
      b2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0Fk
      bWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNI
      QTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1p
      bnMaSgoQT3JkZXJlckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFk
      bWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
