apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-vaultkubenertes-job
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-vaultkubenertes-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: orderer
      component_type: orderer
      namespace: orderer-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://aa34b638ff2ca4f3c9bcefa161f4b801-973901913.eu-west-1.elb.amazonaws.com:8200
      authpath: dev-testorderer-net-auth
      policy: vault-crypto-orderer-orderer-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://EEA6F28184FDB9A50815F81DE7BBA57A.gr7.eu-west-1.eks.amazonaws.com
