apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a4bad08484d15460788deef3b35cce0b-1271918739.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBVKrr0KeZbFC1RtYBNwKUVgUS48IIbqy9rt49hGJpoPEt5cCttcCthcCngKWggBEAEaBgjU
      /+GXBiIKc3lzY2hhbm5lbCpANzI4NDNmMTU5YjAwOTJiZWQxNmQzYzU1ZWM2MjliNjQ5MDYyZGYz
      Mjc4Mjg3YmM2NTJjOTFiZTQxOTYxYzMyNhIaEhhrooJ2f5HEstGspSz1XZEv96oxKbV33TcS21sK
      2FsS1VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVUJWd2FselkxSnFNc1dnWkkwbDdnNHlzYnJJd3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRRd05ETTNNakJhRncweU5UQTJNRE13TkRNM01qQmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFCbzNVUXlyZ1o4MVpZeHkyNXVlME5N
      bWV0M1FZQUZMREJ5TzNQUmlXOWIxNTJtRExlOG8rOVBTa0ZpUWEvCnQyOWplUCtQNGc2UEJkYytq
      WnljeFZHT28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVWC8vdVZ6UDlvcXFnZzBhd2t1QzdYYzM1NWVFd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWhBT1BvNGFRM1ZlOWxHU2lTTE81S1pZZGpUTTQ0dlhNTy9Rb1JpLzh3QzFuMUFp
      QmNpN3F6Ck82WjhSTkg2QzBkQjV2amlkRm8wSWs3MzYxSWhlM1grVXA0UVFBPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFUQ0NB
      bnlnQXdJQkFnSVVGYzhvZDNudmZGcmJHQVJoWkloSjhQWFR4OTh3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UUXdORFF6TURCYUZ3MHlNekE0TVRRd05EUTRNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCTFZyek03K2xTQlRwaWw0ajVKME9PcHhQNFhaa3RUMDJiekVoZFdIa25MVApSK0JtSWNSeVJ4
      dnBObHJpQTBpMHJVMjFwWWs1ZGg2aGR5cDJMaXllMStDamdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVWVQ4WEVtVGtMcHZPWFMr
      TWJ0L2IKSHAvaHpBd3dId1lEVlIwakJCZ3dGb0FVWC8vdVZ6UDlvcXFnZzBhd2t1QzdYYzM1NWVF
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TjJJMll6azVaalprTkMxNE1uSjJOVENCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnZW1nU0ZEb2NnOUZhClNSa3I2bi9RbFNz
      bVNEdFVWb2dHZTJQbFN0ZUIwVllDSUFPNFgxZDQyZUdOcnR6K2FsOUhnTHhYTERsWmVmakwKTW9w
      V2l2ZFpkSjVlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUJWd2FselkxSnFN
      c1dnWkkwbDdnNHlzYnJJd3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRR
      d05ETTNNakJhRncweU5UQTJNRE13TkRNM01qQmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVFCbzNVUXlyZ1o4MVpZeHkyNXVlME5NbWV0M1FZQUZMREJ5TzNQ
      UmlXOWIxNTJtRExlOG8rOVBTa0ZpUWEvCnQyOWplUCtQNGc2UEJkYytqWnljeFZHT28wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      WC8vdVZ6UDlvcXFnZzBhd2t1QzdYYzM1NWVFd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBT1Bv
      NGFRM1ZlOWxHU2lTTE81S1pZZGpUTTQ0dlhNTy9Rb1JpLzh3QzFuMUFpQmNpN3F6Ck82WjhSTkg2
      QzBkQjV2amlkRm8wSWs3MzYxSWhlM1grVXA0UVFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1TUBABGgZBZG1pbnMi
      NwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9yZGVyZXIx
      Lm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBt
      Z0F3SUJBZ0lVQk82R1ZibnJpZVh5UjZCanh0Z1VjeE1YdTZJd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5
      TFc1bGREQWVGdzB5Ck1qQTRNVFF3TkRRek1EQmFGdzB5TXpBNE1UUXdORFE0TURCYU1HMHhDekFK
      QmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFP
      QmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1U
      Rkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVDOExLRk8wNzBFTVNZWkpyVHZ5ZG5GK1ZJdDdLdnRqM2FobUEKU2ozTlJFZ1NSRU04
      ZDdXYXMzWUxvdzJOVmJWb0g3UHBjenZZb1lhZGluOHhlQ1VOQ2FPQ0FTZ3dnZ0VrTUE0RwpBMVVk
      RHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdE
      QVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV6dUQ2NGg4K1cvc0pMbENuNlh0MWIyYkRi
      ZDh3SHdZRFZSMGoKQkJnd0ZvQVVYLy91VnpQOW9xcWdnMGF3a3VDN1hjMzU1ZUV3T3dZRFZSMFJC
      RFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNi
      M0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1a
      bWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXVi
      M0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9Q
      UVFEQWdOSEFEQkVBaUJjN2tsYnpoQk9BUDhEMy92cVIwUnVEak1NUUFhWlF0Unl3dGFGCkpOR05L
      d0lnYTRwODN4TnFnNXgyL3Qva0JERE9yc3lWQVlYZEw5NUVFTHNKYmdxOEt4WT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzhqQ0NB
      cG1nQXdJQkFnSVVCTzZHVmJucmllWHlSNkJqeHRnVWN4TVh1Nkl3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UUXdORFF6TURCYUZ3MHlNekE0TVRRd05EUTRNREJhTUcweEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJB
      TVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpq
      MERBUWNEUWdBRUM4TEtGTzA3MEVNU1laSnJUdnlkbkYrVkl0N0t2dGozYWhtQQpTajNOUkVnU1JF
      TThkN1dhczNZTG93Mk5WYlZvSDdQcGN6dllvWWFkaW44eGVDVU5DYU9DQVNnd2dnRWtNQTRHCkEx
      VWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJ
      d0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVXp1RDY0aDgrVy9zSkxsQ242WHQxYjJi
      RGJkOHdId1lEVlIwagpCQmd3Rm9BVVgvL3VWelA5b3FxZ2cwYXdrdUM3WGMzNTVlRXdPd1lEVlIw
      UkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1W
      c2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pF
      dWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtq
      T1BRUURBZ05IQURCRUFpQmM3a2xiemhCT0FQOEQzL3ZxUjBSdURqTU1RQWFaUXRSeXd0YUYKSk5H
      Tkt3SWdhNHA4M3hOcWc1eDIvdC9rQkRET3JzeVZBWVhkTDk1RUVMc0piZ3E4S3hZPQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hT
      aXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlu
      cxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFk
      bWlucxLvLgoLQ29uc29ydGl1bXMS3y4SlC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvUt
      EsgWCgthdWRpdG9yMU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVU5XWjB1RWYwdkl2UXJD
      WVVXM09TcVdNSmNxMHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE5E
      QTBNemd6TmxvWERUSTFNRFl3TXpBME16Z3pObG93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRUt5VlNDYXVWcUhqUitMQktQakxNU1JvSEkzQ25mdE9xY0dE
      dElBQ1VxbisxNXUvZEduc0UwUlMxCi92QVJkNEF2Ym42VE8yeFl1T213eWtLdmZFZDFvNk5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZFNTF0TUk5TngrSk9ITXM4NGtXY2JQL1puUFFNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUJG
      N2NJMTkzeG43c2xIUmlSOExJY3RacTczMjVpaitGVTlKWVRFQlZOVlpBaUVBCnhHUS8ybVdKZmVs
      UXVWMlZQTVFOaXExQlZWdy9TZzN2aXdzTHgxOVNnRDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBxZ0F3SUJBZ0lVS25a
      RXo4RVUwclNOR2VNNURXSDZKbHJLRVdnd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd4TkRBME5EWXdNRm9YRFRJek1EZ3hOREEwTlRFd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRWlNMStUS21lTisrV1d4MXYKaDVEcjd2WHFyTlNKTUY1Y0JOa3hNaksz
      L0krWExmRmNPREM1RnZZeEcweUZSd2d6NFBiUFg2cE01YWVqdld2ZAp2T1c5L2FPQ0FSb3dnZ0VX
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlJS
      YnpPMTdpSUZGeXJlVUFyUStVcGFib1h0N3pBZkJnTlZIU01FR0RBV2dCUk9kYlRDUFRjZmlUaHoK
      TFBPSkZuR3ovMlp6MERBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDJaR1k1WWpRME9HUmlM
      V3h1WmpVNQpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqRWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      UzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdS
      QUlnTnlNYXAvOEdMeEtxdTloc0tuTVY1dmF1TmtlSkpXa0IwZHlVCmd1UTc2cUlDSUFMWmhQVDZz
      RU5ENWhoSkpDQUMzRC93QzVRTkptclZXWndxSFFjT0wzYUkKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      RENDQWFLZ0F3SUJBZ0lVTldaMHVFZjB2SXZRckNZVVczT1NxV01KY3Ewd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd4TkRBME16Z3pObG9YRFRJMU1EWXdNekEwTXpnek5s
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFS3lWU0Nh
      dVZxSGpSK0xCS1BqTE1TUm9ISTNDbmZ0T3FjR0R0SUFDVXFuKzE1dS9kR25zRTBSUzEKL3ZBUmQ0
      QXZibjZUTzJ4WXVPbXd5a0t2ZkVkMW82TkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkU1MXRNSTlOeCtKT0hNczg0a1djYlAvWm5Q
      UU1Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJQkY3Y0kxOTN4bjdzbEhSaVI4TEljdFpxNzMyNWlq
      K0ZVOUpZVEVCVk5WWkFpRUEKeEdRLzJtV0pmZWxRdVYyVlBNUU5pcTFCVlZ3L1NnM3Zpd3NMeDE5
      U2dEOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8I
      ARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIb
      EggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIG
      CAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJBZ0lVVit3QytKV1E2aHJKS2Rqem1nNEV3S1FCdnBrd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TkRBME16azFORm9YRFRJMU1E
      WXdNekEwTXprMU5Gb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFVVhQSU5IUk02WUxPTnBmMDJyeFl1UHJVL1ZhUFprRjF5NzRjWjI4WGZNWnBwakthUC9Y
      NW5CR2sKNE5RQkI2VlZKSEIwRTQ3R3d1blFKemcxWCtOTm5hTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRklPTDlFVzVmTWRrQVZF
      VzFZZGZ1RlA4YkdZdk1Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJUURvZk1IUVNUZXZiQmJqWm5L
      RXNTQnhnZE44VDZva0pUNW0rdHdOYng0QllBSWcKVEhNTXg4SGFWd0VuVHk3YUhDbTNZV1dlTUZH
      ZmVqZzFUSk8rVDVjeS83OD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHFnQXdJQkFnSVVHM0U3TGhUSk1BYy9vMC9tQWkz
      NFh4ZUxQbVV3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hOREEwTkRn
      d01Gb1hEVEl6TURneE5EQTBOVE13TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      Qk9YWDgydjdvaW5FQkY0ZAp0bmJrSytrZXI3bFJ0SnBucDRPaHpKT1lUTWFxWmhvS2U5WVlBVnc0
      YVBGck11TCtkaHYwUGhwTEd6VUZsTTJSCkhZajJOWEdqZ2dFWk1JSUJGVEFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVVhZ3hYOHVpSko0NW5HL1g5
      UTFIT2RBcThBZll3SHdZRFZSMGpCQmd3Rm9BVWc0djBSYmw4eDJRQgpVUmJWaDErNFUveHNaaTh3
      SXdZRFZSMFJCQnd3R29JWVkyRXRkRzl2YkhNdE9EYzJaalkwWkRnNExXUjNlbXB3Ck1JR1BCZ2dx
      QXdRRkJnY0lBUVNCZ25zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmsK
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVlYVmthWFJ2Y2pJaUxDSm9a
      aTVGYm5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQmhkV1JwZEc5eU1pMXVaWFFpTENKb1ppNVVl
      WEJsSWpvaVlXUnRhVzRpCmZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTlFEVXJWY1EzTGw4
      RllUazlpMFBQM1hwUlRZZFhqZEkyZG8KcndMRFFsR2xBaUE4cXR6bkFmNEJHQWNraXFNVVJEbU9X
      M2RiWGtDU3VGRFZxM2tQTEJGWFBRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJB
      Z0lVVit3QytKV1E2aHJKS2Rqem1nNEV3S1FCdnBrd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd4TkRBME16azFORm9YRFRJMU1EWXdNekEwTXprMU5Gb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFVVhQSU5IUk02WUxPTnBmMDJy
      eFl1UHJVL1ZhUFprRjF5NzRjWjI4WGZNWnBwakthUC9YNW5CR2sKNE5RQkI2VlZKSEIwRTQ3R3d1
      blFKemcxWCtOTm5hTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRklPTDlFVzVmTWRrQVZFVzFZZGZ1RlA4YkdZdk1Bb0dDQ3FHClNN
      NDlCQU1DQTBnQU1FVUNJUURvZk1IUVNUZXZiQmJqWm5LRXNTQnhnZE44VDZva0pUNW0rdHdOYng0
      QllBSWcKVEhNTXg4SGFWd0VuVHk3YUhDbTNZV1dlTUZHZmVqZzFUSk8rVDVjeS83OD0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggSBggBEgII
      ABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggBEgIIABoP
      Eg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggAGhESDwoL
      YXVkaXRvcjJNU1AQARoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1p
      bnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhh
      c2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaSgoQT3JkZXJlckFkZHJlc3NlcxI2EhsK
      GW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
