apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a7e9892a5136f4fa8b1cda6ba31b358b-1780904258.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIHANuQSTUEBv9x5ONAHs67+9mfBeadZcmo6jIpIaz1OcEuJcCt9cCtxcCngKWggBEAEaBgje
      ndKXBiIKc3lzY2hhbm5lbCpAZjE0ZmIxZTgyMDJkMWYxYmE4YTg5OTQ2N2MzZjgyZWFkMjk4ZTk0
      MThjMWM4MGRmNzBkZThiNGJhYTIwNjA5YRIaEhiM66s3uyw/b3FC6LvWCPHwkBTv4wCMIYQS31sK
      3FsS2VsSpyoKB09yZGVyZXISmyoSlhYKCm9yZGVyZXJNU1AShxYaoxQKA01TUBKbFBKQFBKNFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lC
      QWdJVUVzN0RQbGFqYXVGWE1oWHgxTGZEbEE3NGxab3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRFd05EVTFNamhhRncweU5UQTFNekV3TkRVMU1qaGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVR1c3YrQ21hdWhrYlFQMlZ2em9FeGd2
      bEZ0ODlDbkU0dWh4QUtlNlFjVFlaRnE2YlZQMktzenErb3JjeC9sCmVKOE84QXE2QXFGRFhCSFdC
      UTVaQXhKTW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVSjI2YTZkVndpV1Y2czZQdkJQV2NKVGFabVZVd0NnWUlLb1pJemowRQpB
      d0lEU1FBd1JnSWhBTVpocE5uWEgrNVYxamFpTzFOT0UwQ3IyM2k3MzNGSEdOWlRUdkpmVzVNekFp
      RUF4UFRpCkNDV2Q3OE9wTDE4Vk5XSjNqZTlIWXRXM05zd0NtcVVWQzNMMzFVbz0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoilggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFqQ0NB
      bnlnQXdJQkFnSVVCc0R0MG41QmF4UjRZUVgrWHpienlYcU1yVVl3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1URXdORFU0TURCYUZ3MHlNekE0TVRFd05UQXpNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCSnZXNFl6TEE2V3g1MUVIY1F5M0xWamtXREMxR01ldU1JczNYSFVReGpjLwpiRy9uNmNEZ2Zl
      bVZPWlFRMVZldnppMjYwZGlnVVF6aHIxSm0rQ1dSSWg2amdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVS01NUStVVWt0U0lRc2RP
      YmhoVjEKblkwREFCQXdId1lEVlIwakJCZ3dGb0FVSjI2YTZkVndpV1Y2czZQdkJQV2NKVGFabVZV
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TlRnMU5tTmtaamhqTkMxcmFESTVZakNCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU1WQTNPbXpvVjVqCjV6RkRDcVJSL1BV
      TVh0RnBseGJENmUzMzJpcHRKYkM5QWlBQk9PSDNZSHZMNTI1c2pVdExzTUdwZ0N4ZG1XZG0KZjUz
      aEhyQ21VdXJtU2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK
      6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVFczdEUGxh
      amF1RlhNaFh4MUxmRGxBNzRsWm93Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpB
      NE1URXdORFUxTWpoYUZ3MHlOVEExTXpFd05EVTFNamhhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3
      RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dI
      VDNKa1pYSmxjakVYCk1CVUdBMVVFQXd3T1kyRXViM0prWlhKbGNpMXVaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUdXN2K0NtYXVoa2JRUDJWdnpvRXhndmxGdDg5Q25FNHVo
      eEFLZTZRY1RZWkZxNmJWUDJLc3pxK29yY3gvbAplSjhPOEFxNkFxRkRYQkhXQlE1WkF4Sk1vMEl3
      UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRF
      RmdRVUoyNmE2ZFZ3aVdWNnM2UHZCUFdjSlRhWm1WVXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0lo
      QU1aaHBOblhIKzVWMWphaU8xTk9FMENyMjNpNzMzRkhHTlpUVHZKZlc1TXpBaUVBeFBUaQpDQ1dk
      NzhPcEwxOFZOV0ozamU5SFl0VzNOc3dDbXFVVkMzTDMxVW89Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1T
      UBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVy
      TVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hU
      aW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxok
      CgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIR
      ErcRCghldGNkcmFmdBKqEQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzhqQ0NBcG1nQXdJQkFnSVVXUWlydllyT0FVakszMlVkRE1j
      TXhRcG4xaDh3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21W
      eU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1URXdORFU0TURC
      YUZ3MHlNekE0TVRFd05UQXpNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJ
      MU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05W
      CkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYw
      TUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXYvSHg1bytEMENaYkNWamdJYk9H
      cHBWMEgweENGcnpEekJ4ZQpka0ovS2F2Q0FsRUwzenBSTHNYb0hsdlZOa3UzaXBOdTNMT091L1hu
      bHV2Y1ZxZ2hVcU9DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFV
      QmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRF
      RmdRVS9PWFA0M2UvRTlDeHprK3hsMjZDTnBqVHdHSXdId1lEVlIwagpCQmd3Rm9BVUoyNmE2ZFZ3
      aVdWNnM2UHZCUFdjSlRhWm1WVXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEps
      Y2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcK
      QndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXli
      MnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJ
      am9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQjVhdHl3RDBnZURicEty
      eTZGUGhYREVtOW9yWXhVRnJSYWo5disKeGN6cE13SWdaUzFla1RncGI2U2JSNFc1RWVRU21FQU1L
      aWhXYnBCSTN3Q09vdGFiY3g0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVVdRaXJ2WXJPQVVqSzMyVWRE
      TWNNeFFwbjFoOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxj
      bVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRFd05EVTRN
      REJhRncweU16QTRNVEV3TlRBek1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhF
      eEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0Jn
      TlYKQkFzVEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJt
      VjBNRmt3RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFdi9IeDVvK0QwQ1piQ1ZqZ0li
      T0dwcFYwSDB4Q0ZyekR6QnhlCmRrSi9LYXZDQWxFTDN6cFJMc1hvSGx2Vk5rdTNpcE51M0xPT3Uv
      WG5sdXZjVnFnaFVxT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZq
      QVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhR
      NEVGZ1FVL09YUDQzZS9FOUN4emsreGwyNkNOcGpUd0dJd0h3WURWUjBqCkJCZ3dGb0FVSjI2YTZk
      VndpV1Y2czZQdkJQV2NKVGFabVZVd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pY
      SmxjaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFV
      RwpCd2dCQkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1
      eWIyeHNiV1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhC
      bElqb2liM0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCNWF0eXdEMGdlRGJw
      S3J5NkZQaFhERW05b3JZeFVGclJhajl2Kwp4Y3pwTXdJZ1pTMWVrVGdwYjZTYlI0VzVFZVFTbUVB
      TUtpaFdicEJJM3dDT290YWJjeDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1z
      EAoYASAFKICAgAgaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIq
      Cg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxIN
      CAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      KgZBZG1pbnMS7y4KC0NvbnNvcnRpdW1zEt8uEpQuChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1
      bRL1LRLIFgoLYXVkaXRvcjFNU1ASuBYa0BQKA01TUBLIFBK9FBK6FAoLYXVkaXRvcjFNU1AS7QUt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9UQ0NBYUtnQXdJQkFnSVVRU2dZZWx2ZFZQ
      Wkl3a1NQVTBVcmM3Mk1melV3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RB
      aEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1E
      Z3hNVEEwTlRZME0xb1hEVEkxTURVek1UQTBOVFkwTTFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVXZmFvWnZ0SHVvelF2TFgzaHg1R1FFWFhIVWNlL0tL
      UWdPUVhGN2QzSnMwYkxaSWxWMzAwMUdXSAp3bnFkWklVSTY1dklzQ1NFMVQzeWFJbUhKTmtPdEtO
      Q01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIw
      T0JCWUVGS0IyVGFpWlhMdXRIRFowS1dwaS9MMHN5NnpzTUFvR0NDcUcKU000OUJBTUNBMGtBTUVZ
      Q0lRRHExbk9sbjhCdDVqNXZTaUJuSFR6MW1FTTlQemsveThYbkpLS3RXK3BSZFFJaApBSjR4NXdx
      OEJudGZyUFZmbXJKU2FHR1ZNaXZRbTdlaXdrVVc0TXlOUDgvdwotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwcWdBd0lCQWdJ
      VU5JUEl6MFE2c1IyejNGU1Y0Y0t1ZEtKN3RWc3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFV
      RUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJF
      d0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYw
      TUI0WApEVEl5TURneE1UQTFNREV3TUZvWERUSXpNRGd4TVRBMU1EWXdNRm93ZWpFTE1Ba0dBMVVF
      QmhNQ1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFL
      RXdoQmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5
      TVRFYk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBD
      QVFZSUtvWkl6ajBEQVFjRFFnQUViSzhjSGpZdE05TklsMWRaCkVmN05nMGQrVm1RcDYyQ3ExUmNP
      MFVzREpCelRyMXNTV25RVmR5N2dkbmVNcDFFRGhpNDVUeWNNRGl2dGcvb2cKNEpBR1lLT0NBUm93
      Z2dFV01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FX
      QkJUeEFSbFQyL0tDNjdTK2UzbWRBMXFveng2TDFEQWZCZ05WSFNNRUdEQVdnQlNnZGsyb21WeTdy
      UncyCmRDbHFZdnk5TE11czdEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzT1dNME4yWTJZ
      MlE0TFRWa05HdzEKTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBi
      bWwwSWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJ
      am9pWVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBk
      Rzl5TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURS
      d0F3UkFJZ1ZQdGIydGV4Tm13T0hLb3ZoQ3FLdmFzVFNmSjVxbzd2WlV6Swo2aXNHUkc4Q0lIV200
      WllHRC9qcmZ6SHk4UmUxTmV5UTJRNll5QThVNTBjZ0hPNHBmaEpqCi0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL1RDQ0FhS2dBd0lCQWdJVVFTZ1llbHZkVlBaSXdrU1BVMFVyYzcyTWZ6VXdDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE1UQTBOVFkwTTFvWERUSTFNRFV6TVRBME5U
      WTBNMW93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRVdm
      YW9adnRIdW96UXZMWDNoeDVHUUVYWEhVY2UvS0tRZ09RWEY3ZDNKczBiTFpJbFYzMDAxR1dICndu
      cWRaSVVJNjV2SXNDU0UxVDN5YUltSEpOa090S05DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZLQjJUYWlaWEx1dEhEWjBLV3BpL0ww
      c3k2enNNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFEcTFuT2xuOEJ0NWo1dlNpQm5IVHoxbUVN
      OVB6ay95OFhuSktLdFcrcFJkUUloCkFKNHg1d3E4Qm50ZnJQVmZtckpTYUdHVk1pdlFtN2Vpd2tV
      VzRNeU5QOC93Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHUmVhZGVycxIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8I
      ARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0S
      CBIGCAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9y
      Mk1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVWVCcDVKN3N0Wk1TOFpYcldrMlRURlJSblJC
      QXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE1UQTBOVGd3TUZvWERU
      STFNRFV6TVRBME5UZ3dNRm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRUVpdXplTGFxUWZoU2dnN0NOTTIvOEM2dEJVZStYV3kxV2RSM2xiV3lWY2NnOXgw
      WXE2RlVRK3V4Ck1peFlQYW5ldUtwQTA1UWFBcDBLaVd5Q0Fkdit4S05DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZQVmhYUStkUjRM
      SFBOU2V5KzBiVmdJTUJMVlhNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFES0RFY0dBcWxKK0Vh
      SlYzamRFY3RkUnFGN2RmVi92RVY4dW1DY1o3K3ZOUUlnCkU2aDJiY1BmNkkwMDdhM09hdTNjdU0x
      R3hFK1lwYXdvOFlDTzhqODA4VWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQXB1Z0F3SUJBZ0lVTFUvdjdOWjYydmpEOWIw
      SVJXQVhWNHRVOUUwd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TVRB
      MU1ETXdNRm9YRFRJek1EZ3hNVEExTURnd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdO
      VkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4
      SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1N
      RWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VI
      QTBJQUJBb1czQ2dHN0ZOdVg3TlUKNTQrbWpDOVg3WnFPVzZuUC84VENPRld1RjB4MG1QdTRSdTd2
      OXoxYTlyWTZXK2pHQk0zOWpGaGM2c1J2RzJDTwp6cWh1bjZPamdnRWFNSUlCRmpBT0JnTlZIUThC
      QWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVb3pWaW4xWjBuVkJ6
      NHF0L0RxbGN4T2RmbS9Jd0h3WURWUjBqQkJnd0ZvQVU5V0ZkRDUxSGdzYzgKMUo3TDdSdFdBZ3dF
      dFZjd0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXROVGszWkRWall6UTVOQzF6YWpaeQplakNC
      andZSUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlM
      Q0poClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJ
      aXdpYUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lh
      R1l1Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDV1dJNytM
      OHVtOXdzRjM4KzA3TkRDSGVLRDZoblJvUm5kCndPbnhLNitkb1FJZ1N0RGJ6Q2NJVGF5R1JFTzQv
      L3Fqck9EZjl2SitHVlNvTmJYem1uMjFZaDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4K
      BFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dB
      d0lCQWdJVWVCcDVKN3N0Wk1TOFpYcldrMlRURlJSblJCQXdDZ1lJS29aSXpqMEVBd0l3ClhERUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUI0WApEVEl5TURneE1UQTBOVGd3TUZvWERUSTFNRFV6TVRBME5UZ3dNRm93WERFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUVpdXplTGFxUWZoU2dn
      N0NOTTIvOEM2dEJVZStYV3kxV2RSM2xiV3lWY2NnOXgwWXE2RlVRK3V4Ck1peFlQYW5ldUtwQTA1
      UWFBcDBLaVd5Q0Fkdit4S05DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFm
      OEVCQU1DQWFZd0hRWURWUjBPQkJZRUZQVmhYUStkUjRMSFBOU2V5KzBiVmdJTUJMVlhNQW9HQ0Nx
      RwpTTTQ5QkFNQ0EwZ0FNRVVDSVFES0RFY0dBcWxKK0VhSlYzamRFY3RkUnFGN2RmVi92RVY4dW1D
      Y1o3K3ZOUUlnCkU2aDJiY1BmNkkwMDdhM09hdTNjdU0xR3hFK1lwYXdvOFlDTzhqODA4VWM9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggA
      GhESDwoLYXVkaXRvcjJNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIGCAES
      AggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGlj
      eRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2
      GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpK
      ChBPcmRlcmVyQWRkcmVzc2VzEjYSGwoZb3JkZXJlcjEub3JkZXJlci1uZXQ6NzA1MBoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucyIi
      CgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1Jl
      YWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      Gg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
