apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa34b638ff2ca4f3c9bcefa161f4b801-973901913.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIA0eolPVEBUCanOKe7k5PYggUzojBJPw+caqGRpKOPYIEuJcCt9cCtxcCngKWggBEAEaBgjh
      l9mXBiIKc3lzY2hhbm5lbCpAZGEwYWZkNTQ5ODM2NjBlMzNlNzY5Y2E3ZWJlMGJiOWI4ZGFhOTFm
      MGY1YmU2OTAyYWVlODk3N2Q4ZDg0MDAxYRIaEhjCUeXGjbfb1cEaFr1NmkLn9PSmtrktnW0S31sK
      3FsS2VsS8y4KC0NvbnNvcnRpdW1zEuMuEpguChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL5
      LRLMFgoLYXVkaXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVLbGFmTC9obFNOaGlk
      MFRrWFpvTzd3eStWK293Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJk
      V1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hN
      akV5TURZMU1Wb1hEVEkxTURZd01URXlNRFkxTVZvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpC
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpq
      MENBUVlJS29aSXpqMEQKQVFjRFFnQUVoaTA3TmVvbXJ4Z2cxZDB1SVFhQjZoZWhyK2M5UXI5ME5o
      SWVOa0l2M3p2Z1l1bTFuVHMxSStKawp3RUtpL3pPYzRZQ25VVVIxaHRyMURJSmEyN3R6cXFOQ01F
      QXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JC
      WUVGSjR5VE5OdzZnaVJnY1I0Y3JGck9WK2wyWHd5TUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lR
      RE1KcHdPZldlaVdyY1NJaTlBTHNCNzk0VWpTSzlkRk9HN2h4VjJxT0tTL0FJZwpOL0FmbFBickU4
      ajNjaXMvRUJGR1c3RWVKeUdIVFFKeEc1NkpSUytXMG5nPQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiK+CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJVVh6
      bkNQNkllSHVZaUx0MmxtZDZWU29tYkxmSXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJo
      TUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0
      WApEVEl5TURneE1qRXlNRGd3TUZvWERUSXpNRGd4TWpFeU1UTXdNRm93ZWpFTE1Ba0dBMVVFQmhN
      Q1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdo
      QmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRF
      Yk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBEQVFjRFFnQUVjWXl4cHVJR2U2bnZRTWQ2Cm9icWZ6L045ekhVbHNCR3VtdUVVUnNC
      UDJhckVQR2lzMFVRVzBiQi9INmtqaGZuRXhtVThpYlhGZnN3RlhxUE8KaU5pRzVLT0NBUm93Z2dF
      V01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJT
      V3BEN25OZGFORnJYK2VNcEsxbXliRVFWdElUQWZCZ05WSFNNRUdEQVdnQlNlTWt6VGNPb0lrWUhF
      CmVIS3hhemxmcGRsOE1qQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzT1RRNE5XTmtPV1Jr
      TFhZNVpHZHUKTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWww
      SWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      WVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5
      TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURTQUF3
      UlFJaEFQYWYxOUkvNzFYcHpwb2hlZHNraE0vN2ZmbXd0b0hNcWlWNgp2bUJGamhoY0FpQXd5L1lj
      cUZZVVhaQUFYZ3hTRm1SRGh3TGd3TDI1SlNnOEFuelVIWWJGU1E9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQi9EQ0NBYUtnQXdJQkFnSVVLbGFmTC9obFNOaGlkMFRrWFpvTzd3eStWK293Q2dZSUtvWkl6
      ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZ
      MkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hNakV5TURZMU1Wb1hEVEkxTURZd01URXlN
      RFkxTVZvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZ
      MkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVo
      aTA3TmVvbXJ4Z2cxZDB1SVFhQjZoZWhyK2M5UXI5ME5oSWVOa0l2M3p2Z1l1bTFuVHMxSStKawp3
      RUtpL3pPYzRZQ25VVVIxaHRyMURJSmEyN3R6cXFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96
      QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGSjR5VE5OdzZnaVJnY1I0Y3JGck9W
      K2wyWHd5TUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lRRE1KcHdPZldlaVdyY1NJaTlBTHNCNzk0
      VWpTSzlkRk9HN2h4VjJxT0tTL0FJZwpOL0FmbFBickU4ajNjaXMvRUJGR1c3RWVKeUdIVFFKeEc1
      NkpSUytXMG5nPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgKC0VuZG9yc2Vt
      ZW50EikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFkZXJz
      EikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikS
      HwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAES
      HRIIEgYIARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMqBkFkbWlucxLMFgoLYXVkaXRv
      cjJNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVGUGZ3YnZDTVcxUjRRdTJIdGZTazhPZUh6
      ajB3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlN
      QllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hNakV5TURneE1Gb1hE
      VEkxTURZd01URXlNRGd4TUZvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlN
      QllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpq
      MEQKQVFjRFFnQUVGSE1jc25uTmVQOTl2MHlkYXlNYnIvMVd1WVRSQWpVRnpFQWhjRUJJWStYZExr
      NnYrQ0Q1ejlJeQpJWWk2cW1Dc1I4ZVp3aHowRG5SblcvZ1lUOEhlUWFOQ01FQXdEd1lEVlIwVEFR
      SC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGSWM1R1VVVENo
      WG9tcnJ6RXcrNnU4TGo5VjBtTUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lFWktEdzk2QllFc0JP
      UkwvUWZXTEk4ZDVJNE1lelloYUNtY0dndGxKWDRmQWlFQQp0Qit0cXpaY1hNVU91VjBMQjRDN3Jj
      TGIrMWhucGNha0FXUWh4Vys0VW40PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOVRDQ0FwdWdBd0lCQWdJVVdkMUc3ZTlUZlQybHBX
      Wjl4VGNaWmJEbXJDOHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE1q
      RXlNVEV3TUZvWERUSXpNRGd4TWpFeU1UWXdNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFaCkJn
      TlZCQWNURWpVeExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2Y2pJ
      eEh6QU0KQmdOVkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05WQkFN
      TUVrRmtiV2x1UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdF
      SEEwSUFCUDgzbDUxWGhKYnJoWWhLCmszMWFZTWNteUJJUldHdEJxWmVLMzBEQmhFNjQwUFNhdmRx
      OXJGODAxdWk2dFcxVGJkNm1mMWd6bWtpSHN1NWMKZnMvZThIeWpnZ0VhTUlJQkZqQU9CZ05WSFE4
      QkFmOEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVUhGb3B6QTErSUdO
      OEQwZmJRV2kxbGZYYW4rd3dId1lEVlIwakJCZ3dGb0FVaHprWlJSTUtGZWlhCnV2TVREN3E3d3VQ
      MVhTWXdKQVlEVlIwUkJCMHdHNElaWTJFdGRHOXZiSE10Tm1SaU56VmlZMlEyT0Mxak5UUXkKZURD
      Qmp3WUlLZ01FQlFZSENBRUVnWUo3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1Vp
      TENKaApaRzFwYmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1GMVpHbDBiM0l5
      SWl3aWFHWXVSVzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlYVmthWFJ2Y2pJdGJtVjBJaXdp
      YUdZdVZIbHdaU0k2SW1Ga2JXbHUKSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ25pNEpT
      TGhXSmlEanh1WFNUNERzV1dCK2xENVF4dFdHWgpkazZ6K3liZ0l3SWdEc1dId1lOVE8yQ2luaGR0
      YWxmUEhUaTdNV2VGdzZrWWFtZ3h3bTB2Z1c0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIO
      CgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtn
      QXdJQkFnSVVGUGZ3YnZDTVcxUjRRdTJIdGZTazhPZUh6ajB3Q2dZSUtvWkl6ajBFQXdJdwpYREVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZj
      akl0Ym1WME1CNFgKRFRJeU1EZ3hNakV5TURneE1Gb1hEVEkxTURZd01URXlNRGd4TUZvd1hERUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZj
      akl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVGSE1jc25uTmVQOTl2
      MHlkYXlNYnIvMVd1WVRSQWpVRnpFQWhjRUJJWStYZExrNnYrQ0Q1ejlJeQpJWWk2cW1Dc1I4ZVp3
      aHowRG5SblcvZ1lUOEhlUWFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJB
      ZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGSWM1R1VVVENoWG9tcnJ6RXcrNnU4TGo5VjBtTUFvR0ND
      cUcKU000OUJBTUNBMGdBTUVVQ0lFWktEdzk2QllFc0JPUkwvUWZXTEk4ZDVJNE1lelloYUNtY0dn
      dGxKWDRmQWlFQQp0Qit0cXpaY1hNVU91VjBMQjRDN3JjTGIrMWhucGNha0FXUWh4Vys0VW40PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYI
      ARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoR
      Eg8KC2F1ZGl0b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggBEgII
      ABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xp
      Y3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlu
      cyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1AS
      gxYanxQKA01TUBKXFBKMFBKJFAoKb3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUpmZXFJOTh1NDczcmQ3OWxFa3N3OVlRTkpHRXdDZ1lJ
      S29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFE
      REE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRJeE1qQTFNekphRncweU5UQTJNREV4
      TWpBMU16SmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFO
      QmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dP
      WTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRI
      YUdlTlZkOXZZUVBqK3lMQUptbjBJZDBReWdNWXhxYndCNHE2a096Y3Y2NXRiK3NwclpKYkpKUVJ1
      Uys2Ckxld2RvYTlxd1lQNkVFd25LZUxLODZLdm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9N
      QTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVT3hUTS9OdG9ZazRXYlRtTCtJejB3
      TjdUejhFd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdUemRpVnQrbXcwdjFZQVB3YlFJNW4vZjVJ
      NFB1ZmJoQ0NLTCsvMmRQWnpRQ0lRRGR5ODVWCm92TllVd0c4Z2k3ZkQ2YTg1RlArVERkNnZFUUtV
      bFYyeUhxeWFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQzFUQ0NBbnVnQXdJQkFnSVVSVHF3R3pwZTd1SVQrTHpXUThQVGlLdXN4
      bDB3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dG
      UVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1USXhNakEzTURCYUZ3MHlN
      ekE0TVRJeE1qRXlNREJhTUdneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFN
      Qzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RC
      V0ZrYldsdU1Sb3dHQVlEVlFRRERCRkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NN
      NDkKQWdFR0NDcUdTTTQ5QXdFSEEwSUFCRmY1WWRYSTNZR2hqL2RLMEl2VUFtYTZnM243SnFZMXpV
      RXlRdVZSSEY5dApTSHl0RWpONmZadEFPYmFWVlk1NW5VQVFFaU9CbVZFRU1iWU5JOUl6VFdtamdn
      RVBNSUlCQ3pBT0JnTlZIUThCCkFmOEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhR
      NEVGZ1FVMWZlQ1pOTGV1ZHFXcDI5NXUycG8KNnVEbzBQb3dId1lEVlIwakJCZ3dGb0FVT3hUTS9O
      dG9ZazRXYlRtTCtJejB3TjdUejhFd0l3WURWUjBSQkJ3dwpHb0lZWTJFdGRHOXZiSE10Wm1NM1lt
      WTJOamcyTFdOeloyMTNNSUdGQmdncUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1Gakxt
      bHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIy
      NGlPaUlpTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJ
      cwpJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBM0cw
      Y29wT1dWN0YxCmdNQVZVcGRhYTZ5eWVsYldpUDZYOCtjWURMR01BZE1DSUVIK0Foc2MvbkE2SnRl
      R1M3cGVsU2YxQTRxNWlGUnMKRTU0VzlENkZvc2djCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      Qg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0Fa
      NmdBd0lCQWdJVUpmZXFJOTh1NDczcmQ3OWxFa3N3OVlRTkpHRXdDZ1lJS29aSXpqMEVBd0l3Cldq
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5
      dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21W
      eUxXNWxkREFlRncweQpNakE0TVRJeE1qQTFNekphRncweU5UQTJNREV4TWpBMU16SmFNRm94Q3pB
      SkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1S
      dmJqRVFNQTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kx
      dVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRIYUdlTlZkOXZZUVBqK3lM
      QUptbjBJZDBReWdNWXhxYndCNHE2a096Y3Y2NXRiK3NwclpKYkpKUVJ1Uys2Ckxld2RvYTlxd1lQ
      NkVFd25LZUxLODZLdm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dR
      RUF3SUJwakFkQmdOVkhRNEVGZ1FVT3hUTS9OdG9ZazRXYlRtTCtJejB3TjdUejhFd0NnWUlLb1pJ
      emowRQpBd0lEU0FBd1JRSWdUemRpVnQrbXcwdjFZQVB3YlFJNW4vZjVJNFB1ZmJoQ0NLTCsvMmRQ
      WnpRQ0lRRGR5ODVWCm92TllVd0c4Z2k3ZkQ2YTg1RlArVERkNnZFUUtVbFYyeUhxeWFBPT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARIC
      CAAaEBIOCgpvcmRlcmVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggB
      EgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggA
      Gg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIM
      CgpvcmRlcmVyTVNQGgZBZG1pbnMqBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzAS
      ABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIRErcRCghldGNkcmFmdBKqEQqTEQoUb3JkZXJl
      cjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NB
      cG1nQXdJQkFnSVVhYjUrTGw3TlRQNDlrQ1dsbytCY2ZDWUkxWUV3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1USXhNakEzTURCYUZ3MHlNekE0TVRJeE1qRXlNREJhTUcweEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJB
      TVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpq
      MERBUWNEUWdBRWExb2F3WVlOU0ttSlBmQkphN1M1TlRIT1kzeEZ2d1NOL3ZJVApVZGhiR29nSFgz
      MkxRS3pjVy8ySUpmWnZuMUovSmN0dWxrQTRWN1NyUG1jaVVmTkhQYU9DQVNnd2dnRWtNQTRHCkEx
      VWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJ
      d0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVTRqayt0M1d6eURoMVhRN3M2Vm1HUm5N
      azhCa3dId1lEVlIwagpCQmd3Rm9BVU94VE0vTnRvWWs0V2JUbUwrSXowd043VHo4RXdPd1lEVlIw
      UkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1W
      c2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pF
      dWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtq
      T1BRUURBZ05JQURCRkFpRUF2WE01NnRoS0thZytzeTh4NnhMTllzbVdESUFnY1k0VWMxc3oKdVRy
      dmc0VUNJR1d3U0FkbjZCbXlMZzdxREJvY3FmTWZOOGVqQ2drNkxBcSsrYjdzeldYTQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpD
      Q0FwbWdBd0lCQWdJVWFiNStMbDdOVFA0OWtDV2xvK0JjZkNZSTFZRXdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJs
      Y21WeUxXNWxkREFlRncweQpNakE0TVRJeE1qQTNNREJhRncweU16QTRNVEl4TWpFeU1EQmFNRzB4
      Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4
      RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXlaR1Z5WlhJeEhUQWJCZ05W
      QkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApLb1pJemowQ0FRWUlLb1pJ
      emowREFRY0RRZ0FFYTFvYXdZWU5TS21KUGZCSmE3UzVOVEhPWTN4RnZ3U04vdklUClVkaGJHb2dI
      WDMyTFFLemNXLzJJSmZadm4xSi9KY3R1bGtBNFY3U3JQbWNpVWZOSFBhT0NBU2d3Z2dFa01BNEcK
      QTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhB
      d0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVNGprK3QzV3p5RGgxWFE3czZWbUdS
      bk1rOEJrd0h3WURWUjBqCkJCZ3dGb0FVT3hUTS9OdG9ZazRXYlRtTCtJejB3TjdUejhFd093WURW
      UjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxk
      bVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0ltRjBkSEp6SWpwN0ltaG1M
      a0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pYjNKa1pYSmxj
      akV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhKbGNpSjkKZlRBS0JnZ3Fo
      a2pPUFFRREFnTklBREJGQWlFQXZYTTU2dGhLS2FnK3N5OHg2eExOWXNtV0RJQWdjWTRVYzFzegp1
      VHJ2ZzRVQ0lHV3dTQWRuNkJteUxnN3FEQm9jcWZNZk44ZWpDZ2s2TEFxKytiN3N6V1hNCi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAgaBkFkbWlucxoiCglCYXRj
      aFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRt
      aW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZB
      ZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhAS
      Bgj/////DxoGQWRtaW5zGkoKEE9yZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVy
      LW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucyIi
      CgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1Jl
      YWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      Gg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
