apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a91641c4926a744bab980b4d5c9b38c3-443950176.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIDnIIBAUvjMbjeKD41s9JcqFOryDuuvUxMAOR5XwmwkUEt5cCttcCthcCngKWggBEAEaBgjP
      34uYBiIKc3lzY2hhbm5lbCpAOGE4YzYwNmEwYjg2ZmQyYzdhMGM2M2I0MzAyZGFlOTMzN2ViNGU1
      YzQ2M2YzYWIwNTkzZmNiNzZkZmM3MDIzMxIaEhh0RwhNk9Vd9/o/kPWghH/vbgWqBnaMc9QS21sK
      2FsS1VsSnyoKB09yZGVyZXISkyoSjhYKCm9yZGVyZXJNU1AS/xUamxQKA01TUBKTFBKIFBKFFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVU5SbkR0NTlIV0MyRFEydzVyRHJKZ1BUa29BOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TWpJd01qUTBNVGRhRncweU5UQTJNVEV3TWpRME1UZGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNnaHR6am9IWCtpKzBOUUFpKzVxMFlU
      YUdnajFsNVBWTDlBSkdIRXVoa3hINVVYbTJJOGYvSnAyTjlJaHhyCk5IbWluelg0TERXWWVIaTBF
      U2oxcW14dG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVVDZvQlNpTEh5dEdXL2QzSGhDUDBUK3NNODdRd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdNWnlNVmtHMTVmMzFZaXUydUd1anFFMnhYaTUvOC9wL0tKaENNZEIwZDdrQ0lB
      SE52ZThFCjh4YU1LeEVhdG5mMk9WcXVVR29xK09jTnpwOHBUM3JRZE55TQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKWCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMWpDQ0FueWdB
      d0lCQWdJVVJ2VUFCWWwrTm16dko4R1R5VEsyNjJNZUcwY3dDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TWpJd01qUTBNREJhRncweU16QTRNakl3TWpRNU1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJE
      Wktyc1dQU3poZ0ZTa2NrOGJTa051YzB6Q3JlTTZ4QjF0L1FFazNtTEVPCjRWT2pLOVBmbzJXaDdi
      Q1MxUGtDOWY4dGFkc0kzS3QwWDhhbEdLSGhjNktqZ2dFUU1JSUJEREFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVUyK3FPUDNFY01QVFdDSGs1R250
      bgpqV3cxYnVzd0h3WURWUjBqQkJnd0ZvQVVUNm9CU2lMSHl0R1cvZDNIaENQMFQrc004N1F3SkFZ
      RFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROamcxWTJRNFpHUTFOQzF1T1RneU5UQ0JoUVlJS2dN
      RUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYlds
      dUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSkE1WHRBMDlHZTkKUkhiVEtSTVJZVWtOaXVL
      VmJHbnZ4bEV5bUVEYWRMSFpBaUJWeFM0NVYrOThFeGhaNkhNVjlKN1JwV2hZL0w4VApaY3NvRjIw
      Qk1iWnF5dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrlBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVU5SbkR0NTlIV0My
      RFEydzVyRHJKZ1BUa29BOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TWpJ
      d01qUTBNVGRhRncweU5UQTJNVEV3TWpRME1UZGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVNnaHR6am9IWCtpKzBOUUFpKzVxMFlUYUdnajFsNVBWTDlBSkdI
      RXVoa3hINVVYbTJJOGYvSnAyTjlJaHhyCk5IbWluelg0TERXWWVIaTBFU2oxcW14dG8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      VDZvQlNpTEh5dEdXL2QzSGhDUDBUK3NNODdRd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdNWnlN
      VmtHMTVmMzFZaXUydUd1anFFMnhYaTUvOC9wL0tKaENNZEIwZDdrQ0lBSE52ZThFCjh4YU1LeEVh
      dG5mMk9WcXVVR29xK09jTnpwOHBUM3JRZE55TQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoG
      QWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRt
      aW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMi
      MwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyoGQWRt
      aW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9u
      cxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxrUEQoNQ29u
      c2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9yZGVyZXIxLm9yZGVyZXItbmV0EIo3
      GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBtZ0F3SUJBZ0lVZXlzTHcr
      STZTYktMUFV0Sm5wRUxGOStMak00d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1q
      QTRNakl3TWpRME1EQmFGdzB5TXpBNE1qSXdNalE1TURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJz
      d0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdW
      eVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05
      eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUU5cy9KdVQ5
      ZUNUZnYwcGtlVCsrclJvYVpRYW80Rkg4VTd0VlIKSlpFU2xobGhoT0hFVUpqME5vWnhXcWVlb2dV
      b2ZKazlRWnV4WE8vdUVXSlh0Nzl1K3FPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURB
      ZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJ
      d0FEQWRCZ05WSFE0RUZnUVU1eW9VRi9aYmg2TXdCU0ZRZ3dtc3hGNlVjVkV3SHdZRFZSMGoKQkJn
      d0ZvQVVUNm9CU2lMSHl0R1cvZDNIaENQMFQrc004N1F3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEps
      Y2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0
      TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFp
      TENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUE3
      ZXdVTGVDZHVMZEx3OVhDL2RlY3YxQ0hlVHRVMS9vcjY5clRpClRiT1ZUZ0lnVXJ2T0kwaHNucC9F
      ek96ZnBKcWU3V2c2c3drZG81Wkc0aThjd241d1RTaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzhqQ0NBcG1nQXdJQkFnSVVleXNM
      dytJNlNiS0xQVXRKbnBFTEY5K0xqTTR3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkK
      TWpBNE1qSXdNalEwTURCYUZ3MHlNekE0TWpJd01qUTVNREJhTUcweEN6QUpCZ05WQkFZVEFrZENN
      UnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXla
      R1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhM
      bTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRTlzL0p1
      VDllQ1RmdjBwa2VUKytyUm9hWlFhbzRGSDhVN3RWUgpKWkVTbGhsaGhPSEVVSmowTm9aeFdxZWVv
      Z1VvZkprOVFadXhYTy91RVdKWHQ3OXUrcU9DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURx
      REFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9C
      QUl3QURBZEJnTlZIUTRFRmdRVTV5b1VGL1piaDZNd0JTRlFnd21zeEY2VWNWRXdId1lEVlIwagpC
      Qmd3Rm9BVVQ2b0JTaUxIeXRHVy9kM0hoQ1AwVCtzTTg3UXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pY
      SmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVky
      OXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlq
      b2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpY
      UWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFp
      QTdld1VMZUNkdUxkTHc5WEMvZGVjdjFDSGVUdFUxL29yNjlyVGkKVGJPVlRnSWdVcnZPSTBoc25w
      L0V6T3pmcEpxZTdXZzZzd2tkbzVaRzRpOGN3bjV3VFNrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEY
      gIBAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tW
      YWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1Jl
      YWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      EvMuCgtDb25zb3J0aXVtcxLjLhKYLgoaQ2FyYm9uQWNjb3VudGluZ0NvbnNvcnRpdW0S+S0SzBYK
      C2F1ZGl0b3IxTVNQErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IxTVNQEu0FLS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvVENDQWFLZ0F3SUJBZ0lVWTNkdXpIRjdDL2g1NDR1VFFM
      ck9uWllUaGFNd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJB
      Z01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRH
      OXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd5TWpBeU5E
      VXpNMW9YRFRJMU1EWXhNVEF5TkRVek0xb3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJB
      Z01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBECkFRY0RRZ0FFYTJQUHg3WHFoTTV0RkxBU3hVQ1VSMCs0VzYzaG00ZGRLY2RjbDl1
      RkFzRzhHbEE5UFNBMjd0d2IKSmRwNUJueUxuTEpFYVdINyswNDMwZmhNZktWb1pLTkNNRUF3RHdZ
      RFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkMr
      dlg1Y0I5S09NWThhMDcrS3JXaWxxaytiNk1Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUURhbVZG
      WFlIVHR4TWZjVS9PR0ZOVlJ6aytSRmhLR3B0Mm1nbXdQTDV4VDV3SWgKQUxSNHJqZC85bHRjNmRr
      b29JM1Y5d2hkN0xHN3NLVHU5WGQxY2ZOUm9TeXoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi
      vggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHFnQXdJQkFnSVVaL3ZNeGd6
      MHdTRmNCeXZLS0IxSzJ3Wi9jNFV3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBn
      eER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFR
      S0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJ
      eU1EZ3lNakF5TkRZd01Gb1hEVEl6TURneU1qQXlOVEV3TUZvd2VqRUxNQWtHQTFVRUJoTUNRMGd4
      R2pBWQpCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SRXdEd1lEVlFRS0V3aEJkV1Jw
      ZEc5eU1URWZNQXdHCkExVUVDeE1GWVdSdGFXNHdEd1lEVlFRTEV3aGhkV1JwZEc5eU1URWJNQmtH
      QTFVRUF3d1NRV1J0YVc1QVlYVmsKYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      emowREFRY0RRZ0FFOU1TU016UmROWTdYY0kzVgpwL0lzbEE2V0Z2U2F2cHFCNmFLclFwR2lTUjBI
      NUhIZ2krbHU3ek95UEF1cVE4TGk4am1lVFZEWVgvQTlPMm9YCm5SaFRNS09DQVJvd2dnRVdNQTRH
      QTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCU255WlZN
      UGJUZ3V4OEE3a1dQV1JobHVsUWh0akFmQmdOVkhTTUVHREFXZ0JRdnIxK1hBZlNqakdQRwp0Ty9p
      cTFvcGFwUG0rakFrQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kwMVptTmlOelprT1RWaUxUWTVh
      bVpxCk1JR1BCZ2dxQXdRRkJnY0lBUVNCZ25zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmsKYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVlYVmth
      WFJ2Y2pFaUxDSm9aaTVGYm5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQmhkV1JwZEc5eU1TMXVa
      WFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpCmZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhB
      S3lEK0VMeE5KTGFaNUxEWUlGZ1p6ME5PUmlWWjh4Rmo5U00KUWdoQTltODdBaUJlUytvKzVvMloz
      MzByKzdiTHJNOStDZEJJYWpnV2pTQUtPN2gzTTF0cnFnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      VENDQWFLZ0F3SUJBZ0lVWTNkdXpIRjdDL2g1NDR1VFFMck9uWllUaGFNd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd5TWpBeU5EVXpNMW9YRFRJMU1EWXhNVEF5TkRVek0x
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFYTJQUHg3
      WHFoTTV0RkxBU3hVQ1VSMCs0VzYzaG00ZGRLY2RjbDl1RkFzRzhHbEE5UFNBMjd0d2IKSmRwNUJu
      eUxuTEpFYVdINyswNDMwZmhNZktWb1pLTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkMrdlg1Y0I5S09NWThhMDcrS3JXaWxxayti
      Nk1Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUURhbVZGWFlIVHR4TWZjVS9PR0ZOVlJ6aytSRmhL
      R3B0Mm1nbXdQTDV4VDV3SWgKQUxSNHJqZC85bHRjNmRrb29JM1Y5d2hkN0xHN3NLVHU5WGQxY2ZO
      Um9TeXoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAES
      HRIIEgYIARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIf
      CAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAES
      GxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJBZ0lVWUc0QkoyOGkwWmdoajBza2NIS1FvdzZHSHBvd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd5TWpBeU5EWTBPVm9YRFRJMU1E
      WXhNVEF5TkRZME9Wb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFOGRXbGNMdXN0dkRvVGNvT3o5VzBRMkVLaGVUcC9ma0cramJHSE9wKyt3UDhCNFdLbW9Z
      eStGWHYKVUI3WHJ0UzV0UVg3RFdacmhUNnRFeG1ucWwzaWNLTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRlBidVBKdHRRSEN2V3Uw
      MW13VFQ3VTdHekdjUE1Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJUURIUm5DQTJUR0FIaDlORnIr
      aGlUd09xRmJFTmhHeDVONEhRRktPQ09uditnSWcKZndhYlNKeExlZWplVkFlSUJCa1U0c01CY3g1
      YWlGSVVaTFVYbkkxTUc0UT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHVnQXdJQkFnSVVXVXo5TDdUeXAwSzkxMzhqbEJY
      aXVCekVkNGd3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3lNakF5TkRn
      d01Gb1hEVEl6TURneU1qQXlOVE13TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      Qkg3ZElNMVR0Y0ZVQzhzbgpuMlZaZ3ZKTDFFTVROL0RvWXI2ZCtqT2JqRjZ1aUw0WFgxd1RKSGJX
      Q3Z0VmhuYWNDdFpiRkRqUTlkMmhrY282CmxJMnNHMXlqZ2dFYU1JSUJGakFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVVHNGRaWTBlaVBKVExMQ243
      bG9GTG96c2pUNzB3SHdZRFZSMGpCQmd3Rm9BVTl1NDhtMjFBY0s5YQo3VFdiQk5QdFRzYk1adzh3
      SkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE5UZzRORFExWXpZME5DMDROMmh1Ck5qQ0Jqd1lJ
      S2dNRUJRWUhDQUVFZ1lKN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmgK
      WkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNkltRjFaR2wwYjNJeUlpd2lh
      R1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFXNUFZWFZrYVhSdmNqSXRibVYwSWl3aWFHWXVW
      SGx3WlNJNkltRmtiV2x1CkluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJRWZUUUdaSURRRFJn
      ZTI3S2dIbmJRMXBMUFpPTnNhMHN4b3IKWVY1L0JUWk1BaUFqNFZGN1p0TzVnUS9vUm1SdHdTZ09p
      NWpLN3ZvSGMvcEtvc3AreDF5Qnh3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJB
      Z0lVWUc0QkoyOGkwWmdoajBza2NIS1FvdzZHSHBvd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd5TWpBeU5EWTBPVm9YRFRJMU1EWXhNVEF5TkRZME9Wb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFOGRXbGNMdXN0dkRvVGNvT3o5
      VzBRMkVLaGVUcC9ma0cramJHSE9wKyt3UDhCNFdLbW9ZeStGWHYKVUI3WHJ0UzV0UVg3RFdacmhU
      NnRFeG1ucWwzaWNLTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRlBidVBKdHRRSEN2V3UwMW13VFQ3VTdHekdjUE1Bb0dDQ3FHClNN
      NDlCQU1DQTBnQU1FVUNJUURIUm5DQTJUR0FIaDlORnIraGlUd09xRmJFTmhHeDVONEhRRktPQ09u
      ditnSWcKZndhYlNKeExlZWplVkFlSUJCa1U0c01CY3g1YWlGSVVaTFVYbkkxTUc0UT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAa
      ERIPCgthdWRpdG9yMk1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAa
      DxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
