apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://143.198.247.194:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIIJsDNVplvv9sVzunvtUIfjJGgE/zqG0Rq/pWVnEVIeqEt5cCttcCthcCngKWggBEAEaBgiR
      m+iXBiIKc3lzY2hhbm5lbCpAZTg3N2UzZWI3MDQyMGM4ZjUwNzJkMjFiM2ZhOTU0N2M5OTg1NDA1
      MTE1NmRlZDg5OTM3NTQ1MjY5NGU4MjczZRIaEhjK6GffgjlNmMB6wfWUmjbAyP5KdwBwSNIS21sK
      2FsS1VsSnyoKB09yZGVyZXISkyoSjhYKCm9yZGVyZXJNU1AS/xUamxQKA01TUBKTFBKIFBKFFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVVNtQVJLb011Z1poTEM2NzAvVUlhbVlRblhiTXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRVd09EVXpNVFZhRncweU5UQTJNRFF3T0RVek1UVmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJXclRxRENDbUJaY1lDWGI3a1ZQWG1I
      T3VIdytpWUF3RjQ4c2p6TkF3cmNnSkNaODdGVVdQWms2Q2FYeERzCnF5dEtCTG0xdHFjUUhhS2ZM
      VDhoN1l6eW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVWUtHQVUxOFF6ZEppWmtpbCtTQUxTSTkwT05Zd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdOR0ZOTlNFOTF4RjBZK0RHOVJGNzNYeDRlSENwb3pnaVQrR080a3pmY3EwQ0lH
      N0RRcWhBCm5QMExWd2JYcmcreVk5cnZ2ZlBhQi84cUFPMHBmWVVEZ3l0RAotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKWCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMWpDQ0FueWdB
      d0lCQWdJVUEyOUIyT0I3ekFqaFlOdGowTVpiTXdqUnVUQXdDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TVRVd09EVTVNREJhRncweU16QTRNVFV3T1RBME1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJD
      cWVCKzMweGxjbVo5N2NJZjErNnkwK3pPaGcxdkpNSm1BNDJTQnU3RThMCnNlczRUTW1BYkhNZDZt
      ako0bG1oQmxkSDZYODhzQ3lHUml2MlBndGMxemFqZ2dFUU1JSUJEREFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVnMVRmOUo3OWp5dGxrUndMazh5
      VgpwV0c3MzRjd0h3WURWUjBqQkJnd0ZvQVVZS0dBVTE4UXpkSmlaa2lsK1NBTFNJOTBPTll3SkFZ
      RFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROamsxTkRoa09HTmpOaTF5Y2poMmVEQ0JoUVlJS2dN
      RUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYlds
      dUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSVRQaWFOWXdMUE4KMWF3Y3NOSjEzbDhZUXlX
      eHkvRS8xQWxKM2EzbTZUQm9BaUFYclE1aWlXTHI0L0gyak9GLzZvQTQwaVcvTlFmMwo5QlJaSVpx
      Mkc0OUk1UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrlBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVVNtQVJLb011Z1po
      TEM2NzAvVUlhbVlRblhiTXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRV
      d09EVXpNVFZhRncweU5UQTJNRFF3T0RVek1UVmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVJXclRxRENDbUJaY1lDWGI3a1ZQWG1IT3VIdytpWUF3RjQ4c2p6
      TkF3cmNnSkNaODdGVVdQWms2Q2FYeERzCnF5dEtCTG0xdHFjUUhhS2ZMVDhoN1l6eW8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      WUtHQVUxOFF6ZEppWmtpbCtTQUxTSTkwT05Zd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdOR0ZO
      TlNFOTF4RjBZK0RHOVJGNzNYeDRlSENwb3pnaVQrR080a3pmY3EwQ0lHN0RRcWhBCm5QMExWd2JY
      cmcreVk5cnZ2ZlBhQi84cUFPMHBmWVVEZ3l0RAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoG
      QWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyI0
      CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRlcmVyTVNQEAEaBkFkbWlucyoGQWRt
      aW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9u
      cxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxrUEQoNQ29u
      c2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9yZGVyZXIxLm9yZGVyZXItbmV0EIo3
      GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVZjNFaHhM
      SFZIejhES3NLQTl3U3Q5YmZYTEJNd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1q
      QTRNVFV3T0RVNU1EQmFGdzB5TXpBNE1UVXdPVEEwTURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJz
      d0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdW
      eVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05
      eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVwSE5Mdms0
      SUNlWWdlYllxdWdncU82YzZPYVZNRzFTRDRWekYKMjRvR0Y1SUs3TlpaRlJTUUZGdmJVYVMxQ25q
      UlY0MitxZnF4bndnNEdMa2c0RVNJbEtPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURB
      ZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJ
      d0FEQWRCZ05WSFE0RUZnUVU2T3RoR1JDNkFHd3czeC9zSjhYKzZvSzAyaWd3SHdZRFZSMGoKQkJn
      d0ZvQVVZS0dBVTE4UXpkSmlaa2lsK1NBTFNJOTBPTll3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEps
      Y2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0
      TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFp
      TENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVB
      L2NEeG4vZTl0cndVY3JtZ2pZMFdFMkdNamt4UlpkN3l1S1d2Cmk5OFI0OElDSUdmTzZ6T21kTG9O
      MjdUR3phdVhLa3g2L2FscWxrK0EvT0pHakNCdUUralYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NBcG1nQXdJQkFnSVVmM0Vo
      eExIVkh6OERLc0tBOXdTdDliZlhMQk13Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkK
      TWpBNE1UVXdPRFU1TURCYUZ3MHlNekE0TVRVd09UQTBNREJhTUcweEN6QUpCZ05WQkFZVEFrZENN
      UnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXla
      R1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhM
      bTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXBITkx2
      azRJQ2VZZ2ViWXF1Z2dxTzZjNk9hVk1HMVNENFZ6RgoyNG9HRjVJSzdOWlpGUlNRRkZ2YlVhUzFD
      bmpSVjQyK3FmcXhud2c0R0xrZzRFU0lsS09DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURx
      REFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9C
      QUl3QURBZEJnTlZIUTRFRmdRVTZPdGhHUkM2QUd3dzN4L3NKOFgrNm9LMDJpZ3dId1lEVlIwagpC
      Qmd3Rm9BVVlLR0FVMThRemRKaVpraWwrU0FMU0k5ME9OWXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pY
      SmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVky
      OXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlq
      b2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpY
      UWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFp
      RUEvY0R4bi9lOXRyd1Vjcm1nalkwV0UyR01qa3hSWmQ3eXVLV3YKaTk4UjQ4SUNJR2ZPNnpPbWRM
      b04yN1RHemF1WEtreDYvYWxxbGsrQS9PSkdqQ0J1RStqVgotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEY
      gIBAGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5z
      EvMuCgtDb25zb3J0aXVtcxLjLhKYLgoaQ2FyYm9uQWNjb3VudGluZ0NvbnNvcnRpdW0S+S0SzBYK
      C2F1ZGl0b3IxTVNQErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IxTVNQEu0FLS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvVENDQWFLZ0F3SUJBZ0lVVjJZZ2ZDcWphYmJycjlaMVBZ
      aERtbDZreWQwd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJB
      Z01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRH
      OXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd4TlRBNE5U
      UXpOMW9YRFRJMU1EWXdOREE0TlRRek4xb3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJB
      Z01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBECkFRY0RRZ0FFZGEzSEd5YkVzZkxrbFViTVFYLy9pM2R1N0xFQTdDMUx6NlFneE40
      RFRzQitrU2g4bXJuYmdkZEQKNW5OcStRYWExWk9za0VOdU9xYXVjU0REKzJSalg2TkNNRUF3RHdZ
      RFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRk1W
      WnVOUTcvZG90Q3FXbnQ0WUxIK0cyU1FrL01Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUUR1LzZp
      MFlmcUNqeXZwbVBTRi9IRnBla0VCdWU4TkN0bVZrNmx6S21nL1FRSWgKQUxNYS9JT0FBRmFhRmpm
      Y01iZXdJUStXaEpRdi8zRlIxL201Ty9tdS9aZ3cKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi
      vggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHFnQXdJQkFnSVVPVTV6dTYy
      NVNreDJsWU1CK2lMTVc1U25JNkl3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBn
      eER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFR
      S0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJ
      eU1EZ3hOVEE1TURJd01Gb1hEVEl6TURneE5UQTVNRGN3TUZvd2VqRUxNQWtHQTFVRUJoTUNRMGd4
      R2pBWQpCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SRXdEd1lEVlFRS0V3aEJkV1Jw
      ZEc5eU1URWZNQXdHCkExVUVDeE1GWVdSdGFXNHdEd1lEVlFRTEV3aGhkV1JwZEc5eU1URWJNQmtH
      QTFVRUF3d1NRV1J0YVc1QVlYVmsKYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      emowREFRY0RRZ0FFMlB2OWwrTHdIQSsvVTY1TApOeUt2TlRBUTBTVDBjMDRMU0ljZUhNbFVBRzU2
      N1FtdjJxSWFzWUVIRnYzNWk0YmEwSkhJRDN4WURNTDFweXR2Clo5UFdVYU9DQVJvd2dnRVdNQTRH
      QTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCVEo0QzJ6
      S0F0QTU2Nlhra0U1SkJSMlJ0bERaekFmQmdOVkhTTUVHREFXZ0JURldialVPLzNhTFFxbApwN2VH
      Q3gvaHRra0pQekFrQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kwM05EVm1OemhrWWpaaUxUZDBa
      SEZpCk1JR1BCZ2dxQXdRRkJnY0lBUVNCZ25zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmsKYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVlYVmth
      WFJ2Y2pFaUxDSm9aaTVGYm5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQmhkV1JwZEc5eU1TMXVa
      WFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpCmZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhB
      SWNGYzNvTkxycGprdzc3V1RRSEZYUTd6Qlh2NkNBSlM1c0IKeXBQOE1DTENBaUE5M0U2WGNRMFVa
      RDArWURrS3oweXl2RldzU3VoSnh6TFdCL2QraUlQV3JRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      VENDQWFLZ0F3SUJBZ0lVVjJZZ2ZDcWphYmJycjlaMVBZaERtbDZreWQwd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd4TlRBNE5UUXpOMW9YRFRJMU1EWXdOREE0TlRRek4x
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFZGEzSEd5
      YkVzZkxrbFViTVFYLy9pM2R1N0xFQTdDMUx6NlFneE40RFRzQitrU2g4bXJuYmdkZEQKNW5OcStR
      YWExWk9za0VOdU9xYXVjU0REKzJSalg2TkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRk1WWnVOUTcvZG90Q3FXbnQ0WUxIK0cyU1Fr
      L01Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUUR1LzZpMFlmcUNqeXZwbVBTRi9IRnBla0VCdWU4
      TkN0bVZrNmx6S21nL1FRSWgKQUxNYS9JT0FBRmFhRmpmY01iZXdJUStXaEpRdi8zRlIxL201Ty9t
      dS9aZ3cKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAES
      HRIIEgYIARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIf
      CAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAES
      GxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJBZ0lVYUlZa1ViRzNBUTE5OHBZN1lDSEJ5eUd6Y2pJd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TlRBNE5UWXdNMW9YRFRJMU1E
      WXdOREE0TlRZd00xb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFR3pMZk1kLzBQSkFJM0h1YjdDaVViTUVhenlpVk5XeGtieUNmd2R3YTY0VEZYYkcwamkw
      S0ozQTQKKy93b2lXbE9BbVlFR3NoR1NGZzkwWERkdE1QRndhTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkNVTlZyYTNsZ2lkUSt3
      RzNJVFMySDZtRDNwMU1Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNJRW1UR0RnRit0VFE1a1IwVU5u
      aktnY3BZVjI5eVh2QnhUWlBBVlU0Z0J1aUFpQUcKWUhhVjJiRVVFN1I1ektwaVdLNzlZN1R2b3I0
      MWpMVk95RGptSTRTVkVRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHVnQXdJQkFnSVVPMk5KSGlRQUkwVUtkQkZnenFq
      VkVSQUdaZnd3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hOVEE1TURV
      d01Gb1hEVEl6TURneE5UQTVNVEF3TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      QlA0UVpwbnBOOHpCckRuNAp1cTljUVdLMmMxcVMvZGMxQmtKZEgvWERSNXJzZzE2Qi9wTnMyK3lD
      dk4vbmQ0ZXFpVmJ1ZGRYT1ZDM1E0cElqCm9FSkVoRXVqZ2dFYU1JSUJGakFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVVUQk1ld3N5ald3THg3amt2
      TDJIZFo4Y2NmSFV3SHdZRFZSMGpCQmd3Rm9BVUpRMVd0cmVXQ0oxRAo3QWJjaE5MWWZxWVBlblV3
      SkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE5tWTJZelkyWkRWa05DMHljWEZxCmNqQ0Jqd1lJ
      S2dNRUJRWUhDQUVFZ1lKN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmgK
      WkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNkltRjFaR2wwYjNJeUlpd2lh
      R1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFXNUFZWFZrYVhSdmNqSXRibVYwSWl3aWFHWXVW
      SGx3WlNJNkltRmtiV2x1CkluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJQzY1bDQ0bi9vSjk3
      S09Qbi9yMUZDdHBqZXVXMklpaGpoOVEKRy9ieC9GMFdBaUJ1Skpqcm9nbVdtdXNqdVlOWWJkTGpP
      c0pPdEFXb1AraVpYVS9KSmN3eWN3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJB
      Z0lVYUlZa1ViRzNBUTE5OHBZN1lDSEJ5eUd6Y2pJd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd4TlRBNE5UWXdNMW9YRFRJMU1EWXdOREE0TlRZd00xb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFR3pMZk1kLzBQSkFJM0h1YjdD
      aVViTUVhenlpVk5XeGtieUNmd2R3YTY0VEZYYkcwamkwS0ozQTQKKy93b2lXbE9BbVlFR3NoR1NG
      ZzkwWERkdE1QRndhTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRkNVTlZyYTNsZ2lkUSt3RzNJVFMySDZtRDNwMU1Bb0dDQ3FHClNN
      NDlCQU1DQTBjQU1FUUNJRW1UR0RnRit0VFE1a1IwVU5uaktnY3BZVjI5eVh2QnhUWlBBVlU0Z0J1
      aUFpQUcKWUhhVjJiRVVFN1I1ektwaVdLNzlZN1R2b3I0MWpMVk95RGptSTRTVkVRPT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggSBggBEgII
      ABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggBEgIIABoP
      Eg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggAGhESDwoL
      YXVkaXRvcjJNU1AQARoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP//
      //8PGgZBZG1pbnMaSgoQT3JkZXJlckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0
      OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJf
      MBIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
