apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIJSCBdE0OweAUUpf4yKtr0gnx8brYNPjxPFXazdPfjDvEuJcCt9cCtxcCngKWggBEAEaBgi8
      nvaXBiIKc3lzY2hhbm5lbCpAZmJkN2U5ODJiY2IzZTQ5YmQ1NTM5NGY3NzgyOTllMmU2YzlkODY0
      NDkxY2E5OTZjNGRhYzQxZDZiZDllOWNmYRIaEhgPRzwatbZDYo2vglmjhvsvtifha8uhCnQS31sK
      3FsS2VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVU04T3l0cnhoY3pESzJIT1RuU05La1pHaVBlMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRjeE56QTBORFphRncweU5UQTJNRFl4TnpBME5EWmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFYZHRNc0hTNkpDNEUyM0FYaFdsTmdR
      cTVtVzdpVkVNL2hLZkVCRkJOc29obENyN3dzYlF5UWZnNWRjN3BRClFaSnNUVk9mNHhuK3VOZ2Jv
      U2IweFlibW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVR0lmWlR3VkVGN1dNNVZqcENjOEVyVjFDcDAwd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdjbXFRWWZuRTBIcTQzKzY2MktpZnZ5blZWM2hFU2c4WWN0QkJNSFdCdUhjQ0lR
      RCtHTkZvCnJEdk05ZU1nWUZpZHBMMk5sdUZOUUs0SWhuWTBRdkdzaENiRDVRPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFUQ0NB
      bnVnQXdJQkFnSVVPdXc3cUtzNXp1SGZVbXlFZ3lDaTdLWVBrbUF3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UY3hOekV4TURCYUZ3MHlNekE0TVRjeE56RTJNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCQlYvYTFsVGI1S00xWTlPR1FaTll5ZmNudlhTS3BqNE1kQTNIc1RSVnR1bwpKMmhRN0hPNUgz
      c1lYelErVzVyeXBRSUlIaE5ScGhkLzVWUDZOZ1UvRC9XamdnRVBNSUlCQ3pBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVOTh6Z3V6d0FxdUtleVRx
      WDhCdlAKdnRtRjNoc3dId1lEVlIwakJCZ3dGb0FVR0lmWlR3VkVGN1dNNVZqcENjOEVyVjFDcDAw
      d0l3WURWUjBSQkJ3dwpHb0lZWTJFdGRHOXZiSE10WXpSa1lqZzNOamRpTFhSbmVHMDVNSUdGQmdn
      cUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJcwpJbWhtTGxSNWNHVWlPaUpoWkcx
      cGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBaTBvdWZRaGY1cDFvCmF1U0xPdDhnNzZS
      ZDJwQnN1TGdBNGtKL0s4WkNPellDSUFubUhrYkNhNFJReEppQ0IyWmcxMTkwamw4dnJxL0UKcE1Y
      M0xWRDcreHRQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVU04T3l0cnhoY3pE
      SzJIT1RuU05La1pHaVBlMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRj
      eE56QTBORFphRncweU5UQTJNRFl4TnpBME5EWmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVFYZHRNc0hTNkpDNEUyM0FYaFdsTmdRcTVtVzdpVkVNL2hLZkVC
      RkJOc29obENyN3dzYlF5UWZnNWRjN3BRClFaSnNUVk9mNHhuK3VOZ2JvU2IweFlibW8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      R0lmWlR3VkVGN1dNNVZqcENjOEVyVjFDcDAwd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdjbXFR
      WWZuRTBIcTQzKzY2MktpZnZ5blZWM2hFU2c4WWN0QkJNSFdCdUhjQ0lRRCtHTkZvCnJEdk05ZU1n
      WUZpZHBMMk5sdUZOUUs0SWhuWTBRdkdzaENiRDVRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRlcmVyTVNQEAEa
      BkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMS
      FBIKCggKBFYyXzASABoGQWRtaW5zGtQRCg1Db25zZW5zdXNUeXBlEsIRErcRCghldGNkcmFmdBKq
      EQqTEQoUb3JkZXJlcjEub3JkZXJlci1uZXQQijcauggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQzh6Q0NBcG1nQXdJQkFnSVVhS2pXNTZuemdTR3owQ21aNmZtNThOTEtyTTh3Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERB
      NWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1UY3hOekV4TURCYUZ3MHlNekE0TVRjeE56
      RTJNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15
      OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpY
      SXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpq
      MENBUVlJS29aSXpqMERBUWNEUWdBRVBOd1daKzQ0THlSTHdlTTRGN0FSY1JFM0FRUXRHUUxvV0k4
      VApsems4SFZSUUdZci9tcVU0NGdWdTN3dU4vem1pVjVmRlppb3VVcmdFSE9BTHN2ZWZxcU9DQVNn
      d2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZ
      SUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVW1kK0lZWFZ5cmk0
      UGRVM0QrV0JoUnlJQll2QXdId1lEVlIwagpCQmd3Rm9BVUdJZlpUd1ZFRjdXTTVWanBDYzhFclYx
      Q3AwMHdPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdW
      eVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhK
      eklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpv
      aWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5
      CmZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE3M3ZkZ1Z1dEwwQzRoclk1SjRDTldqVkNWK0Y0
      dmxQSFVHR2IKeEk3UVlKOENJQ2gwQnVOWG10S3JVNjJ3eVJUZnprS1ozMEtya3lOemtYdGhHSkpu
      dXg2RAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJVWFLalc1Nm56Z1NHejBDbVo2Zm01OE5MS3JNOHdDZ1lJ
      S29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFE
      REE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRjeE56RXhNREJhRncweU16QTRNVGN4
      TnpFMk1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4
      TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXlaR1Z5
      WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApLb1pJ
      emowQ0FRWUlLb1pJemowREFRY0RRZ0FFUE53V1orNDRMeVJMd2VNNEY3QVJjUkUzQVFRdEdRTG9X
      SThUCmx6azhIVlJRR1lyL21xVTQ0Z1Z1M3d1Ti96bWlWNWZGWmlvdVVyZ0VIT0FMc3ZlZnFxT0NB
      U2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RB
      UVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVbWQrSVlYVnly
      aTRQZFUzRCtXQmhSeUlCWXZBd0h3WURWUjBqCkJCZ3dGb0FVR0lmWlR3VkVGN1dNNVZqcENjOEVy
      VjFDcDAwd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dtOXla
      R1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0ltRjBk
      SEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJ
      am9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhKbGNp
      SjkKZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTczdmRnVnV0TDBDNGhyWTVKNENOV2pWQ1Yr
      RjR2bFBIVUdHYgp4STdRWUo4Q0lDaDBCdU5YbXRLclU2Mnd5UlRmemtLWjMwS3JreU56a1h0aEdK
      Sm51eDZECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAgaBkFk
      bWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQS
      DhIECgIycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLzLgoLQ29uc29ydGl1bXMS4y4SmC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvkt
      EswWCgthdWRpdG9yMU1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVUJYSzhPelUraGo0OVpI
      TlRYRHU3bWdTei9iRXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE56
      RTNNRFl3TkZvWERUSTFNRFl3TmpFM01EWXdORm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRVZIZ0dRMUZXb2Nuck5HN2dQSFBtUHdpaU1DaFJNL3A2U3FU
      bHl0Kzhyem1CK1JGdWROUUIvYUpBCkhXSkFIN01ubWtmdFBza2pzcmhCakI3MUMvdmpncU5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZOYTNUcDJpT0lGdDE3ZkdlVC9QY0NTUGltVVVNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUNM
      RWU5R1dwVDZwUVMvM2NXTDZEdERwMHRtWndWM3o5Vm1BUDFtVkZEUG1BaUVBCjV2alNzMGJIdW5k
      VHVBZWRlTWJ1RzFrLzdTTzh0Tjh1dFh2U2x6MHRRckU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIr4ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXBxZ0F3SUJBZ0lVZEl1
      dHpuSWJROW1sbjlsV25JR1d1MVNPQzVjd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd4TnpFM01UTXdNRm9YRFRJek1EZ3hOekUzTVRnd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRUNBQVQ3bkd3K0Z0U216R3MKS2t3Y2NQRHVwNXZEd2xOM25lelRZbm1R
      RTZzRTdHcEZBUVo1OEVsZmhaVndHd2pXWjFVb2RxLyt2dWJ3cUR6OApPTUx0RmFPQ0FSb3dnZ0VX
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlJi
      MkZDWksrWHJmMnlUYXgvWUFya0FOdkJHUmpBZkJnTlZIU01FR0RBV2dCVFd0MDZkb2ppQmJkZTMK
      eG5rL3ozQWtqNHBsRkRBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDFOVGRtWW1ZM1lqWTJM
      WGMwTW01bwpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqRWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      UzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdS
      UUloQUw0Y3JLUUtyL2dsY2pZN2U5TmNic1Y1VUw4d0c2YlRJbkFnCmVEN21nZE5vQWlCWmQzYm9n
      SFplZWtVZWY4dVBjSUJKYWJ1QkM4UmFJbjNnQ1lSMjRKbm9UZz09Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL0RDQ0FhS2dBd0lCQWdJVUJYSzhPelUraGo0OVpITlRYRHU3bWdTei9iRXdDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE56RTNNRFl3TkZvWERUSTFNRFl3TmpFM01E
      WXdORm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRVZI
      Z0dRMUZXb2Nuck5HN2dQSFBtUHdpaU1DaFJNL3A2U3FUbHl0Kzhyem1CK1JGdWROUUIvYUpBCkhX
      SkFIN01ubWtmdFBza2pzcmhCakI3MUMvdmpncU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZOYTNUcDJpT0lGdDE3ZkdlVC9QY0NT
      UGltVVVNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUNMRWU5R1dwVDZwUVMvM2NXTDZEdERwMHRt
      WndWM3o5Vm1BUDFtVkZEUG1BaUVBCjV2alNzMGJIdW5kVHVBZWRlTWJ1RzFrLzdTTzh0Tjh1dFh2
      U2x6MHRRckU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHUmVhZGVycxIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8I
      ARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0S
      CBIGCAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9y
      Mk1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVVFFeFhRR0g3d0V6b3FDVDlHbGNwbEo3aUVC
      Y3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE56RTNNRGN5TVZvWERU
      STFNRFl3TmpFM01EY3lNVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRU1pbWFFOGJyeDc1SkNMMFhmdW91bDNFV2t2QXc1ZnUxVXNMMTQwY3J4TE5waG1u
      alhFbGJPQ0tDCmdxS0hBVXhkK01tQnZQNXN5RS81Q242S2FSTGZ3YU5DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZGc3FSYXlXOWpY
      T0J5L0h1NlBMMmc5SFUxRDNNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFENVlFZmxxL3paVGxD
      SS8zeDVhT3IydUFzY2Z5M1MwSHlrMEN6eHdOV3FId0lnClQvZ2YzMUN2NFRFV1hnZU9jcmR0MVVP
      TkRGZC9BY1htdlJDQnRNTHhEL2c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXB1Z0F3SUJBZ0lVSHc1SGdQTStXR05ySGR5
      RG0vWlMyclFlMlFnd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TnpF
      M01UWXdNRm9YRFRJek1EZ3hOekUzTWpFd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdO
      VkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4
      SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1N
      RWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VI
      QTBJQUJCTi9FS29tYkQ0REY2RkYKM3dPTDQ4cVNMZVI2S2J6ZGlCMW9idnhrZEdmS3V3VkJFR0JH
      RGlVbG12d1MxT2hCdG1Nd2NvaTIyVStidVJCMgppY2V0aGVHamdnRWFNSUlCRmpBT0JnTlZIUThC
      QWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVNkM4c3gwQmtZVk1H
      dy9UL01xQm90ampUdnNJd0h3WURWUjBqQkJnd0ZvQVVXeXBGckpiMk5jNEgKTDhlN284dmFEMGRU
      VVBjd0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXROemRpWXpVME9XUTROQzB5YTJnMgpaRENC
      andZSUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlM
      Q0poClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJ
      aXdpYUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lh
      R1l1Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUF4dzZJZ1JZ
      OUQweXM3U2hLTG83VjIva29PWm1FT2ZoYjR5Cko4UTg0M1R1QWlBRGlJMHczYUdobUpCTEpQVEZ6
      aFlEU25lWTlZK0dFWkVVNXNSRnBnaFFOZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4K
      BFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dB
      d0lCQWdJVVFFeFhRR0g3d0V6b3FDVDlHbGNwbEo3aUVCY3dDZ1lJS29aSXpqMEVBd0l3ClhERUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUI0WApEVEl5TURneE56RTNNRGN5TVZvWERUSTFNRFl3TmpFM01EY3lNVm93WERFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRU1pbWFFOGJyeDc1SkNM
      MFhmdW91bDNFV2t2QXc1ZnUxVXNMMTQwY3J4TE5waG1ualhFbGJPQ0tDCmdxS0hBVXhkK01tQnZQ
      NXN5RS81Q242S2FSTGZ3YU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFm
      OEVCQU1DQWFZd0hRWURWUjBPQkJZRUZGc3FSYXlXOWpYT0J5L0h1NlBMMmc5SFUxRDNNQW9HQ0Nx
      RwpTTTQ5QkFNQ0EwZ0FNRVVDSVFENVlFZmxxL3paVGxDSS8zeDVhT3IydUFzY2Z5M1MwSHlrMEN6
      eHdOV3FId0lnClQvZ2YzMUN2NFRFV1hnZU9jcmR0MVVPTkRGZC9BY1htdlJDQnRNTHhEL2c9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAES
      AggAGhESDwoLYXVkaXRvcjJNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIG
      CAESAggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAES
      AggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGlj
      eRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoG
      QWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0Rh
      dGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9yZGVyZXJBZGRyZXNzZXMS
      NhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5z
      Gg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
