apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: devorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIKmG4o37AwurmKLHJC9enYwF/RL0l4Lt84P4MYtPeZLjEt5cCttcCthcCngKWggBEAEaBgin
      n7mXBiIKc3lzY2hhbm5lbCpAMmVjYzNiZjFhMjg3MjM3MTVhYjg3OWUzMmQ0NTdiMjYwMjllYjQ3
      YzBmNDVmYzZjOTMzM2M5MGNmYjVjYjU0ZRIaEhhdpSQ7mopxNs3bOamYCKLJNpPW8gYXb4cS21sK
      2FsS1VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVVdWSTFIRVpab281dm5ocG1rV051Nk9Tdld3RXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURZeE1UQTRNamRhRncweU5UQTFNall4TVRBNE1qZGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJQRkFlQXp0Zzg4T0x3aUdSb3Bodmdr
      TG5nNC9rQkZSdjhsVmsvOXlSaTZ2Q2JDNlNWc1RHeTN0U1dzWkcrCm5pNHQ0b0RvaGJMQTl1cy9C
      RUNqN3ZObW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVbGpuaXJoZkpwZTl1Z1VNYm5KOU5sYVJiSFRZd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdJMFJsb0UzbVY5dmd0UTUxSnFwZGVuSERkUzEydnJ6NGJGa2tXZDBoSFcwQ0lR
      QzlrN0F4ClJNSnZmRyttNjdzM2J3NGdwQlltVkdCQm14ZjhqZ0NMZ1VpQzdBPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFEQ0NB
      bnVnQXdJQkFnSVVSTkg3SkMvMFRSTnJOcUZoeWpqSTJiOGNzWW93Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1EWXhNVEV4TURCYUZ3MHlNekE0TURZeE1URTJNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCSkJxRXJlU0tFWFhIYUlVYzgxRURuK1N5Qkkvdm1mdkU4NW5jVnNnU1NaOApPdnA0QlBENVNQ
      a2dSYzhOZUNUMzE0WU1ZN210RFVtYUlsOFltY2kzRktxamdnRVBNSUlCQ3pBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVRGpwcnMrSTNMZGlkcDE2
      dEc4cHUKSCtEb092NHdId1lEVlIwakJCZ3dGb0FVbGpuaXJoZkpwZTl1Z1VNYm5KOU5sYVJiSFRZ
      d0l3WURWUjBSQkJ3dwpHb0lZWTJFdGRHOXZiSE10TlRsbU9EVTNZMlkwTFhKcU1uaHdNSUdGQmdn
      cUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJcwpJbWhtTGxSNWNHVWlPaUpoWkcx
      cGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFTOW9RK2JWdkhmSmpTCnZKd0Q1Ny9xaE9l
      ZHF2T0d1YkhTV2VqTTRkaEFlUUlnTkkwcGR3WEptU09aS2hZWVFtTzRKTmJiWVZKZ1FYcUgKa01H
      SUtEb2dwU289Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVdWSTFIRVpab281
      dm5ocG1rV051Nk9Tdld3RXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURZ
      eE1UQTRNamRhRncweU5UQTFNall4TVRBNE1qZGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVJQRkFlQXp0Zzg4T0x3aUdSb3BodmdrTG5nNC9rQkZSdjhsVmsv
      OXlSaTZ2Q2JDNlNWc1RHeTN0U1dzWkcrCm5pNHQ0b0RvaGJMQTl1cy9CRUNqN3ZObW8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      bGpuaXJoZkpwZTl1Z1VNYm5KOU5sYVJiSFRZd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdJMFJs
      b0UzbVY5dmd0UTUxSnFwZGVuSERkUzEydnJ6NGJGa2tXZDBoSFcwQ0lRQzlrN0F4ClJNSnZmRytt
      NjdzM2J3NGdwQlltVkdCQm14ZjhqZ0NMZ1VpQzdBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRt
      aW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9yZGVyZXIx
      Lm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBt
      Z0F3SUJBZ0lVT0ZyTWhjc2NZWmVSRHlvUVhvbGZxVkNZam9Zd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5
      TFc1bGREQWVGdzB5Ck1qQTRNRFl4TVRFeE1EQmFGdzB5TXpBNE1EWXhNVEUyTURCYU1HMHhDekFK
      QmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFP
      QmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1U
      Rkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVtUEpiM2JJeTkwbStGRjRYRG5iZTFBTDZZSWdhZEl5TG5DUFEKQ0xQeDNYN3NERGZT
      a1pKU2U4elpySE9TTlZLcklUbk1DRVZheE0vb25qT3lTYWlhYmFPQ0FTZ3dnZ0VrTUE0RwpBMVVk
      RHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdE
      QVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVGeVRUczhFRkZsN3F5UXFIclUxcXVZYUJq
      MjR3SHdZRFZSMGoKQkJnd0ZvQVVsam5pcmhmSnBlOXVnVU1ibko5TmxhUmJIVFl3T3dZRFZSMFJC
      RFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNi
      M0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1a
      bWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXVi
      M0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9Q
      UVFEQWdOSEFEQkVBaUF0WDI5WE9Dd2dQcm9PU1p1Ym1RNzkyYW05TDZ6MW5WbTZLM1ZyCjRVT0NR
      Z0lnYlYvcDV6dHdBc1ZVNzBCVlNaNi9lbW5XUU5uN05YekZyelIxcUlkRDhuaz0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzhqQ0NB
      cG1nQXdJQkFnSVVPRnJNaGNzY1laZVJEeW9RWG9sZnFWQ1lqb1l3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1EWXhNVEV4TURCYUZ3MHlNekE0TURZeE1URTJNREJhTUcweEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJB
      TVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpq
      MERBUWNEUWdBRW1QSmIzYkl5OTBtK0ZGNFhEbmJlMUFMNllJZ2FkSXlMbkNQUQpDTFB4M1g3c0RE
      ZlNrWkpTZTh6WnJIT1NOVktySVRuTUNFVmF4TS9vbmpPeVNhaWFiYU9DQVNnd2dnRWtNQTRHCkEx
      VWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJ
      d0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVUZ5VFRzOEVGRmw3cXlRcUhyVTFxdVlh
      QmoyNHdId1lEVlIwagpCQmd3Rm9BVWxqbmlyaGZKcGU5dWdVTWJuSjlObGFSYkhUWXdPd1lEVlIw
      UkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1W
      c2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pF
      dWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtq
      T1BRUURBZ05IQURCRUFpQXRYMjlYT0N3Z1Byb09TWnVibVE3OTJhbTlMNnoxblZtNkszVnIKNFVP
      Q1FnSWdiVi9wNXp0d0FzVlU3MEJWU1o2L2VtbldRTm43Tlh6RnJ6UjFxSWREOG5rPQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hT
      aXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlu
      cxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Js
      b2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJ
      CgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLvLgoLQ29uc29ydGl1bXMS3y4SlC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvUt
      EsgWCgthdWRpdG9yMU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVU1nRytDaFdqV25JUEFl
      VFNJb004SHBzVUJIOHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURnd05q
      RXhNRGswTlZvWERUSTFNRFV5TmpFeE1EazBOVm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRTcrYmZ5ZjRjS1ExSnQ2YnRKVzROZVFXVDMwWnpVT1RUcFRn
      OGxvZkxsVnlMWFU2U2gvUHNZL1BiCmhTaTJMaTVCcUo2UnpkWmxBNnhtQmc1M0R6WThjNk5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZQZ1BjdXpFbzgyb2VOOWhGaEZMckVKZlpReVdNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFD
      ZEM1aVo1TmFhWnBkQXRYTHVIK3ByUk1CNmJacnhRZXlNR0ZuWWF5YUZqUUloCkFJN3JBSUlFd01M
      QmlnZWUwSG5paUNPaXVwUU9FS3lCZ2ROUGQyOHkreFAxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBxZ0F3SUJBZ0lVRGpF
      R21XRFhBZWZDNlRMbWQyNmZ6emI2NFl3d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd3TmpFeE1UY3dNRm9YRFRJek1EZ3dOakV4TWpJd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRStyT3JMbU9ITWxtdjRNaGYKZVpSc0g3ZWhrRk5HdmxNRUZjV1VlNU5l
      SnpJZE1iNW5PTENwVGJYVzh4YzJBd3pUSGFsSjVTVVlLVUh3cVBkKworOXJQanFPQ0FSb3dnZ0VX
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlRi
      RjNoUDFkOVBxMXkvNmhBdXFVN2JkNVFhckRBZkJnTlZIU01FR0RBV2dCVDREM0xzeEtQTnFIamYK
      WVJZUlM2eENYMlVNbGpBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDJPR1ptTnpZMVpqazJM
      WGhpYzJ3MgpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqRWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      UzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdS
      QUlnVzNpMnprQmZvVWw5UnRzQzc0aE5EbCtGWEVCRk8zQjNZV0lnCjgrMEV0UHNDSUF0d1p5Y2JB
      aTBNdkZRZmx3b3BUVHJNRVAvMTY4ams4L0NoalcwV3lMaGQKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      VENDQWFLZ0F3SUJBZ0lVTWdHK0NoV2pXbklQQWVUU0lvTThIcHNVQkg4d0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd3TmpFeE1EazBOVm9YRFRJMU1EVXlOakV4TURrME5W
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFNytiZnlm
      NGNLUTFKdDZidEpXNE5lUVdUMzBaelVPVFRwVGc4bG9mTGxWeUxYVTZTaC9Qc1kvUGIKaFNpMkxp
      NUJxSjZSemRabEE2eG1CZzUzRHpZOGM2TkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRlBnUGN1ekVvODJvZU45aEZoRkxyRUpmWlF5
      V01Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUUNkQzVpWjVOYWFacGRBdFhMdUgrcHJSTUI2Ylpy
      eFFleU1HRm5ZYXlhRmpRSWgKQUk3ckFJSUV3TUxCaWdlZTBIbmlpQ09pdXBRT0VLeUJnZE5QZDI4
      eSt4UDEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAES
      HRIIEgYIARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIf
      CAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAES
      GxIIEgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IyTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJBZ0lVZkhzWWVGVEc4ck5YamdveUsyV1d1Y1lKT1FRd0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3TmpFeE1URXdNVm9YRFRJMU1E
      VXlOakV4TVRFd01Wb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFb3pSSlNQREFRdVFkU0lTM2wyakJndHlmUi9zNFltWGhFOWVIazFsM3VyY0hTTWNlWlZs
      SUdHQWwKbHA5T3RrclhnSStoRy9pcFNGbmFTQXFYT0ZxaVFhTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRlA1V29ud2tsaHhFdlZM
      bkxNcW9VUGFjZFFsbE1Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJUUR5SW5iTDVhcExZaVQ1TnNQ
      Q05rZTBnUUFOWUI3WGZDTk5ybGJxM1ZVMlVBSWcKSGtmUnZXbFdadGhTa3VWa2NlM3Q4YnE2SEZ3
      RFJnaEhMMXdHcDlIOEpodz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlUQ0NBcHVnQXdJQkFnSVVWZHFKMDg2M0NTOGhNa0xqNmdy
      Sjg4SWQvRW93Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3dOakV4TVRr
      d01Gb1hEVEl6TURnd05qRXhNalF3TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFj
      VEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZrYVhSdmNqSXhIekFN
      CkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFaQmdOVkJBTU1Fa0Zr
      YldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      QkdJcmh0ckVYUk1Qa0c5Zgp6aTF4OWV5OE9abkhhT1o1MGF1KzUxTWxCUWNrRlFreWJ2MW1vUm5n
      UnUxazdQMHhtcjZFZmlSRm9Ka0xhT2VDCnVHUEFMWDJqZ2dFYU1JSUJGakFPQmdOVkhROEJBZjhF
      QkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVUySXI3UU4xemYvZ1hQOEU3
      ZmVDaml1V1plQVV3SHdZRFZSMGpCQmd3Rm9BVS9sYWlmQ1NXSEVTOQpVdWNzeXFoUTlweDFDV1V3
      SkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE56WmtORGM0T0RRMk5DMTBOemg0CllqQ0Jqd1lJ
      S2dNRUJRWUhDQUVFZ1lKN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmgK
      WkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNkltRjFaR2wwYjNJeUlpd2lh
      R1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFXNUFZWFZrYVhSdmNqSXRibVYwSWl3aWFHWXVW
      SGx3WlNJNkltRmtiV2x1CkluMTlNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJUURHZ2JlMytaa2g0
      SHZiaUo4V05LbnVndjNGUXRwZEZLdEYKUTB4WHJaZTFQd0lnRmtnb2ZqVjFtTXBoamFuSGNxRzNr
      MGpwMGkxc0RhekZ5bzJwZk9LNzEyUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJB
      Z0lVZkhzWWVGVEc4ck5YamdveUsyV1d1Y1lKT1FRd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNQjRYCkRUSXlNRGd3TmpFeE1URXdNVm9YRFRJMU1EVXlOakV4TVRFd01Wb3dYREVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFb3pSSlNQREFRdVFkU0lTM2wy
      akJndHlmUi9zNFltWGhFOWVIazFsM3VyY0hTTWNlWlZsSUdHQWwKbHA5T3RrclhnSStoRy9pcFNG
      bmFTQXFYT0ZxaVFhTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRlA1V29ud2tsaHhFdlZMbkxNcW9VUGFjZFFsbE1Bb0dDQ3FHClNN
      NDlCQU1DQTBnQU1FVUNJUUR5SW5iTDVhcExZaVQ1TnNQQ05rZTBnUUFOWUI3WGZDTk5ybGJxM1ZV
      MlVBSWcKSGtmUnZXbFdadGhTa3VWa2NlM3Q4YnE2SEZ3RFJnaEhMMXdHcDlIOEpodz0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAa
      ERIPCgthdWRpdG9yMk1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAa
      DxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1p
      bnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhh
      c2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaSgoQT3JkZXJlckFkZHJlc3NlcxI2EhsK
      GW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
