apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://143.198.247.194:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIISqPjSdRRbfvKW7Ez3xghHwlSFNjDMylsCokNoSpLPZEtpcCtdcCtRcCngKWggBEAEaBgi/
      ueeXBiIKc3lzY2hhbm5lbCpAY2FkMmQwMDgyZjE4ODY3NWQ4MWJhMDIxOWRmZDc4MThlYzRlMzJm
      OTQxNDM1N2RmMWUxNTNkMzY5ZDEwYjkzNhIaEhju+3ta7iKemmMiNkhK/mNS8T/Fq4tffcAS11sK
      1FsS0VsSmyoKB09yZGVyZXISjyoSihYKCm9yZGVyZXJNU1AS+xUalxQKA01TUBKPFBKEFBKBFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVVZRcENHMjZ6dUJ1RnpwNFZKY2tlcXFyZy9WY3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRVd05ESXhOVFphRncweU5UQTJNRFF3TkRJeE5UWmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJnNm9EL3pKV3IyZkRjY0ZIRWl3M2ho
      ZzFjWDJGNW96aVY4b2RMQnYzMlFyRnY2eE9SaHRDVmx0WTlSRnNmCnd1R1RZU1BhSGhCM256UzNu
      UHZRa0gvc28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVTExRUklaUXZSS1BCWVQ3MGxzRW1aV2pkY21rd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdZalNPcVhFS25oQUxMSFlKbUJsdE9qVHBMNVFuWnZJSldyeXorNnFPbDRnQ0lF
      UUMxSVRhCjZLQnBHaDVwNmdaeGcybDBMVm5KQWFNZ0VHOHp6T05pVWdadAotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKSCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMVRDQ0FueWdB
      d0lCQWdJVU03Q085elhNb3IyQXhSck5lVk9sRSs3SDgxTXdDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TVRVd05ETTBNREJhRncweU16QTRNVFV3TkRNNU1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJ
      bUUzVlFJV0ZldnFPNng0VVFSKzhhcnlDYzB1cjQxSVB1VUZPcDcxNkd5CjVHMWFiVlZMUlFHK2lK
      bTEvTjFnL1ZCREp5YW90NUFtUEd4Vnl1YzlET21qZ2dFUU1JSUJEREFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVJeitNSDRIYTZiT2pKbWIzRlNU
      bgo3K3JBbVRnd0h3WURWUjBqQkJnd0ZvQVVMTFFSSVpRdlJLUEJZVDcwbHNFbVpXamRjbWt3SkFZ
      RFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROamsxTkRoa09HTmpOaTFqZW5aMk5qQ0JoUVlJS2dN
      RUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYlds
      dUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdiTENudzR2T294QjgKU1FlYnBmaytDaWVTcGFV
      QjJkbUR0MkN2cHJxRnJsZ0NJRFFNMWoyYkpqU3BlVXcyQjhSaUVUL0N5TFlkQWllbApzNXA1SGUz
      MmxUNHkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVVlFwQ0cyNnp1QnVGenA0
      Vkpja2VxcXJnL1Zjd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVFV3TkRJ
      eE5UWmFGdzB5TlRBMk1EUXdOREl4TlRaYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEps
      Y2pFWApNQlVHQTFVRUF3d09ZMkV1YjNKa1pYSmxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DCkFBUmc2b0QvekpXcjJmRGNjRkhFaXczaGhnMWNYMkY1b3ppVjhvZExCdjMy
      UXJGdjZ4T1JodENWbHRZOVJGc2YKd3VHVFlTUGFIaEIzbnpTM25QdlFrSC9zbzBJd1FEQVBCZ05W
      SFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVMTFFS
      SVpRdlJLUEJZVDcwbHNFbVpXamRjbWt3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ1lqU09xWEVL
      bmhBTExIWUptQmx0T2pUcEw1UW5adklKV3J5eis2cU9sNGdDSUVRQzFJVGEKNktCcEdoNXA2Z1p4
      ZzJsMExWbkpBYU1nRUc4enpPTmlVZ1p0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyIz
      CgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRtaW5zIjQKBkFk
      bWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMa
      HwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRW
      Ml8wEgAaBkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRjZHJhZnQSqhEKkxEKFG9y
      ZGVyZXIxLm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4
      akNDQXBtZ0F3SUJBZ0lVSVR3SnFkUHVrcDFxUnFHc0xETmtIRlFnMDZrd0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1dmNt
      UmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVFV3TkRNME1EQmFGdzB5TXpBNE1UVXdORE01TURCYU1H
      MHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2Iy
      NHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5eVpHVnlaWEl4SFRBYkJn
      TlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lICktvWkl6ajBDQVFZSUtv
      Wkl6ajBEQVFjRFFnQUVyalJodStKSHd5dWh0TWROTHZHSU9NOXhPbVNIWmp0WnRsdXMKT1hYQmMv
      eDBLbm5qeTNUTzhXRmFQM0N2N2tnS040TlpnRVh0aDVBOW94L0w1Sm5RMzZPQ0FTZ3dnZ0VrTUE0
      RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFV
      SEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVSV0RCdkFtVjZ3T1hoUzJndlIz
      TTlyWDF2K0F3SHdZRFZSMGoKQkJnd0ZvQVVMTFFSSVpRdlJLUEJZVDcwbHNFbVpXamRjbWt3T3dZ
      RFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFNDR205eVpHVnlaWEl4TG1S
      bGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3SW1GMGRISnpJanA3SW1o
      bUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2liM0prWlhK
      bGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOQpmVEFLQmdn
      cWhrak9QUVFEQWdOSEFEQkVBaUFDb2xJdEEzUGxYVlNNT0Z0RDFnaHFCc1EwM1N1T3FFaWk0VG5u
      CnlVSUtQQUlnYlZzN2l5eTZNaU5zaDNOMWw0dUI1MnlqUjhpUStNLzA3bGNEWmhZdTNVcz0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      QzhqQ0NBcG1nQXdJQkFnSVVJVHdKcWRQdWtwMXFScUdzTEROa0hGUWcwNmt3Q2dZSUtvWkl6ajBF
      QXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2
      Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1UVXdORE0wTURCYUZ3MHlNekE0TVRVd05ETTVNREJh
      TUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVr
      YjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFi
      QmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRXJqUmh1K0pId3l1aHRNZE5MdkdJT005eE9tU0haanRadGx1cwpPWFhC
      Yy94MEtubmp5M1RPOFdGYVAzQ3Y3a2dLTjROWmdFWHRoNUE5b3gvTDVKblEzNk9DQVNnd2dnRWtN
      QTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJC
      UVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVVJXREJ2QW1WNndPWGhTMmd2
      UjNNOXJYMXYrQXdId1lEVlIwagpCQmd3Rm9BVUxMUVJJWlF2UktQQllUNzBsc0VtWldqZGNta3dP
      d1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhM
      bVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJ
      bWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmta
      WEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtC
      Z2dxaGtqT1BRUURBZ05IQURCRUFpQUNvbEl0QTNQbFhWU01PRnREMWdocUJzUTAzU3VPcUVpaTRU
      bm4KeVVJS1BBSWdiVnM3aXl5Nk1pTnNoM04xbDR1QjUyeWpSOGlRK00vMDdsY0RaaFl1M1VzPQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJ
      QmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMa
      BkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcS
      DQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlu
      cyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMS8y4K
      C0NvbnNvcnRpdW1zEuMuEpguChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1bRL5LRLMFgoLYXVk
      aXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQi9UQ0NBYUtnQXdJQkFnSVVSSGxNTTRjdURSekhnQmlhai9odTRD
      MkFTNXN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hOVEEwTWpNek1G
      b1hEVEkxTURZd05EQTBNak16TUZvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1U
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUUrYUFueE96YXJDZ3hEd0poM3cxMk5VY05FL2tSQ0ZKdEE4Mi9aUHhFdktp
      eTg4Wmt6SWZiT20wUwozUXJLMEU5RzhxNWtJcm8rWHNHZzNYQldtb3pkSDZOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGTkNiTHRh
      cnUvd2ErZWRSNDJhZVN4Q3VXbkpNTUFvR0NDcUcKU000OUJBTUNBMGtBTUVZQ0lRRE0vclZ2NWxv
      REdJc3dUYnZjeWdRUXVtaGRXWi9CQk83ajI4QUVsMkVwUXdJaApBTVFhMWhUSGxJcWdyeGNmaDBl
      WklZcHZUa2ZvSlYwQzVwNG9KMVRkT2ZXZgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJVWRLUVNMaEdBMXVi
      dWdwb3NRVWdRTUlnQ1JUTXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURn
      eE5UQTBNemN3TUZvWERUSXpNRGd4TlRBME5ESXdNRm93ZWpFTE1Ba0dBMVVFQmhNQ1EwZ3hHakFZ
      CkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFLRXdoQmRXUnBkRzl5
      TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5TVRFYk1Ca0dBMVVF
      QXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBE
      QVFjRFFnQUVGSHFSYXBoRGI1QzlVSnR6CkNVRndjRmtYUjlUUm1FL2pFZE9jUXU4KzJNOUl1c1Uw
      Rm5XeVU0NXk1UnU4N1RxN3FHUXJidGlKUFdmaFBLVVMKSEt6VjVhT0NBUm93Z2dFV01BNEdBMVVk
      RHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJSZWYwVjlOT1Mv
      OEd1NUxJNUpOdk42MXdtWjdqQWZCZ05WSFNNRUdEQVdnQlRRbXk3V3E3djhHdm5uClVlTm1ua3NR
      cmxweVREQWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzTkRWbU56aGtZalppTFRSdFkySnoK
      TUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFa
      U0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWVhWa2FYUnZj
      akVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBkRzl5TVMxdVpYUWlM
      Q0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFJMHpk
      UGE3YngzSWIrUXI2NCtzMEpUSEhrS3RMeXFFNXdHRwoxWkZsZnlaNUFpQjZESkN2VDRsVEtCSDFx
      RzhHbzAzdVRWWXRZS1RoTGhybHk3TkhJVWU1N2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      CkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9UQ0NB
      YUtnQXdJQkFnSVVSSGxNTTRjdURSekhnQmlhai9odTRDMkFTNXN3Q2dZSUtvWkl6ajBFQXdJdwpY
      REVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hOVEEwTWpNek1Gb1hEVEkxTURZd05EQTBNak16TUZvd1hE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUUrYUFueE96YXJD
      Z3hEd0poM3cxMk5VY05FL2tSQ0ZKdEE4Mi9aUHhFdktpeTg4Wmt6SWZiT20wUwozUXJLMEU5Rzhx
      NWtJcm8rWHNHZzNYQldtb3pkSDZOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhR
      OEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGTkNiTHRhcnUvd2ErZWRSNDJhZVN4Q3VXbkpNTUFv
      R0NDcUcKU000OUJBTUNBMGtBTUVZQ0lRRE0vclZ2NWxvREdJc3dUYnZjeWdRUXVtaGRXWi9CQk83
      ajI4QUVsMkVwUXdJaApBTVFhMWhUSGxJcWdyeGNmaDBlWklZcHZUa2ZvSlYwQzVwNG9KMVRkT2ZX
      ZgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYI
      ARICCAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgII
      ABoREg8KC2F1ZGl0b3IxTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMqBkFkbWlucxLMFgoLYXVkaXRvcjJNU1ASvBYa
      1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVDbWlVbXpFZ0JNM0tNU2ZuRzRkR3VOMkxyNGN3Q2dZSUtv
      Wkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hOVEEwTWpRMU9Gb1hEVEkxTURZd05E
      QTBNalExT0Zvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFn
      QUVveXAwM0hPcmRrTGtzVm1TL2RQOUtEejA1MkZpMitiUUNEU1hQNWJPRVhWbno2elFkRjRvdzlj
      UApNSTRXM1g1Mjh2Ti9DS1lBZmYyTlZEUTVTMVVoc2FOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdF
      Qi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQ0dHM0MrYmNGTzBIZFFqOE9v
      dTkxaGVNU01WTUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lGSS82Q1Iwam5va3B3MEJWamFoc3RN
      elQxQmFoWkx3OStnUEtlTW1jSlFvQWlFQQo1YTdvY0ZqZENIWDlrN2RYTGh6ZE5GdUNMNWJhYTVK
      TzlFOW9hdzNOSWw0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOVRDQ0FwdWdBd0lCQWdJVUZ5SFFaVDRlb3B0c2FNZzBZSVl4RVho
      NHVna3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpF
      WU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE5UQTBOREl3TUZv
      WERUSXpNRGd4TlRBME5EY3dNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFaCkJnTlZCQWNURWpV
      eExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2Y2pJeEh6QU0KQmdO
      VkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05WQkFNTUVrRmtiV2x1
      UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTGFx
      WStWWVQwNkgxL2ZLCi9TN1JMZm5JWGsvSDZraEFsSHFabGdRNGFLdHlCZzVFZ2ZESjZWRXErQ1dO
      TDNEZzV6MXZjTDhOTll2UElGajQKWkdvV3BFV2pnZ0VhTUlJQkZqQU9CZ05WSFE4QkFmOEVCQU1D
      QjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVWFLYzRZNGh2VjNzRHcwRFZBSFAy
      bjZLcFkvOHdId1lEVlIwakJCZ3dGb0FVSVliY0w1dHdVN1FkCjFDUHc2aTczV0Y0eEl4VXdKQVlE
      VlIwUkJCMHdHNElaWTJFdGRHOXZiSE10Tm1ZMll6WTJaRFZrTkMwMk5HTm8KYWpDQmp3WUlLZ01F
      QlFZSENBRUVnWUo3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaApaRzFw
      YmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1GMVpHbDBiM0l5SWl3aWFHWXVS
      VzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlYVmthWFJ2Y2pJdGJtVjBJaXdpYUdZdVZIbHda
      U0k2SW1Ga2JXbHUKSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ0pFTElGTmlOdE41UlVZ
      Qjkyam1sZlA0NXJqU0hsQVc5dAp3SUdZL2I3bHNBSWdmaTM3dnZIUkFWZzRTTGVjRTJFV0hnS05H
      bFhvOE0rQ0xCZ0xrK2FnNCtNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZT
      SEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVD
      bWlVbXpFZ0JNM0tNU2ZuRzRkR3VOMkxyNGN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdE
      d1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1C
      NFgKRFRJeU1EZ3hOVEEwTWpRMU9Gb1hEVEkxTURZd05EQTBNalExT0Zvd1hERUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1G
      a3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVveXAwM0hPcmRrTGtzVm1TL2RQOUtE
      ejA1MkZpMitiUUNEU1hQNWJPRVhWbno2elFkRjRvdzljUApNSTRXM1g1Mjh2Ti9DS1lBZmYyTlZE
      UTVTMVVoc2FOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0Fh
      WXdIUVlEVlIwT0JCWUVGQ0dHM0MrYmNGTzBIZFFqOE9vdTkxaGVNU01WTUFvR0NDcUcKU000OUJB
      TUNBMGdBTUVVQ0lGSS82Q1Iwam5va3B3MEJWamFoc3RNelQxQmFoWkx3OStnUEtlTW1jSlFvQWlF
      QQo1YTdvY0ZqZENIWDlrN2RYTGh6ZE5GdUNMNWJhYTVKTzlFOW9hdzNOSWw0PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoREg8KC2F1
      ZGl0b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggBEgIIABoPEg0K
      C2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1
      ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMS
      CAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5z
      Gi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaSgoQT3JkZXJl
      ckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoA
      CgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
