apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa077027a6c1c43ff8b037247269814a-1850677720.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIEpCs+mbutPtydqcrNQHkA829Ubb4V9SG8C7vSSDaVHREt5cCttcCthcCngKWggBEAEaBgi5
      2L+XBiIKc3lzY2hhbm5lbCpAZDk4ZmNjMGY2NmYxY2M1OTc2NDA5YTI4MDUxMGU0NTY2OWYzOWRk
      NTExMjExZjRhZTEwZDA3Y2UwNzMzNjcxZRIaEhhxQhSB4yozyhGEtyWYM+ovG2gBnJ5lDn8S21sK
      2FsS1VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVVdhVi83MHVkeDJlWWhBM3ZHUlBkNXBEeHpjNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURjeE5UUTVOVFZhRncweU5UQTFNamN4TlRRNU5UVmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFUTUZCQU1hTXE1VkJBaXNTdlI0WVZt
      U2tWdS9mQk9LKzltWmhMMHYxVnl2UzBSdmVtN1lmeVErb254NlpLClpTUFdIUXpudWVtS1B6NnV4
      VUpQQTArZW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVeksrNSs0WWYrYWV6Slgxajk2VXQyendOdm1Vd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdlbzJSRXZPN09TOVA3OHJWRVdEa1dpL3U5c1p5R3lNVXNmNlJwQytXT2ZVQ0lR
      REl3REpkCmdTc1NlYTFNM3ZFMzV3V0R4WmVwTlp4UU56Y1picTAvVkh4K3hnPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFUQ0NB
      bnlnQXdJQkFnSVVMSCs1RTNQOXJwMkNwYmgxa0IxenFrRmlqYm93Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1EY3hOVFUxTURCYUZ3MHlNekE0TURjeE5qQXdNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCTHd4REhpZStNYTVBSDhsVFVac2VNWnltN2YyaHdFZ21vOXEwVXVJR1lZSApzK2JrYzFMY1g1
      aEYwOGxiWG93MXNkSzl5S0ZGNGd6SmYvYmdCOHkvTzM2amdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVK1oxWmI4bzFWdE9GbWhx
      cjhaaW0KUGVFNW5Pc3dId1lEVlIwakJCZ3dGb0FVeksrNSs0WWYrYWV6Slgxajk2VXQyendOdm1V
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TnprNU5EWmlPVFUxWWkxNGFuZHpkakNCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnSEtZR1BLbVlEQzJNCmpmNHIyczJEYW01
      dm5zaTVCREF1QWI3bmg4WllTaFFDSUVQV2RqWHpDRzdPL2FEUjkyYUxuWS9WNWpnWTdacWsKMUVt
      RytqQllRYXVlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVdhVi83MHVkeDJl
      WWhBM3ZHUlBkNXBEeHpjNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURj
      eE5UUTVOVFZhRncweU5UQTFNamN4TlRRNU5UVmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVFUTUZCQU1hTXE1VkJBaXNTdlI0WVZtU2tWdS9mQk9LKzltWmhM
      MHYxVnl2UzBSdmVtN1lmeVErb254NlpLClpTUFdIUXpudWVtS1B6NnV4VUpQQTArZW8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      eksrNSs0WWYrYWV6Slgxajk2VXQyendOdm1Vd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdlbzJS
      RXZPN09TOVA3OHJWRVdEa1dpL3U5c1p5R3lNVXNmNlJwQytXT2ZVQ0lRREl3REpkCmdTc1NlYTFN
      M3ZFMzV3V0R4WmVwTlp4UU56Y1picTAvVkh4K3hnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRlcmVyTVNQEAEa
      BkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVv
      dXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENh
      cGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa1BEKDUNvbnNlbnN1c1R5cGUSwhEStxEK
      CGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVyLW5ldBCKNxq6CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOGpDQ0FwbWdBd0lCQWdJVVdiUzUyT3prdVJpOUJibVJNcGJMRmxX
      YjMrRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJj
      d0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURjeE5UVTFNREJhRncw
      eU16QTRNRGN4TmpBd01EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFz
      VEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3
      RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFQ1FQenZyUkh3cXB0aEI2Q1lYTFd2Rmgr
      emNSVWNDVFRmNUlkCkgrZXJ5SU50RC9PUWdva3lxQm9QS2ZLNVNKTjBWSExJaHlOK3UzU1N6ZDZz
      ZkVVZVFhT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dy
      QmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FV
      cEdySmF0aTVyUldXcjUrS2prQ0JZTnlRa3Vvd0h3WURWUjBqCkJCZ3dGb0FVeksrNSs0WWYrYWV6
      Slgxajk2VXQyendOdm1Vd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dC
      QkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2li
      M0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCd2drYUs0azU1Umt3V2h0eENU
      Y0owUUI2VExzNGN6Y0JieDRqcApwcDhaMGdJZ0piMklzdGtYY0prcEJ5bGFrejE4VEtkcHk4b3Mr
      MFRXcmhIWXliQ1BFUUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQXBtZ0F3SUJBZ0lVV2JTNTJPemt1Umk5QmJtUk1wYkxG
      bFdiMytFd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNRGN4TlRVMU1EQmFG
      dzB5TXpBNE1EY3hOakF3TURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFN
      UzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpC
      QXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1G
      a3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVDUVB6dnJSSHdxcHRoQjZDWVhMV3ZG
      aCt6Y1JVY0NUVGY1SWQKSCtlcnlJTnREL09RZ29reXFCb1BLZks1U0pOMFZITEloeU4rdTNTU3pk
      NnNmRVVlUWFPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJn
      Z3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVwR3JKYXRpNXJSV1dyNStLamtDQllOeVFrdW93SHdZRFZSMGoKQkJnd0ZvQVV6Sys1KzRZZith
      ZXpKWDFqOTZVdDJ6d052bVV3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNp
      MXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3
      Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpv
      aWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJ3Z2thSzRrNTVSa3dXaHR4
      Q1RjSjBRQjZUTHM0Y3pjQmJ4NGpwCnBwOFowZ0lnSmIySXN0a1hjSmtwQnlsYWt6MThUS2RweThv
      cyswVFdyaEhZeWJDUEVRST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Js
      b2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJ
      CgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLvLgoLQ29uc29ydGl1bXMS3y4SlC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvUt
      EswWCgthdWRpdG9yMk1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dBd0lCQWdJVVFOaE5jc2phdEpOdys5
      VWVkYmZnNVNsZ2ZlUXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURnd056
      RTFOVEl5T1ZvWERUSTFNRFV5TnpFMU5USXlPVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRUhkUkkxYnNRbW5NZ3F4bVFVUFJWZGtXRVRRd0xSdWFlaGxm
      WGdua0FCRlJJaHBjcmpsRmJhTVMrCkZxY0laR2lKd1pjMzdSUW82bldRdTdZQWN5SGRCcU5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZNTGJvZ1RkRGZJTGQwTU1BY3lmTlp2VW9IOWZNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUJp
      Zllid2dzODFZdzB5S1BGUjhjdUllVmpTWTMrZkF0YlZ1d3VTTDFMSFNBaUEyCmZvOGlrYTFYbUg1
      UndqOVRBS09aYTdlQkFRaktGRCsrZ0hQamVKc1B2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIr4ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXBxZ0F3SUJBZ0lVVmpL
      R3J2SnpLOWZOK0p4NDF1cTU1VERTSFFNd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRY
      CkRUSXlNRGd3TnpFMU5Ua3dNRm9YRFRJek1EZ3dOekUyTURRd01Gb3dlekVMTUFrR0ExVUVCaE1D
      UjBJeEd6QVoKQmdOVkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1J
      UVhWa2FYUnZjakl4SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4
      R3pBWkJnTlZCQU1NRWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VH
      Q0NxR1NNNDlBd0VIQTBJQUJHU3QydTFFNG1WMmRZWEgKNWUrSjZnUUNDWjhYVUs4OUYzN1NxTnV5
      c3V2Mll6S3lvWnV1eWlMNFhkNS82eEk2a0FMekZSR2l2eStrUSthZgpzUGlUeTdtamdnRVpNSUlC
      RlRBT0JnTlZIUThCQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FV
      WkU3cnFzT3dTMTZUT3NYSnR2RkVKSEVZVVpJd0h3WURWUjBqQkJnd0ZvQVV3dHVpQk4wTjhndDMK
      UXd3QnpKODFtOVNnZjE4d0l3WURWUjBSQkJ3d0dvSVlZMkV0ZEc5dmJITXRaR1ppWTJNMFl6UTBM
      WEI0TmpoMgpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqSWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      aTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdS
      UUloQU1NamtXcFJUWnk5VzI0M2QwZmk4eFo0WFR1UUVtNldBeTRJCk1sU3NmbkVmQWlCdjBVY1dh
      dkY3Y3ZaMndUMnBsQ3RreWUyMDZoZDBHMjdNNE5xK3BOenlDQT09Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCK3pDQ0FhS2dBd0lCQWdJVVFOaE5jc2phdEpOdys5VWVkYmZnNVNsZ2ZlUXdDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURnd056RTFOVEl5T1ZvWERUSTFNRFV5TnpFMU5U
      SXlPVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUhk
      UkkxYnNRbW5NZ3F4bVFVUFJWZGtXRVRRd0xSdWFlaGxmWGdua0FCRlJJaHBjcmpsRmJhTVMrCkZx
      Y0laR2lKd1pjMzdSUW82bldRdTdZQWN5SGRCcU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZNTGJvZ1RkRGZJTGQwTU1BY3lmTlp2
      VW9IOWZNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUJpZllid2dzODFZdzB5S1BGUjhjdUllVmpT
      WTMrZkF0YlZ1d3VTTDFMSFNBaUEyCmZvOGlrYTFYbUg1UndqOVRBS09aYTdlQkFRaktGRCsrZ0hQ
      amVKc1B2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoLRW5kb3JzZW1l
      bnQSKRIfCAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMS
      KRIfCAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIf
      CAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARId
      EggSBggBEgIIABoREg8KC2F1ZGl0b3IyTVNQEAEaBkFkbWlucyoGQWRtaW5zEsgWCgthdWRpdG9y
      MU1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMU1TUBLtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dBd0lCQWdJVWIrRXg0N3VWSDFUc05YekNmNmYrazhxV0c1
      Y3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURnd056RTFOVEV4TTFvWERU
      STFNRFV5TnpFMU5URXhNMW93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRWkvRmVmc1R1NytUOE56S014MGZZRjZkelprVm90VDdOSEJyTGRGK280WTFJU0hZ
      SVowSFY4K0lqCm1leHdmeDN3RFN6SHdmOW5uSWJKTkJhaXpYRTM1S05DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZDZzRYTWxTejQ0
      NkJOWVJpR3JpTFhsYS9IT25NQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUN6NTMybEJYK2o0TnpO
      R01waVlqdk1ZYWJ1NDd5THdiWUZMQ3RKek05eDlBaUFQCmo2cXZXRDBRS0ZFakhncEFTR1p4Uk9w
      WWZIQVVoK2ZabEg0LzZqdUdVdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVVk1uYWsvY0FsZUNNbnNH
      Mk5RenRObmUyMk1rd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdO
      VkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd3TnpF
      MU5UWXdNRm9YRFRJek1EZ3dOekUyTURFd01Gb3dlakVMTUFrR0ExVUVCaE1DUTBneEdqQVkKQmdO
      VkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hCZFdScGRHOXlNVEVm
      TUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEViTUJrR0ExVUVBd3dT
      UVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNE
      UWdBRVh2TVRVeElkSTJvVE5Bd0EKNDE0L081ekpBYUF6b3J2QTlxL1hWNXdDb1B1b0RVOXpjdGU1
      QmE1RUc3cjVYZFB2MVRnNEFkSGJRaXBsMXJnNQpoRWpuRmFPQ0FSa3dnZ0VWTUE0R0ExVWREd0VC
      L3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlNPYWw4Ujk3SGFGOUZ6
      N3NvclcwekwrUmZnY1RBZkJnTlZIU01FR0RBV2dCUW9PRnpKVXMrT09nVFcKRVlocTRpMTVXdnh6
      cHpBakJnTlZIUkVFSERBYWdoaGpZUzEwYjI5c2N5MWlPR1ppWkdZM1kyUXROVFkxYkhNdwpnWThH
      Q0NvREJBVUdCd2dCQklHQ2V5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZ
      V1J0CmFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmhkV1JwZEc5eU1TSXNJ
      bWhtTGtWdWNtOXMKYkcxbGJuUkpSQ0k2SWtGa2JXbHVRR0YxWkdsMGIzSXhMVzVsZENJc0ltaG1M
      bFI1Y0dVaU9pSmhaRzFwYmlKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBNG5tY1hrZEp5
      RmxwdFNNR1FNNVRPU1B4ZElOazVPcDQ5QmV0ClNjaFFQaTBDSUVpeDZ5Tk92djYwVy83WmZSRzNv
      c3l6V2x4M0hQWFJVQlcwSDlUSFkrNTYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJB
      Z0lVYitFeDQ3dVZIMVRzTlh6Q2Y2ZitrOHFXRzVjd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJt
      VjBNQjRYCkRUSXlNRGd3TnpFMU5URXhNMW9YRFRJMU1EVXlOekUxTlRFeE0xb3dYREVMTUFrR0Ex
      VUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFaS9GZWZzVHU3K1Q4TnpLTXgw
      ZllGNmR6WmtWb3RUN05IQnJMZEYrbzRZMUlTSFlJWjBIVjgrSWoKbWV4d2Z4M3dEU3pId2Y5bm5J
      YkpOQmFpelhFMzVLTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRkNnNFhNbFN6NDQ2Qk5ZUmlHcmlMWGxhL0hPbk1Bb0dDQ3FHClNN
      NDlCQU1DQTBjQU1FUUNJQ3o1MzJsQlgrajROek5HTXBpWWp2TVlhYnU0N3lMd2JZRkxDdEp6TTl4
      OUFpQVAKajZxdldEMFFLRkVqSGdwQVNHWnhST3BZZkhBVWgrZlpsSDQvNmp1R1V3PT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAa
      ERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARIC
      CAAaDxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAa
      DxINCgthdWRpdG9yMU1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
