apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a98fe9a1d4dbd422fa7db7c78066059a-2533884.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIKg22i4OHUOBKPRcNA8OdVa1+BcoQzGpj8blRDTJHCozEuZcCuNcCuBcCngKWggBEAEaBgiu
      rPGXBiIKc3lzY2hhbm5lbCpAZTJlNGNkNDA2OGVjNWZjZTBkNmJlZjgzMDUxN2FlNWE5OTM0NjNl
      NjE3ZWYxZjFjYzg4YzZkMmI3MTY1MzYwYxIaEhjBWB9hITbNGn51svkuxsrlT40YvTFaKooS41sK
      4FsS3VsSpyoKB09yZGVyZXISmyoSlhYKCm9yZGVyZXJNU1AShxYaoxQKA01TUBKbFBKQFBKNFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVUhXS0pWVDc0dDJicFU4Q3duZHp6UWduUlhCSXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRjd01qTXhOVGxhRncweU5UQTJNRFl3TWpNeE5UbGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRTZmRzTmhJcWlDVXFrU1JKRU5ROTM1
      WXprSHh3Vm5WK28yNmhtOUV0TUQ5clhLRHozczcxd3dmYnZkVlB4Cmd3MmJHY085MVJjSmphQm9k
      Uk9GTWo5aG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVSGtlei9DMmM3TkVxdmFjNlUyUXdyN041MDBNd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdVNWRlaWNZTzlyZjBWb2tpWWs3OTRqTGhTUVgrQWowU0lkczFGYWFNYzc0Q0lR
      RDJjT3ErCkhQM0R6TjcyZHZHVlFXcVEzeSt1am1sNVM3UGhkWFYxUDY1VktBPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoilggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFqQ0NB
      bnlnQXdJQkFnSVVEajF0TUlxZ1orNjY4clpIcHlac1RzdkYzWEV3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UY3dNak0xTURCYUZ3MHlNekE0TVRjd01qUXdNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCS2NOWmk2K0ZpYWZRdGh2amhhZ1AvUVdlNXhKVGNtT1FHdUd5bm9IWlhsQgpNbmdqeVlOUUhW
      SzRuRWNZWVo4ZHkzTEl3VXAwYlNYS3ZpL1phMWpvaDNXamdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVM2V4Skt0eXdJVVpwaXly
      S3pZUFUKN0VYbUJ3MHdId1lEVlIwakJCZ3dGb0FVSGtlei9DMmM3TkVxdmFjNlUyUXdyN041MDBN
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TldJM09HSmpPVFZrWWkxcVpIRTNkekNCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU1wYURCZmJObG5PCnVMVzB0ZTJTWVNa
      Qk5hcXBvNWtTQVI0NHhNb2ZoNEFDQWlCSGZabWRVenB2eXVCMlp5VDFHQUNlZisrSFFHOTIKV1p0
      SmVmTUhCczU4d1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK
      6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVIV0tKVlQ3
      NHQyYnBVOEN3bmR6elFnblJYQkl3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpB
      NE1UY3dNak14TlRsYUZ3MHlOVEEyTURZd01qTXhOVGxhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3
      RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dI
      VDNKa1pYSmxjakVYCk1CVUdBMVVFQXd3T1kyRXViM0prWlhKbGNpMXVaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUU2Zkc05oSXFpQ1Vxa1NSSkVOUTkzNVl6a0h4d1ZuVitv
      MjZobTlFdE1EOXJYS0R6M3M3MXd3ZmJ2ZFZQeApndzJiR2NPOTFSY0pqYUJvZFJPRk1qOWhvMEl3
      UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRF
      RmdRVUhrZXovQzJjN05FcXZhYzZVMlF3cjdONTAwTXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUln
      VTVkZWljWU85cmYwVm9raVlrNzk0akxoU1FYK0FqMFNJZHMxRmFhTWM3NENJUUQyY09xKwpIUDNE
      ek43MmR2R1ZRV3FRM3krdWptbDVTN1BoZFhWMVA2NVZLQT09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1T
      UBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVy
      TVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zKgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVz
      dHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5z
      GtQRCg1Db25zZW5zdXNUeXBlEsIRErcRCghldGNkcmFmdBKqEQqTEQoUb3JkZXJlcjEub3JkZXJl
      ci1uZXQQijcauggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NBcG1nQXdJQkFn
      SVVVVHJKK2c2RTFZUEhRZndwVHJNWjdKMHYxTzB3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERB
      ZUZ3MHkKTWpBNE1UY3dNak0xTURCYUZ3MHlNekE0TVRjd01qUXdNREJhTUcweEN6QUpCZ05WQkFZ
      VEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFv
      VEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RCMjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdW
      eVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdB
      RTJ1Ri9ZNFBCOVlWOVZUTG5tdFBHM0FxR3hsRTN3S0pPUm5TaQpWR0pkTmdTQUJDRkY5UC83M0lx
      THljbWw5M0VPV1ZTVFJ1Sndjbms5OHhVWnlWczFoS09DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dR
      RUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIw
      VEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVXdZNUc1UkF1OEZjNDlJNzFzdDlqK2JHVXloUXdId1lE
      VlIwagpCQmd3Rm9BVUhrZXovQzJjN05FcXZhYzZVMlF3cjdONTAwTXdPd1lEVlIwUkJEUXdNb0lV
      YjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlq
      WVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJGeDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0Yw
      YVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEps
      Y2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRkFpRUFrcGdIcmlqZzlxRDJNUGJZVjVrOTBEUXo3eUg4UGQwTnJXenYKN1EvL0lkUUNJR2sr
      Z2gzS0ZOUlBjRGMrT0d3cVNMZkIzS3I5RWxRTWdvN3dhUFJmSTBGTAotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCiK6CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lC
      QWdJVVVUckorZzZFMVlQSFFmd3BUck1aN0owdjFPMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRjd01qTTFNREJhRncweU16QTRNVGN3TWpRd01EQmFNRzB4Q3pBSkJnTlZC
      QVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZC
      QW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFzVEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXla
      R1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RR
      Z0FFMnVGL1k0UEI5WVY5VlRMbm10UEczQXFHeGxFM3dLSk9SblNpClZHSmROZ1NBQkNGRjlQLzcz
      SXFMeWNtbDkzRU9XVlNUUnVKd2Nuazk4eFVaeVZzMWhLT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIv
      d1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApW
      UjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVd1k1RzVSQXU4RmM0OUk3MXN0OWorYkdVeWhRd0h3
      WURWUjBqCkJCZ3dGb0FVSGtlei9DMmM3TkVxdmFjNlUyUXdyN041MDBNd093WURWUjBSQkRRd01v
      SVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJH
      OWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dCQkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FX
      RjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pY
      SmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2liM0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFn
      TklBREJGQWlFQWtwZ0hyaWpnOXFEMk1QYllWNWs5MERRejd5SDhQZDBOcld6dgo3US8vSWRRQ0lH
      aytnaDNLRk5SUGNEYytPR3dxU0xmQjNLcjlFbFFNZ283d2FQUmZJMEZMCi0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAgaBkFkbWlucxoiCglCYXRjaFNpemUSFRIL
      CAoQgICAMRiAgEAaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoG
      QWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5z
      KgZBZG1pbnMS8y4KC0NvbnNvcnRpdW1zEuMuEpguChpDYXJib25BY2NvdW50aW5nQ29uc29ydGl1
      bRL5LRLMFgoLYXVkaXRvcjFNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjFNU1AS7QUt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVKcHFGUVZERjVv
      UEFqbXM3WU53MXRpTDdBY2N3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RB
      aEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1E
      Z3hOekF5TXpNeE4xb1hEVEkxTURZd05qQXlNek14TjFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVxNUtQVHhJa1BQa3ZhTzlXcm1DVllPQU1helFBUWww
      di9zdEFEdlF3cmYzVWlmZzdDWHpTUG5NMApyZVRZZmpGTHhtc280SFdBWVh4NEtEVzFLWC9qMGFO
      Q01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIw
      T0JCWUVGTTY5RkVGSUt2a1RXQmIxVFJ6SHhrNm1qM0pyTUFvR0NDcUcKU000OUJBTUNBMGNBTUVR
      Q0lETDY0ZEtYbWVGaHpQSldQa3pVaElDemZhKzhidHhQbHVuNThRMGplWnBOQWlCTQoxN05Udk44
      MkNLaUpqSGpacnUvSEZqelZOVFFaK3hCQVVLcGgwcWpYdVE9PQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tCiK+CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOURDQ0FwcWdBd0lCQWdJ
      VVd4bnJWc3Q0ejZLcG14cFhuUk5IODZLY2xjWXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFV
      RUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJF
      d0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYw
      TUI0WApEVEl5TURneE56QXlNemN3TUZvWERUSXpNRGd4TnpBeU5ESXdNRm93ZWpFTE1Ba0dBMVVF
      QmhNQ1EwZ3hHakFZCkJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJFd0R3WURWUVFL
      RXdoQmRXUnBkRzl5TVRFZk1Bd0cKQTFVRUN4TUZZV1J0YVc0d0R3WURWUVFMRXdoaGRXUnBkRzl5
      TVRFYk1Ca0dBMVVFQXd3U1FXUnRhVzVBWVhWawphWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBD
      QVFZSUtvWkl6ajBEQVFjRFFnQUVFRGlVc2lXWWFkS0poYnFuCkYxOUd4Vi8rT3RWd0F5K2RTN0NG
      b0JRNENoZ203bDh2Um5LeUZocjhZNjlHUFNFbjBkUkkwRGs2anJOK3NHTWsKelJVMUdxT0NBUm93
      Z2dFV01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FX
      QkJUNHk4RXhiZVZGKzVReS9qcjVmTitVcG0veG96QWZCZ05WSFNNRUdEQVdnQlRPdlJSQlNDcjVF
      MWdXCjlVMGN4OFpPcG85eWF6QWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAyWmpRNE5EZGlZ
      amsyTFhBMWVqbHgKTUlHUEJnZ3FBd1FGQmdjSUFRU0JnbnNpWVhSMGNuTWlPbnNpWVdKaFl5NXBi
      bWwwSWpvaWRISjFaU0lzSW1GawpiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJ
      am9pWVhWa2FYUnZjakVpTENKb1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCaGRXUnBk
      Rzl5TVMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGkKZlgwd0NnWUlLb1pJemowRUF3SURT
      QUF3UlFJaEFKbU9mRmZ0MVVXNFRYcSt0dTV4cWJxYkg1QUFjcWt6cVlyTwpRclFBc29SYUFpQW5J
      U3dOMmloUVo5MG1laFFDakJTS253d28zbGlPWU83N0JEQ1NmdG9oekE9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVKcHFGUVZERjVvUEFqbXM3WU53MXRpTDdBY2N3Q2dZSUtv
      Wkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hOekF5TXpNeE4xb1hEVEkxTURZd05q
      QXlNek14TjFvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3
      d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFn
      QUVxNUtQVHhJa1BQa3ZhTzlXcm1DVllPQU1helFBUWwwdi9zdEFEdlF3cmYzVWlmZzdDWHpTUG5N
      MApyZVRZZmpGTHhtc280SFdBWVh4NEtEVzFLWC9qMGFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdF
      Qi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGTTY5RkVGSUt2a1RXQmIxVFJ6
      SHhrNm1qM0pyTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lETDY0ZEtYbWVGaHpQSldQa3pVaElD
      emZhKzhidHhQbHVuNThRMGplWnBOQWlCTQoxN05Udk44MkNLaUpqSGpacnUvSEZqelZOVFFaK3hC
      QVVLcGgwcWpYdVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgKC0VuZG9y
      c2VtZW50EikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdSZWFk
      ZXJzEikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJz
      EikSHwgBEhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIh
      CAESHRIIEgYIARICCAAaERIPCgthdWRpdG9yMU1TUBABGgZBZG1pbnMqBkFkbWlucxLMFgoLYXVk
      aXRvcjJNU1ASvBYa1BQKA01TUBLMFBLBFBK+FAoLYXVkaXRvcjJNU1AS7QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVEMk0wWDRmbVFDY09oeHVScEdXcjJ1
      OU1Wend3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1q
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hOekF5TXpRek1s
      b1hEVEkxTURZd05qQXlNelF6TWxvd1hERUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1q
      RVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMEQKQVFjRFFnQUUySjBscVJyS09SQWV1TEVpdC9CTVpPMHArajlNYUhjdG5vd0dqaG9CcXUv
      YjJRczNIRWRJOThLUgozOVJsNTJSUkRnSXBSYWtHNmNnUmJmNWdnc0pjYTZOQ01FQXdEd1lEVlIw
      VEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGT0xLNFRM
      M1R4R0FTUTJoelk2R0hiWEpaT096TUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lBS3ZGanJVZjFJ
      bmhTejQvTGpLU2dNbXRqRmNyaXdyUWQyaWljcVJ5Z1c0QWlBcgo2K3BwVTRKMGkrUXlxVGpRV2Y4
      Nk0zSERNZmVUeHdJZXdFRXhGc01kNXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK+CC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOVRDQ0FwdWdBd0lCQWdJVVNmL0RtbC9SWCtj
      SmtTNURPNXkrSTZldmRmNHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFo
      QmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURn
      eE56QXlNemt3TUZvWERUSXpNRGd4TnpBeU5EUXdNRm93ZXpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFa
      CkJnTlZCQWNURWpVeExqVXdMeTB3TGpFekwweHZibVJ2YmpFUk1BOEdBMVVFQ2hNSVFYVmthWFJ2
      Y2pJeEh6QU0KQmdOVkJBc1RCV0ZrYldsdU1BOEdBMVVFQ3hNSVlYVmthWFJ2Y2pJeEd6QVpCZ05W
      QkFNTUVrRmtiV2x1UUdGMQpaR2wwYjNJeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5
      QXdFSEEwSUFCSmtHdmlQMzA0UkhsZHZsCnpsQUxuZkcxeW16OGNJVU5Za0NDRDNHZkFRTS94dkVW
      c2lucGdVY3FWTjJrellvcTVCc1h3aHBGZWxNRjVOSWEKYyt1ZDJraWpnZ0VhTUlJQkZqQU9CZ05W
      SFE4QkFmOEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVgpIUTRFRmdRVXF2TWpLcWpn
      NVVBUFcrSXRnaVRveVl1QU5ad3dId1lEVlIwakJCZ3dGb0FVNHNyaE12ZFBFWUJKCkRhSE5qb1lk
      dGNsazQ3TXdKQVlEVlIwUkJCMHdHNElaWTJFdGRHOXZiSE10T0RSa05XWmtOemMwTkMxbmNXUXkK
      ZHpDQmp3WUlLZ01FQlFZSENBRUVnWUo3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlk
      V1VpTENKaApaRzFwYmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1GMVpHbDBi
      M0l5SWl3aWFHWXVSVzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlYVmthWFJ2Y2pJdGJtVjBJ
      aXdpYUdZdVZIbHdaU0k2SW1Ga2JXbHUKSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQzA0
      S09NOGlQQnp2VDNIMGpsRG5WU2JXYjExMFk5bDhOaQova0hZWEZVa1lBSWdhbHh2aHN4TmdKQWs4
      NTUzUGo5MG0ySmZEdkYvQmthR3hTbFRQbmgzM1JZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      CkIOCgRTSEEyEgZTSEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQit6Q0NB
      YUtnQXdJQkFnSVVEMk0wWDRmbVFDY09oeHVScEdXcjJ1OU1Wend3Q2dZSUtvWkl6ajBFQXdJdwpY
      REVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakl0Ym1WME1CNFgKRFRJeU1EZ3hOekF5TXpRek1sb1hEVEkxTURZd05qQXlNelF6TWxvd1hE
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTgpCZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1TVJFd0R3WURWUVFLREFoQmRXUnBkRzl5Ck1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FY
      UnZjakl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUUySjBscVJyS09S
      QWV1TEVpdC9CTVpPMHArajlNYUhjdG5vd0dqaG9CcXUvYjJRczNIRWRJOThLUgozOVJsNTJSUkRn
      SXBSYWtHNmNnUmJmNWdnc0pjYTZOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhR
      OEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGT0xLNFRMM1R4R0FTUTJoelk2R0hiWEpaT096TUFv
      R0NDcUcKU000OUJBTUNBMGNBTUVRQ0lBS3ZGanJVZjFJbmhTejQvTGpLU2dNbXRqRmNyaXdyUWQy
      aWljcVJ5Z1c0QWlBcgo2K3BwVTRKMGkrUXlxVGpRV2Y4Nk0zSERNZmVUeHdJZXdFRXhGc01kNXc9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggB
      EgIIABoREg8KC2F1ZGl0b3IyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggS
      BggBEgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Q
      b2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0Fk
      bWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVy
      ZRIQEgYI/////w8aBkFkbWlucxpKChBPcmRlcmVyQWRkcmVzc2VzEjYSGwoZb3JkZXJlcjEub3Jk
      ZXJlci1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQS
      CgoICgRWMl8wEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1p
      bnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJ
      CgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
