apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a7e9892a5136f4fa8b1cda6ba31b358b-1780904258.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIIcYd+RvOOkU+8oV5syKdPS51jxDAvhlW7icawux+hQJEt5cCttcCthcCngKWggBEAEaBgiw
      u8qXBiIKc3lzY2hhbm5lbCpAZjliOWI5MzE1OTY4NzUwZDg1Mjc4ZDJiNWQ4NTZjNGFmYTQ0Y2Ji
      NzJkOTA5ZWIyNTUxYjAxNDQ0NDEyNTkyMhIaEhinLsgnmFEr9U1nFexAQKxMx4Q+kSBzjTMS21sK
      2FsS1VsSnyoKB09yZGVyZXISkyoSjhYKCm9yZGVyZXJNU1AS/xUamxQKA01TUBKTFBKIFBKFFAoK
      b3JkZXJlck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lC
      QWdJVUIxdFRhQU9yeExCUmI3cnFmWDlKd0pNc0ZOOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TURreE56TTNORFphRncweU5UQTFNamt4TnpNM05EWmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJwSzVpRzcvUGhvSnB2alVma1IreE54
      S2lXS2kyY2dLOENjRm5BTGY3Y0haRTZTSDY5TTRMcFpnMmp5UDJYCjNrUS8zQlZDUGRXVHYwSjlC
      bVFYa0xsbW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVQnpsc1hJUDRTK1Y5WW1OUFJ6eHJFRFRlckhNd0NnWUlLb1pJemowRQpB
      d0lEUndBd1JBSWdLRisvdXF6YW5TMTMzQXd1dXc5c3Y5dFlTM3VyTjBrZjhWYzhyOGd5SkdvQ0lD
      UTlxYTZLClo5dHdBckVCdW5WRlAva2pnUjJZZ0Q3WWkrWjZFR2tmckppKwotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiKWCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDMWpDQ0FueWdB
      d0lCQWdJVURTMjZvZ3c2bnBMVHJCQXNGUm05L2tBWE9DNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxX
      NWxkREFlRncweQpNakE0TURreE56TTNNREJhRncweU16QTRNRGt4TnpReU1EQmFNR2d4Q3pBSkJn
      TlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0Jn
      TlZCQW9UQjA5eVpHVnlaWEl4RGpBTUJnTlYKQkFzVEJXRmtiV2x1TVJvd0dBWURWUVFEREJGQlpH
      MXBia0J2Y21SbGNtVnlMVzVsZERCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJG
      Z3YxV1FhWkxVY0lVNXBLMHFpakZTYm9GTFRhWHp5c3g3NXBzZDlqU0RICmNWaXpxY3Y5RERPNW55
      UzhkSXJTV1ZEZS9teVRZNGd2K2Mzb2Y4QzdpajZqZ2dFUU1JSUJEREFPQmdOVkhROEIKQWY4RUJB
      TUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVNK3V5cCtCSTFKSHZqWTRWb1Rv
      TQp4ZkRibTdnd0h3WURWUjBqQkJnd0ZvQVVCemxzWElQNFMrVjlZbU5QUnp4ckVEVGVySE13SkFZ
      RFZSMFJCQjB3Ckc0SVpZMkV0ZEc5dmJITXROVGcxTm1Oa1pqaGpOQzF0WTI1M2N6Q0JoUVlJS2dN
      RUJRWUhDQUVFZVhzaVlYUjAKY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYlds
      dUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1scwphV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pUVdSdGFXNUFiM0prWlhKbGNpMXVaWFFpCkxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTUFnV2F6R21GQysKbnRKK3hLQzdCQkN3RXI3
      ZlV2eGJRcFN3QTQwSDU3UUlBaUFjTXZkTXdiRmczb2ZJc2JpajF5MnRxaHBmMzdkMwoycHdjUlFn
      V0VHNlgrUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrlBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVUIxdFRhQU9yeExC
      UmI3cnFmWDlKd0pNc0ZOOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TURr
      eE56TTNORFphRncweU5UQTFNamt4TnpNM05EWmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVJwSzVpRzcvUGhvSnB2alVma1IreE54S2lXS2kyY2dLOENjRm5B
      TGY3Y0haRTZTSDY5TTRMcFpnMmp5UDJYCjNrUS8zQlZDUGRXVHYwSjlCbVFYa0xsbW8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      Qnpsc1hJUDRTK1Y5WW1OUFJ6eHJFRFRlckhNd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdLRisv
      dXF6YW5TMTMzQXd1dXc5c3Y5dFlTM3VyTjBrZjhWYzhyOGd5SkdvQ0lDUTlxYTZLClo5dHdBckVC
      dW5WRlAva2pnUjJZZ0Q3WWkrWjZFR2tmckppKwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoG
      QWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1p
      bnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKb3JkZXJlck1TUBABGgZBZG1pbnMi
      NwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMi
      MwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1AaBkFkbWlucyoGQWRt
      aW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIO
      EgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJp
      bGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxrUEQoNQ29uc2Vuc3VzVHlwZRLCERK3EQoIZXRj
      ZHJhZnQSqhEKkxEKFG9yZGVyZXIxLm9yZGVyZXItbmV0EIo3GroILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM4akNDQXBtZ0F3SUJBZ0lVQ2dWL2pJeXBIbFlwTXR6Y3dTVWg1cjNxSDZV
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNRGt4TnpNM01EQmFGdzB5TXpB
      NE1Ea3hOelF5TURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4
      dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpCQXNUQjI5
      eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1Ga3dFd1lI
      CktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVuKzllQUpNYjY2TklUNTNZeGo5SVMyZHlTK0Fp
      S0JPRG1yN2YKK3kxTC95RlI1TXUzQm41VGRtQzJiQ3RiVEF5ODJwOHRwSjQ4OVJRd2l4bFBUbWRn
      L3FPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VG
      QlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVsNmQr
      b3pPQUI1STZVSUFWQTJLV2pLazcwcE13SHdZRFZSMGoKQkJnd0ZvQVVCemxzWElQNFMrVjlZbU5Q
      Unp4ckVEVGVySE13T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNpMXVaWFND
      R205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3Z0JCRng3
      SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnUK
      ZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaWIzSmta
      WEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJPbUM5Vy9SOFE0T3B2dGhQMGE5VDBm
      QmtpcXAvMktrTm55NXVqCno5d29zQUlnYmNFNllhTHkwa2hxRmtSUW96cm1taGNENUpSYUhSMXBH
      dXBOYUpvOVYyST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQzhqQ0NBcG1nQXdJQkFnSVVDZ1Yvakl5cEhsWXBNdHpjd1NVaDVyM3FI
      NlV3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dG
      UVlEVlFRRERBNWpZUzV2Y21SbGNtVnlMVzVsZERBZUZ3MHkKTWpBNE1Ea3hOek0zTURCYUZ3MHlN
      ekE0TURreE56UXlNREJhTUcweEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFN
      Qzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEVEQU9CZ05WCkJBc1RC
      Mjl5WkdWeVpYSXhIVEFiQmdOVkJBTVRGRzl5WkdWeVpYSXhMbTl5WkdWeVpYSXRibVYwTUZrd0V3
      WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRW4rOWVBSk1iNjZOSVQ1M1l4ajlJUzJkeVMr
      QWlLQk9EbXI3ZgoreTFML3lGUjVNdTNCbjVUZG1DMmJDdGJUQXk4MnA4dHBKNDg5UlF3aXhsUFRt
      ZGcvcU9DQVNnd2dnRWtNQTRHCkExVWREd0VCL3dRRUF3SURxREFkQmdOVkhTVUVGakFVQmdnckJn
      RUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVWw2
      ZCtvek9BQjVJNlVJQVZBMktXaktrNzBwTXdId1lEVlIwagpCQmd3Rm9BVUJ6bHNYSVA0UytWOVlt
      TlBSenhyRURUZXJITXdPd1lEVlIwUkJEUXdNb0lVYjNKa1pYSmxjakV1CmIzSmtaWEpsY2kxdVpY
      U0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dVkyOXRNR2dHQ0NvREJBVUcKQndnQkJG
      eDdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldW
      dQpkRWxFSWpvaWIzSmtaWEpsY2pFdWIzSmtaWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pYjNK
      a1pYSmxjaUo5CmZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQk9tQzlXL1I4UTRPcHZ0aFAwYTlU
      MGZCa2lxcC8yS2tObnk1dWoKejl3b3NBSWdiY0U2WWFMeTBraHFGa1JRb3pybW1oY0Q1SlJhSFIx
      cEd1cE5hSm85VjJJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiA
      gIAIGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      EvMuCgtDb25zb3J0aXVtcxLjLhKYLgoaQ2FyYm9uQWNjb3VudGluZ0NvbnNvcnRpdW0S+S0SzBYK
      C2F1ZGl0b3IyTVNQErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IyTVNQEu0FLS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJBZ0lVZmFCTStFVnJYSTBqVFB1dk9D
      bkNIMERYOWxjd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRH
      OXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3T1RFM05E
      QXlNRm9YRFRJMU1EVXlPVEUzTkRBeU1Gb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBECkFRY0RRZ0FFNUREUGYxanVYVTFuM2s0RGhjNU1keEhGcFdNOG54djU4a00vRERs
      UUpRbnpPZ1E3WURQYUlSSEcKZ0RKSnR6ekdpVDdzdFZWaVJ1Zk5oeFplQjRicStxTkNNRUF3RHdZ
      RFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkxj
      bUNzMDNPNVFKK1dFMHJaQXNYaklSOGZsNU1Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJQm5EaDJT
      UklRWkNackR6SDhzT0RSOWxWWTVEYUE1QllDa2hmbWVEUjBYZkFpRUEKemlCWjVqZ1AzMTdDeHMr
      aVFtRW91UEpXaElXbEdoempZc3YyM0FaYVRWND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi
      vggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHVnQXdJQkFnSVVFVTZpUGFV
      QmNZdWlkZk1pREVXZHYzaGNlYXN3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SRXdEd1lEVlFR
      S0RBaEJkV1JwZEc5eU1qRVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakl0Ym1WME1CNFgKRFRJ
      eU1EZ3dPVEUzTkRJd01Gb1hEVEl6TURnd09URTNORGN3TUZvd2V6RUxNQWtHQTFVRUJoTUNSMEl4
      R3pBWgpCZ05WQkFjVEVqVXhMalV3THkwd0xqRXpMMHh2Ym1SdmJqRVJNQThHQTFVRUNoTUlRWFZr
      YVhSdmNqSXhIekFNCkJnTlZCQXNUQldGa2JXbHVNQThHQTFVRUN4TUlZWFZrYVhSdmNqSXhHekFa
      QmdOVkJBTU1Fa0ZrYldsdVFHRjEKWkdsMGIzSXlMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FH
      U000OUF3RUhBMElBQkV6NGR1VEp1RlNZRUE0SwpFQlhHYWVUY3NLdkR0VFYrU2poWGhRTFJZMzk5
      d0pPUkcxM3hld09FMnVQOFY0Zm9XTnFYcFZmYWs2WjFYZDNVCnhkNVBUMW1qZ2dFYU1JSUJGakFP
      QmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVUvUXNU
      alVHOXFtM2lwWEpUb0x5cmg1OWlpR1V3SHdZRFZSMGpCQmd3Rm9BVXR5WUt6VGM3bEFuNQpZVFN0
      a0N4ZU1oSHgrWGt3SkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE5UazNaRFZqWXpRNU5DMXNa
      M281CmN6Q0Jqd1lJS2dNRUJRWUhDQUVFZ1lKN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJ
      blJ5ZFdVaUxDSmgKWkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNkltRjFa
      R2wwYjNJeUlpd2lhR1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFXNUFZWFZrYVhSdmNqSXRi
      bVYwSWl3aWFHWXVWSGx3WlNJNkltRmtiV2x1CkluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJ
      QjhCQW1aYS9jZ0MwTHJxU0xnRC9WWUJ6b1JzaUxIbUJScTgKSmRxcTBCZnZBaUJwdVBoVm9SUlNE
      aWpFclpsNjI5ZEN1YVVLNmYzV2FaT08zYWZVeUFMMkp3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      RENDQWFLZ0F3SUJBZ0lVZmFCTStFVnJYSTBqVFB1dk9DbkNIMERYOWxjd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd3T1RFM05EQXlNRm9YRFRJMU1EVXlPVEUzTkRBeU1G
      b3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFNUREUGYx
      anVYVTFuM2s0RGhjNU1keEhGcFdNOG54djU4a00vRERsUUpRbnpPZ1E3WURQYUlSSEcKZ0RKSnR6
      ekdpVDdzdFZWaVJ1Zk5oeFplQjRicStxTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkxjbUNzMDNPNVFKK1dFMHJaQXNYaklSOGZs
      NU1Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJQm5EaDJTUklRWkNackR6SDhzT0RSOWxWWTVEYUE1
      QllDa2hmbWVEUjBYZkFpRUEKemlCWjVqZ1AzMTdDeHMraVFtRW91UEpXaElXbEdoempZc3YyM0Fa
      YVRWND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8I
      ARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIb
      EggSBggBEgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIG
      CAESAggAGhESDwoLYXVkaXRvcjJNU1AQARoGQWRtaW5zKgZBZG1pbnMSzBYKC2F1ZGl0b3IxTVNQ
      ErwWGtQUCgNNU1ASzBQSwRQSvhQKC2F1ZGl0b3IxTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJBZ0lVSlFKcysxeUVzSnYyN1B5M3BSQ0VRR0QxSi80d0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFE
      RVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd3T1RFM016a3dNMW9YRFRJMU1E
      VXlPVEUzTXprd00xb3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFE
      RVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFY2FyVU1tMTd2bUJJQUFwSy9NazRLYWwwdGlKeDlNUWRGRndiWkFNRENlSVRHVzQvTTcy
      elJXVEIKVDZkNWMxelo1a0VHWXNjbGxLeUpEYUZHS01INWthTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkVtTmU3OU83N1JMaXZw
      NFo1T2Q4UmxtK2MxZE1Bb0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJR0N1LzBQYTZ6SEVXaXVzVEV6
      bjE3dm91OGNOOEdBKzNFVzNoU1BKZzM5SkFpRUEKMTlzd0NNc01sRkh3QldZMzMybGNzak9XcWVj
      cE9PaG1UM3dJcU92QUJMUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoivggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzlEQ0NBcHFnQXdJQkFnSVVGeVdhdDMxakplQ2ZMVXpoWmVQ
      WmZydzhjMEF3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFn
      TUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3dPVEUzTXpr
      d01Gb1hEVEl6TURnd09URTNORFF3TUZvd2VqRUxNQWtHQTFVRUJoTUNRMGd4R2pBWQpCZ05WQkFj
      VEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SRXdEd1lEVlFRS0V3aEJkV1JwZEc5eU1URWZNQXdH
      CkExVUVDeE1GWVdSdGFXNHdEd1lEVlFRTEV3aGhkV1JwZEc5eU1URWJNQmtHQTFVRUF3d1NRV1J0
      YVc1QVlYVmsKYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FF
      a3VUVnQ5NEVSbkRLRmo0UApNdlBPbU9tK012a0owOVFhTVFHNXNVWmYybWp4MnYxRDQ3dm1CZDkz
      V3Nzd3l3VEVaZEYvUXc2cDZuV3pTZTBrCkQ3dmZWcU9DQVJvd2dnRVdNQTRHQTFVZER3RUIvd1FF
      QXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCU1M4SWV5NERZcXdvMm5ESXJQ
      RDFZYUZlT1dyakFmQmdOVkhTTUVHREFXZ0JSSmpYdS9UdSswUzRyNgplR2VUbmZFWlp2bk5YVEFr
      QmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kwM09XTTBOMlkyWTJRNExXZDZjbXA0Ck1JR1BCZ2dx
      QXdRRkJnY0lBUVNCZ25zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmsK
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVlYVmthWFJ2Y2pFaUxDSm9a
      aTVGYm5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQmhkV1JwZEc5eU1TMXVaWFFpTENKb1ppNVVl
      WEJsSWpvaVlXUnRhVzRpCmZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTS9LcUJNTWVSdmhZ
      SWl3c3NuQnVGaUxWdTVlVEd0bTRJdUsKL2hUbThJTVBBaUFxYUJXeisxZ2xQWTBKbFFvdmxqQ25l
      NnFVcmg3SytnMHlVZFYxeU1ORE1nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hB
      MhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvRENDQWFLZ0F3SUJB
      Z0lVSlFKcysxeUVzSnYyN1B5M3BSQ0VRR0QxSi80d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dB
      MVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpN
      UkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJt
      VjBNQjRYCkRUSXlNRGd3T1RFM016a3dNMW9YRFRJMU1EVXlPVEUzTXprd00xb3dYREVMTUFrR0Ex
      VUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01S
      RXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJt
      VjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFY2FyVU1tMTd2bUJJQUFwSy9N
      azRLYWwwdGlKeDlNUWRGRndiWkFNRENlSVRHVzQvTTcyelJXVEIKVDZkNWMxelo1a0VHWXNjbGxL
      eUpEYUZHS01INWthTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJB
      TUNBYVl3SFFZRFZSME9CQllFRkVtTmU3OU83N1JMaXZwNFo1T2Q4UmxtK2MxZE1Bb0dDQ3FHClNN
      NDlCQU1DQTBnQU1FVUNJR0N1LzBQYTZ6SEVXaXVzVEV6bjE3dm91OGNOOEdBKzNFVzNoU1BKZzM5
      SkFpRUEKMTlzd0NNc01sRkh3QldZMzMybGNzak9XcWVjcE9PaG1UM3dJcU92QUJMUT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggAGg8S
      DQoLYXVkaXRvcjFNU1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAaERIPCgth
      dWRpdG9yMU1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMU1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGkoKEE9y
      ZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVyLW5ldDo3MDUwGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
