apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://aa34b638ff2ca4f3c9bcefa161f4b801-973901913.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIGh/C4ZYXmhNCGQF32vW0Jp+FFMVHVsQz5dQpHHT39cXEuJcCt9cCtxcCngKWggBEAEaBgi2
      idmXBiIKc3lzY2hhbm5lbCpANGI0M2NjZWMzMDdhMDRiMzliNWU3NGU3YzI3ZjAyOGY3Y2IxMDAz
      ZTdlMTcwNDcxMzU4MGU2MjU3MzkwYzA0MRIaEhiMBklP3sadGBOgFrV4Qy00BQ+aSmarRHYS31sK
      3FsS2VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVUpmZXFJOTh1NDczcmQ3OWxFa3N3OVlRTkpHRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRJeE1qQTFNekphRncweU5UQTJNREV4TWpBMU16SmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRIYUdlTlZkOXZZUVBqK3lMQUptbjBJ
      ZDBReWdNWXhxYndCNHE2a096Y3Y2NXRiK3NwclpKYkpKUVJ1Uys2Ckxld2RvYTlxd1lQNkVFd25L
      ZUxLODZLdm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVT3hUTS9OdG9ZazRXYlRtTCtJejB3TjdUejhFd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdUemRpVnQrbXcwdjFZQVB3YlFJNW4vZjVJNFB1ZmJoQ0NLTCsvMmRQWnpRQ0lR
      RGR5ODVWCm92TllVd0c4Z2k3ZkQ2YTg1RlArVERkNnZFUUtVbFYyeUhxeWFBPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFUQ0NB
      bnVnQXdJQkFnSVVSVHF3R3pwZTd1SVQrTHpXUThQVGlLdXN4bDB3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1USXhNakEzTURCYUZ3MHlNekE0TVRJeE1qRXlNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCRmY1WWRYSTNZR2hqL2RLMEl2VUFtYTZnM243SnFZMXpVRXlRdVZSSEY5dApTSHl0RWpONmZa
      dEFPYmFWVlk1NW5VQVFFaU9CbVZFRU1iWU5JOUl6VFdtamdnRVBNSUlCQ3pBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVMWZlQ1pOTGV1ZHFXcDI5
      NXUycG8KNnVEbzBQb3dId1lEVlIwakJCZ3dGb0FVT3hUTS9OdG9ZazRXYlRtTCtJejB3TjdUejhF
      d0l3WURWUjBSQkJ3dwpHb0lZWTJFdGRHOXZiSE10Wm1NM1ltWTJOamcyTFdOeloyMTNNSUdGQmdn
      cUF3UUZCZ2NJQVFSNWV5SmhkSFJ5CmN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHAKWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J2Y21SbGNtVnlMVzVsZENJcwpJbWhtTGxSNWNHVWlPaUpoWkcx
      cGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBM0cwY29wT1dWN0YxCmdNQVZVcGRhYTZ5
      eWVsYldpUDZYOCtjWURMR01BZE1DSUVIK0Foc2MvbkE2SnRlR1M3cGVsU2YxQTRxNWlGUnMKRTU0
      VzlENkZvc2djCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUpmZXFJOTh1NDcz
      cmQ3OWxFa3N3OVlRTkpHRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRJ
      eE1qQTFNekphRncweU5UQTJNREV4TWpBMU16SmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVRIYUdlTlZkOXZZUVBqK3lMQUptbjBJZDBReWdNWXhxYndCNHE2
      a096Y3Y2NXRiK3NwclpKYkpKUVJ1Uys2Ckxld2RvYTlxd1lQNkVFd25LZUxLODZLdm8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      T3hUTS9OdG9ZazRXYlRtTCtJejB3TjdUejhFd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdUemRp
      VnQrbXcwdjFZQVB3YlFJNW4vZjVJNFB1ZmJoQ0NLTCsvMmRQWnpRQ0lRRGR5ODVWCm92TllVd0c4
      Z2k3ZkQ2YTg1RlArVERkNnZFUUtVbFYyeUhxeWFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpvcmRlcmVyTVNQEAEa
      BkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCm9yZGVyZXJNU1Aa
      BkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVv
      dXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENh
      cGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa1BEKDUNvbnNlbnN1c1R5cGUSwhEStxEK
      CGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVyLW5ldBCKNxq6CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJVWFiNStMbDdOVFA0OWtDV2xvK0JjZkNZ
      STFZRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJj
      d0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRJeE1qQTNNREJhRncw
      eU16QTRNVEl4TWpFeU1EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFz
      VEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3
      RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFYTFvYXdZWU5TS21KUGZCSmE3UzVOVEhP
      WTN4RnZ3U04vdklUClVkaGJHb2dIWDMyTFFLemNXLzJJSmZadm4xSi9KY3R1bGtBNFY3U3JQbWNp
      VWZOSFBhT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dy
      QmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FV
      NGprK3QzV3p5RGgxWFE3czZWbUdSbk1rOEJrd0h3WURWUjBqCkJCZ3dGb0FVT3hUTS9OdG9ZazRX
      YlRtTCtJejB3TjdUejhFd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dC
      QkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2li
      M0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXZYTTU2dGhLS2FnK3N5OHg2
      eExOWXNtV0RJQWdjWTRVYzFzegp1VHJ2ZzRVQ0lHV3dTQWRuNkJteUxnN3FEQm9jcWZNZk44ZWpD
      Z2s2TEFxKytiN3N6V1hNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVYWI1K0xsN05UUDQ5a0NXbG8rQmNm
      Q1lJMVlFd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVEl4TWpBM01EQmFG
      dzB5TXpBNE1USXhNakV5TURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFN
      UzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpC
      QXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1G
      a3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVhMW9hd1lZTlNLbUpQZkJKYTdTNU5U
      SE9ZM3hGdndTTi92SVQKVWRoYkdvZ0hYMzJMUUt6Y1cvMklKZlp2bjFKL0pjdHVsa0E0VjdTclBt
      Y2lVZk5IUGFPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJn
      Z3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVU0amsrdDNXenlEaDFYUTdzNlZtR1JuTWs4Qmt3SHdZRFZSMGoKQkJnd0ZvQVVPeFRNL050b1lr
      NFdiVG1MK0l6MHdON1R6OEV3T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNp
      MXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3
      Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpv
      aWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBdlhNNTZ0aEtLYWcrc3k4
      eDZ4TE5Zc21XRElBZ2NZNFVjMXN6CnVUcnZnNFVDSUdXd1NBZG42Qm15TGc3cURCb2NxZk1mTjhl
      akNnazZMQXErK2I3c3pXWE0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLzLgoLQ29uc29ydGl1bXMS4y4SmC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvkt
      EswWCgthdWRpdG9yMU1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMU1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVUtsYWZML2hsU05oaWQw
      VGtYWm9PN3d5K1Yrb3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE1q
      RXlNRFkxTVZvWERUSTFNRFl3TVRFeU1EWTFNVm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTVRFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRWhpMDdOZW9tcnhnZzFkMHVJUWFCNmhlaHIrYzlRcjkwTmhJ
      ZU5rSXYzenZnWXVtMW5UczFJK0prCndFS2kvek9jNFlDblVVUjFodHIxRElKYTI3dHpxcU5DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZKNHlUTk53NmdpUmdjUjRjckZyT1YrbDJYd3lNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFE
      TUpwd09mV2VpV3JjU0lpOUFMc0I3OTRValNLOWRGT0c3aHhWMnFPS1MvQUlnCk4vQWZsUGJyRThq
      M2Npcy9FQkZHVzdFZUp5R0hUUUp4RzU2SlJTK1cwbmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIr4ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQXBxZ0F3SUJBZ0lVWHpu
      Q1A2SWVIdVlpTHQybG1kNlZTb21iTGZJd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRY
      CkRUSXlNRGd4TWpFeU1EZ3dNRm9YRFRJek1EZ3hNakV5TVRNd01Gb3dlakVMTUFrR0ExVUVCaE1D
      UTBneEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hC
      ZFdScGRHOXlNVEVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hoZFdScGRHOXlNVEVi
      TUJrR0ExVUVBd3dTUVdSdGFXNUFZWFZrCmFYUnZjakV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSXpqMERBUWNEUWdBRWNZeXhwdUlHZTZudlFNZDYKb2JxZnovTjl6SFVsc0JHdW11RVVSc0JQ
      MmFyRVBHaXMwVVFXMGJCL0g2a2poZm5FeG1VOGliWEZmc3dGWHFQTwppTmlHNUtPQ0FSb3dnZ0VX
      TUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlNX
      cEQ3bk5kYU5GclgrZU1wSzFteWJFUVZ0SVRBZkJnTlZIU01FR0RBV2dCU2VNa3pUY09vSWtZSEUK
      ZUhLeGF6bGZwZGw4TWpBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDNPVFE0TldOa09XUmtM
      WFk1WkdkdQpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqRWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      UzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdS
      UUloQVBhZjE5SS83MVhwenBvaGVkc2toTS83ZmZtd3RvSE1xaVY2CnZtQkZqaGhjQWlBd3kvWWNx
      RllVWFpBQVhneFNGbVJEaHdMZ3dMMjVKU2c4QW56VUhZYkZTUT09Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL0RDQ0FhS2dBd0lCQWdJVUtsYWZML2hsU05oaWQwVGtYWm9PN3d5K1Yrb3dDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUI0WApEVEl5TURneE1qRXlNRFkxTVZvWERUSTFNRFl3TVRFeU1E
      WTFNVm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTVRFWU1CWUdBMVVFQXd3UFky
      RXVZWFZrYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRWhp
      MDdOZW9tcnhnZzFkMHVJUWFCNmhlaHIrYzlRcjkwTmhJZU5rSXYzenZnWXVtMW5UczFJK0prCndF
      S2kvek9jNFlDblVVUjFodHIxRElKYTI3dHpxcU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZKNHlUTk53NmdpUmdjUjRjckZyT1Yr
      bDJYd3lNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFETUpwd09mV2VpV3JjU0lpOUFMc0I3OTRV
      alNLOWRGT0c3aHhWMnFPS1MvQUlnCk4vQWZsUGJyRThqM2Npcy9FQkZHVzdFZUp5R0hUUUp4RzU2
      SlJTK1cwbmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHUmVhZGVycxIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8I
      ARIbEggSBggBEgIIABoPEg0KC2F1ZGl0b3IxTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0S
      CBIGCAESAggAGhESDwoLYXVkaXRvcjFNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgB
      EhsSCBIGCAESAggAGg8SDQoLYXVkaXRvcjFNU1AaBkFkbWlucyoGQWRtaW5zEswWCgthdWRpdG9y
      Mk1TUBK8FhrUFAoDTVNQEswUEsEUEr4UCgthdWRpdG9yMk1TUBLtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVUZQZndidkNNVzFSNFF1Mkh0ZlNrOE9lSHpq
      MHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE1qRXlNRGd4TUZvWERU
      STFNRFl3TVRFeU1EZ3hNRm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1C
      WUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRUZITWNzbm5OZVA5OXYweWRheU1ici8xV3VZVFJBalVGekVBaGNFQklZK1hkTGs2
      ditDRDV6OUl5CklZaTZxbUNzUjhlWndoejBEblJuVy9nWVQ4SGVRYU5DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZJYzVHVVVUQ2hY
      b21ycnpFdys2dThMajlWMG1NQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUVaS0R3OTZCWUVzQk9S
      TC9RZldMSThkNUk0TWV6WWhhQ21jR2d0bEpYNGZBaUVBCnRCK3RxelpjWE1VT3VWMExCNEM3cmNM
      YisxaG5wY2FrQVdRaHhXKzRVbjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIr4ILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQXB1Z0F3SUJBZ0lVV2QxRzdlOVRmVDJscFda
      OXhUY1paYkRtckM4d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TWpF
      eU1URXdNRm9YRFRJek1EZ3hNakV5TVRZd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdO
      VkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JUVhWa2FYUnZjakl4
      SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4R3pBWkJnTlZCQU1N
      RWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VI
      QTBJQUJQODNsNTFYaEpicmhZaEsKazMxYVlNY215QklSV0d0QnFaZUszMERCaEU2NDBQU2F2ZHE5
      ckY4MDF1aTZ0VzFUYmQ2bWYxZ3pta2lIc3U1Ywpmcy9lOEh5amdnRWFNSUlCRmpBT0JnTlZIUThC
      QWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVSEZvcHpBMStJR044
      RDBmYlFXaTFsZlhhbit3d0h3WURWUjBqQkJnd0ZvQVVoemtaUlJNS0ZlaWEKdXZNVEQ3cTd3dVAx
      WFNZd0pBWURWUjBSQkIwd0c0SVpZMkV0ZEc5dmJITXRObVJpTnpWaVkyUTJPQzFqTlRReQplRENC
      andZSUtnTUVCUVlIQ0FFRWdZSjdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlM
      Q0poClpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJbUYxWkdsMGIzSXlJ
      aXdpYUdZdVJXNXkKYjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBWVhWa2FYUnZjakl0Ym1WMElpd2lh
      R1l1Vkhsd1pTSTZJbUZrYldsdQpJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDbmk0SlNM
      aFdKaURqeHVYU1Q0RHNXV0IrbEQ1UXh0V0daCmRrNnoreWJnSXdJZ0RzV0h3WU5UTzJDaW5oZHRh
      bGZQSFRpN01XZUZ3NmtZYW1neHdtMHZnVzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4K
      BFNIQTISBlNIQTI1NkrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dB
      d0lCQWdJVUZQZndidkNNVzFSNFF1Mkh0ZlNrOE9lSHpqMHdDZ1lJS29aSXpqMEVBd0l3ClhERUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJFd0R3WURWUVFLREFoQmRXUnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUI0WApEVEl5TURneE1qRXlNRGd4TUZvWERUSTFNRFl3TVRFeU1EZ3hNRm93WERFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXVNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNq
      SXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUZITWNzbm5OZVA5OXYw
      eWRheU1ici8xV3VZVFJBalVGekVBaGNFQklZK1hkTGs2ditDRDV6OUl5CklZaTZxbUNzUjhlWndo
      ejBEblJuVy9nWVQ4SGVRYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFm
      OEVCQU1DQWFZd0hRWURWUjBPQkJZRUZJYzVHVVVUQ2hYb21ycnpFdys2dThMajlWMG1NQW9HQ0Nx
      RwpTTTQ5QkFNQ0EwZ0FNRVVDSUVaS0R3OTZCWUVzQk9STC9RZldMSThkNUk0TWV6WWhhQ21jR2d0
      bEpYNGZBaUVBCnRCK3RxelpjWE1VT3VWMExCNEM3cmNMYisxaG5wY2FrQVdRaHhXKzRVbjQ9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoHV3JpdGVycxIpEh8IARIbEggSBggB
      EgIIABoPEg0KC2F1ZGl0b3IyTVNQGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggA
      GhESDwoLYXVkaXRvcjJNU1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIGCAES
      AggAGg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggA
      Gg8SDQoLYXVkaXRvcjJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGlj
      eRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhAS
      Bgj/////DxoGQWRtaW5zGkoKEE9yZGVyZXJBZGRyZXNzZXMSNhIbChlvcmRlcmVyMS5vcmRlcmVy
      LW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucyIi
      CgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRt
      aW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5z
      Gg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
