apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-orderer1
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: orderer-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordererMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: orderersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a4bad08484d15460788deef3b35cce0b-1271918739.eu-west-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: dev-testorderer-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/orderer-net/orderers/orderer1.orderer-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIKp7bxpy38iSKQxiDi2gg9yK+zIdiYJvxvLJTIeDlq6EEtpcCtdcCtRcCngKWggBEAEaBgj7
      3eGXBiIKc3lzY2hhbm5lbCpANzQ3MjVhOGY0YmFmZDg0ZjhmOGJhYzc4YTdhYzFjZWIwYmQwNTg1
      ODFjMGVhMGQ4YjRjMzNhMzE5NjM3MGI4ZBIaEhjkbAfHf/Pqx4vOPHw2UeChlvp6o9pFQEkS11sK
      1FsS0VsSoyoKB09yZGVyZXISlyoSkhYKCm9yZGVyZXJNU1ASgxYanxQKA01TUBKXFBKMFBKJFAoK
      b3JkZXJlck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVU50MkNDblFDVTZTL29ZbEw3Q3R5TFZSa3RaNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxk
      REFlRncweQpNakE0TVRRd016STFNamhhRncweU5UQTJNRE13TXpJMU1qaGFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRRQ3J1clFmckVkZlR2N09YVFZ3VjFN
      UldoRHYvTlpXSkhrUld3VmdzNDRhRTVzempUU1hQSkw5Zmw0YmNTCmt1aHkrdGl1VjdEa3RlNlJj
      NEt4dnRzWm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVRk5HOTlKVlNtdkRQRWF3WFdJQUxPcG51ZzNvd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWdNTXFNeU1ZUXNIOG1tbE0rTVJTUmQzVkZJY1d6enc4aUZaYkJPdHk1NVFJQ0lR
      Q0xzYVFHCk5MQVd0a1pFWFFtczcrRWphU1dFU0VBS2J4eTdRcjNqVU1BYUZnPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoikggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzFUQ0NB
      bnlnQXdJQkFnSVVUUElJM3ZwK2pySWZZbnVzRDFoK0ZRZXVSNjB3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzV2Y21SbGNt
      VnlMVzVsZERBZUZ3MHkKTWpBNE1UUXdNek15TURCYUZ3MHlNekE0TVRRd016TTNNREJhTUdneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1CZ05WCkJBc1RCV0ZrYldsdU1Sb3dHQVlEVlFRRERC
      RkJaRzFwYmtCdmNtUmxjbVZ5TFc1bGREQlpNQk1HQnlxR1NNNDkKQWdFR0NDcUdTTTQ5QXdFSEEw
      SUFCQTJkZ3UyVFk3VmxJcFVieHN4N3ljOWhFZU1Hc0oxeng0QzRjWkxWVTJ3YgpxaTUyMGEvUnFw
      YWEwdERGV1BGS3Zkamx6SS9CZmxVNXZZN0NZaDg0L2dHamdnRVFNSUlCRERBT0JnTlZIUThCCkFm
      OEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVaDFHWEthZldKK2tOblBS
      OFJMdE8Kd1V1ajVTQXdId1lEVlIwakJCZ3dGb0FVRk5HOTlKVlNtdkRQRWF3WFdJQUxPcG51ZzNv
      d0pBWURWUjBSQkIwdwpHNElaWTJFdGRHOXZiSE10TjJJMll6azVaalprTkMwNFltTjRjakNCaFFZ
      SUtnTUVCUVlIQ0FFRWVYc2lZWFIwCmNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHMKYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnVkRWxFSWpvaVFXUnRhVzVBYjNKa1pYSmxjaTF1WlhRaQpMQ0pvWmk1VWVYQmxJam9pWVdS
      dGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnRHAwQXdVd0l3Y1Q3CnlDS1pmTVZxdEFa
      QkVQUGRJeEt4MU9pUVpTK3JpVDRDSUNKU0JaeFBVSUFwVWlnd2dKdE9HejJJa1ZyekpCcG4KZVNw
      VlFCRVA1Rm5zCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVU50MkNDblFDVTZT
      L29ZbEw3Q3R5TFZSa3RaNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRR
      d016STFNamhhRncweU5UQTJNRE13TXpJMU1qaGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlE
      ClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0pr
      WlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdWIzSmtaWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQwpBQVRRQ3J1clFmckVkZlR2N09YVFZ3VjFNUldoRHYvTlpXSkhrUld3
      VmdzNDRhRTVzempUU1hQSkw5Zmw0YmNTCmt1aHkrdGl1VjdEa3RlNlJjNEt4dnRzWm8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      Rk5HOTlKVlNtdkRQRWF3WFdJQUxPcG51ZzNvd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdNTXFN
      eU1ZUXNIOG1tbE0rTVJTUmQzVkZJY1d6enc4aUZaYkJPdHk1NVFJQ0lRQ0xzYVFHCk5MQVd0a1pF
      WFFtczcrRWphU1dFU0VBS2J4eTdRcjNqVU1BYUZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoG
      QWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCm9yZGVyZXJNU1AQARoGQWRt
      aW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKb3JkZXJlck1TUBoGQWRt
      aW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpvcmRlcmVyTVNQGgZBZG1pbnMq
      BkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVv
      dXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENh
      cGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa1BEKDUNvbnNlbnN1c1R5cGUSwhEStxEK
      CGV0Y2RyYWZ0EqoRCpMRChRvcmRlcmVyMS5vcmRlcmVyLW5ldBCKNxq6CC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDOHpDQ0FwbWdBd0lCQWdJVVdobHpRdGRFUzdZd2ZRbU1VMXNYODNC
      cHM2RXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJj
      d0ZRWURWUVFEREE1allTNXZjbVJsY21WeUxXNWxkREFlRncweQpNakE0TVRRd016TXlNREJhRncw
      eU16QTRNVFF3TXpNM01EQmFNRzB4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RURBT0JnTlYKQkFz
      VEIyOXlaR1Z5WlhJeEhUQWJCZ05WQkFNVEZHOXlaR1Z5WlhJeExtOXlaR1Z5WlhJdGJtVjBNRmt3
      RXdZSApLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFWU5weGZKRzRyS21DVFIyZkpqeUdjM2dS
      YUpITWZLVU5DcFcyCnpBNjZyYjZ2cUlTN0pBeHVHM2VDNS9TRTRrYnByY1VJN1BySWNxa3owVTNy
      RkdVbzhxT0NBU2d3Z2dFa01BNEcKQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVVCZ2dy
      QmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FV
      bUs2ODh5VnpSN1RCeW5xVUlLZkUrOFNhcHY4d0h3WURWUjBqCkJCZ3dGb0FVRk5HOTlKVlNtdkRQ
      RWF3WFdJQUxPcG51ZzNvd093WURWUjBSQkRRd01vSVViM0prWlhKbGNqRXUKYjNKa1pYSmxjaTF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1HZ0dDQ29EQkFVRwpCd2dC
      QkZ4N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pYjNKa1pYSmxjakV1YjNKa1pYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2li
      M0prWlhKbGNpSjkKZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQStLb05obGV3Zm4yMGEyM0NG
      dUdRTUErZXRQRm5vU0lSbllsbgp5TitKNHhRQ0lFN3RUbXRlb3dJaVpLcHlwQ2RhNGV4V25HdU5n
      SUk4emhGMnd2WDlLejNrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBtZ0F3SUJBZ0lVV2hselF0ZEVTN1l3ZlFtTVUxc1g4
      M0JwczZFd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UmN3RlFZRFZRUUREQTVqWVM1dmNtUmxjbVZ5TFc1bGREQWVGdzB5Ck1qQTRNVFF3TXpNeU1EQmFG
      dzB5TXpBNE1UUXdNek0zTURCYU1HMHhDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFN
      UzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCMDl5WkdWeVpYSXhFREFPQmdOVgpC
      QXNUQjI5eVpHVnlaWEl4SFRBYkJnTlZCQU1URkc5eVpHVnlaWEl4TG05eVpHVnlaWEl0Ym1WME1G
      a3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVZTnB4ZkpHNHJLbUNUUjJmSmp5R2Mz
      Z1JhSkhNZktVTkNwVzIKekE2NnJiNnZxSVM3SkF4dUczZUM1L1NFNGticHJjVUk3UHJJY3FrejBV
      M3JGR1VvOHFPQ0FTZ3dnZ0VrTUE0RwpBMVVkRHdFQi93UUVBd0lEcURBZEJnTlZIU1VFRmpBVUJn
      Z3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEClZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVtSzY4OHlWelI3VEJ5bnFVSUtmRSs4U2Fwdjh3SHdZRFZSMGoKQkJnd0ZvQVVGTkc5OUpWU212
      RFBFYXdYV0lBTE9wbnVnM293T3dZRFZSMFJCRFF3TW9JVWIzSmtaWEpsY2pFdQpiM0prWlhKbGNp
      MXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdnR0NDb0RCQVVHCkJ3
      Z0JCRng3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4
      c2JXVnUKZEVsRUlqb2liM0prWlhKbGNqRXViM0prWlhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpv
      aWIzSmtaWEpsY2lKOQpmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBK0tvTmhsZXdmbjIwYTIz
      Q0Z1R1FNQStldFBGbm9TSVJuWWxuCnlOK0o0eFFDSUU3dFRtdGVvd0lpWktweXBDZGE0ZXhXbkd1
      TmdJSTh6aEYyd3ZYOUt6M2sKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Js
      b2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJ
      CgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLrLgoLQ29uc29ydGl1bXMS2y4SkC4KGkNhcmJvbkFjY291bnRpbmdDb25zb3J0aXVtEvEt
      EsgWCgthdWRpdG9yMk1TUBK4FhrQFAoDTVNQEsgUEr0UEroUCgthdWRpdG9yMk1TUBLtBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL1RDQ0FhS2dBd0lCQWdJVVJsYTJCVG1MZzJGVzRn
      bFlEVjBmNG85eUVQNHdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoQmRX
      UnBkRzl5TWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUI0WApEVEl5TURneE5E
      QXpNamd3TVZvWERUSTFNRFl3TXpBek1qZ3dNVm93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhCZFdS
      cGRHOXkKTWpFWU1CWUdBMVVFQXd3UFkyRXVZWFZrYVhSdmNqSXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJemowRApBUWNEUWdBRVFIcFFqeUtST3hJSFNMdGVGNFI3N2JkTzlzSElieHhTWDN3
      ZnlaR1pqQTJWbnJBOU9NMWNLQ0NFCk5kWlZCdzMzMGdsWXRiaDhxdG85Zk9pTHJJMnFLS05DTUVB
      d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZ
      RUZLUmJGNDFpRFVjSWlsNTVDNDFDdjJJT1JiMVNNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFD
      NHlnVlAza29zWGxSeU4zbTlHVG8xdWFzdmt5QUNLSkRrUGV4aFJhMTFrQUloCkFOc0RiTW5TSmRz
      VitFNHo1S2h3d3N5TWd4NUVEbU1FcXQ0S0hDSVFsMysxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KIroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBxZ0F3SUJBZ0lVWDhW
      R1JOdXYvaEU0b3RYVFV1Q0s3MEJtUnhjd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhN
      Q1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZ
      RFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlYVmthWFJ2Y2pJdGJtVjBNQjRY
      CkRUSXlNRGd4TkRBek16WXdNRm9YRFRJek1EZ3hOREF6TkRFd01Gb3dlekVMTUFrR0ExVUVCaE1D
      UjBJeEd6QVoKQmdOVkJBY1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1J
      UVhWa2FYUnZjakl4SHpBTQpCZ05WQkFzVEJXRmtiV2x1TUE4R0ExVUVDeE1JWVhWa2FYUnZjakl4
      R3pBWkJnTlZCQU1NRWtGa2JXbHVRR0YxClpHbDBiM0l5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VH
      Q0NxR1NNNDlBd0VIQTBJQUJCbkFrWW5QRUxvT1BhRXEKR3JkemZYdEh3YVRYQnlrQ2J6dUlSVUFZ
      eFFYQjkwSmx1ZlROUEVqVWFCU2c4emNyU28wUXQwc0NBT1Q0eWd0eQpHdCtwQ3pDamdnRVpNSUlC
      RlRBT0JnTlZIUThCQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FV
      OEcvQU1xU0E1VEVCSHpGU1c1WHY4L0o2NFdJd0h3WURWUjBqQkJnd0ZvQVVwRnNYaldJTlJ3aUsK
      WG5rTGpVSy9ZZzVGdlZJd0l3WURWUjBSQkJ3d0dvSVlZMkV0ZEc5dmJITXRPRGMyWmpZMFpEZzRM
      WGMxYldSMwpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJ
      am9pZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZ
      WFZrYVhSdmNqSWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JoZFdScGRHOXlN
      aTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdS
      QUlnR252U2tUNllUeDVJOHZ2dVZiMHNSTWRsNS80M0JNZFlkaGZHCmwzVnQ2WHNDSUY3dlFRZkhV
      dTZMdW4zSmtlRTcveTZUQW42SXByOTVoSjdxT29qVVBkU3QKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIv
      VENDQWFLZ0F3SUJBZ0lVUmxhMkJUbUxnMkZXNGdsWURWMGY0bzl5RVA0d0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNakVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pJdGJtVjBNQjRYCkRUSXlNRGd4TkRBek1qZ3dNVm9YRFRJMU1EWXdNekF6TWpnd01W
      b3dYREVMTUFrR0ExVUVCaE1DUjBJeER6QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNakVZTUJZR0ExVUVBd3dQWTJFdVlY
      VmthWFJ2Y2pJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFUUhwUWp5
      S1JPeElIU0x0ZUY0Ujc3YmRPOXNISWJ4eFNYM3dmeVpHWmpBMlZuckE5T00xY0tDQ0UKTmRaVkJ3
      MzMwZ2xZdGJoOHF0bzlmT2lMckkycUtLTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRktSYkY0MWlEVWNJaWw1NUM0MUN2MklPUmIx
      U01Bb0dDQ3FHClNNNDlCQU1DQTBrQU1FWUNJUUM0eWdWUDNrb3NYbFJ5TjNtOUdUbzF1YXN2a3lB
      Q0tKRGtQZXhoUmExMWtBSWgKQU5zRGJNblNKZHNWK0U0ejVLaHd3c3lNZ3g1RURtTUVxdDRLSENJ
      UWwzKzEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAES
      HRIIEgYIARICCAAaERIPCgthdWRpdG9yMk1TUBABGgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIf
      CAESGxIIEgYIARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1JlYWRlcnMSKRIfCAES
      GxIIEgYIARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxII
      EgYIARICCAAaDxINCgthdWRpdG9yMk1TUBoGQWRtaW5zKgZBZG1pbnMSyBYKC2F1ZGl0b3IxTVNQ
      ErgWGtAUCgNNU1ASyBQSvRQSuhQKC2F1ZGl0b3IxTVNQEu0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJBZ0lVYUhlWlpaQ0ZqNEdzMlUrcEdxNWczemNhQm84d0Nn
      WUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFE
      RVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhCZFdScGRHOXlNVEVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNQjRYCkRUSXlNRGd4TkRBek1qWTBORm9YRFRJMU1E
      WXdNekF6TWpZME5Gb3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFE
      RVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaEJkV1JwZEc5eQpNVEVZTUJZR0Ex
      VUVBd3dQWTJFdVlYVmthWFJ2Y2pFdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFR
      Y0RRZ0FFcVBkUmsrTkNHb3FxZXh4OGhJTlNmcDMwbFFUem84K1ErMEhHQjBuOUpuaDAvcUh3M2F6
      UUdFcGkKM0xEOTgvZVRCSzZaNjVtYzVIUUE4TUExRDBISmZxTkNNRUF3RHdZRFZSMFRBUUgvQkFV
      d0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkFsUjN0TkVDQW5vQTlC
      RW4zd0p3L3JhY2FNUU1Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNJQ2xRN3V3dlFBV1ZuVHdiREQ4
      d3VrZ09uRnBYSlpaenFwOGQ3eHgxMEhxUEFpQVUKTWhPVmhKL09Sb29NQmFVV1ZlY2cvMWJHTDlC
      MnExb2RvbHRRV1MyZzR3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoiuggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NBcHFnQXdJQkFnSVVPckpyVVNLcXlmdCtJb3Rsd1py
      Q1hHRHZXTjh3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFn
      TUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaEJkV1JwZEc5
      eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1CNFgKRFRJeU1EZ3hOREF6TXpR
      d01Gb1hEVEl6TURneE5EQXpNemt3TUZvd2VqRUxNQWtHQTFVRUJoTUNRMGd4R2pBWQpCZ05WQkFj
      VEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SRXdEd1lEVlFRS0V3aEJkV1JwZEc5eU1URWZNQXdH
      CkExVUVDeE1GWVdSdGFXNHdEd1lEVlFRTEV3aGhkV1JwZEc5eU1URWJNQmtHQTFVRUF3d1NRV1J0
      YVc1QVlYVmsKYVhSdmNqRXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FF
      a0tNbGFTZnNLQ3hYR0RKSApJWG9Jd1pPMEdISyt5dlZ3WVJMVHkyemxsZXl2Zld6ejNBNVZaZk5R
      TkRJYm1Tb2l5RVVQNGZibW0rN3hUeUUwCnJvd1hxYU9DQVJvd2dnRVdNQTRHQTFVZER3RUIvd1FF
      QXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCU1hOeFZxaktmWUt5clBJSC9X
      dXQraVpoNW9QakFmQmdOVkhTTUVHREFXZ0JRSlVkN1RSQWdKNkFQUQpSSjk4Q2NQNjJuR2pFREFr
      QmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kwMlpHWTVZalEwT0dSaUxYQm9NbWg0Ck1JR1BCZ2dx
      QXdRRkJnY0lBUVNCZ25zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmsK
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVlYVmthWFJ2Y2pFaUxDSm9a
      aTVGYm5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQmhkV1JwZEc5eU1TMXVaWFFpTENKb1ppNVVl
      WEJsSWpvaVlXUnRhVzRpCmZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdZVDlnTklXcTdraEU1
      SEVPekFkVXBXb3dmdmRDYjhBSDhlQ0MKMy9NUGpia0NJRjFscFViRUh1eTJEUnJkREtGcWtkU2Qw
      czFqMmI2SE9QWXpMRGRLZVhVUgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZT
      SEEyNTZK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQit6Q0NBYUtnQXdJQkFnSVVh
      SGVaWlpDRmo0R3MyVStwR3E1ZzN6Y2FCbzh3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVC
      aE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdE
      d1lEVlFRS0RBaEJkV1JwZEc5eU1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1C
      NFgKRFRJeU1EZ3hOREF6TWpZME5Gb1hEVEkxTURZd016QXpNalkwTkZvd1hERUxNQWtHQTFVRUJo
      TUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3
      WURWUVFLREFoQmRXUnBkRzl5Ck1URVlNQllHQTFVRUF3d1BZMkV1WVhWa2FYUnZjakV0Ym1WME1G
      a3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVxUGRSaytOQ0dvcXFleHg4aElOU2Zw
      MzBsUVR6bzgrUSswSEdCMG45Sm5oMC9xSHczYXpRR0VwaQozTEQ5OC9lVEJLNlo2NW1jNUhRQThN
      QTFEMEhKZnFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0Fh
      WXdIUVlEVlIwT0JCWUVGQWxSM3RORUNBbm9BOUJFbjN3SncvcmFjYU1RTUFvR0NDcUcKU000OUJB
      TUNBMGNBTUVRQ0lDbFE3dXd2UUFXVm5Ud2JERDh3dWtnT25GcFhKWlp6cXA4ZDd4eDEwSHFQQWlB
      VQpNaE9WaEovT1Jvb01CYVVXVmVjZy8xYkdMOUIycTFvZG9sdFFXUzJnNHc9PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxIN
      CgthdWRpdG9yMU1TUBoGQWRtaW5zIjUKBkFkbWlucxIrEiEIARIdEggSBggBEgIIABoREg8KC2F1
      ZGl0b3IxTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNlbWVudBIpEh8IARIbEggSBggBEgIIABoPEg0K
      C2F1ZGl0b3IxTVNQGgZBZG1pbnMiNAoHUmVhZGVycxIpEh8IARIbEggSBggBEgIIABoPEg0KC2F1
      ZGl0b3IxTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMS
      CAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5z
      Gi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaSgoQT3JkZXJl
      ckFkZHJlc3NlcxI2EhsKGW9yZGVyZXIxLm9yZGVyZXItbmV0OjcwNTAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoA
      CgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
