apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: auditor1-net-ca
  namespace: auditor1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: auditor1-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: auditor1-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    deployment:
      annotations:
    annotations:  
      service:
      pvc:
 
    server:
      name: ca
      tlsstatus: true
      admin: auditor1-admin 
  
    storage:
      storageclassname: auditor1sc
      storagesize: 1Gi
    vault:
      role: vault-role
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      authpath: dev-testauditor1-net-auth
      secretcert: secretsv2/data/crypto/peerOrganizations/auditor1-net/ca?ca.auditor1-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/auditor1-net/ca?auditor1-net-CA.key
      secretadminpass: secretsv2/data/credentials/auditor1-net/ca/auditor1?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: develop.local.com
