apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurestorageclass
allowVolumeExpansion: true
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
parameters:
  skuname: StandardSSD_LRS


