apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-vaultk8s-job
  namespace: supplychain-bes
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/vault-k8s-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    metadata:
      name: supplychain-vaultk8s-job
      namespace: supplychain-bes
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        pullPolicy: IfNotPresent

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://20.42.153.110:8200
      authpath: besusupplychain
      policy: vault-crypto-organization-supplychain-ro
      policydata: "{\n  \"policy\": \"path \\\"secretsv2/data/supplychain-bes/crypto/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\", \\\"create\\\", \\\"update\\\"]\n  }\n  path \\\"secretsv2/data/supplychain-bes/smartContracts/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\"]\n  }\"\n}"
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred

    k8s:
      kubernetes_url: https://bevel-test-dns-91b0b83c.hcp.westus2.azmk8s.io:443
