apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: orderer-net-ca
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/ca    
  values:
    deployment:
      annotations:
    annotations:  
      service:
      pvc:
    metadata:
      namespace: orderer-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: orderer-admin
        
    storage:
      storageclassname: orderersc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      authpath: dev-testorderer-net-auth
      secretcert: secretsv2/data/crypto/ordererOrganizations/orderer-net/ca?ca.orderer-net-cert.pem
      secretkey: secretsv2/data/crypto/ordererOrganizations/orderer-net/ca?orderer-net-CA.key
      secretadminpass: secretsv2/data/credentials/orderer-net/ca/orderer?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: orderer
      external_url_suffix: develop.local.com
