apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: approve-auditor1-emissionchannel-peer0emission1-1
  namespace: auditor1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: approve-auditor1-emissionchannel-peer0emission1-1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: auditor1-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.auditor1-net:7051
      localmspid: auditor1MSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://a98fe9a1d4dbd422fa7db7c78066059a-2533884.eu-west-1.elb.amazonaws.com:8200
      authpath: dev-testauditor1-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/auditor1-net/users/admin 
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/auditor1-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.orderer-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: emission
      version: 1
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: emissionchannel
